### ISSUE TITLE
rename katib-manager and katib-db

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#1004]
/kind feature

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
For now, when install katib, we have katib-manager and katib-db service/deployment, in fact, we should rename them to katib-db-manager and katib-mysql respectively to reduce confusion

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by hougangliu** [comment]
@johnugeorge @gaocegege @richardsliu WDYT?

**Comment by johnugeorge** [comment]
SGTM

**Comment by gaocegege** [comment]
SGTM
