### ISSUE TITLE
Can I change the metrics-collector's docker repo address? 

### ISSUE THREAD

**Issue by b675987273** [kubeflow/katib#1014]
/kind feature

**Describe the solution you'd like**
It seems like the pod created by katib contains a official metrics-collector. I believe that metrics-collector is created by the katib's controller. Is it more friendly using that created by job-controller.

**Anything else you would like to add:**
Maybe we can add more docs to descript how to use katib.

**Comment by gaocegege** [comment]
You can change it. It is defined in https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/katib-controller/katib-config.yaml
