### ISSUE TITLE
Release v0.1.2-alpha 

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#102]
The API of Katib is drastically changed from v0.1.1-alpha.
Though we can't update v0.2 yet, we need to release v0.1.2-alpha, update docker images and update docs.
cc @gaocegege

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/releases/tag/v0.1.2-alpha

Version is created in GitHub, things to do are:

- [ ] Publish Docker images to DockerHub

**Comment by gaocegege** [comment]
@YujiOshima Could you please push the images? I think I have no permission to push to katib or kubeflow (we are using katib now).

**Comment by YujiOshima** [comment]
@gaocegege Thank you!

>push the images

done!

**Comment by gaocegege** [comment]
I am closing the issue since we have:

- released the new version in GitHub and upload CLI for Linux and Darwin
- published new Docker images
- Updated the docs.
