### ISSUE TITLE
[bug] Status is not correct in kubectl

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#1029]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We get the trial status in kubectl:

```
katib-distributed-example-z2rxgztq   Succeeded   False    9m52s
```

But when we describe it:

```
Status:
  Conditions:
    Last Transition Time:  2020-01-21T03:37:43Z
    Last Update Time:      2020-01-21T03:37:43Z
    Message:               Trial is created
    Reason:                TrialCreated
    Status:                True
    Type:                  Created
    Last Transition Time:  2020-01-21T03:39:21Z
    Last Update Time:      2020-01-21T03:39:21Z
    Message:               Trial is running
    Reason:                TrialRunning
    Status:                False
    Type:                  Running
    Last Transition Time:  2020-01-21T03:39:21Z
    Last Update Time:      2020-01-21T03:39:21Z
    Message:               Metrics are not available
    Reason:                MetricsUnavailable
    Status:                False
    Type:                  Succeeded
  Start Time:              2020-01-21T03:37:43Z
```

And we treat such a trial `pending` in experiment status. It is not appropriate, I think.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/katib/blob/27fbd98247a6149bd89f1b467a8a8fb9d328cd0e/pkg/controller.v1alpha3/trial/trial_controller_util.go#L55

**Comment by gaocegege** [comment]
Should we make it failed?
```go
		} else {
			msg := "Metrics are not available"
			instance.MarkTrialStatusSucceeded(corev1.ConditionFalse, TrialMetricsUnavailableReason, msg)

			eventMsg := fmt.Sprintf("Metrics are not available for Job %s", deployedJob.GetName())
			r.recorder.Eventf(instance, corev1.EventTypeWarning, JobMetricsUnavailableReason, eventMsg)
		}
```

**Comment by johnugeorge** [comment]
Metrics not available is not a terminal state of being failed.   when did you see this? Did it recover from this state?

**Comment by johnugeorge** [comment]
If it is a terminal condition, we can mark it failed

**Comment by gaocegege** [comment]
> Will there be a situation like this:  Job completed but side car metric collector takes time to push metrics to DB.  won't we hit the same : https://github.com/kubeflow/katib/blob/27fbd98247a6149bd89f1b467a8a8fb9d328cd0e/pkg/controller.v1alpha3/trial/trial_controller_util.go#L55

**Comment by gaocegege** [comment]
> What will happen if the sidecar is still running? Will the pod be set Completed?

We should verify it.

**Comment by fedeesku1** [comment]
I'm having the issue as above. The pod associated with a trail has a status of complete but the description of the trial is marked as still running due to metrics unavailable. Running the random-example.yaml. This state persisted for almost an hour before I killed the experiment. Any ideas on this issue? #1033 Has people with the same issue and specs outlined.

**Comment by andreyvelich** [comment]
@fedeesku1 Can you verify that metrics are reported to the DB? If you have any problems, feel free to create new issue.

Corresponding issue about new Trial status with metrics unavailable: https://github.com/kubeflow/katib/issues/1343.
