### ISSUE TITLE
suggestion pods running after experiment completes

### ISSUE THREAD

**Issue by timothyjlaurent** [kubeflow/katib#1043]
/kind bug

**What steps did you take and what happened:**
Ran experiments in the examples folder.

Experiments that finished, (not broken) show up in the ui:
![image](https://user-images.githubusercontent.com/2000204/73702597-150c5f00-46a2-11ea-866d-63582fc5ded4.png)

But their associated pods remain running on the cluster:

![image](https://user-images.githubusercontent.com/2000204/73702742-906e1080-46a2-11ea-9806-1b2912061cae.png)

**What did you expect to happen:**

The suggestion pods would get cleaned up

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.14.6
- OS (e.g. from `/etc/os-release`):

**Comment by gaocegege** [comment]
It is a by-design feature since we may want to recreate new trials in the experiment to resume.

**Comment by timothyjlaurent** [comment]
I see -- This could cause an unbounded increase of resources, consider allowing experiments to resume from the metadata collected in the Experment and Trial K8s objects.
