### ISSUE TITLE
Please document api access

### ISSUE THREAD

**Issue by timothyjlaurent** [kubeflow/katib#1044]
/kind feature

**Describe the solution you'd like**
The docs describe a rest api but I can't seem to find it. The VirtualServices installed by kubeflow lack a route to the api. Since the UI is so light on details and in some cases reports incorrect values, it would be nice to be able to access a programmatic api.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaocegege** [comment]
What do you want to do with the API?

**Comment by timothyjlaurent** [comment]
Query for trials by experiment, get all experiments, get 'winning' trial hyperparameters.

**Comment by nrchakradhar** [comment]
Do we have SDK for Karib also? From notebbok via fairing or SDK if its possible to trigger karib experiment it will be more useful.

**Comment by nrchakradhar** [comment]
There was a mention about getting the best trial using a python API in the below issue:
https://github.com/kubeflow/katib/issues/459
Is something like that still available? The file mentioned is no longer available. I guess it should be part of the SDK generation

**Comment by sakaia** [comment]
It seems noting progress. Does Any API  exist for getting best trial for Python?

**Comment by andreyvelich** [comment]
Hi @sakaia, yes we created python SDK for Katib: https://github.com/kubeflow/katib/tree/master/sdk/python.

Currently, we support only v1alpha3, but later we will add SDK for v1beta1 also.
This API: https://github.com/kubeflow/katib/blob/master/sdk/python/docs/KatibClient.md#get_optimal_hyperparmeters, gives you current optimal Trial for the Experiment.

I close this issue, @nrchakradhar @timothyjlaurent  if you have more questions, please let me know.
