### ISSUE TITLE
Experiment never ends and metrics are not collected

### ISSUE THREAD

**Issue by chauvenne** [kubeflow/katib#1045]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I started by deploying Kubeflow using the UI (https://deploy.kubeflow.cloud). Then I simply applied the random example with `kubectl apply -f https://raw.githubusercontent.com/kubeflow/katib/master/examples/v1alpha3/random-example.yaml`
The trials container have completed unlike the experiment container that is still running. 

I also tried adding a StdOut `metricsCollectorSpec`. Then (and only then) I have two containers per trial pods (one for the actual model training, and the other for collecting the metrics) but no metrics are collected by the latter. And the experiment never ends too.

![katib](https://user-images.githubusercontent.com/8996148/73751431-675f8580-475f-11ea-8468-38ca90ae14e2.png)

![katib_2](https://user-images.githubusercontent.com/8996148/73751630-c02f1e00-475f-11ea-8778-5cc8c1df7062.png)

**What did you expect to happen:**

Metrics to be collected from the stdout and plotted on the Kubeflow UI.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Here are the logs of the container which is supposed to train the models: 
![empty](https://user-images.githubusercontent.com/8996148/73753967-dfc84580-4763-11ea-9fd9-1b760cfc9d7e.PNG) i.e. it is empty.
Whereas the logs for the metrics-logger-and-collector containers are:

> I0204 14:12:28.774382      19 main.go:83] Trial Name: random-example-hzchjbjd
> I0204 14:12:29.547190      19 main.go:77] 2020-02-04T14:12:29Z INFO     start with arguments Namespace(add_stn=False, batch_size=64, disp_batches=100, dtype='float32', gc_threshold=0.5, gc_type='none', gpus=None, image_shape='1, 28, 28', initializer='default', kv_store='device', load_epoch=None, loss='', lr=0.011479313940528528, lr_factor=0.1, lr_step_epochs='10', macrobatch_size=0, model_prefix=None, mom=0.9, monitor=0, network='mlp', num_classes=10, num_epochs=10, num_examples=60000, num_layers=4, optimizer='adam', profile_server_suffix='', profile_worker_suffix='', save_period=1, test_io=0, top_k=0, use_imagenet_data_augmentation=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
> I0204 14:12:29.554785      19 main.go:77] 2020-02-04T14:12:29Z DEBUG    Starting new HTTP connection (1): yann.lecun.com:80
> I0204 14:12:29.721292      19 main.go:77] 2020-02-04T14:12:29Z DEBUG    http://yann.lecun.com:80 "GET /exdb/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 200 28881
> I0204 14:12:29.808254      19 main.go:77] 2020-02-04T14:12:29Z DEBUG    Starting new HTTP connection (1): yann.lecun.com:80
> I0204 14:12:29.985639      19 main.go:77] 2020-02-04T14:12:29Z DEBUG    http://yann.lecun.com:80 "GET /exdb/mnist/train-images-idx3-ubyte.gz HTTP/1.1" 200 9912422
> I0204 14:12:31.340536      19 main.go:77] 2020-02-04T14:12:31Z DEBUG    Starting new HTTP connection (1): yann.lecun.com:80
> I0204 14:12:31.507767      19 main.go:77] 2020-02-04T14:12:31Z DEBUG    http://yann.lecun.com:80 "GET /exdb/mnist/t10k-labels-idx1-ubyte.gz HTTP/1.1" 200 4542
> I0204 14:12:31.515053      19 main.go:77] 2020-02-04T14:12:31Z DEBUG    Starting new HTTP connection (1): yann.lecun.com:80
> I0204 14:12:31.700887      19 main.go:77] 2020-02-04T14:12:31Z DEBUG    http://yann.lecun.com:80 "GET /exdb/mnist/t10k-images-idx3-ubyte.gz HTTP/1.1" 200 1648877
> I0204 14:12:33.214310      19 main.go:77] 2020-02-04T14:12:33Z INFO     Epoch[0] Batch [0-100]  Speed: 16440.95 samples/sec     accuracy=0.827042
> I0204 14:12:33.547301      19 main.go:77] 2020-02-04T14:12:33Z INFO     Epoch[0] Batch [100-200]        Speed: 19240.75 samples/sec     accuracy=0.919531

...

> I0204 14:13:56.447298      19 main.go:77] 2020-02-04T14:13:56Z INFO     Epoch[9] Batch [800-900]        Speed: 6905.49 samples/sec      accuracy=0.962031
> I0204 14:13:56.782314      19 main.go:77] 2020-02-04T14:13:56Z INFO     Epoch[9] Train-accuracy=0.960638
> I0204 14:13:56.782534      19 main.go:77] 2020-02-04T14:13:56Z INFO     Epoch[9] Time cost=9.510
> I0204 14:13:57.654289      19 main.go:77] 2020-02-04T14:13:57Z INFO     Epoch[9] Validation-accuracy=0.961385
> I0204 14:13:58.782090      19 main.go:118] **Metrics reported. :**

The training is not supposed to happen inside the metric-collector container right ?

**Environment:**

- Kubeflow version: 0.7.1
- Minikube version:
- Kubernetes version: (use `kubectl version`): 
>  Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", 
> GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-gke.33", GitCommit:"2c6d0ee462cee7609113bf9e175c107599d5213f", GitTreeState:"clean", BuildDate:"2020-01-15T17:47:46Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Update** 

I just tried with kubectl **v.1.14.8** and **v.1.15.7**, but the same problem happens

**Comment by chauvenne** [comment]
Solved with https://github.com/kubeflow/katib/issues/1033#issuecomment-581963771

**Comment by chauvenne** [comment]
The fix from https://github.com/kubeflow/katib/issues/1033#issuecomment-581963771 worked for the random example but not for my personal experiment.

What I observe is that all the training logs for the random-example are in the `metrics-logger-and-collector` containers which I find weird. But in this case, the metrics are correctly collected.

For my experiment, the training logs are printed in the container associated with the trial-name but the metrics are never collected and the experiment is stuck after the first trials.

**Comment by timothyjlaurent** [comment]
@chauvenne try to add

```
  metricsCollectorSpec:
    collector:
      kind: StdOut
```

to your experiment.

I found that I need that with the 0.7.0 estimator images.

**Comment by chauvenne** [comment]
> @chauvenne try to add
> 
> ```
>   metricsCollectorSpec:
>     collector:
>       kind: StdOut
> ```
> 
> to your experiment.
> 
> I found that I need that with the 0.7.0 estimator images.

I already tried but the result is the same 😕

**Comment by chauvenne** [comment]
> @chauvenne try to add
> 
> ```
>   metricsCollectorSpec:
>     collector:
>       kind: StdOut
> ```
> 
> to your experiment.
> 
> I found that I need that with the 0.7.0 estimator images.

@timothyjlaurent Already tried without success 😕

**Comment by andreyvelich** [comment]
@chauvenne Can you show full description of your experiment after you create it, with removing `control-plane` label ?
Not needed to add `metricsCollectorSpec` to the experiment before submitting.

**Comment by chauvenne** [comment]
@andreyvelich  Here is the output of `kubectl describe experiment` :

> Name:         synthetic-cars-bayesian
Namespace:    kubeflow
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubeflow.org/v1alpha3","kind":"Experiment","metadata":{"annotations":{},"name":"synthetic-cars-bayesian","namespace":"kubef...
API Version:  kubeflow.org/v1alpha3
Kind:         Experiment
Metadata:
  Creation Timestamp:  2020-02-06T10:05:45Z
  Finalizers:
    update-prometheus-metrics
  Generation:        1
  Resource Version:  1885656
  Self Link:         /apis/kubeflow.org/v1alpha3/namespaces/kubeflow/experiments/synthetic-cars-bayesian
  UID:               3db6555c-48c8-11ea-85d6-42010a800088
Spec:
  Algorithm:
    Algorithm Name:  bayesianoptimization
    Algorithm Settings:
      Name:                random_state
      Value:               10
  Max Failed Trial Count:  3
  Max Trial Count:         12
  Metrics Collector Spec:
    Collector:
      Kind:  StdOut
  Objective:
    Goal:                   0.99
    Objective Metric Name:  f1_per_object@[IoU=0.25]
    Type:                   maximize
  Parallel Trial Count:     3
  Parameters:
    Feasible Space:
      Max:           0.001
      Min:           0.0000001
    Name:            --lr
    Parameter Type:  double
    Feasible Space:
      List:
        adam
        sgd
    Name:            --optimizer_name
    Parameter Type:  categorical
    Feasible Space:
      List:
        1
        2
        4
        8
    Name:            --batch_size
    Parameter Type:  categorical
    Feasible Space:
      Max:           0.5
      Min:           0.0000001
    Name:            --weight_decay
    Parameter Type:  double
  Trial Template:
    Go Template:
      Raw Template:  # KUBERNETES Parameters
apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Trial}}
  namespace: {{.NameSpace}}
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        cloud.google.com/gke-nodepool: v100
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: {{.Trial}}
        image: eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest # Docker image to use
        resources:
          limits:
            nvidia.com/gpu: 1
        command:
          - /bin/sh
          - -c
          - |
            'cld_download_file -f experiments/katib_test.yml -p GOOGLE_STORAGE -b tesseract-experiments -n config/katib_test.yml ;
            python /home/appuser/scripts/run.py experiments/katib_test.yml {{with .HyperParameters}} {{range .}} {{.Name}}={{.Value}} {{end}} {{end}}'
Status:
  Conditions:
    Last Transition Time:  2020-02-06T10:05:45Z
    Last Update Time:      2020-02-06T10:05:45Z
    Message:               Experiment is created
    Reason:                ExperimentCreated
    Status:                True
    Type:                  Created
    Last Transition Time:  2020-02-06T10:06:59Z
    Last Update Time:      2020-02-06T10:06:59Z
    Message:               Experiment is running
    Reason:                ExperimentRunning
    Status:                True
    Type:                  Running
  Current Optimal Trial:
    Observation:
      Metrics:              <nil>
    Parameter Assignments:  <nil>
  Start Time:               2020-02-06T10:05:45Z
  Trials:                   3
  Trials Running:           3
Events:                     <none>


It looks like the injection label is not present in the kubeflow namespace?

**Comment by andreyvelich** [comment]
@chauvenne With this experiment your training containers pods don't have metrics collector container? Can you also describe one of training container pod, please?

**Comment by chauvenne** [comment]
@andreyvelich I can see two containers, one for the training and the other is the metric collector.
Here is the output of `kubectl describe pod` for the training pod:

> Name:               synthetic-cars-bayesian-nsmf5swq-z4x7j
Namespace:          kubeflow
Priority:           0
PriorityClassName:  <none>
Node:               gke-kubeflow-v100-v100-7c41de1c-xvxp/10.128.0.50
Start Time:         Thu, 06 Feb 2020 13:16:42 +0100
Labels:             controller-uid=2f4f2d62-48da-11ea-85d6-42010a800088
                    job-name=synthetic-cars-bayesian-nsmf5swq
Annotations:        <none>
Status:             Running
IP:                 10.28.7.3
Controlled By:      Job/synthetic-cars-bayesian-nsmf5swq
Containers:
  synthetic-cars-bayesian-nsmf5swq:
    Container ID:  docker://8bcbcd4c83f3b8e35c1f67365836c2e2a1d63d9a4cf0129c314a9a3be96692e4
    Image:         eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest
    Image ID:      docker-pullable://eu.gcr.io/sincere-scheme-246214/tcv@sha256:c34dd61ddff79dc9837efea2ce69e1a78b4ce2542b947c05a57c6ded87ec11a4
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      /bin/sh -c 'cld_download_file -f experiments/katib_test.yml -p GOOGLE_STORAGE -b tesseract-experiments -n config/katib_test.yml ;
      python /home/appuser/scripts/run.py experiments/katib_test.yml   --lr=1.5669120035467289e-06  --optimizer_name=adam  --batch_size=2  --weight_decay=0.009805464096659722  '
       1>/var/log/katib/metrics.log 2>&1
    State:          Running
      Started:      Thu, 06 Feb 2020 13:17:22 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/log/katib from metrics-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-twwwr (ro)
  metrics-logger-and-collector:
    Container ID:  docker://89651aed404a22382f84ab2e92d5f6a059c7b3e3251fffd03e206776ac5a5c7b
    Image:         gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0
    Image ID:      docker-pullable://gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector@sha256:92b830cd374366d95f1eef9d00734f90f784714a8c8072ddf97dbca8365570e6
    Port:          <none>
    Host Port:     <none>
    Args:
      -t
      synthetic-cars-bayesian-nsmf5swq
      -m
      f1_per_object@[IoU=0.25]
      -s
      katib-manager.kubeflow:6789
      -path
      /var/log/katib/metrics.log
    State:          Running
      Started:      Thu, 06 Feb 2020 13:17:23 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/log/katib from metrics-volume (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-twwwr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-twwwr
    Optional:    false
  metrics-volume:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       BestEffort
Node-Selectors:  cloud.google.com/gke-nodepool=v100
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 nvidia.com/gpu:NoSchedule
Events:
  Type     Reason            Age                    From                                           Message
  ----     ------            ----                   ----                                           -------
  Normal   TriggeredScaleUp  5m25s                  cluster-autoscaler                             pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/sincere-scheme-246214/zones/us-central1-a/instanceGroups/gke-kubeflow-v100-v100-7c41de1c-grp 0->2 (max: 10)}]
  Warning  FailedScheduling  4m49s (x3 over 6m)     default-scheduler                              0/2 nodes are available: 2 Insufficient nvidia.com/gpu, 2 node(s) didn't match node selector.
  Warning  FailedScheduling  4m20s                  default-scheduler                              0/3 nodes are available: 2 node(s) didn't match node selector, 3 Insufficient nvidia.com/gpu.
  Warning  FailedScheduling  3m38s (x7 over 4m19s)  default-scheduler                              0/4 nodes are available: 2 node(s) didn't match node selector, 4 Insufficient nvidia.com/gpu.
  Normal   Scheduled         3m30s                  default-scheduler                              Successfully assigned kubeflow/synthetic-cars-bayesian-nsmf5swq-z4x7j to gke-kubeflow-v100-v100-7c41de1c-xvxp
  Normal   Pulling           3m29s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Pulling image "eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest"
  Normal   Pulled            2m54s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Successfully pulled image "eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest"
  Normal   Created           2m50s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Created container synthetic-cars-bayesian-nsmf5swq
  Normal   Started           2m50s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Started container synthetic-cars-bayesian-nsmf5swq
  Normal   Pulling           2m50s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Pulling image "gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0"
  Normal   Pulled            2m49s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Successfully pulled image "gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0"
  Normal   Created           2m49s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Created container metrics-logger-and-collector
  Normal   Started           2m49s                  kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Started container metrics-logger-and-collector

Thanks for the help btw!

**Comment by andreyvelich** [comment]
@chauvenne And after training container finished corresponding Trial is still running?
Can you check latest logs from metrics-logger-and-collector container?

**Comment by chauvenne** [comment]
![empty_2](https://user-images.githubusercontent.com/8996148/73937633-c0f1bc80-48e5-11ea-98b9-108141e79a32.png)

Trials are marked as Completed:
![empty_3](https://user-images.githubusercontent.com/8996148/73937638-c2bb8000-48e5-11ea-9df8-3dc7ea88df02.PNG)

Describe output after training finished:

> Name:               synthetic-cars-bayesian-nsmf5swq-z4x7j
Namespace:          kubeflow
Priority:           0
PriorityClassName:  <none>
Node:               gke-kubeflow-v100-v100-7c41de1c-xvxp/10.128.0.50
Start Time:         Thu, 06 Feb 2020 13:16:42 +0100
Labels:             controller-uid=2f4f2d62-48da-11ea-85d6-42010a800088
                    job-name=synthetic-cars-bayesian-nsmf5swq
Annotations:        <none>
Status:             Succeeded
IP:                 10.28.7.3
Controlled By:      Job/synthetic-cars-bayesian-nsmf5swq
Containers:
  synthetic-cars-bayesian-nsmf5swq:
    Container ID:  docker://8bcbcd4c83f3b8e35c1f67365836c2e2a1d63d9a4cf0129c314a9a3be96692e4
    Image:         eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest
    Image ID:      docker-pullable://eu.gcr.io/sincere-scheme-246214/tcv@sha256:c34dd61ddff79dc9837efea2ce69e1a78b4ce2542b947c05a57c6ded87ec11a4
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      /bin/sh -c 'cld_download_file -f experiments/katib_test.yml -p GOOGLE_STORAGE -b tesseract-experiments -n config/katib_test.yml ;
      python /home/appuser/scripts/run.py experiments/katib_test.yml   --lr=1.5669120035467289e-06  --optimizer_name=adam  --batch_size=2  --weight_decay=0.009805464096659722  '
       1>/var/log/katib/metrics.log 2>&1
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 06 Feb 2020 13:17:22 +0100
      Finished:     Thu, 06 Feb 2020 13:26:14 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/log/katib from metrics-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-twwwr (ro)
  metrics-logger-and-collector:
    Container ID:  docker://89651aed404a22382f84ab2e92d5f6a059c7b3e3251fffd03e206776ac5a5c7b
    Image:         gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0
    Image ID:      docker-pullable://gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector@sha256:92b830cd374366d95f1eef9d00734f90f784714a8c8072ddf97dbca8365570e6
    Port:          <none>
    Host Port:     <none>
    Args:
      -t
      synthetic-cars-bayesian-nsmf5swq
      -m
      f1_per_object@[IoU=0.25]
      -s
      katib-manager.kubeflow:6789
      -path
      /var/log/katib/metrics.log
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 06 Feb 2020 13:17:23 +0100
      Finished:     Thu, 06 Feb 2020 13:26:14 +0100
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/log/katib from metrics-volume (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-twwwr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-twwwr
    Optional:    false
  metrics-volume:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       BestEffort
Node-Selectors:  cloud.google.com/gke-nodepool=v100
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
                 nvidia.com/gpu:NoSchedule

> Events:
>   Type     Reason            Age                From                                           Message
>  Normal   TriggeredScaleUp  22m                cluster-autoscaler                             pod triggered scale-up: [{https://content.googleapis.com/compute/v1/projects/sincere-scheme-246214/zones/us-central1-a/instanceGroups/gke-kubeflow-v100-v100-7c41de1c-grp 0->2 (max: 10)}]
>   Warning  FailedScheduling  22m (x3 over 23m)  default-scheduler                              0/2 nodes are available: 2 Insufficient nvidia.com/gpu, 2 node(s) didn't match node selector.
>   Warning  FailedScheduling  21m                default-scheduler                              0/3 nodes are available: 2 node(s) didn't match node selector, 3 Insufficient nvidia.com/gpu.
>   Warning  FailedScheduling  21m (x7 over 21m)  default-scheduler                              0/4 nodes are available: 2 node(s) didn't match node selector, 4 Insufficient nvidia.com/gpu.
>   Normal   Scheduled         21m                default-scheduler                              Successfully assigned kubeflow/synthetic-cars-bayesian-nsmf5swq-z4x7j to gke-kubeflow-v100-v100-7c41de1c-xvxp
>   Normal   Pulling           21m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Pulling image "eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest"
>   Normal   Pulled            20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Successfully pulled image "eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest"
>   Normal   Created           20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Created container synthetic-cars-bayesian-nsmf5swq
>   Normal   Started           20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Started container synthetic-cars-bayesian-nsmf5swq
>   Normal   Pulling           20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Pulling image "gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0"
>   Normal   Pulled            20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Successfully pulled image "gcr.io/kubeflow-images-public/katib/v1alpha3/file-metrics-collector:v0.7.0"
>   Normal   Created           20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Created container metrics-logger-and-collector
>   Normal   Started           20m                kubelet, gke-kubeflow-v100-v100-7c41de1c-xvxp  Started container metrics-logger-and-collector
>

**Comment by andreyvelich** [comment]
@chauvenne Also, can you show Training Job description?

After that, try to change StdOut metrics collector image tag to latest. You can change it in ConfigMap `katib-config`. After that submit experiment again.

In the meantime, have you tried to run your container with image `eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest` separate? If yes, have you seen any logs there?

If you are using default StdOut metrics collector you should print metrics to the training container log as `MetricName=MetricValue`. Ref: https://www.kubeflow.org/docs/components/hyperparameter-tuning/experiment/#metrics-collector.

**Comment by chauvenne** [comment]
@andreyvelich 

> @chauvenne Also, can you show Training Job description?

![describe_job](https://user-images.githubusercontent.com/8996148/73939407-ade0eb80-48e9-11ea-91e2-ec27fad1df2e.PNG)

> After that, try to change StdOut metrics collector image tag to latest. You can change it in ConfigMap `katib-config`. After that submit experiment again.

Ok thanks, I'll try

> In the meantime, have you tried to run your container with image `eu.gcr.io/sincere-scheme-246214/tcv:CUDA10.0-CC70-latest` separate? If yes, have you seen any logs there?
> 
> If you are using default StdOut metrics collector you should print metrics to the training container log as `MetricName=MetricValue`. Ref: https://www.kubeflow.org/docs/components/hyperparameter-tuning/experiment/#metrics-collector.

I confirm that it is already printed on stdout in that format.

**Comment by andreyvelich** [comment]
@chauvenne Also, I saw that you don't have `echo completed > /var/log/katib/$$$$.pid` in your training container args.

Maybe you are using not the latest image for the Katib controller also. Can you try to update from 0.7 to the latest in katib-controller deployment.

**Comment by chauvenne** [comment]
@andreyvelich Ok I've just updated the tags to latest for both StdOut and katib-controller images.
Now I've got this error when applying the experiment:

`Error from server (InternalError): error when creating "katib_opti.yml": Internal error occurred: failed calling webhook "mutating.experiment.katib.kubeflow.org": Post https://katib-controller.kubeflow.svc:443/mutate-experiments?timeout=30s: ssh: rejected: connect failed (Connection refused)`

Any idea?

**Comment by andreyvelich** [comment]
@chauvenne Did you deploy Katib as part of Kubeflow? 
If yes, can you try to deploy Katib with Kubeflow using kfctl and this config: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml.

I think you got this error because your images or yaml manifests are from 0.7 version.
To be able to run master version of Katib controller you need to deploy Katib from latest manifests.
UI and other part of Katib should be available.

**Comment by chauvenne** [comment]
It finally works! 

All the steps I have taken are: 

1. Download the latest `kfctl` version on https://github.com/kubeflow/kfctl/releases/tag/v1.0-rc.4
2. Deploy Kubeflow on a new cluster using CLI and the latest manifest for gcp (https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_gcp_iap.yaml)
3. Remove the quotation marks in my experiment yaml in the `command` spec (where I use /bin/sh so that I can enter multiple commands)

I didn't edit no namespace, configmaps or whatever. 
Thanks @andreyvelich for the help!

**Comment by wyljpn** [comment]
I have been using Kubeflow v1.3.0.
In the beginning, I also encountered the same issue.
After changing the image versions of **metrics-collector-sidecar** from v0.11.0 to the latest, Katib works well. 
```
docker.io/kubeflowkatib/file-metrics-collector:latest
docker.io/kubeflowkatib/tfevent-metrics-collector:latest
```
https://github.com/kubeflow/manifests/blob/v1.3-branch/apps/katib/upstream/components/controller/katib-config.yaml

![image](https://user-images.githubusercontent.com/37242439/159666088-b6b66eac-31d5-4459-9ad2-78f321d4bd08.png)

**Comment by abijith-pradeep** [comment]
I'm on kubeflow v1.10.0 and I'm facing a similar issue with the metrics not being collected for the random-experiment using the StdOut metricsCollector.
