### ISSUE TITLE
Metrics containing '=' character in their name are not collected

### ISSUE THREAD

**Issue by chauvenne** [kubeflow/katib#1051]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I try to optimize the hyperparameters of an object-detection algorithm. For this kind of task, we typically use metrics that depend on a chosen Intersection-over-Union (IoU). e.g for the COCO dataset, we usually evaluate the mean average-precision (maP) at an IoU of 0.5: 

`maP@[IoU=0.5]=...`

However, metrics printed with that format are not collected by Katib. On the other hand, by spliting and keeping only the left part of the metric, Katib works correctly:

`maP=...`

I wonder if it would be simply due to the '=' character inside the metric name?

**What did you expect to happen:**

Metric name to be parsed correctly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: v1.0
- Minikube version: -
- Kubernetes version: (use `kubectl version`): v15.7
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by andreyvelich** [comment]
@chauvenne How did you specify your `objectiveMetricName` in Experiment yaml file?

**Comment by chauvenne** [comment]
@andreyvelich  I tried both 
`objectiveMetricName: 'f1_per_object@[IoU=0.25]'`
and
`objectiveMetricName: f1_per_object@[IoU=0.25]`

**Comment by andreyvelich** [comment]
Did you get any errors or metrics collector just collect nothing?
Can you show latest log from metrics collector container?
