### ISSUE TITLE
Delete Suggestion deployment after Experiment is finished

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1061]
/kind feature

Right now, when user creates Experiment, Suggestion deployment is always running. Even after Experiment is finished. 
We should add Flag in the API if user wants to delete Suggestion deployment after Experiment is finished.

For example we can use `ResumeExperiment` flag here: https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/experiments/v1alpha3/experiment_types.go#L54.

1. `ResumeExperiment: False` if user wants to delete Suggestion after experiment is finished.
2. `ResumeExperiment: True` if user doesn't want to delete Suggestion after experiment is finished.

/cc @johnugeorge @richardsliu @hougangliu @gaocegege

**Comment by sperlingxx** [comment]
Really useful feature!

**Comment by andreyvelich** [comment]
Close this issue, since PR is merged.
/close
