### ISSUE TITLE
Save Suggestion state after deployment is deleted

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1062]
/kind feature

Katib should have functionality to save Suggestion state somewhere besides Suggestion pod. 
Some users would like to resume Experiments, but they don't want to have always running Suggestion deployment. For example we can use PV.

We can use `ResumeExperiment` flag from here: https://github.com/kubeflow/katib/issues/1061 to specify resuming experiment mechanism.

/cc @johnugeorge @gaocegege @hougangliu @richardsliu

**Comment by andreyvelich** [comment]
@johnugeorge @gaocegege What do you think about saving Suggestion states using object serialisation, e.g pickle in Python: https://docs.python.org/3/library/pickle.html. 
I believe Fairing also uses pickle to serialise training code.

In that case, if `ResumeExperiment: Always`, after each GetSuggestion call, Suggestion can create pickle file with the current object state. Each suggestion has `<AlgorithmNameService>` class. For example: https://github.com/kubeflow/katib/blob/58e07646b165a30ec1c2e6306dc7d72ebb793474/pkg/suggestion/v1alpha3/hyperopt/service.py#L15.

Then, we can save this pickle file in PV and use it to resume experiment with appropriate state for the Suggestion service class

**Comment by gaocegege** [comment]
The approach LGTM if the suggestion is implemented in Python. But I prefer a general solution for different languages.

**Comment by andreyvelich** [comment]
Let's discuss implementation here: https://github.com/kubeflow/katib/issues/1250.
