### ISSUE TITLE
Cannot deploy sample experiment 

### ISSUE THREAD

**Issue by k4rth33k** [kubeflow/katib#1073]
The katib UI gives the following error:
`
experiments.kubeflow.org is forbidden: User "system:serviceaccount:kubeflow:katib-ui" cannot create resource "experiments" in API group "kubeflow.org" in the namespace "kubeflow"
`
I am using microk8s with Kubeflow installed with snap. Kubernetes master gives out the following

`
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
`
System Specs:
Pop-Os, NVIDIA GTX 1060

**Comment by andreyvelich** [comment]
@k4rth33k Can you run```kubectl describe clusterrole katib-ui```, please?

It should have these permissions: https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/ui/rbac.yaml#L16

**Comment by JackDallas** [comment]
Hi I have a fresh install of Kubeflow using `microk8s.enable kubflow` and have this same issue the output of that command for me is 
```
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "katib-ui" not found
```

**Comment by andreyvelich** [comment]
@JackDallas I apologize for the long reply. 
I am sure which manifests microk8s is using and why katib-ui Cluster Role is not part of it. I would recommend open this issue under [microk8s](https://github.com/ubuntu/microk8s/issues) and cc me.

/cc @knkski

**Comment by JackDallas** [comment]
@andreyvelich I ended up on the k8s slack and resolved this but honestly I can't for the life of me remember what the issue was. I believe I ended up using a new version of k8s or kubeflow though

**Comment by andreyvelich** [comment]
Thank you for the confirmation @JackDallas.
I close this, feel free to open if this issue is raised again.
