### ISSUE TITLE
How to specify service account for an experiment

### ISSUE THREAD

**Issue by nrchakradhar** [kubeflow/katib#1079]
/kind bug

**What steps did you take and what happened:**
Using kubectl when we create an experiment, how can we specify the "serivceaccount" to be used?
I understand that Experiment CR creates a Suggestion CR which creates a Deployment. For this Deployment, I want to specify a specific serviceaccount to be used? Is this possible.?

As per the code here, I do not see a way to set the serviceaccount.
https://github.com/kubeflow/katib/blob/82679294ecaecd83dba30d42f9ce9e36f732cd89/pkg/controller.v1alpha3/suggestion/composer/composer.go#L119

**What did you expect to happen:**
It should be possible to specify service account for Katib experiments.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7 and 1.0
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.15
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
@nrchakradhar Right now, all components regarding to Experiment is created by katib-controller with this serviceAccount: https://github.com/kubeflow/katib/blob/82679294ecaecd83dba30d42f9ce9e36f732cd89/manifests/v1alpha3/katib-controller/rbac.yaml#L71

I am not sure that we have functionality to add service account to Suggestion Deployment.
We can add functionality to add ServiceAccount to Suggestion Deployment using katib-config (https://github.com/kubeflow/katib/blob/82679294ecaecd83dba30d42f9ce9e36f732cd89/manifests/v1alpha3/katib-controller/katib-config.yaml#L24).

What do you think @gaocegege @johnugeorge ?

**Comment by nrchakradhar** [comment]
Karib controller using its service account is fine. The suggestion cr which creates deployment in user namespace should also have a provision for using any service account provided by user. The service account would need role binding with required permissions.

**Comment by andreyvelich** [comment]
@nrchakradhar Yes, I agree, it can be useful.

**Comment by andreyvelich** [comment]
I think, as I mentioned above, `katib-config` can be the place where we can add ServiceAccount for the Suggestion deployment.
Also, we can include it to the Experiment yaml file, for example in `ExperimentSpec`.

What do you think @richardsliu  @gaocegege @hougangliu ?

**Comment by hougangliu** [comment]
@andreyvelich agree

**Comment by andreyvelich** [comment]
I will add this feature

/assign @andreyvelich
