### ISSUE TITLE
Using an existing remote DB cluster for Katib

### ISSUE THREAD

**Issue by kunalyogenshah** [kubeflow/katib#1080]
/kind bug

I am looking to use an existing DB cluster as the connector for Katib. Is there a way for me to expose that endpoint using the `katib-db` service for the components?

**Environment:**

- Kubeflow version: N/A
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.17
- OS (e.g. from `/etc/os-release`):

**Comment by kunalyogenshah** [comment]
👍

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/mysql/mysql.go#L34

We support the feaure. You can set these environment variables.
