### ISSUE TITLE
Is v1alpha3 going to provide REST API?

### ISSUE THREAD

**Issue by hyeonsangjeon** [kubeflow/katib#1084]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Is v1alpha3 goint to provide REST API?

I am now trying to create a backend module that calls katib.
api.proto from v1alpha1 to v1alpha2 contains information about the http call of gRPC. However, I could only find a brief rpc service content for Manager, Suggestion in v1alpha3 api.proto.

If V1ALPHA3 is going to provide Rest Api, can we know when it will be merged?
or 
If you have any API specification for katib calls that can use gRPC, please let me know.

**Comment by gaocegege** [comment]
We have no REST API now. But you can create katib resources with kubernetes API. You can create experiments by calling k8s api server.

**Comment by hyeonsangjeon** [comment]
Is there any way to use katib's gRPC to create, search, or delete[1] HPO instead of do not use kubernetes core v1 api directly?

[1] i mean this below, in UI katib
/katib/fetch_hp_job_info/
/katib/fetch_hp_jobs/
/katib/submit_yaml/
/katib/submit_hp_job/
/katib/delete_experiment/
/katib/update_template/

**Comment by andreyvelich** [comment]
Katib UI in backend itself using Kubernetes API.

If you want to use Katib UI handlers, you can serve Katib UI locally, which describing here: https://github.com/kubeflow/katib/tree/master/pkg/ui/v1alpha3#serve-ui-frontend-and-backend.

Also, you can find in `sagas` how we call each method for the UI, for example `delete_experiment`: https://github.com/kubeflow/katib/blob/master/pkg/ui/v1alpha3/frontend/src/sagas/index.js#L92.
Some calls can return information, for example `fetch_experiment`: https://github.com/kubeflow/katib/blob/master/pkg/ui/v1alpha3/frontend/src/sagas/index.js#L190.

I hope this is useful for you.

**Comment by andreyvelich** [comment]
@hyeonsangjeon As well, you can use our Python SDK: https://github.com/kubeflow/katib/tree/master/sdk/python/v1beta1.
Feel free to create an issue if you want to see any other API call there.
