### ISSUE TITLE
chocolate-MOCMAES has illegal name

### ISSUE THREAD

**Issue by terrykong** [kubeflow/katib#1094]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I tried to see if the other undocumented suggestion algorithms worked and came across some issues. In particular when an experiment uses `chocolate-MOCMAES`, the controller complains that the name doesn't follow conventions. It looks like the fix could just be to lowercase this suggestion algorithm's name

```
Service \"sp-mocmaes-int-n3-p1-chocolate-MOCMAES\" is invalid: metadata.name: Invalid value: \"sp-mocmaes-int-n3-p1-chocolate-MOCMAES\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')"
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
Thank you for your issue.
Yes, we can fix it like this.

@gaocegege Do you know, do we support `MOCMAES` algorithm?
According to this: https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py#L57, we can specify `algorithm_name=chocolate-MOCMAES`

I haven't tested, if this algorithm works properly.
