### ISSUE TITLE
Sorting trials by columns in UI

### ISSUE THREAD

**Issue by terrykong** [kubeflow/katib#1095]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
In an older version of katib I recall there was a way to sort the columns in the UI, but I don't see any way to do that anymore (katib v0.8). Is it possible to bring that feature back?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
@terrykong Thank you for your suggestion.
Yes, we have this feature in our TODO list.

/area front-end

**Comment by prabhat04011998** [comment]
Trials can be sorted by column structure , it could be happen by any D3.js column structure.
