### ISSUE TITLE
Katib User Interface User Experience

### ISSUE THREAD

**Issue by elviraux** [kubeflow/katib#1099]
Katib's user interface is at premature state and we would like to bring its user experience to a new level

That would be great if we can improve current Katib UI/UX.
Here is the guid for the Katib UI: https://github.com/kubeflow/katib/tree/master/pkg/ui/v1alpha3. Let me know about any questions.

Feel free to view current Frontend issues in Katib: https://github.com/kubeflow/katib/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Ffront-end

This is the list of UI improvements that can be implemented:
1. https://github.com/kubeflow/katib/issues/1088
2. https://github.com/kubeflow/katib/issues/1087
3. https://github.com/kubeflow/katib/issues/643 - Trial Status for NAS Jobs.
4. https://github.com/kubeflow/katib/issues/1095

If you want to add any other improvements, you are more then welcome to create `front-end` issue or assign existing issue in Katib.

**Comment by andreyvelich** [comment]
That would be great if we can improve current Katib UI/UX.
Here is the guid for the Katib UI: https://github.com/kubeflow/katib/tree/master/pkg/ui/v1alpha3. Let me know about any questions.

Feel free to view current Frontend issues in Katib: https://github.com/kubeflow/katib/issues?q=is%3Aissue+is%3Aopen+label%3Aarea%2Ffront-end

This is the list of UI improvements that can be implemented:
1. https://github.com/kubeflow/katib/issues/1088
2. https://github.com/kubeflow/katib/issues/1087
3. https://github.com/kubeflow/katib/issues/643 - Trial Status for NAS Jobs.
4. https://github.com/kubeflow/katib/issues/1095

If you want to add any other improvements, you are more then welcome to create `front-end` issue or assign existing issue in Katib.

**Comment by andreyvelich** [comment]
This is another very good issue to work with: https://github.com/kubeflow/katib/issues/1136.

**Comment by adhilcodes** [comment]
I would like to work on this issue @elviraux

**Comment by andreyvelich** [comment]
@adhilcodes Thank you for your interest in this issue.
We are planing to work on the new Katib UI design, see this: https://github.com/kubeflow/katib/issues/1277.
Please attend one of the AutoML community meeting after the New Year and we can discuss how we can collaborate on this.
