### ISSUE TITLE
[discussion] Katib 2020 Roadmap

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#1104]
We should decide on the roadmap next week.

/assign @hougangliu @andreyvelich @johnugeorge @richardsliu

**Comment by johnugeorge** [comment]
Let’s do it during katib community call

**Comment by StefanoFioravanzo** [comment]
@johnugeorge  Is there a recurring Katib community call? I would love to hear what are the plans for 2020, is it possible to have an invite?

**Comment by gaocegege** [comment]
@StefanoFioravanzo Of course. Welcome. But I am not sure if we should re-schedule the time of the call since there are some people in Europe and I am not sure if the old time works.

@johnugeorge Should we re-schedule the community call time?

**Comment by johnugeorge** [comment]
We can.  Can we discuss this in the Katib slack channel ? 
@richardsliu Does it work for you?

**Comment by gaocegege** [comment]
Things I want to discuss:

- Early Stopping
- HA (Algorithm parameter validation)
- Cleanup (Cleanup suggestions)
- Resume
- User-friendly trial template

**Comment by johnugeorge** [comment]
Tracked

1. Early stopping - https://github.com/kubeflow/katib/issues/692
2. Cleanup- https://github.com/kubeflow/katib/issues/1062, https://github.com/kubeflow/katib/issues/1061
3.  User-friendly trial template - https://github.com/kubeflow/katib/issues/906

**Comment by gaocegege** [comment]
- Persistent storage for suggestion state.
- NAS 
- auto feature engineering

**Comment by johnugeorge** [comment]
UI fixes and enhancements

**Comment by gaocegege** [comment]
@johnugeorge Will you update our Roadmap doc? Or I can help do it.

**Comment by johnugeorge** [comment]
Please go ahead. Thanks
