### ISSUE TITLE
Enrich logging

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#112]
Currently, the logs of Katib components are so poor.
We need enrich logs in the debug, verbose, and info level.
Maybe we should introduce `glog` pkg.

**Comment by gaocegege** [comment]
We prefer logrus in the community, I think. Since it supports structured logging.

**Comment by jlewi** [comment]
@YujiOshima can we make this issue more specific this will make it easier to get help from the community?

Here are some questions for you:

1. Which microservices within Katib should we start logging using logrus
1. What metadata should be included in log entries?
    * In logrus log entries are json records with key-value pairs for metadata
    * So we can attach metadata that is useful for filtering the logs; eg study id
1. Are there metrics that should be exported e.g. via promtheus to allow better monitoring of Katib?

**Comment by YujiOshima** [comment]
Logging Component:
* vizier-core
* SuggestionService
  * Random
  * Grid
  * HyperBand
* EarlyStoppping
  * Median

BayseOpt Suggestion is implemented with python. I don't know which log liberally is better for python.

Metadata:
`StudyID`, `TrialID`, `WorkerID`  or `System`
`System` means the error is not related any study, trial or worker. It is occurred around the component itself.

Integration with Prometheus sounds nice. It enable monitoring across languages.

@gaocegege @jlewi BTW, this library https://github.com/uber-go/zap looks nice since it is faster than logrus. WDYT?

**Comment by gaocegege** [comment]
I love zap, while we are using logrus now. I think we could use zap in katib if you like as a feasibility research.

**Comment by YujiOshima** [comment]
@gaocegege Thanks! Lets's try zap for Katib. As zap is also structured with key-value, we can migrate logrus easily when we need.

**Comment by gaocegege** [comment]
Yeah, I opened an issue here: https://github.com/kubeflow/tf-operator/issues/534

I closed it because I think the performance of the logging is not the bottleneck. If the migration is painless, I am glad to use zap.
