### ISSUE TITLE
Structure for NAS algorithms

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1125]
/kind feature

Since I am planning to support DARTS in Katib, I have few thoughts and questions about current NAS algorithms.

1. Do we want to name each NAS algorithm starting with `nas`. For example: `nasdarts`? Or we can name it with algorithm name, e.g `darts`.
2. Rename `nasrl` to `enas`. I think it will be more clear to user, since we are using ENAS implementation.
3. Do we want to create `nas` directory under [`suggestion` folder](https://github.com/kubeflow/katib/tree/master/pkg/suggestion/v1alpha3). User can easily see what HP and NAS algorithms do we support.

What do you think @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
SGTM. I will add it into 2020 roadmap.

/priority p1

**Comment by andreyvelich** [comment]
What do you think about 1st and 3rd step? @gaocegege @johnugeorge 
Should we name nas algorithms starting with `nas` or just like name of the algorithm?

**Comment by johnugeorge** [comment]
3 looks ok as it is just directory refactoring.

For 1, is it really required? If it needs to be added, I feel that we have to tag existing hp algorithms too.

**Comment by andreyvelich** [comment]
> For 1, is it really required? If it needs to be added, I feel that we have to tag existing hp algorithms too.

No, is it not required. I am just worried how users will distinguish HP and NAS algorithms.
