### ISSUE TITLE
Add validation for algortihms (a.k.a suggestions)

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#1126]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We should validate algorithm settings in the suggestion services.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/priority p1
/kind feature

**Comment by anencore94** [comment]
Could you explain more information about this issue please? Thanks in advance :) @andreyvelich

**Comment by andreyvelich** [comment]
> Could you explain more information about this issue please? Thanks in advance :) @andreyvelich

Sure. We have `ValidateAlgorithmSettings` gRPC call which is used to validate [`spec.algorithmSettings`](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/bayesianoptimization-example.yaml#L15-L17).
For example, in hyperopt Suggestion: https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1beta1/hyperopt/service.py#L57.
We run this request once Suggestion is created: https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/suggestion/suggestion_controller.go#L271.

If `ValidateAlgorithmSettings` fails, Katib controller changes `Suggestion` and `Experiment` status to `failed`.

We should implement this feature in each `Suggestion` which Katib supports.

In addition to that, we have pending PR to implement it in `Chocolate` suggestion: https://github.com/kubeflow/katib/pull/1205.

We would appreciate if you could help us with the implementation for other Suggestions, for example: `skopt`: https://github.com/kubeflow/katib/tree/master/pkg/suggestion/v1beta1/skopt.

**Comment by anencore94** [comment]
Thank you for such a friendly and detailed reply :+1: @andreyvelich 
Sure, I'd like to implement validation for another suggestion algorithms. I agree this feature needs to be implemented. I'll take a look and will send a PR soon.

**Comment by gaocegege** [comment]
Thanks!

**Comment by tenzen-y** [comment]
I take this issue about optuna.

**Comment by tenzen-y** [comment]
I take darts.

**Comment by tenzen-y** [comment]
From what I can see, we have completed implementing validation for all suggestions.
I think that we can close this issue. What do you think? @kubeflow/wg-automl-leads

**Comment by johnugeorge** [comment]
Looks great.

Thanks @tenzen-y and @anencore94

**Comment by johnugeorge** [comment]
Closing this issue as validations are added for all algorithms
