### ISSUE TITLE
Persist meta data of experiments

### ISSUE THREAD

**Issue by sperlingxx** [kubeflow/katib#1128]
/kind feature

**Describe the solution you'd like**
Meta data generated during HPO process is worthy to restore. It can be used to guide subsequent tuning works. Maybe it can also be precious data of further academic research.

To me, since katib has DB abstraction layer _(KatibDBInterface)_ ,  we can extend it to persist meta data such as experiment settings and corresponding trial information (param assignments and metrics).

**Anything else you would like to add:**
In current katib UI system,  visualization will be unavailable once experiment instance deleted. If we can persist all information in DB, it is possible for users to review all history experiments. I think  it will be helpful.
/cc @andreyvelich @gaocegege @richardsliu @hougangliu @johnugeorge

**Comment by sperlingxx** [comment]
@andreyvelich  What do you think of this idea?

**Comment by andreyvelich** [comment]
@sperlingxx Thank you for the issue. SGTM. 
Previously, we stored Experiments search space in the Katib DB as well as metrics.
Currently, ones user deletes Experiment, all Trials metrics are cleaned in the DB.

Maybe we can control it with resuming Experiment flag.

**Comment by sperlingxx** [comment]
@andreyvelich I fully agree with the approach "control it with resuming Experiment flag". Shall we add this issue into 2020 roadmap?

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge Any thoughts?

**Comment by johnugeorge** [comment]
related:https://github.com/kubeflow/katib/pull/1150#discussion_r409626967

**Comment by andreyvelich** [comment]
Resuming Experiment was implemented, feed free to re-open the issue if you have any other questions.

**Comment by pod3275** [comment]
I have one question about this issue.

We can now control whether the Suggestion deploy is deleted after the experiment is finished by setting `ResumePolicy=never` or `ResumePolicy=FromVolume`.

However, Trial, Suggestion, and Experiment CRs still remain.
If we delete Experiment CR, the results of the experiment will not be displayed on the Katib UI.
Managing the number of CRs could be challenging when a large number of experiments are performed.

As discussed at the beginning of this issue, how about adding an option to persist all meta data of the experiment in DB and delete Katib CRs?
