### ISSUE TITLE
[UI Feature] Handle global namespace change from Kubeflow Central Dashboard

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1136]
/kind feature

Currently, after updating namespace in Kubeflow Central Dashboard, user must go to the Central Dashboard main page and open Katib UI again to see this change.
See here: https://github.com/kubeflow/katib/blob/master/pkg/ui/v1alpha3/frontend/src/components/KubeflowDashboard.jsx#L5.

It would be great if we can automatically handle this change directly from the Katib UI.

/area front-end
/area gsoc

**Comment by avdaredevil** [comment]
The SDK has an event that you can bind to, to pick up on namespace changes.
It seems like you are using it [here](https://github.com/kubeflow/katib/blob/master/pkg/ui/v1alpha3/frontend/src/components/KubeflowDashboard.jsx#L21): as `cdeh.onNamespaceSelected = handler`

This event can be expected to be fired multiple times (as the user chooses different namespaces)

**Comment by andreyvelich** [comment]
That should be fixed by: https://github.com/kubeflow/katib/issues/1322.
