### ISSUE TITLE
Suggestion services folder structure

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1144]
/kind feature

Currently, we store all suggestion `<algorithm_name>_service.py` files under `/pkg/suggestion/v1alpha3` directory.

Is there are reason to have structure like that? For example, for Golang Algorithms we have to store service in the same package as other files for the algorithm (See comment: https://github.com/kubeflow/katib/pull/1131#discussion_r406737331).

I think we can add `<algorithm_name>_service.py` files to appropriate algorithm folder. 

For example, `hyperopt_service.py` to https://github.com/kubeflow/katib/tree/master/pkg/suggestion/v1alpha3/hyperopt.
What do you think @gaocegege @johnugeorge @c-bata ?

/cc @richardsliu

**Comment by c-bata** [comment]
I agree with your opinion 👍 

Furthermore I think we can move `/pkg/suggestion/v1alpha3/bayesianoptimization/src` to  `/pkg/suggestion/v1alpha3/bayesianoptimization`.

**Comment by johnugeorge** [comment]
SGTM
