### ISSUE TITLE
[UI Feature] Show Suggestion information in Experiment page

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1148]
/kind feature

Currently, in Experiment view page user can view only Experiment yaml information.
I think it would be useful to show Suggestion CR yaml or Suggestion statuses.

For example, if ValidateAlgorithmSettings fails Experiment fails also and user can see error only in Suggestion CR statuses.

What do you think @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
I think it is an awesome feature!

**Comment by johnugeorge** [comment]
+1

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge Do you have any ideas how to show Suggestion to the user?
We can make another dialog view, like with Experiment with all CR view.

**Comment by gaocegege** [comment]
I am not a UI expert. Personally I think another dialog LGTM
