### ISSUE TITLE
hyperband example

### ISSUE THREAD

**Issue by vinaykakade** [kubeflow/katib#115]
Katib readme mentions hyperband as a supported algorithm, but there isn't an example in the repository. Is it possible to provide an example that uses hyperband?

**Comment by vinaykakade** [comment]
And the code here is commented out: https://github.com/kubeflow/katib/blob/master/pkg/suggestion/hyperband_service.go. Please let us know where we can take a look at the source as well.

**Comment by YujiOshima** [comment]
@vinaykakade Hyperband needs some fix for new version API.
I will update it and add an example!

**Comment by vinaykakade** [comment]
Thank you. Appreciate it @YujiOshima !
