### ISSUE TITLE
Rename Chocolate algorithm names

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1163]
/kind feature

Currently, in Chocolate suggestion we name algorithms starting with `chocolate-`:
https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py#L56-L70.

We should name them by algorithm names, without `chocolate-`, like we did with `grid` to be consistent with other suggestion implementation (e.g Goptuna)

See comments here: https://github.com/kubeflow/katib/pull/1131#discussion_r407955790.

/cc @gaocegege @johnugeorge @c-bata

**Comment by c-bata** [comment]
I'm sorry. Now I noticed this issue and assigned you.
I've just submitted a pull request to https://github.com/kubeflow/katib/pull/1164.
Please feel free to close #1164.

**Comment by andreyvelich** [comment]
@c-bata It is fine, thank you for the PR. I will take a look 👍 
I haven't started yet.
/assign @c-bata

**Comment by c-bata** [comment]
I see. Thank you!
