### ISSUE TITLE
[Feature] Support DARTS in Katib

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1167]
/kind feature

We should support DARTS algorithm in Katib.
I start to work on it.

Original paper: https://arxiv.org/abs/1806.09055.

/area nas

**Comment by gaocegege** [comment]
Ref https://github.com/caicloud/katib/pull/9

**Comment by andreyvelich** [comment]
Check-list to integrate DARTS in Katib:

1. [ ] DARTS Suggestion + Training Container
2. [ ] Build image in the CI, update `katib-config`
3. [ ] Add tests for the service
4. [ ] Update documentation for DARTS

**Comment by gaocegege** [comment]
Ref https://github.com/kubeflow/katib/pull/1175

**Comment by andreyvelich** [comment]
Close this since DARTS is implemented to Katib.
