### ISSUE TITLE
REST api

### ISSUE THREAD

**Issue by vinaykakade** [kubeflow/katib#117]
Is there any plan to provide REST api, in addition to grpc? We have a use-case for REST and could write one using, say grpc-gateway. Will that be something useful to the community here?

cc @YujiOshima

**Comment by lluunn** [comment]
cc @lluunn

**Comment by YujiOshima** [comment]
It would be easy to add by using grpc-gateway.
@lluunn Does it will be useful for your issue #117?
If the CLI will use REST, you won't need to care about grpc.

**Comment by lluunn** [comment]
I guess you mean https://github.com/kubeflow/katib/issues/118.
Yes I think so.

**Comment by YujiOshima** [comment]
fixed by #142 
/close
