### ISSUE TITLE
OpenAPI validation for Katib CRs - prevent invalid specs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#1170]
/kind feature

I'm getting customer reports that invalid Experiment specs lead to experiments being stuck. 

This is a common failure mode with custom resources; if the resource spec is invalid the resource will get created but when the controller tries to parse it the parsing will fail.

I think the new/recommended way of handling this might be to use OpenAPI schema validation in the CRD.
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

It looks like Katib CRDs might be missing this
https://github.com/kubeflow/manifests/blob/master/katib/katib-crds/base/experiment-crd.yaml

**Comment by johnugeorge** [comment]
@jlewi  Can you explain more on the invalid experiment specs that get created? Katib already has a validating webhook

**Comment by gaocegege** [comment]
Kubebuilder supports generating OpenAPI schema for CRDs. I think we can support it in the next API version. (v1beta1, maybe)

**Comment by jlewi** [comment]
I believe the customer was passing names which were too long for the experiments and this caused the controller to stop working.
