### ISSUE TITLE
Make Katib work with reverse proxy and ambassador

### ISSUE THREAD

**Issue by lluunn** [kubeflow/katib#118]
- ModelDB UI is now only accessible by port-forwarding. We should make it work with reverse proxy and ambassador.
- vizier-core is also used via port-forwarding. It's a gRPC service, so need the ingress that supports gRPC.

**Comment by swiftdiaries** [comment]
Would like to take this up if someone isn't already working on this.

**Comment by lluunn** [comment]
@swiftdiaries You can take it if you want, I haven't started.
But for vizier-core, it might depend on #117

**Comment by swiftdiaries** [comment]
Oh ok I'll wait on this.

**Comment by jlewi** [comment]
The result is the same with Ambassador so doesn't seem to be an issue with IAP.

**Comment by jlewi** [comment]
I had some success changing the Ambassador route from

      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: modeldb-mapping
      prefix: /modeldb/
      rewrite: /
      method: GET
      service: modeldb-frontend.kubeflow:3000

to
  ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: modeldb-mapping
      prefix: /katib/
      rewrite: /katib/
      method: GET

When i looked in the Ambassador logs I was seeing some 504's to /katib. It looks like we configure katib to be rooted at "/katib" so that might explain why we need the mapping to start with "/katib"
