### ISSUE TITLE
Pull Request #1176 broke backward compatibility

### ISSUE THREAD

**Issue by sperlingxx** [kubeflow/katib#1186]
/kind bug

**What steps did you take and what happened:**
The refactoring of metric schema in this [commit](https://github.com/kubeflow/katib/commit/2d35d5583e033645848c7d585628c6212b47cc2c) made the schema of `TrialStatus.Observation` incompatible with legacy trials (because float metric value in legacy trials can't be parsed as string value).  So, the trial controller will crash after updating to latest master.

**What did you expect to happen:**
In my opinion, we had better to fix this problem. Otherwise, users have to evict all existing trials before updating katib. Maybe we can keep the original float64 field `value`, and add another string field like `non_numeric_value` (which stores non-numeric metric value). If field`non_numeric_value` is set, then take value of this field as metric value; If not, take value of original field `value`. 

What do you think ? @andreyvelich @gaocegege

**Comment by gaocegege** [comment]
How about creating a new version v1beta1 @johnugeorge @andreyvelich

**Comment by andreyvelich** [comment]
Good point @sperlingxx.

I am not sure that we should duplicate parameters in API. That can increase API complexity. 
Currently, we don't have stable Katib API and versions update mechanism, Katib is in alpha version. 
I think, if users don't want to use Kubeflow 1.0 version with 0.8 Katib version and use latest Katib release, they should restart running Experiment or they can have more errors.

I am ok with reverting this commit from upstream now and push it to the new version (v1beta1).

What do you think @johnugeorge @gaocegege ?

**Comment by gaocegege** [comment]
SGTM

**Comment by sperlingxx** [comment]
@andreyvelich  The approach ( "reverting this commit from upstream now and push it to the new version (v1beta1)" ) looks great. And when we setup v1beta1?

**Comment by andreyvelich** [comment]
@johnugeorge @gaocegege Do we want to try to resolve some p0/p1 tasks before new release?

**Comment by gaocegege** [comment]
I think we can do it now and start developing on v1beta1. WDYT @johnugeorge

**Comment by johnugeorge** [comment]
Agree. @gaocegege Lets work on v1beta1 api and get all new api changes in v1beta1
