### ISSUE TITLE
Katib Experiment Graph is not shown

### ISSUE THREAD

**Issue by sakaia** [kubeflow/katib#1196]
/kind bug

**What steps did you take and what happened:**
I can successfully execute the random-experiment but graph is not shown (empty).
But I can see result of execution in text 

<img width="809" alt="katib" src="https://user-images.githubusercontent.com/144597/82780526-6aa78a00-9e92-11ea-9ac7-89dd16073924.png">
<img width="809" alt="katib1" src="https://user-images.githubusercontent.com/144597/82780600-afcbbc00-9e92-11ea-8987-9dd62c3b2341.png">

**What did you expect to happen:**
I can run the code with graph output. (item 6
 Figure)
[example-using-random-algorithm](https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/#example-using-random-algorithm)

**Anything else you would like to add:**

**Environment:**

- Kubeflow version:1.0.2
- Minikube version:microk8s 
- Kubernetes version: (use `kubectl version`):15.1
- OS (e.g. from `/etc/os-release`):ubuntu 19.10

**Comment by andreyvelich** [comment]
@sakaia Can you check logs from `katib-ui` pod, please?

**Comment by sakaia** [comment]
Thank you My katib-ui pod logs are follows. but, still graph is not shown.

```
kubectl logs katib-ui-6f97756598-gclzx -n kubeflow
```

```
2020/05/26 23:25:23 Serving the frontend dir /app/build
2020/05/26 23:25:23 Serving at 0.0.0.0:8080
2020/05/26 23:32:07 Got Experiment
2020/05/26 23:32:07 Got metrics names
2020/05/26 23:32:07 Got Parameters names
2020/05/26 23:32:07 Got Trial List
2020/05/26 23:32:07 Logs parsed, results:
 trialName,Status,Validation-accuracy,accuracy,--lr,--num-layers,--optimizer
2020/05/26 23:32:25 Got Experiment
2020/05/26 23:32:25 Got metrics names
2020/05/26 23:32:25 Got Parameters names
2020/05/26 23:32:25 Got Trial List
2020/05/26 23:32:25 Logs parsed, results:
 trialName,Status,Validation-accuracy,accuracy,--lr,--num-layers,--optimizer
2020/05/26 23:32:33 Got Experiment
2020/05/26 23:32:33 Got metrics names
2020/05/26 23:32:33 Got Parameters names
2020/05/26 23:32:33 Got Trial List
2020/05/26 23:32:33 Logs parsed, results:
 trialName,Status,Validation-accuracy,accuracy,--lr,--num-layers,--optimizer
random-experiment-9h7kxz48,Running,,,0.014115112699862925,5,ftrl
random-experiment-mq9rkr8q,Running,,,0.015907948511341558,2,ftrl
random-experiment-z9ck29hh,Running,,,0.013710131519663613,3,ftrl
2020/05/26 23:39:16 Got Experiment
2020/05/26 23:39:16 Got metrics names
2020/05/26 23:39:16 Got Parameters names
2020/05/26 23:39:16 Got Trial List
2020/05/26 23:39:16 Logs parsed, results:
 trialName,Status,Validation-accuracy,accuracy,--lr,--num-layers,--optimizer
random-experiment-8k4f75w9,Succeeded,0.113854,0.121719,0.024844551620860085,3,ftrl
random-experiment-9h7kxz48,Succeeded,0.113854,0.121906,0.014115112699862925,5,ftrl
random-experiment-9tfq8gcb,Succeeded,0.113854,0.120938,0.027901018829838475,2,ftrl
random-experiment-c4vl6rck,Succeeded,0.113854,0.122969,0.02976483919797447,3,ftrl
random-experiment-dxsqpqq6,Succeeded,0.978603,0.996250,0.017494586655338925,3,sgd
random-experiment-h295h7lc,Running,,,0.027933050705964572,2,sgd
random-experiment-ltdbrpwf,Running,,,0.025982093612760965,4,ftrl
random-experiment-mq9rkr8q,Succeeded,0.113854,0.124219,0.015907948511341558,2,ftrl
random-experiment-rskwmqc6,Succeeded,0.113854,0.122656,0.011650364554826508,2,ftrl
random-experiment-sknhmt9l,Succeeded,0.113854,0.123906,0.018498079446027316,4,ftrl
random-experiment-sp76xt94,Running,,,0.021721815138828454,4,adam
random-experiment-z9ck29hh,Succeeded,0.113854,0.125156,0.013710131519663613,3,ftrl
```

**Comment by andreyvelich** [comment]
@sakaia Thanks, logs are looking good.

Try to update this page few times and check errors inside the Google Chrome console.
Also, try to click on any Trial name and see if Metrics Graph is shown.

**Comment by sakaia** [comment]
Thank you for your suggestion.

It seems following file problem (on jsx). Is there any good way to monitor it?

pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx

(react-ploty.js seems drwaring soft for graph?)

**Comment by andreyvelich** [comment]
@sakaia Yes, we are using `react-plotly.js` to draw this plot. 
I think you can check frontend errors in the browser console.
Maybe you need to enable JS in your browser?

Or try to disable cache in the console and refresh page:
<img width="1079" alt="Screenshot 2020-05-27 at 17 55 10" src="https://user-images.githubusercontent.com/31112157/83049762-725a6080-a043-11ea-83e7-911e26f0d287.png">

**Comment by sakaia** [comment]
Thank you for your suggestion.
I try to disable cache but the problem still remain.
app bundle returns 503. Is there any way to digging this?

<img width="926" alt="katibhpgithub" src="https://user-images.githubusercontent.com/144597/83088981-25709b80-a0d0-11ea-95ef-fb119192ba05.PNG">

**Comment by gaocegege** [comment]
Can you show us the request detail of the 503 request?

**Comment by sakaia** [comment]
Is this view help to investigate?

<img width="924" alt="katibgithub2" src="https://user-images.githubusercontent.com/144597/83089668-d9bef180-a0d1-11ea-8dd0-fcac2c015422.PNG">

**Comment by sakaia** [comment]
PS. I can see nas graph. but I still cannot see HP graph.

<img width="859" alt="katibnas1" src="https://user-images.githubusercontent.com/144597/83115165-f4f72480-a104-11ea-92ba-5e254062b35b.PNG">

**Comment by andreyvelich** [comment]
@sakaia Can you try to update your `katib-ui` deployment image to the latest. You don't need to redeploy all Kubeflow components, just run: `kubectl edit deploy katib-ui -n kubeflow` and modify the container image to: `gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui`.
After that, the `katib-ui` pod will be restarting.

Then, try to access Katib UI using port-forwarding:
`kubectl port-forward svc/katib-ui 8080:80 -n kubeflow`.

You should be able to access Katib UI with this URL: http://localhost:8080/katib.
Try if it works for you.

**Comment by sakaia** [comment]
Thank you after updating from v0.8.0 to nothing.
Web UI error is changed to follows.
Even I enable WebGL on chrome,  the problem still keeps

<img width="857" alt="katibhpgithub2" src="https://user-images.githubusercontent.com/144597/83223770-b91c9780-a1b6-11ea-9e38-4f1c55bf9bb3.PNG">

My environment is follows.

Google Chrome | 81.0.4044.138 (Official Build) （64 ビット）
-- | --
変更履歴 | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Windows 8.1 (Build 9600)
JavaScript | V8 8.1.307.32
Flash | 24.0.0.189 internal-not-yet-present
ユーザー エージェント | Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
コマンドライン | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --enable-audio-service-sandbox --flag-switches-begin --enable-webgl-draft-extensions --enable-webgl2-compute-context --flag-switches-end --enable-audio-service-sandbox
実行ファイルのパス | C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

**Comment by andreyvelich** [comment]
@sakaia Thanks, at least we can see the error now.
Maybe try to disable `--enable-webgl-draft-extensions --enable-webgl2-compute-context` flags.
Try to visit https://get.webgl.org/ to see if WebGL works in your browser after it.
