### ISSUE TITLE
Rename algorithm setting in manager

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1203]
/kind bug

I think we should rename `algorithm_setting` to `algorithm_settings` in manager (https://github.com/kubeflow/katib/blob/master/pkg/apis/manager/v1beta1/api.proto#L107) to be consistent with other `repeated` values.

We also named it `algorithmSettings` in Experiment API (https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/common/v1beta1/common_types.go#L26).

We can make this change in new v1beta1 version.

/cc @johnugeorge @gaocegege

**Comment by gaocegege** [comment]
LGTM
