### ISSUE TITLE
Support new Trial Template in v1beta1

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1208]
/kind feature

To support new Trial Template API in v1beta1 we need to make few changes:
- [x] Submit new API changes (https://github.com/kubeflow/katib/pull/1202).
- [x] Change Controller logic to support new Template. Also, modify Trial CR API (https://github.com/kubeflow/katib/pull/1202).
- [x] Change examples according to the new API (https://github.com/kubeflow/katib/pull/1202).
- [x] Enable testing for v1beta1 (https://github.com/kubeflow/katib/pull/1202).
- [x] Modify validation webhook. Make sure that `metadata.name` and `metadata.namespace` in `TrialSpec` is omitted (https://github.com/kubeflow/katib/pull/1215).
- [x] Add more test-cases for `generator.go` (https://github.com/kubeflow/katib/pull/1216).

If I missed something, please let me know.
/cc @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
I will start work on the second step.

@gaocegege @johnugeorge What do you think about [`RunSpec`](https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/trials/v1beta1/trial_types.go#L35) in Trial CR API, should we make it `unstructured` and store current Trial specification?

**Comment by gaocegege** [comment]
I think we should use unstructured.

**Comment by andreyvelich** [comment]
We can close this issue, since we fully implemented this.
