### ISSUE TITLE
Katib Acceleration using FPGAs

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/katib#1209]
Per Chris Kachris from InAccel:

> We have managed to integrate it FPGAs for XGBoost in order to speedup the tuning by more than 4.5x. You can check the relevant video and the blog.
> * https://inaccel.com/accelerate-ml-workflows-with-kubeflow-using-inaccel-fpga-orchestrator/
> * https://www.youtube.com/watch?v=5_IMstcic6E
> 
> We would be glad to further discuss how we can contribute on Katib and further promote it.

Let's continue our discussion here so it's transparent to the community.

/kind feature

**Comment by terrytangyuan** [comment]
cc @johnugeorge @richardsliu @gaocegege @hougangliu @andreyvelich

**Comment by kachris** [comment]
Thanks Terry.
you can find detailed instructions on how to test it on your own here:
https://docs.inaccel.com/labs/kubeflow/

**Comment by andreyvelich** [comment]
@kachris Thank you for the presentation today.

As I said before, I think it would be great if you can add your Katib Experiment yaml and maybe README with link to your example to the `examples/` folder. So others can see that they can use FPGAs with Katib.

Also, if you have any ideas about improving Katib UI, please let me know.

**Comment by andreyvelich** [comment]
Examples was created. We can close it.
