### ISSUE TITLE
Katib cut release for Kubeflow 1.1 

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1211]
/kind feature

We should make new release for Kubeflow 1.1. We need to update manifests and website documentation.

1. For manifests my suggestion is to take this commit: https://github.com/kubeflow/katib/commit/5df1bd2836f1b9ba1e7c4c4a5c6ab48ae21c62b0. It is the latest commit when we build images for v1alpha3 (https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/katib/v1alpha3/katib-controller?gcrImageListsize=30). What do you think @gaocegege @johnugeorge ?

TODOs list for manifests update (https://github.com/kubeflow/manifests/pull/1239):
- [x] Update Katib-UI RBAC. Ref issue: https://github.com/kubeflow/katib/issues/1165.
- [x] Submit new labeled Trial Template (trialTemplateConfigmapLabeled.yaml). Ref PR: https://github.com/kubeflow/katib/pull/1083.
- [x] Rename nasrl to enas in katib-config. Ref PR: https://github.com/kubeflow/katib/pull/1143.
- [x] Add cmaes to katib-config. Ref PR: https://github.com/kubeflow/katib/pull/1154.
- [x] Add darts to katib-config. Ref PR: https://github.com/kubeflow/katib/pull/1178.

2. TODOs list for website documentation update.
- [x] Get merged https://github.com/kubeflow/website/pull/1907.
- [x] Rename nasrl to enas in docs. Make sure that all links work. Ref PR: https://github.com/kubeflow/katib/pull/1143. (https://github.com/kubeflow/website/pull/1989).
- [x] Add information about running experiment without the goal. Ref PR: https://github.com/kubeflow/katib/pull/1065. (https://github.com/kubeflow/website/pull/1983).
- [x] Update Katib UI pictures on the website. (https://github.com/kubeflow/website/pull/1989).
- [x] Add DARTS algorithm to nas list. Ref PR: https://github.com/kubeflow/katib/pull/1175. (https://github.com/kubeflow/website/pull/1991).
- [x] Add information about Katib SDK. Ref PR: https://github.com/kubeflow/katib/pull/1177. (https://github.com/kubeflow/website/pull/1990).
- [x] Add information about `ResumePolicy`. Ref PR: https://github.com/kubeflow/katib/pull/1150. (https://github.com/kubeflow/website/pull/1995).
- [x] Add information about new algorithm CMAES. Ref PR: https://github.com/kubeflow/katib/pull/1131. (https://github.com/kubeflow/website/pull/1993).

If I missed something, please let me know. 
/cc @gaocegege @johnugeorge @c-bata @sperlingxx @jlewi 

/priority p0

**Comment by johnugeorge** [comment]
What does it mean by TODO list? We just need to update the latest built images in manifest. right?

**Comment by c-bata** [comment]
Thank you for mentioning me. Recently I'm busy. So can someone handle https://github.com/kubeflow/website/pull/1907 on behalf of me?

**Comment by andreyvelich** [comment]
> What does it mean by TODO list? We just need to update the latest built images in manifest. right?

To keep manifests and website documentation up-to-date, I think we should make these changes.

**Comment by andreyvelich** [comment]
All website and manifest changes have been merged.
Do we need to cut new release (https://github.com/kubeflow/katib/releases) ?
What do you think @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
SGTM.

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge Any ideas about the name? Should we name it v0.9.0-alpha, sine the latest image tag was v0.8.0 ?

**Comment by andreyvelich** [comment]
I published new release v0.9.0: https://github.com/kubeflow/katib/releases/tag/v0.9.0. 
@gaocegege @johnugeorge If you want to add some more information to description, let me know.

**Comment by johnugeorge** [comment]
LGTM

**Comment by jlewi** [comment]
* the apps cd pipelines have been fixed
* application owners please review PRs to update your apps and ensure they get merged
    * https://github.com/kubeflow/manifests/pulls/kubeflow-bot

**Comment by jlewi** [comment]
@andreyvelich @johnugeorge any update?

**Comment by andreyvelich** [comment]
@jlewi It was done 2 weeks ago, we can close it.

**Comment by andreyvelich** [comment]
I have updated `v0.9.0` Katib images tags to correct [Release commit - 917164a](https://github.com/kubeflow/katib/commit/917164a3cb2b1f246abd6396172a2b232e672a7d) for this release in the GCR. 
Before that, `v0.9.0` tag was pointed to wrong commit.

For example, `katib-controller` images: https://console.cloud.google.com/gcr/images/kubeflow-images-public/GLOBAL/katib/v1alpha3/katib-controller?project=kubeflow-images-public&gcrImageListsize=30.

Users can use `v0.9.0` tag instead of `917164a`, if they want to.

/cc @gaocegege @johnugeorge @jlewi
