### ISSUE TITLE
Unable to parse NaN value in Trial CR

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1227]
/kind bug

I tried to run Experiment with additional metric names that were not collected from the Trial pod.

Because of that, in Trial Controller we try to write [`math.NaN()`](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller_util.go#L175-L176) value to observation and Trial can't be updated.

I got error [here](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller.go#L192-L199) while comparing Trial statuses.
I am not sure that Kubernetes objects supports `math.NaN()`, since it must be valid JSON.

We should think how we can handle empty metric results.

This issue can be related to https://github.com/kubeflow/katib/issues/889.

/cc @sperlingxx @gaocegege @johnugeorge

**Comment by sperlingxx** [comment]
In addition, I think we should fail the trial if job is succeed without any ObservationLog, which are usually caused by incorrect metrics collecting configuration. Currently, trial status will be locked at pending under this situation.

**Comment by andreyvelich** [comment]
@sperlingxx As you can see here: https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller_util.go#L126-L139, we convert Trial to succeeded state only if any observation was reported.

My suggestion for this issue is to convert all API metrics parameters to "string". 
1. As you can see here: https://github.com/kubernetes-sigs/controller-tools/issues/245 it is recommended by Kubernetes.
2. We can add [initial state](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller_util.go#L173-L178) for max, min, latest as "not reported". So user can see which metrics were reported and which were not.

What do you think @sperlingxx @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
SGTM.

**Comment by johnugeorge** [comment]
Sgtm

**Comment by andreyvelich** [comment]
Will make this change.
/assign @andreyvelich
