### ISSUE TITLE
adding trial template error if there is no previous trial template

### ISSUE THREAD

**Issue by evonit** [kubeflow/katib#1234]
/kind bug

**What steps did you take and what happened:**
In Katib UI, Ive deleted my previous (provided by default) trial template.
and when I tried to add a new one, then there is no change.
when I checked the chrome developer console, I found that the url /katib/update_template got 503 error response.
So, I started to debug from where I got the error, and I found using by k8s dashboard in katib ui pod.
katib ui log shows me the below error:

---------------
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
2020/06/24 02:21:32 http: panic serving 192.168.3.247:51390: assignment to entry in nil map
goroutine 242 [running]:
net/http.(*conn).serve.func1(0xc0001e6000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x116dd80, 0x1457fb0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kubeflow/katib/pkg/ui/v1alpha3.(*KatibUIHandler).updateTemplates(0xc0005e3350, 0xc00062a540, 0x12d3600, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0004a6000, 0xc00020fc38)
	/go/src/github.com/kubeflow/katib/pkg/ui/v1alpha3/util.go:70 +0x456
github.com/kubeflow/katib/pkg/ui/v1alpha3.(*KatibUIHandler).AddEditDeleteTemplate(0xc0005e3350, 0x149b340, 0xc0004a6000, 0xc0002b6300)
	/go/src/github.com/kubeflow/katib/pkg/ui/v1alpha3/backend.go:156 +0x1d2
net/http.HandlerFunc.ServeHTTP(0xc0005e3450, 0x149b340, 0xc0004a6000, 0xc0002b6300)
...
-------------------

I checked the katib source code and I found the trial template configmap is empty.
So, Ivs restored the configmap back to the default, and now adding function is ok.

**What did you expect to happen:**
either 1) katib ui prevents from deleting all trial templates
      or 2) allow no trial templates
 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 1.0.1
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.15
- OS (e.g. from `/etc/os-release`): centos 7

**Comment by andreyvelich** [comment]
@evonit Thank you for reporting this!
What version of `katib-ui` image are you using ?

**Comment by evonit** [comment]
@andreyvelich 
I am using kubeflow 1.0.1 in which katib 0.8.0 version is running.

**Comment by andreyvelich** [comment]
@evonit Please, try to use latest Kubeflow release on master.
It has all latest Katib UI fixes with the new view for Trial template editor: https://github.com/kubeflow/manifests/blob/master/katib/katib-controller/base/kustomization.yaml#L32-L33.

**Comment by evonit** [comment]
@andreyvelich 
Ive tried to re-install the latest version of kubeflow, 1.0.2.
Still I got the same problem that If I remove all the trial template then I cannot add a new one.

**Comment by andreyvelich** [comment]
@evonit Can you check version of image for `katib-ui` deploy ?
`kubectl describe deploy katib-ui -n kubeflow`

**Comment by evonit** [comment]
katib 0.8.0 @andreyvelich

**Comment by andreyvelich** [comment]
@evonit Please, try to use this latest kfdef to deploy Kubeflow: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml.
It should use latests images for Katib v1alpha3 with working Trial template editor for Katib UI.

**Comment by evonit** [comment]
@andreyvelich I already use the latest version using by the official kubeflow guide
https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml

**Comment by andreyvelich** [comment]
@evonit Yeah, because Kubeflow website is not updated yet to 1.1 version: https://www.kubeflow.org/docs/started/getting-started/#configuration-quick-reference. With config that you mentioned your Katib version is v0.8.0.

If you want to use istio-dex config, please try to use this kfdef: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.yaml, which is referenced to the master manifest branch.

**Comment by evonit** [comment]
@andreyvelich do you mean that I need to downgrade from 1.0.2 to 1.0.0?

**Comment by andreyvelich** [comment]
> @andreyvelich do you mean that I need to downgrade from 1.0.2 to 1.0.0?

How did you deploy Kubeflow, using website or CLI?

**Comment by evonit** [comment]
@andreyvelich I followed this guide, https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/
installing on linux using by cli shell command

**Comment by andreyvelich** [comment]
Can you follow these steps:
1. On [step 1](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#prepare-your-environment) download kfctl 1.1: https://github.com/kubeflow/kfctl/releases/tag/v1.1-rc.0, instead of kfctl v1.0.2.
2. On [step 1](https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#prepare-your-environment), when you setup **`${CONFIG_URI}`**, please set it to: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.yaml:
`export CONFIG_URI=https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.yaml`

After that, you should be able to deploy Kubeflow from the master manifest branch with the latest images version.

**Comment by evonit** [comment]
@andreyvelich 
Hi, I have installed the latest version of Katib.
It is totally changed, applied the multi-user feature into Katib, Good!
Could you tell me when kubeflow 1.1 ga is going to be released? ( I saw the roadmap page, was planned late June.)

**Comment by andreyvelich** [comment]
@evonit Great!
I am not sure about the date, maybe end of the July.
It will be released when all Kubeflow components will be ready.
You can track this issue: https://github.com/kubeflow/kubeflow/issues/5022 for the status.
