### ISSUE TITLE
[Documentation] Add information about Katib controller flags

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1239]
/kind feature

As we can see here: https://github.com/kubeflow/katib/blob/master/cmd/katib-controller/v1beta1/main.go#L48-L55, user can specify flags for the Katib Controller.
I think it would be good if we can document this information in Kubeflow website or in [developer guide](https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md).

/good-first-issue
/area docs

**Comment by annajung** [comment]
Opened up a PR to address the documentation. Please take a look when you can @andreyvelich

**Comment by andreyvelich** [comment]
Thank you so much for doing this @annajung!
I will take a look soon.
