### ISSUE TITLE
Is releaser working?

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#126]
The releasing workflow was added #113.
I expect to push images to `gcr.io/kubeflow-ci/vizier-core`, `gcr.io/kubeflow-ci/suggestion-random` etc.
But I can't find the images.
@jlewi @gaocegege How to check the releasing workflow status? Do we need to do something for building releasing?

**Comment by kunmingg** [comment]
@YujiOshima 
Workflow defined [here](https://github.com/kubeflow/katib/blob/master/releasing/prow_config_release.yaml) duplicate with release workflows defined in [kubeflow repo config file](https://github.com/kubeflow/kubeflow/blob/master/releasing/prow_config_release.yaml)
Can we migrate katib release workflow's ksonnet app to kubeflow repo?
I think [pytorch](https://github.com/kubeflow/kubeflow/tree/master/releasing/pytorch-operator) is a good example: having it's own repo while release workflow is in kubeflow repo.
[Docs for releasing](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md#image-auto-release)
Sorry for the inconvenience.

**Comment by kunmingg** [comment]
I can help reviewing the PR and keep eye on image registry. Thanks!

**Comment by YujiOshima** [comment]
@kunmingg Thank you for your help! I will open PR on kubeflow repp.

**Comment by YujiOshima** [comment]
@kunmingg I opened PR! https://github.com/kubeflow/kubeflow/pull/1102

**Comment by jlewi** [comment]
@YujiOshima is this fixed?

**Comment by YujiOshima** [comment]
Yes, we can close this.
