### ISSUE TITLE
[UI Feature] Monitor Experiment dynamically

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1278]
/kind feature

Currently, on Experiments monitor and Experiment info page user has to refresh page to see updated information.

We can add timer on these pages to automatically fetch new information every "x" seconds.

**Comment by andreyvelich** [comment]
That should be fixed in the new UI as part of: https://github.com/kubeflow/katib/pull/1427.
cc @kimwnasptd .

**Comment by kimwnasptd** [comment]
I'm also looking into ways to even remove the polling mechanism and have the UI perform a watch operation instead, which will be more efficient.

But I'll provide more updates once I've finished my researched and am satisfied with the implementation.
