### ISSUE TITLE
Add a link to Katib to the Central UI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#128]
We should add a link to  Katib in the central UI.

Ideally we would either

1. Always deploy Katib so the link would always work
1. Only show the link if Katib is deployed.

1 Is probably simpler.

**Comment by jlewi** [comment]
@swiftdiaries Do you want to pick this up?

**Comment by jlewi** [comment]
Is there an easy way to add a flag to the central UI that controls whether a link is shown or not? Then we could just add a ksonnet parameter to control whether or not to enable the link

**Comment by swiftdiaries** [comment]
https://github.com/kubeflow/kubeflow/pull/1242. 
Let me look at adding a ksonnet param to enable or disable the link.

**Comment by swiftdiaries** [comment]
It doesn’t add a ksonnet parameter though.

**Comment by jlewi** [comment]
So does that mean we just always have the link?

**Comment by swiftdiaries** [comment]
It checks if the katib pods are deployed and enables/disables the link now.

**Comment by jlewi** [comment]
That's great.

@swiftdiaries Can we mark this issue as fixed or is there more work to be done?

**Comment by swiftdiaries** [comment]
It's done. We can close this. 
/close
