### ISSUE TITLE
Upgrade Goptuna to v0.8.0 which supports IPOP-CMA-ES and BIPOP-CMA-ES.

### ISSUE THREAD

**Issue by c-bata** [kubeflow/katib#1283]
/kind feature

**Describe the solution you'd like**

I've just released [Goptuna v0.6.0](https://github.com/c-bata/goptuna/releases/tag/v0.6.0). It includes IPOP-CMA-ES and BIPOP-CMA-ES supports. As the benchmark results of two-dimensional [Rastrigin function](https://www.sfu.ca/~ssurjano/rastr.html) shows, these algorithms outperforms on multimodal functions.

![rastrigin-function-dim-2-1a14f4610cabf55e51b3b006bfe723dcadef3a57d9eb5c82a09c2c9fbb804c42](https://user-images.githubusercontent.com/5564044/88657031-35c2e800-d10c-11ea-869b-c84a8420dcd1.png)

* [Auger, A., Hansen, N.: A restart CMA evolution strategy with increasing population size. In: Proceedings of the 2005 IEEE Congress on Evolutionary Computation (CEC’2005), pp. 1769–1776 (2005a)](https://sci2s.ugr.es/sites/default/files/files/TematicWebSites/EAMHCO/contributionsCEC05/auger05ARCMA.pdf)
* [Hansen N. Benchmarking a BI-Population CMA-ES on the BBOB-2009 Function Testbed. In the workshop Proceedings of the Genetic and Evolutionary Computation Conference, GECCO, pages 2389–2395. ACM, 2009.](https://hal.inria.fr/inria-00382093/document)

**TODOs**

* [ ] Add Katib options to enable IPOP-CMA-ES and BIPOP-CMA-ES.
* [ ] Remove the use of deprecated APIs (Some study options are renamed).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
@c-bata Thank you very much for contributing with this!

I think you can directly add changes for v1beta1 version, since v1alpha3 has been already released and we have plans to release v1beta1 later.

**Comment by gaocegege** [comment]
Cool! Thanks for the awesome work.

**Comment by c-bata** [comment]
Probably I will be able to open a pull request next month.

Goptuna now supports Sobol's quasirandom sequence at v0.8.0.
https://github.com/c-bata/goptuna/releases/tag/v0.8.0

**Comment by andreyvelich** [comment]
That's great, thank you for your help @c-bata!
