### ISSUE TITLE
Disable unit test in travis-ci.org

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1296]
/kind feature

See comment: https://github.com/kubeflow/katib/pull/1288#issuecomment-668307242.
Currently, Katib unit tests are running on [`travis-ci.com`](https://travis-ci.com/github/kubeflow/katib/builds) and [`travis-ci.org`](https://travis-ci.org/github/kubeflow/katib/builds). 
We should disable `travis-ci.org` tests since it is outdated version.

/cc @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
@Bobgy @jlewi Can you help us to disable `travis-ci.org` for Katib here: https://travis-ci.org/organizations/kubeflow/repositories, please?
It seems I don't have sufficient permissions to do it.

Currently, under Katib the CI runs 2 Travis: `travis-ci.org` and `travis-ci.com`.

**Comment by Bobgy** [comment]
Hi @andreyvelich! I've disabled it.
Let me know if it doesn't work

**Comment by andreyvelich** [comment]
As I can see it was removed: https://github.com/kubeflow/katib/pull/1391. It uses only `travis-ci.com`.
Thank you so much @Bobgy!
