### ISSUE TITLE
What is the role of the additional metric?

### ISSUE THREAD

**Issue by devxoxo** [kubeflow/katib#1301]
/kind feature

I referenced [the source code](https://github.com/kubeflow/katib/blob/8aaf8647725a458d963376da0747f4f3d6bdc44a/pkg/ui/v1alpha3/hp.go).
But I couldn't fully understand what the additional metric does.

In this case, which trial does Katib recognize as OptimalTrial?
* random algorithm 
* f1_score is an objective metric and accuracy is an additional metric

trial | f1_score | accuracy 
trial1 | 97.0 | 75.0
trial2 | 98.0 | 70.0

**Comment by andreyvelich** [comment]
@devxoxo Additional metrics is used just for metrics collector to save additional values to the DB and show in the UI in Trial information plot.

In your example, `f1_score` is used to find Optimal Trial and `accuracy` should be collected from training container to the `observation_logs` mysql DB table.

**Comment by devxoxo** [comment]
@andreyvelich Thank you. It was really helpful!
