### ISSUE TITLE
[Documentation] Metrics strategies information

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1310]
/kind feature

We should document how user can specify [`MetricStrategies`](https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/common/v1beta1/common_types.go#L55) in Experiment.

/cc @sperlingxx @johnugeorge @gaocegege

**Comment by sperlingxx** [comment]
Great idea! And I can take this job if necessary.

**Comment by gaocegege** [comment]
LGTM

**Comment by andreyvelich** [comment]
That would be awesome, thanks @sperlingxx!
I think you can submit PR directly to Kubeflow website.
