### ISSUE TITLE
Maintaining python SDK versions

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1331]
/kind feature

How we want to maintain our python SDK package version located here: https://pypi.org/project/kubeflow-katib/?
Do we want to change version for each time when we update SDK or upload only release version of API?

As well, @prem0912 can you give us Owner permission to manage this package, please?
Currently, I can't give new permissions or view the package options.

/cc @sperlingxx @gaocegege @johnugeorge

**Comment by prem0912** [comment]
@andreyvelich  given Owner permission

**Comment by andreyvelich** [comment]
Thank you for your help @prem0912!
