### ISSUE TITLE
Namespace for workers is hardcoded

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#134]
It looks like the namespace used to launch jobs is hardcoded here
https://github.com/kubeflow/katib/blob/master/pkg/manager/worker/kubernetes/kubernetes.go#L212

This was causing my HP job to fail with

```
2018/06/29 18:38:47 RunTrial Error rpc error: code = Unknown desc = namespaces "katib" not found
```

It would probably make more sense to make the namespace configurable.

I think this is part of a larger issue about how much control users have over the "Job spec" used to train individual models. For example, what if we wanted to train models distributing using TFJob as opposed to using a K8s job?

**Comment by YujiOshima** [comment]
@jlewi Yes, we can close this. It is fixed, we can use a flexible template.
/close
