### ISSUE TITLE
[Documentation] New Trial template design

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1341]
/area docs

We should document our new trial template design and how to use new CRD in the Trial template.

Since user doesn't need to manually modify controller source code to support new CRD, do we need [new-trial-kind](https://github.com/kubeflow/katib/blob/master/docs/new-trial-kind.md) in our Katib repository ?
Or it is better to add this information under https://www.kubeflow.org/ website ?

@gaocegege @johnugeorge What do you think ?

**Comment by gaocegege** [comment]
LGTM
