### ISSUE TITLE
Katib standalone deployment has certificate issues

### ISSUE THREAD

**Issue by sadeel** [kubeflow/katib#1347]
/kind bug

**What steps did you take and what happened:**

1.  I installed Katib (standalone) on my GKE cluster using the following commands:
git clone git@github.com:kubeflow/katib.git
bash katib/scripts/v1beta1/deploy.sh

2. I launched a sample hyperparameter tuning job and ran into the following issue with the katib-controller
 
{"level":"info","ts":1600888893.660251,"logger":"trial-controller","msg":"Job watch error. CRD might be missing. Please install CRD and restart katib-controller","CRD Kind":"TFJob"}
{"level":"info","ts":1600888893.6602554,"logger":"trial-controller","msg":"Trial controller created"}
{"level":"info","ts":1600888893.660258,"logger":"entrypoint","msg":"Setting up webhooks"}
{"level":"info","ts":1600888893.660348,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1600888893.760727,"logger":"kubebuilder.webhook","msg":"installing webhook configuration in cluster"}
{"level":"info","ts":1600888893.760758,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"suggestion-controller"}
{"level":"info","ts":1600888893.7608273,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"experiment-controller"}
{"level":"info","ts":1600888893.7608397,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"trial-controller"}
{"level":"info","ts":1600888893.8610892,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"experiment-controller","worker count":1}
{"level":"info","ts":1600888893.8611126,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"trial-controller","worker count":1}
{"level":"info","ts":1600888893.86118,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"suggestion-controller","worker count":1}
{"level":"info","ts":1600888893.8612761,"logger":"experiment-controller","msg":"Statistics","Experiment":"kubeflow/hyperparameter-tuning","requiredActiveCount":3,"parallelCount":3,"activeCount":0,"completedCount":0}
{"level":"info","ts":1600888893.8613026,"logger":"experiment-controller","msg":"Reconcile Suggestion","Experiment":"kubeflow/hyperparameter-tuning","addCount":3}
{"level":"info","ts":1600888893.8613286,"logger":"experiment-controller","msg":"GetOrCreateSuggestion","Experiment":"kubeflow/hyperparameter-tuning","name":"hyperparameter-tuning","Suggestion Requests":3}
{"level":"info","ts":1600888893.8617506,"logger":"kubebuilder.admission.cert.writer","msg":"cert is invalid or expiring, regenerating a new one"}
E0923 19:21:33.861780       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)

**What did you expect to happen:**
No error

**Anything else you would like to add:**
Note I am trying to run this in a private GKE cluster (no outside internet access)

**Environment:**

- Kubeflow version (`kfctl version`):
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
@sadeel If you are using private GKE it might be this problem: https://github.com/kubeflow/katib/issues/1258#issuecomment-656386139. 
You need to create firewall rule to enable webhooks.
