### ISSUE TITLE
Update deprecated api apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by daftping** [kubeflow/katib#1354]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Update deprecated api group apiextensions.k8s.io/v1beta1 - [code](https://github.com/kubeflow/katib/search?q=%22apiextensions.k8s.io%2Fv1beta1%22).

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals
The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19. Use apiextensions.k8s.io/v1 instead. ([#79604](https://github.com/kubernetes/kubernetes/pull/79604), @liggitt)

> The `CustomResourceDefinition` API type is promoted to `apiextensions.k8s.io/v1` with the following changes:
> * Use of the new `default` feature in validation schemas is limited to v1
> * `spec.scope` is no longer defaulted to `Namespaced` and must be explicitly specified
> * `spec.version` is removed; use `spec.versions` instead
> * `spec.validation` is removed; use `spec.versions[*].schema` instead
> * `spec.subresources` is removed; use `spec.versions[*].subresources` instead
> * `spec.additionalPrinterColumns` is removed; use `spec.versions[*].additionalPrinterColumns` instead
> * `spec.conversion.webhookClientConfig` is moved to `spec.conversion.webhook.clientConfig`
> * `spec.conversion.conversionReviewVersions` is moved to `spec.conversion.webhook.conversionReviewVersions`
> * `spec.versions[*].schema.openAPIV3Schema` is now required when creating v1 CustomResourceDefinitions
> * `spec.preserveUnknownFields: true` is disallowed when creating v1 CustomResourceDefinitions; it must be specified within schema definitions as `x-kubernetes-preserve-unknown-fields: true`
> * In `additionalPrinterColumns` items, the `JSONPath` field was renamed to `jsonPath` (fixes https://github.com/kubernetes/kubernetes/issues/66531)
> The `apiextensions.k8s.io/v1beta1` version of `CustomResourceDefinition` is deprecated and will no longer be served in v1.19.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version (`kfctl version`):
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
Thanks for the information @daftping.
@gaocegege @johnugeorge Should we fix it before the 1.2 release?

I am concerned that we use other deprecated APIs. For example, [`admissionregistration.k8s.io/v1beta1`](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/webhook.go#L20)

**Comment by gaocegege** [comment]
I think we should have a detailed review for this.

**Comment by gaocegege** [comment]
https://github.com/kubernetes/apiextensions-apiserver/issues/50

**Comment by gaocegege** [comment]
We have some problems with v1
