### ISSUE TITLE
Allow running KFP components as Katib Experiments 

### ISSUE THREAD

**Issue by fvde** [kubeflow/katib#1369]
/kind feature

**Describe the solution you'd like**
As a user of kubeflow pipelines, there is quite a gap between KFP and Katib. Clean KFP code dictates that I put my operations in isolated components, such as ([XGBoost Training](https://github.com/kubeflow/pipelines/tree/master/components/XGBoost/Train)). Katib on the other hand requires me to dockerize my training. As a katib _and_ KFP user it would be amazing to submit components to katib for running experiments on.

**Anything else you would like to add:**
- Fairing could help under the hood, to dockerize the component?

**Comment by gaocegege** [comment]
/cc @johnugeorge @andreyvelich 

I think it should be our highest priority task in the next release. Thanks for the issue!

**Comment by andreyvelich** [comment]
Thank you for creating the issue @fvde.
We will start work on that after the 0.10 release.

/cc @Bobgy @jlewi

**Comment by andreyvelich** [comment]
We updated Katib component for KFP.
@fvde Check few examples here: https://github.com/kubeflow/pipelines/tree/master/samples/contrib/kubeflow-katib.
