### ISSUE TITLE
Katib needs to use durable storage that outlives the pod.

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#137]
Katib uses two databases
- MySQL (for Katib)
- MongoDB (for ModelDB)

It doesn't look like we are using any sort of durable storage for either one.

Here's the MySQL deployment it doesn't look like its using a persistent volume
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/vizier.libsonnet#L185

Here's the MongoDB deployment:
https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/modeldb.libsonnet#L39

@YujiOshima @gaocegege Is this accurate or am I missing something?

**Comment by gaocegege** [comment]
No, I don't think so.

**Comment by YujiOshima** [comment]
@jlewi @gaocegege I agree we need PVC.
For Katib, adding PVC for MySQL is enough for persistence.
But for ModelDB, adding it for only Mongo may be not enough.
The ModelDB's backend component (ModelDB has frontend, backend, and DB) also has state.
We probably need to add PVC for both of ModelDB's backend and DB.

**Comment by YujiOshima** [comment]
@gaocegege Sorry I don't understand ModelDB backend perfectly. But I couldn't persistent model data by only DB.
I think it is not good design. We should make the DB the only stateful component.

**Comment by YujiOshima** [comment]
@jlewi we need to persistent data of ModelDB. Maybe we need to do something. I will work on this.

**Comment by YujiOshima** [comment]
@jlewi Sorry, I need more time since ModelDB-backend app stores sqlite data and it looks to resets at beginning of its process. We need to fix it.

**Comment by YujiOshima** [comment]
We should fix [this]( https://github.com/mitdbg/modeldb/issues/221 ) at first.

**Comment by jlewi** [comment]
@YujiOshima What would it take to make Katib (but not ModelDB) robust to pod failure? For example, if its true that ModelDB is only used for long term storage and not during actual hyperparameter searches; what needs to happen so that if pods are preempted during the HP tuning job, the job can complete successfully, even if not all of the data is successfully persisted in ModelDB?

**Comment by jlewi** [comment]
For #178, we will need ot get those changes into our Katib prototype
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/katib

I think for experiment / model tracking we need a database not an operator. Users could have 1000's of models but most of those will just be entries in a DB with data attached to them.

**Comment by YujiOshima** [comment]
@jlewi >we will need ot get those changes into our Katib prototype
I will try it.

> I think for experiment / model tracking we need a database not an operator. Users could have 1000's of models but most of those will just be entries in a DB with data attached to them.
 OK, but experiment tracking and model management are extremely needed from Katib/KubeFlow users.
So I want to switch ModelDB to MLFlow and enrich the model management API of Katib the users can use model management without hp-tuning in v0.04.
WDYT?

**Comment by jlewi** [comment]
@YujiOshima Why MLFLow? When I last looked it didn't look like it was using a DB to track models. It looked like it was just using a filesystem. I'm not sure that's the best solution.

How about writing up a proposal and considering the various options?

**Comment by jlewi** [comment]
@inc0 Is this fixed?

**Comment by inc0** [comment]
PVC is fixed. For Model tracking please, include your feedback here: https://github.com/kubeflow/community/pull/195 let's design this thing properly

**Comment by jlewi** [comment]
@inc0 Does that mean there's no way to make model tracking work reliably with ModelDB? We have to go and build a whole new model tracking system?

**Comment by YujiOshima** [comment]
I propose new UI #208 for Katib and want to remove ModelDB.
When we will introduce another tool(MLFlow or StudioML etc), let's open a new issue.

**Comment by jlewi** [comment]
kubeflow/kubeflow#1678 added the PVC for MySql for Katib.

**Comment by jlewi** [comment]
@YujiOshima What's the status of this? It looks like you removed ModelDB. Is Katib now deployed with Durable storage?

/cc @richardsliu
