### ISSUE TITLE
Allow istio sidecar injection to trial pods 

### ISSUE THREAD

**Issue by robbertvdg** [kubeflow/katib#1374]
/kind feature

**Describe the solution you'd like**
At the moment the trial pods are hardcoded with the "sidecar.istio.io/inject=false" annotation. For security reasons we would like to enable istio for our experiments. I would suggest an optional parameter `trial_istio_enabled` with default false so the current flow is not interrupted.

**Anything else you would like to add:**
I already implemented this in our cluster. Are you willing to accept a PR for this feature?

**Comment by andreyvelich** [comment]
Hi @robbertvdg.

For v1beta1 it is already possible.
We don't attach `sidecar.istio.io/inject=false` annotation to Trial's Jobs by default.
Users need to do it manually, if they want it (https://github.com/kubeflow/website/pull/2320).

We will release Katib 0.10 soon.

**Comment by robbertvdg** [comment]
Ah I am currently using v1alpha3. I will check out v1beta1 and try to make it work!
