### ISSUE TITLE
Refresh in HP monitor UI lets me see and select all namespaces and their experiments

### ISSUE THREAD

**Issue by robbertvdg** [kubeflow/katib#1379]
/kind bug

**What steps did you take and what happened:**
From Kubeflow central dashboard go to Katib -> HP monitor. I see only my own experiments and namespace selector is read only.   
I reload the page, and can select all namespaces and see all experiments.

**What did you expect to happen:**
See only my own experiments and readonly namespace selector field after a reload.

**Anything else you would like to add:**
Katib v1beta1 version deployed with kubeflow manifests.

**Environment:**

- Kubeflow version (`kfctl version`): 1.0
- Minikube version (`minikube version`): 
- Kubernetes version: (use `kubectl version`): 1.18.10
- OS (e.g. from `/etc/os-release`):

**Comment by andreyvelich** [comment]
Thank you for pointing this @robbertvdg.
Yes, it is a known issue: https://github.com/kubeflow/katib/issues/1322.
We have plans to fix it.

/area front-end
/priority p1

**Comment by andreyvelich** [comment]
Let's continue discussion under this issue: https://github.com/kubeflow/katib/issues/1322.
