### ISSUE TITLE
make  problem

### ISSUE THREAD

**Issue by jerriezhou** [kubeflow/katib#1381]
[root@VM-92-93-centos ~/going/going_proj/src/github.com/kubeflow/katib]# make build
dep ensure -v
go generate ./pkg/... ./cmd/...
go: finding module for package sigs.k8s.io/controller-runtime/pkg/webhook/admission/types
go: finding module for package sigs.k8s.io/controller-runtime/pkg/webhook/admission/builder
Generating clients for experiments:v1alpha3,v1beta1 suggestions:v1alpha3,v1beta1 trials:v1alpha3,v1beta1 common:v1alpha3,v1beta1  ...
# git.code.oa.com/going/going/going_proj/src/github.com/kubeflow/katib/vendor/k8s.io/code-generator/cmd/client-gen
cmd/client-gen/main.go:59:25: not enough arguments in call to generators.NameSystems
        have ()
        want (map[string]string)
# git.code.oa.com/going/going/going_proj/src/github.com/kubeflow/katib/vendor/k8s.io/code-generator/cmd/lister-gen
cmd/lister-gen/main.go:52:25: not enough arguments in call to generators.NameSystems
        have ()
        want (map[string]string)
# git.code.oa.com/going/going/going_proj/src/github.com/kubeflow/katib/vendor/k8s.io/code-generator/cmd/informer-gen
cmd/informer-gen/main.go:55:25: not enough arguments in call to generators.NameSystems
        have ()
        want (map[string]string)
pkg/apis/controller/apis.go:17: running "../../../hack/update-codegen.sh": exit status 1
make: *** [generate] Error 1

thanks for any suggestions

**Comment by andreyvelich** [comment]
Hi @jerriezhou.
It seems that you have used the wrong version of `code-generator`.

Can you try to clone latest Katib repo. And, without `dep ensure`, try to run: 
`go generate ./pkg/... ./cmd/...`.
