### ISSUE TITLE
Support v1beta1 API on KFP component

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/katib#1397]
/kind feature

**Describe the solution you'd like**
Current the Katib component in KFP is still using v1alpha3. Is there a plan to move this to v1beta1? Thanks.
https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/katib-launcher

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
Hi @Tomcli,
Yes, we are planning to integrate the new component on this week on earlier next week.
Corresponding issue: https://github.com/kubeflow/katib/issues/1369

**Comment by Tomcli** [comment]
Thanks @andreyvelich
