### ISSUE TITLE
Consider "using" duecredit

### ISSUE THREAD

**Issue by yarikoptic** [kubeflow/katib#1399]
I saw katib listed among duecredit dependents: https://github.com/duecredit/duecredit/network/dependents?package_id=UGFja2FnZS01MjAzODE5OA%3D%3D  but apparently it is only present in the "frozen" requirements.txt specs.  So thought to alert that you might as well consider "using" it and provide citation , see https://github.com/duecredit/duecredit#duecredit for more info.

**Comment by andreyvelich** [comment]
Hi @yarikoptic.
Thank you to point this.

@gaocegege @johnugeorge Do we need this package in our Suggestions ?
I think we can remove it, I was able to generate citation only for the `numpy` package.

**Comment by gaocegege** [comment]
I have no objection to it.

Thanks
