### ISSUE TITLE
Error with example

### ISSUE THREAD

**Issue by lluunn** [kubeflow/katib#140]
From mgyong:

I am running Katib on gke in namespace katib

When i try to run the mnist example, i checked that the port forwarding for 3000 & 6789 are both working yet when i try to run the client-example.go 
I keep getting the rpc error
```
go run client-example.go -a random
Handling connection for 6789
2018/07/22 09:12:25 StudyConfig Error rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
exit status 1

[examples (⎈ |gke-west:default)]$ kubectl get pods -n katib
NAME                                                   READY     STATUS    RESTARTS   AGE
modeldb-backend-57667f44f6-sxpfb                       1/1       Running   0          14h
modeldb-db-6fc46458f6-rm7nx                            1/1       Running   0          14h
modeldb-frontend-74f475f4d-x87pg                       1/1       Running   0          14h
vizier-core-74457b7c5c-955n6                           1/1       Running   1          14h
vizier-db-7b6f8c59bc-cbvc6                             1/1       Running   0          14h
vizier-earlystopping-medianstopping-7c7f686c68-vmwkl   1/1       Running   0          14h
vizier-suggestion-grid-7754c88588-86xnz                1/1       Running   0          14h
vizier-suggestion-hyperband-d4574b54d-69vwn            1/1       Running   0          14h
vizier-suggestion-random-7597b9599d-wvxqh              1/1       Running   0          14h
```

**Comment by Nidhidamodaran** [comment]
@lluunn @YujiOshima is there any workaround to get this program running ?

**Comment by YujiOshima** [comment]
@Nidhidamodaran Please try to use automate built image : `gcr.io/kubeflow-images-public/{vizier-core, suggestion-random...}`

**Comment by mgyong** [comment]
@YujiOshima What's the difference between the automated built images? & the github code repository for katib?

**Comment by lluunn** [comment]
@mgyong 
I can still run the script:

```
go run client-example.go
2018/07/25 17:41:07 Study ID p75141048489295c
2018/07/25 17:41:07 Study ID p75141048489295c StudyConfname:"mnist-demo" owner:"katib" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.03" min:"0.01" > > configs:<name:"--num-layers" parameter_type:INT feasible:<max:"5" min:"2" > > configs:<name:"--optimizer" parameter_type:CATEGORICAL feasible:<list:"sgd" list:"adam" list:"ftrl" > > configs:<name:"--num-epochs" parameter_type:INT feasible:<max:"20" min:"20" > > > objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" 
2018/07/25 17:41:07 Get Grid Suggestions:
2018/07/25 17:41:07 trial_id:"k7edbb707e4f89d6" study_id:"p75141048489295c" parameter_set:<name:"--lr" parameter_type:DOUBLE value:"0.0131" > parameter_set:<name:"--num-layers" parameter_type:INT value:"2" > parameter_set:<name:"--optimizer" parameter_type:CATEGORICAL value:"sgd" > parameter_set:<name:"--num-epochs" parameter_type:INT value:"20" > 
2018/07/25 17:41:07 trial_id:"gf3fd31d9d008487" study_id:"p75141048489295c" parameter_set:<name:"--lr" parameter_type:DOUBLE value:"0.0117" > parameter_set:<name:"--num-layers" parameter_type:INT value:"3" > parameter_set:<name:"--optimizer" parameter_type:CATEGORICAL value:"ftrl" > parameter_set:<name:"--num-epochs" parameter_type:INT value:"20" > 
2018/07/25 17:41:07 WorkerID b84f35101a329742 start
2018/07/25 17:41:08 WorkerID f68e55fdd5aef55c start

kubectl get job -n katib
NAME               DESIRED   SUCCESSFUL   AGE
b84f35101a329742   1         0            59s
f68e55fdd5aef55c   1         0            59s

```

**Comment by Nidhidamodaran** [comment]
Thanks @YujiOshima . That worked.

**Comment by mgyong** [comment]
@YujiOshima @lluunn  
When i installed Katib and had the errors as reported by lluunn, i used the method of running the deploy.sh script from 
https://github.com/kubeflow/katib/blob/master/examples/MinikubeDemo/deploy.sh
 
As advised by lluunn, i instead used the ks apply approach to install as detailed here
https://github.com/kubeflow/kubeflow/tree/master/kubeflow/katib

I am now able to run go run client-example.go
However, the localhost:3000 is giving me a 404 even after i port-forward correctly

Not Found
404
Error: Not Found
    at /modeldb/frontend/app.js:33:13
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/modeldb/frontend/node_modules/express/lib/router/index.js:330:12)
    at next (/modeldb/frontend/node_modules/express/lib/router/index.js:271:10)
    at cookieParser (/modeldb/frontend/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/modeldb/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/modeldb/frontend/node_modules/express/lib/router/index.js:312:13)
    at /modeldb/frontend/node_modules/express/lib/router/index.js:280:7

**Comment by lluunn** [comment]
Did you use http://localhost:3000/katib?

https://github.com/kubeflow/kubeflow/blob/master/kubeflow/katib/README.md

**Comment by mgyong** [comment]
@lluunn My mistake. I didn't do  http://localhost:3000/katib 
It works
