### ISSUE TITLE
Update Katib Bundle for Juju

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1400]
/kind feature

The [Katib bundle](https://github.com/juju-solutions/bundle-katib) should be up-to-date with the latest manifests changes for the Katib 0.10 version.
We can take the latest manifests from here: https://github.com/kubeflow/manifests/tree/v1.2-branch/katib.
Let's continue discussion how we want to keep it updated under this issue.

In the meantime, that would be great if we can update [Adopters](https://github.com/kubeflow/katib/blob/master/ADOPTERS.md) list with information about Juju usage of Katib.

/cc @RFMVasconcelos @knkski @gaocegege @johnugeorge

**Comment by RFMVasconcelos** [comment]
Hey @andreyvelich, 

Thank you for creating this and sharing the latest manifests! I have added us to Adopters.

**Comment by gaocegege** [comment]
Should we maintain it in Katib?

**Comment by RFMVasconcelos** [comment]
Sounds great @gaocegege!

**Comment by RFMVasconcelos** [comment]
I'll make a PR

**Comment by andreyvelich** [comment]
I thought we want to maintain it under https://github.com/juju-solutions/bundle-katib and we add the link from the Katib README ? Or it's better to have this bundle under Katib repo ?

@RFMVasconcelos Are you planning to push these bundles in Kubeflow upstream ?
What do you think @RFMVasconcelos @gaocegege @johnugeorge ?

**Comment by RFMVasconcelos** [comment]
Hey @andreyvelich! 

We are quite open to contributing this code under Katib if that makes the process to collaborate on them easier. They are in essence 3 python scripts and 1 yaml file. If that's ok with you, it might be more efficient than having a repo for that purpose. 

WDYT?

**Comment by andreyvelich** [comment]
@RFMVasconcelos I think that should work, we can create an OWNERS file under this folder.
Any ideas where we should locate this code ?
What do you think @gaocegege ?

**Comment by RFMVasconcelos** [comment]
Looking at the current folder structure and the widespread terminology of [Kubernetes operators](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/), I would propose creating a `operators` folder with an OWNERS file, as @andreyvelich proposes. 

This will create a space for other operators that might be contributed by the community in the future. 🚀

**Comment by gaocegege** [comment]
SGTM

Thanks for your contribution! :tada: :+1:

**Comment by RFMVasconcelos** [comment]
Awesome, I will try to do the PR still today!

**Comment by aronchick** [comment]
This is terrific, thanks for your contribution!
