### ISSUE TITLE
Worker pod goes to error state while running median-stop.yaml example experiment

### ISSUE THREAD

**Issue by Pallavi-28** [kubeflow/katib#1418]
Hi,
I am trying to run https://github.com/kubeflow/katib/blob/master/examples/v1beta1/early-stopping/median-stop.yaml , 
but worker pod goes to error state with below log,

Here is my yaml file with some changes

apiVersion: "kubeflow.org/v1beta1"
kind: Experiment
metadata:
  **namespace: kf**
  name: median-stop
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: random
  earlyStopping:
    algorithmName: medianstop
    algorithmSettings:
      - name: min_trials_required
        value: "3"
      - name: start_step
        value: "5"
  parallelTrialCount: 2
  maxTrialCount: 15
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.5"
    - name: num-epochs
      parameterType: int
      feasibleSpace:
        min: "7"
        max: "8"
  trialTemplate:
    retain: true
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numberEpochs
        description: Number of epochs to train the model
        reference: num-epochs
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            **securityContext:
               runAsUser: 65532
            serviceAccountName: default**
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:v1beta1-e294a90
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-epochs=${trialParameters.numberEpochs}"
            restartPolicy: Never

**log of worker pod**:
 kubectl logs -f  median-stop-vr4d6gvr-w6f49 -n kf -c metrics-logger-and-collector
I0119 10:31:47.939675      26 main.go:342] Trial Name: median-stop-vr4d6gvr
I0119 10:31:49.082819      26 main.go:180] 2021-01-19T10:31:49Z INFO     start with arguments Namespace(add_stn=False, batch_size=64, disp_batches=100, dtype='float32', gc_threshold=0.5, gc_type='none', gpus=None, image_shape='1, 28, 28', initializer='default', kv_store='device', load_epoch=None, loss='', lr=0.4953072977603158, lr_factor=0.1, lr_step_epochs='10', macrobatch_size=0, model_prefix=None, mom=0.9, monitor=0, network='mlp', num_classes=10, num_epochs=8, num_examples=60000, num_layers=None, optimizer='sgd', profile_server_suffix='', profile_worker_suffix='', save_period=1, test_io=0, top_k=0, use_imagenet_data_augmentation=0, warmup_epochs=5, warmup_strategy='linear', wd=0.0001)
I0119 10:31:49.088914      26 main.go:180] 2021-01-19T10:31:49Z DEBUG    Starting new HTTP connection (1): 87.254.212.120:8080
I0119 10:31:49.391701      26 main.go:180] 2021-01-19T10:31:49Z DEBUG    http://87.254.212.120:8080 "GET http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 200 28881
I0119 10:31:49.493744      26 main.go:180] 2021-01-19T10:31:49Z DEBUG    Starting new HTTP connection (1): 87.254.212.120:8080
I0119 10:31:49.747678      26 main.go:180] 2021-01-19T10:31:49Z DEBUG    http://87.254.212.120:8080 "GET http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz HTTP/1.1" 200 9912422
I0119 10:31:55.743888      26 main.go:180] 2021-01-19T10:31:55Z DEBUG    Starting new HTTP connection (1): 87.254.212.120:8080
I0119 10:31:56.049923      26 main.go:180] 2021-01-19T10:31:56Z DEBUG    http://87.254.212.120:8080 "GET http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz HTTP/1.1" 200 4542
I0119 10:31:56.053656      26 main.go:180] 2021-01-19T10:31:56Z DEBUG    Starting new HTTP connection (1): 87.254.212.120:8080
I0119 10:31:56.356101      26 main.go:180] 2021-01-19T10:31:56Z DEBUG    http://87.254.212.120:8080 "GET http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz HTTP/1.1" 200 1648877
I0119 10:31:57.967732      26 main.go:180] [10:31:57] src/executor/graph_executor.cc:1981: Subgraph backend MKLDNN is activated.
I0119 10:31:58.866604      26 main.go:180] 2021-01-19T10:31:58Z INFO     Epoch[0] Batch [0-100] Speed: 8286.67 samples/sec     accuracy=0.145885
I0119 10:31:59.249114      26 main.go:180] 2021-01-19T10:31:59Z INFO     Epoch[0] Batch [100-200]       Speed: 16741.35 samples/sec     accuracy=0.103594
I0119 10:31:59.606723      26 main.go:180] 2021-01-19T10:31:59Z INFO     Epoch[0] Batch [200-300]       Speed: 17916.07 samples/sec     accuracy=0.106719
I0119 10:32:00.260522      26 main.go:180] 2021-01-19T10:32:00Z INFO     Epoch[0] Batch [300-400]       Speed: 9807.65 samples/sec      accuracy=0.108125
I0119 10:32:01.177905      26 main.go:180] 2021-01-19T10:32:01Z INFO     Epoch[0] Batch [400-500]       Speed: 6984.36 samples/sec      accuracy=0.098125
I0119 10:32:01.893153      26 main.go:180] 2021-01-19T10:32:01Z INFO     Epoch[0] Batch [500-600]       Speed: 8938.59 samples/sec      accuracy=0.101094
I0119 10:32:02.627784      26 main.go:180] 2021-01-19T10:32:02Z INFO     Epoch[0] Batch [600-700]       Speed: 8708.92 samples/sec      accuracy=0.108438
I0119 10:32:03.253520      26 main.go:180] 2021-01-19T10:32:03Z INFO     Epoch[0] Batch [700-800]       Speed: 10261.09 samples/sec     accuracy=0.108281
I0119 10:32:03.926978      26 main.go:180] 2021-01-19T10:32:03Z INFO     Epoch[0] Batch [800-900]       Speed: 9520.87 samples/sec      accuracy=0.111250
I0119 10:32:04.743642      26 main.go:180] 2021-01-19T10:32:04Z INFO     Epoch[0] Train-accuracy=0.109975
I0119 10:32:04.743672      26 main.go:180] 2021-01-19T10:32:04Z INFO     Epoch[0] Time cost=6.769
I0119 10:32:04.960042      26 main.go:180] 2021-01-19T10:32:04Z INFO     Epoch[0] Validation-accuracy=0.098428
I0119 10:32:05.648070      26 main.go:180] 2021-01-19T10:32:05Z INFO     Epoch[1] Batch [0-100] Speed: 12309.84 samples/sec    accuracy=0.097618
I0119 10:32:06.305143      26 main.go:180] 2021-01-19T10:32:06Z INFO     Epoch[1] Batch [100-200]       Speed: 9735.95 samples/sec      accuracy=0.097344
I0119 10:32:07.141325      26 main.go:180] 2021-01-19T10:32:07Z INFO     Epoch[1] Batch [200-300]       Speed: 7654.86 samples/sec      accuracy=0.097500
I0119 10:32:08.180651      26 main.go:180] 2021-01-19T10:32:08Z INFO     Epoch[1] Batch [300-400]       Speed: 6162.79 samples/sec      accuracy=0.109375
I0119 10:32:09.057553      26 main.go:180] 2021-01-19T10:32:09Z INFO     Epoch[1] Batch [400-500]       Speed: 7299.97 samples/sec      accuracy=0.104688
I0119 10:32:09.750611      26 main.go:180] 2021-01-19T10:32:09Z INFO     Epoch[1] Batch [500-600]       Speed: 9239.46 samples/sec      accuracy=0.103438
I0119 10:32:10.476605      26 main.go:180] 2021-01-19T10:32:10Z INFO     Epoch[1] Batch [600-700]       Speed: 8843.38 samples/sec      accuracy=0.100156
I0119 10:32:10.871611      26 main.go:180] 2021-01-19T10:32:10Z INFO     Epoch[1] Batch [700-800]       Speed: 16129.54 samples/sec     accuracy=0.097344
I0119 10:32:11.272630      26 main.go:180] 2021-01-19T10:32:11Z INFO     Epoch[1] Batch [800-900]       Speed: 15988.91 samples/sec     accuracy=0.101094
I0119 10:32:11.435608      26 main.go:180] 2021-01-19T10:32:11Z INFO     Epoch[1] Train-accuracy=0.101179
I0119 10:32:11.435713      26 main.go:180] 2021-01-19T10:32:11Z INFO     Epoch[1] Time cost=6.317
I0119 10:32:11.648544      26 main.go:180] 2021-01-19T10:32:11Z INFO     Epoch[1] Validation-accuracy=0.100916
I0119 10:32:12.363594      26 main.go:180] 2021-01-19T10:32:12Z INFO     Epoch[2] Batch [0-100] Speed: 12266.27 samples/sec    accuracy=0.103496
I0119 10:32:13.056580      26 main.go:180] 2021-01-19T10:32:13Z INFO     Epoch[2] Batch [100-200]       Speed: 9251.76 samples/sec      accuracy=0.097969
I0119 10:32:13.402534      26 main.go:180] 2021-01-19T10:32:13Z INFO     Epoch[2] Batch [200-300]       Speed: 18504.80 samples/sec     accuracy=0.103750
I0119 10:32:13.932423      26 main.go:180] 2021-01-19T10:32:13Z INFO     Epoch[2] Batch [300-400]       Speed: 12086.21 samples/sec     accuracy=0.098906
I0119 10:32:15.118528      26 main.go:180] 2021-01-19T10:32:15Z INFO     Epoch[2] Batch [400-500]       Speed: 5395.96 samples/sec      accuracy=0.104375
I0119 10:32:15.672550      26 main.go:180] 2021-01-19T10:32:15Z INFO     Epoch[2] Batch [500-600]       Speed: 11556.84 samples/sec     accuracy=0.104375
I0119 10:32:16.515553      26 main.go:180] 2021-01-19T10:32:16Z INFO     Epoch[2] Batch [600-700]       Speed: 7604.07 samples/sec      accuracy=0.105156
I0119 10:32:17.376018      26 main.go:180] 2021-01-19T10:32:17Z INFO     Epoch[2] Batch [700-800]       Speed: 7430.10 samples/sec      accuracy=0.100781
I0119 10:32:18.352576      26 main.go:180] 2021-01-19T10:32:18Z INFO     Epoch[2] Batch [800-900]       Speed: 6555.32 samples/sec      accuracy=0.101094
I0119 10:32:18.559570      26 main.go:180] 2021-01-19T10:32:18Z INFO     Epoch[2] Train-accuracy=0.102079
I0119 10:32:18.559600      26 main.go:180] 2021-01-19T10:32:18Z INFO     Epoch[2] Time cost=6.726
I0119 10:32:19.029360      26 main.go:180] 2021-01-19T10:32:19Z INFO     Epoch[2] Validation-accuracy=0.089172
I0119 10:32:19.852786      26 main.go:180] 2021-01-19T10:32:19Z INFO     Epoch[3] Batch [0-100] Speed: 10892.02 samples/sec    accuracy=0.098391
I0119 10:32:20.416261      26 main.go:180] 2021-01-19T10:32:20Z INFO     Epoch[3] Batch [100-200]       Speed: 11374.01 samples/sec     accuracy=0.097812
I0119 10:32:21.597588      26 main.go:180] 2021-01-19T10:32:21Z INFO     Epoch[3] Batch [200-300]       Speed: 5415.78 samples/sec      accuracy=0.105156
I0119 10:32:22.215388      26 main.go:180] 2021-01-19T10:32:22Z INFO     Epoch[3] Batch [300-400]       Speed: 10362.50 samples/sec     accuracy=0.096875
I0119 10:32:22.906646      26 main.go:180] 2021-01-19T10:32:22Z INFO     Epoch[3] Batch [400-500]       Speed: 9262.43 samples/sec      accuracy=0.103594
I0119 10:32:23.228705      26 main.go:180] 2021-01-19T10:32:23Z INFO     Epoch[3] Batch [500-600]       Speed: 19939.70 samples/sec     accuracy=0.100156
I0119 10:32:23.935310      26 main.go:180] 2021-01-19T10:32:23Z INFO     Epoch[3] Batch [600-700]       Speed: 9072.30 samples/sec      accuracy=0.102031
I0119 10:32:24.255550      26 main.go:180] 2021-01-19T10:32:24Z INFO     Epoch[3] Batch [700-800]       Speed: 19995.68 samples/sec     accuracy=0.099687
I0119 10:32:24.869657      26 main.go:180] 2021-01-19T10:32:24Z INFO     Epoch[3] Batch [800-900]       Speed: 10414.91 samples/sec     accuracy=0.102344
I0119 10:32:24.949937      26 main.go:180] 2021-01-19T10:32:24Z INFO     Epoch[3] Train-accuracy=0.100913
I0119 10:32:24.949969      26 main.go:180] 2021-01-19T10:32:24Z INFO     Epoch[3] Time cost=5.689
I0119 10:32:25.122299      26 main.go:180] 2021-01-19T10:32:25Z INFO     Epoch[3] Validation-accuracy=0.098428
I0119 10:32:25.547538      26 main.go:180] 2021-01-19T10:32:25Z INFO     Epoch[4] Batch [0-100] Speed: 23064.42 samples/sec    accuracy=0.106745
I0119 10:32:26.148221      26 main.go:180] 2021-01-19T10:32:26Z INFO     Epoch[4] Batch [100-200]       Speed: 10665.18 samples/sec     accuracy=0.097969
I0119 10:32:26.603538      26 main.go:180] 2021-01-19T10:32:26Z INFO     Epoch[4] Batch [200-300]       Speed: 14085.86 samples/sec     accuracy=0.105313
I0119 10:32:26.980907      26 main.go:180] 2021-01-19T10:32:26Z INFO     Epoch[4] Batch [300-400]       Speed: 16943.41 samples/sec     accuracy=0.100469
I0119 10:32:27.350507      26 main.go:180] 2021-01-19T10:32:27Z INFO     Epoch[4] Batch [400-500]       Speed: 17301.42 samples/sec     accuracy=0.100937
I0119 10:32:27.720638      26 main.go:180] 2021-01-19T10:32:27Z INFO     Epoch[4] Batch [500-600]       Speed: 17326.99 samples/sec     accuracy=0.101562
I0119 10:32:28.094565      26 main.go:180] 2021-01-19T10:32:28Z INFO     Epoch[4] Batch [600-700]       Speed: 17140.63 samples/sec     accuracy=0.101406
I0119 10:32:28.676649      26 main.go:180] 2021-01-19T10:32:28Z INFO     Epoch[4] Batch [700-800]       Speed: 11008.17 samples/sec     accuracy=0.099375
I0119 10:32:29.475874      26 main.go:180] 2021-01-19T10:32:29Z INFO     Epoch[4] Batch [800-900]       Speed: 8002.03 samples/sec      accuracy=0.097812
I0119 10:32:29.681917      26 main.go:180] 2021-01-19T10:32:29Z INFO     Epoch[4] Train-accuracy=0.100979
I0119 10:32:29.681948      26 main.go:180] 2021-01-19T10:32:29Z INFO     Epoch[4] Time cost=4.417
I0119 10:32:29.927754      26 main.go:180] 2021-01-19T10:32:29Z INFO     Epoch[4] Validation-accuracy=0.098428
I0119 10:32:29.927909      26 main.go:258] **Training container is early stopped
F0119 10:32:29.928701      26 main.go:277] Get children proceses for main PID: 6 failed: process does not have children
goroutine 36 [running]:**
github.com/kubeflow/katib/vendor/k8s.io/klog.stacks(0xc000326000, 0xc0001a0000, 0x78, 0xd3)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:830 +0xb9
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).output(0x10efac0, 0xc000000003, 0xc00019e000, 0x108772d, 0x7, 0x115, 0x0)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:781 +0x2da
github.com/kubeflow/katib/vendor/k8s.io/klog.(*loggingT).printf(0x10efac0, 0x3, 0xc1b80e, 0x31, 0xc000093c60, 0x2, 0x2)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:678 +0x153
github.com/kubeflow/katib/vendor/k8s.io/klog.Fatalf(...)
        /go/src/github.com/kubeflow/katib/vendor/k8s.io/klog/klog.go:1209
main.watchMetricsFile(0x7fff96f41b29, 0x1a, 0xc000210fc0, 0x0, 0x1, 0x0, 0x0, 0x0)
        /go/src/github.com/kubeflow/katib/cmd/metricscollector/v1beta1/file-metricscollector/main.go:277 +0x192c
created by main.main
        /go/src/github.com/kubeflow/katib/cmd/metricscollector/v1beta1/file-metricscollector/main.go:351 +0x215

**Pod status:**

 kubectl get pod -n kf   -w
NAME                                  READY   STATUS      RESTARTS   AGE
median-stop-48n9hxjk-c8h54            0/2     Completed   0          3m30s
median-stop-9w6x74b6-sflsn            0/2     Completed   0          76s
median-stop-hxpm95s6-zzwv2            0/2     Completed   0          2m21s
median-stop-jcnt6bl5-84lsl            2/2     Running     0          16s
median-stop-kkvcrvr9-rvm4z            0/2     Completed   0          2m20s
median-stop-llrq7qcv-gqfqg            0/2     Completed   0          3m30s
median-stop-random-685d686854-bjjk4   2/2     Running     0          4m25s
median-stop-t22mnkbs-h9f2r            0/2     Completed   0          75s
**median-stop-vr4d6gvr-w6f49            2/2     Running     0          15s
median-stop-vr4d6gvr-w6f49            1/2     Error       0          45s
median-stop-jcnt6bl5-84lsl            1/2     Error       0          47s
median-stop-vr4d6gvr-w6f49            0/2     Error       0          64s**

**Environment:**

- Kubeflow version - 1.2 
- Kubernetes version: (use `kubectl version`):  1.17

Any help on the issue?

**Comment by andreyvelich** [comment]
Thank you for creating this @Pallavi-28.

1. Do you get this error every time when you run the median stop Experiment ? 
2. Did you try to install Katib standalone without Kubeflow and run median stop example ?

**Comment by Pallavi-28** [comment]
Hi @andreyvelich ,
yes I am getting this error every time I run this experiment.
No, katib(0.10.0) is installed as part of kubeflow-1.2.

**Comment by andreyvelich** [comment]
@Pallavi-28 Can you share the config that you used to install Kubeflow 1.2 please?

**Comment by Pallavi-28** [comment]
you mean kfdef file ?

**Comment by andreyvelich** [comment]
> you mean kfdef file ?

Yeah

**Comment by Pallavi-28** [comment]
I am installing katib by calling kustomization.yaml file in this path https://github.com/kubeflow/manifests/tree/master/katib/installs/katib-external-db

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../admission-webhook/webhook/v3
  - ../../common/centraldashboard/overlays/stacks
  - ../../kubeflow-roles/base
  - ../../jupyter/jupyter-web-app/base_v3
  - ../../jupyter/notebook-controller/base_v3
  - ../../profiles/base_v3
  - ../../pytorch-job/pytorch-job-crds/overlays/application
  - ../../pytorch-job/pytorch-operator/overlays/application
  - ../../tf-training/tf-job-crds/overlays/application
  - ../../tf-training/tf-job-operator/overlays/application
  - ../../argo/base_v3
  - ../../pipeline/minio/installs/generic
  - ../../pipeline/mysql/installs/generic
  - ../../pipeline/installs/generic
  - ../../metadata/v3
  # This package will create a profile resource so it needs to be installed after the profiles CR
  - ../../default-install/base
  - ../../katib/installs/katib-standalone

**Comment by andreyvelich** [comment]
> I am installing katib by calling kustomization.yaml file in this path https://github.com/kubeflow/manifests/tree/master/katib/installs/katib-external-db
> 
> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> namespace: kubeflow
> resources:
> 
> * ../../admission-webhook/webhook/v3
> * ../../common/centraldashboard/overlays/stacks
> * ../../kubeflow-roles/base
> * ../../jupyter/jupyter-web-app/base_v3
> * ../../jupyter/notebook-controller/base_v3
> * ../../profiles/base_v3
> * ../../pytorch-job/pytorch-job-crds/overlays/application
> * ../../pytorch-job/pytorch-operator/overlays/application
> * ../../tf-training/tf-job-crds/overlays/application
> * ../../tf-training/tf-job-operator/overlays/application
> * ../../argo/base_v3
> * ../../pipeline/minio/installs/generic
> * ../../pipeline/mysql/installs/generic
> * ../../pipeline/installs/generic
> * ../../metadata/v3
> 
> # This package will create a profile resource so it needs to be installed after the profiles CR
> * ../../default-install/base
> * ../../katib/installs/katib-external-db

So you didn't use one of the [kfdef configs](https://github.com/kubeflow/manifests/tree/master/kfdef) and `kfctl` to install Kubeflow?
Did you use one of the [existing stacks](https://github.com/kubeflow/manifests/tree/master/stacks) or you have your own Kustomization file to install necessary Kubeflow components ?

**Comment by Pallavi-28** [comment]
Hi @andreyvelich 
 we used a file-collector image which was incorrect during our build. With the proper file collector image containing shell access, its working. (Probably  file-collector image needs a shell to start child process to impose early stopping.)
Thank you for your support
May be you can close this ticket

**Comment by andreyvelich** [comment]
@Pallavi-28 It's good to hear!
Let us know if you face any other issues.
