### ISSUE TITLE
Create a new Katib UI

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/katib#1421]
/kind feature

**Describe the solution you'd like**
Create a new Katib UI, as we've discussed in the [shared doc](https://docs.google.com/document/d/14cfGYJiTl32GWBUTbYQHzXC4UWA7r_ysgWYSWsxcDvU/edit).

We can use this as a tracking issue to track the progress of this effort as well as design decisions. I'll also be linking future issues to this one to keep everything organized and linked together.

**Anything else you would like to add:**
The switch should happen gradually. We should maintain both UIs until we ensure that this new version is on par, feature wise, with the functionality provided by the current UI.

cc @kubeflow/wg-automl-leads 
/assign @kimwnasptd

**Comment by andreyvelich** [comment]
Thank you for your great work @kimwnasptd!
Sounds good to me.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by andreyvelich** [comment]
@kimwnasptd I created Project for the new Katib UI: https://github.com/kubeflow/katib/projects/1.

Feel free to create issues that your first initial PR is currently missing and what should be integrated as part of your proposal.

**Comment by kimwnasptd** [comment]
Adding a tracking comment to sum up the state of this effort.

The new UI is currently located under the [pkg/new-ui/v1beta1](https://github.com/kubeflow/katib/tree/5ed27d703b9e9401780c22d181fbdb8e2c1b4ee0/pkg/new-ui/v1beta1) and [cmd/new-ui/v1beta1](https://github.com/kubeflow/katib/tree/5ed27d703b9e9401780c22d181fbdb8e2c1b4ee0/cmd/new-ui/v1beta1) directories. Currently a user can use this UI to perform list, delete and create operations on the `Experiment` CRs of their cluster.

These are the things that we are working on and discussing:
* Define how we want the app to manage and handle the `TrialTemplates` https://github.com/kubeflow/katib/issues/1440. This might require us to redefine where these ConfigMaps should live and how the web app could enhance the UX of managing them
* Allow the app to work in standalone mode and not only with Kubeflow and the Central Dashboard https://github.com/kubeflow/katib/issues/1437
* Fully expose all the missing fields in the form https://github.com/kubeflow/katib/issues/1443
* Add CI tests for this new UI and CI/CD processes

There are also other ideas we have and track in our dedicated [kanban board](https://github.com/kubeflow/katib/projects/1)

**Comment by kimwnasptd** [comment]
As we briefly discussed in the AutoML WG's meeting for 1.3 the manifests will be using the image of the **current UI** by default and not for this one. That's because this UI still needs some more work in order to be able to be on par with the existing one, so that we can flip the switch and use this instead.

But in the mean time we also want to get more people to try out this new UI and give us their feedback. Ideally we would like to provide manifests for the new UI and build images for it, which as a result will also require effort on extending the CI/CD for automating the build/push process #1469.

We'll do the best that we can for making it seamless for people to try out this UI with new manifests, but since the first RC for 1.3 is really close we might not be able to provide pre-build images for this app. 

So I'll try to document how someone could manually build the image and use this UI instead:
```bash
# build the image manually
cd /path/to/kubeflow/katib

IMG=<image you will build and push to your registry>
docker build -t ${IMG} -f cmd/new-ui/v1beta1/Dockerfile .
docker push ${IMG}

# edit the deployment of the Katib UI. The UI is currently only working as 
# part of a Kubeflow installation and not as a standalone app
kubectl -n kubeflow edit deployments.apps katib-ui

# change the image of the deployment to $IMG
```

cc @andreyvelich @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
We can close this issue and track improvements separately.
