### ISSUE TITLE
Question about metrics collector

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#1429]
I review the code about the metrics collector, and find out the log to stdout can be collected by file-metrics-collector.  But i didnot see how to achieve it.  who can explain it.

**Comment by wukong1992** [comment]
@hougangliu

**Comment by gaocegege** [comment]
We will redirect STDOUT to a file, and share the file between main container and metrics collector container.

**Comment by wukong1992** [comment]
@gaocegege I see the file, but not find where is the 'redirect STDOUT' code, the code in which director?

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/blob/621973712e780eb85167e39211b3da769cf776bb/pkg/webhook/v1beta1/pod/inject_webhook.go

We are using a Pod level webhook to implement it.

**Comment by andreyvelich** [comment]
@wukong1992 
> @gaocegege I see the file, but not find where is the 'redirect STDOUT' code, the code in which director?

The training container for the file metrics collector example redirects StdOut logs to the file: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/file-metrics-collector/mnist.py#L16.

You can also check the docs [in the official Kubeflow documentation](https://www.kubeflow.org/docs/components/katib/experiment/#metrics-collector).

**Comment by andreyvelich** [comment]
Feel free to re-open the issue if you have other questions.
