### ISSUE TITLE
katib-cli problem

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#143]
when i used katib-cli stop study {studyid/studyname} -s {server},  it returned :StopStudy failed: rpc error: code = Unimplemented desc = unknown method GetStudies. Who know how to solve it?

**Comment by jlewi** [comment]
Should we close this issue now that the StudyJob CRD has been committed?

**Comment by YujiOshima** [comment]
Yes, the katib-cli no longer needed.
