### ISSUE TITLE
Double-type search spaces should allow ranges including zero.

### ISSUE THREAD

**Issue by thomas-mueller** [kubeflow/katib#1430]
/kind feature

**Describe the solution you'd like**
It sould be nice if double type search spaces would allow ranges that overlap with zero. Currently this is problematic due to the [log-uniform prior](https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1beta1/skopt/base_service.py#L44). A solution could be to make this prior configurable and to allow other options supported by skopt as well.

**Anything else you would like to add:**
See slack discussion here: https://kubeflow.slack.com/archives/C7REE0EHK/p1612878620179500?thread_ts=1612864835.178100&cid=C7REE0EHK

**Comment by andreyvelich** [comment]
Thank you for creating this @thomas-mueller.
I think this feature is similar to this: https://github.com/kubeflow/katib/issues/1207.
Let's continue discussion there.
/close
