### ISSUE TITLE
e2e: Test breakage

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/katib#1433]
/kind bug

**What steps did you take and what happened:**
E2E tests are not succeeding because they can't install the tf-operator manifests:
https://github.com/kubeflow/katib/blob/172999716efe76b73539391c2b028ebc5f0a837c/test/scripts/v1beta1/setup-katib.sh#L70

This is an artifact of using the manifests master branch to install the tf-operator.
A recent folder restructuring in manifests is what triggered it:
https://github.com/kubeflow/manifests/issues/1738
https://github.com/kubeflow/manifests/pull/1739

**What did you expect to happen:**
E2E tests should succeed.

**Anything else you would like to add:**
This is an artifact of using the manifests master branch to install the tf-operator.
As master is not guarranteed to be stable or avoid any folder renames, the e2e tests for katib broke.

These are the possible solutions:
- Pin the manifests version to the latest stable release (v1.2). This will prevent it from breaking in the future and I think is the best choice. We can update it regularly as with other deps.
- Change the directories they use to the new ones.

I recommend the first approach. If you agree, I can make a quick PR.

cc @kubeflow/wg-automl-leads

**Comment by andreyvelich** [comment]
I agree with the first approach since we can verify our e2e test on the latest stable training operator releases.
It would be great if you can submit the PR @yanniszark!

**Comment by andreyvelich** [comment]
Fixed by: https://github.com/kubeflow/katib/pull/1438.
