### ISSUE TITLE
[UI Feature] Standalone mode for the new Katib UI

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1437]
/kind feature

The new Katib UI should work in the standalone mode when user deploys Katib without Kubeflow central dashboard.
Let's continue discussion here how we should do that.
Also check this comment: https://github.com/kubeflow/katib/pull/1427#discussion_r577589302.

/cc @kimwnasptd @gaocegege @johnugeorge

**Comment by kimwnasptd** [comment]
First off, from the technical side of view, the frontend can figure out if it's in Kubeflow mode or in Standalone dynamically. So we won't need to extend the backend to provide this info to the frontend. I've tried to document the more technical details of why the above approach works in https://github.com/kubeflow/kubeflow/issues/5566#issuecomment-779278036.

The changes we will need to make to the UI, that will be aware of the mode, are:
1. Showing a namespace drop-down component in standalone mode
2. Have a side panel for app navigation in standalone mode [HP Tuning, NAS]
3. Rely on the CentralDashboard's side-panel for navigating into the app's different pages in Kubeflow mode

In both cases the UI will be checking if the `window.centraldashboard` object is present to detect if the app is exposed under the CentralDashboard

**Comment by kimwnasptd** [comment]
For the side-panel we should try to avoid showing two distinct sidebars in Kubeflow mode https://github.com/kubeflow/kubeflow/issues/5566#issuecomment-782036247.

The Katib UI should only expose a hamburger-menu/sidebar only if the CentralDashboard is not present, which means no `window.centraldashboard` object exists in the app's window.

![Screenshot from 2021-02-19 13-42-11](https://user-images.githubusercontent.com/11134742/108503471-19abb180-72bd-11eb-853c-8b075aaa103a.png)

**Comment by andreyvelich** [comment]
> For the side-panel we should try to avoid showing two distinct sidebars in Kubeflow mode kubeflow/kubeflow#5566 (comment).

The Katib UI should only expose a hamburger-menu/sidebar only if the CentralDashboard is not present, which means no window.centraldashboard object exists in the app's window.

Then how we will navigate between Trial template editor page, Katib Config and main page where user can create new Experiment?
Are you planing to integrate this pages in the central dashboard menu?

**Comment by kimwnasptd** [comment]
> Are you planing to integrate these pages in the central dashboard menu?

Correct, we can have any entries that would be in the sidebar-menu to be in the dashboard. I've already done something like this in the picture above, where the Dashboard has a `NAS` and `HP Tuning` entries under `Experiments`.

Ofc we can discuss about using different names, just wanted to show how it would look like.

**Comment by kimwnasptd** [comment]
Also adding a comment on this issue wrt what Namespace will be selected from the app in standalone mode. Right now there will be none and the user will always need to manually click one https://github.com/kubeflow/katib/pull/1427#discussion_r581023201

We've described some iterations we could do here in the general tracking issue for standalone/kf modes of the web apps https://github.com/kubeflow/kubeflow/issues/5566#issuecomment-786576445

**Comment by andreyvelich** [comment]
> Correct, we can have any entries that would be in the sidebar-menu to be in the dashboard. I've already done something like this in the picture above, where the Dashboard has a NAS and HP Tuning entries under Experiments.

Make sense, I think we should discuss which pages we want to see in the menu in the current Katib status.
For example, currently we use the same CRD for NAS and HP which makes possible to use one page to deploy Experiments.

**Comment by djmcgreal** [comment]
Hi,
I’m trying to put Katib UI behind OIDC authn. I believe Kubeflow UI supports oidc but it doesn’t look like I can do it at the moment with a standalone Katib? Is that the sort of thing you’d like to support?
Thanks, Dan.

**Comment by andreyvelich** [comment]
Hi @djmcgreal, maybe this PR might be helpful for your use-case: https://github.com/kubeflow/katib/pull/2145 that adds support for groups.
Please feel free to create a separate issue to track usage Katib UI behind custom OIDC provider.
