### ISSUE TITLE
Katib imagePullPolicy is by default "Always" in given sample code

### ISSUE THREAD

**Issue by nidhidamodaran** [kubeflow/katib#144]
imagePullPolicy of Image specified in worker-config.yml is by default being set as Always.

As such I am unable to use locally available docker images for running tests.
Even if "imagePullPolicy: Never" is specified in worker-config.yml, during  client execution, it is still trying to pull image from public repo.

Is there any other option to be set for this ?

**Comment by nidhidamodaran** [comment]
mxnet image used to validate hyperparameters with. Even if the image is available, it is still pulled everytime.

**Comment by nidhidamodaran** [comment]
Is there a way to specify local images in worker-config.yml so that local images are picked ?

**Comment by YujiOshima** [comment]
Sorry, there is no way to specify image pull policy for worker pod.
We will improve that probrem in this PR https://github.com/kubeflow/katib/pull/141 .
After that, you can use any manifests for workers.
