### ISSUE TITLE
[UI Feature] Sorting for the Trial list table

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1441]
/kind feature

User should be able to sort Trial table by columns and Trial table should have pages.
Ref PRs for the old UI: https://github.com/kubeflow/katib/pull/1251, https://github.com/kubeflow/katib/pull/1262.

/cc @kimwnasptd

**Comment by Christian-Jansen** [comment]
Hello and thank you for the great work so far!
Are there currently any plans to implement this feature in the near future?

**Comment by andreyvelich** [comment]
This feature was implemented as part of https://github.com/kubeflow/katib/pull/2040.
/close
cc @elenzio9 @Christian-Jansen
