### ISSUE TITLE
[UI bug] Missing configuration fields in form

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/katib#1443]
/kind bug

The new Katib UI's form for submitting `Experiment` CRs is missing the following fields, which are present in the current UI's form:
- [x] [ResumePolicy](https://github.com/kubeflow/katib/blob/60f6c207ce8e1c88545450480c3a6f6dd0909ad5/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L58) https://github.com/kubeflow/katib/pull/1463
- [x] [EarlyStopping](https://github.com/kubeflow/katib/blob/60f6c207ce8e1c88545450480c3a6f6dd0909ad5/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L37) https://github.com/kubeflow/katib/pull/1463
- [x] [TrialParameters](https://github.com/kubeflow/katib/blob/60f6c207ce8e1c88545450480c3a6f6dd0909ad5/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L217) https://github.com/kubeflow/katib/pull/1463

The most important one is the `TrialParameters` since without it the user cannot submit an Experiment by only using the form.
```
admission webhook "validating.experiment.katib.kubeflow.org" denied the request: spec.trialTemplate.trialParameters must be specified
```

/cc @andreyvelich

**Comment by kimwnasptd** [comment]
I'll continue working on this now that the first iteration of our new UI #1421 is merged.

@andreyvelich @gaocegege @johnugeorge I see that the current UI has a way to automatically detect the Trial parameters. How exactly does this work? Does the UI parse the string content from the provided ConfigMaps and detects the `${trialParameters.<name>}`?

Also @andreyvelich could you also add this issue to our Kanban board?

**Comment by andreyvelich** [comment]
> I'll continue working on this now that the first iteration of our new UI #1421 is merged.

Thanks @kimwnasptd!

> @andreyvelich @gaocegege @johnugeorge I see that the current UI has a way to automatically detect the Trial parameters. How exactly does this work? Does the UI parse the string content from the provided ConfigMaps and detects the `${trialParameters.<name>}`?

Yes:
https://github.com/kubeflow/katib/blob/081db0dd7f6f9470400f45dd4431c96927608845/pkg/ui/v1beta1/frontend/src/reducers/general.js#L88-L109

It just parses parameters for the given YAML Trial template.

**Comment by kimwnasptd** [comment]
ACK, I'll mimic this logic then.

Also, I was thinking about making the `Reference` field a dropdown list instead of a simple text input. My rationale was that if the field's value will be one of the hyper parameters then lets reduce the input required from the user and just list to them the available options.

My only question is if this holds for NAS Experiments. Looking at the docs I see they hint that the `reference` value of the trial params can be one of the hyper params, but it's not clear to me what's the case for NAS.
https://www.kubeflow.org/docs/components/katib/trial-template/#configure-trial-template-specification

Do you guys think I could make the `reference` input a dropdown instead or should we stick to basic text inputs?
![Screenshot from 2021-03-09 00-15-49](https://user-images.githubusercontent.com/11134742/110389067-a780ee00-806c-11eb-82ad-9014ae909c15.png)

**Comment by kimwnasptd** [comment]
Also I can confirm that I can create Experiments using the new UI's form, once it also sets the `trialParameters` form field.

So I'll move on to including the `EarlyStopping` and `ResumePolicy` settings, as mentioned in the beginning of the issue, which are the last missing ones for the new form to be on par with the current one.

I see that [EarlyStopping](https://github.com/kubeflow/katib/blob/60f6c207ce8e1c88545450480c3a6f6dd0909ad5/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L37) accepts an arbitrary list of algorithm settings. Are these settings defined as finite list of values? Was thinking if it would make sense to pre-define these values like we do for the other algorithm settings
![Screenshot from 2021-03-09 00-38-16](https://user-images.githubusercontent.com/11134742/110391164-c6cd4a80-806f-11eb-9337-e621c80bab03.png)

**Comment by andreyvelich** [comment]
> Also, I was thinking about making the Reference field a dropdown list instead of a simple text input. My rationale was that if the field's value will be one of the hyper parameters then lets reduce the input required from the user and just list to them the available options

I think it's great improvements for the HP experiment since almost every time `reference` is equal to one of the parameters.
We have only one case when `reference` is not equal to parameters right now, it is described [here](https://www.kubeflow.org/docs/components/katib/trial-template/#use-trial-metadata-in-template).
You check the example with metadata substitution here: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-metadata-substitution.yaml#L27-L48
I think we should discuss how we can provide user that functionality via submit page.

For `NAS` since "`reference` - the parameter name that experiment’s suggestion returns.", `reference` differs from parameters. For ENAS `reference` is equal to this: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/enas-example-cpu.yaml#L128-L133.
For DARTS `reference` is equal to this: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/darts-example-cpu.yaml#L45-L53.
We can setup some default parameter list for NAS experiment, I think. 

WDYT @gaocegege @johnugeorge ?

**Comment by andreyvelich** [comment]
> Also I can confirm that I can create Experiments using the new UI's form, once it also sets the `trialParameters` form field.
> 
> So I'll move on to including the `EarlyStopping` and `ResumePolicy` settings, as mentioned in the beginning of the issue, which are the last missing ones for the new form to be on par with the current one.
> 
> I see that [EarlyStopping](https://github.com/kubeflow/katib/blob/60f6c207ce8e1c88545450480c3a6f6dd0909ad5/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L37) accepts an arbitrary list of algorithm settings. Are these settings defined as finite list of values? Was thinking if it would make sense to pre-define these values like we do for the other algorithm settings
> ![Screenshot from 2021-03-09 00-38-16](https://user-images.githubusercontent.com/11134742/110391164-c6cd4a80-806f-11eb-9337-e621c80bab03.png)

Thank you for your effort @kimwnasptd, it's great.
Yes, you can find Early Stopping algorithm settings here: https://www.kubeflow.org/docs/components/katib/early-stopping/#median-stopping-rule.

**Comment by kimwnasptd** [comment]
closing this issue since https://github.com/kubeflow/katib/pull/1463 has added the missing fields of the form.

The form is now on par with the current default UI.
