### ISSUE TITLE
[SDK] list_trials and list_experiments should return list of objects

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1447]
/kind feature

See discussion https://github.com/kubeflow/katib/pull/1442#discussion_r579503300.
`list_trials` and `list_experiments` should return list of corresponding objects instead of names and statuses to give user more functionality.

/cc @gaocegege @johnugeorge @Adarsh2910

**Comment by anencore94** [comment]
Hi @andreyvelich again :)
I think this issue needs to be resolved too. May I take this issue ?

**Comment by andreyvelich** [comment]
Hey @anencore94!
Sure, that would be great, thank you!

/assign @anencore94

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:
