### ISSUE TITLE
the error about  the bayesianoptimization

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#145]
when i want to run katib/cmd/suggestion/bayesianoptimization/main.py  it throwed error :AttributeError: 'module' object has no attribute 'GenerateTrialsRequest'.  and there "module" refers to the pkg.api.python.api_pb2. and it indeed didn't has method GenerateTrialsRequest.

**Comment by YujiOshima** [comment]
@wukong1992 Thank you for reporting.
Bayse optimization probably uses outdated API.

**Comment by wukong1992** [comment]
how to get the latest code @YujiOshima

**Comment by YujiOshima** [comment]
@wukong1992 Sorry for confusing you.
Currently, Bayse optimization looks broken. And it is not tested in CI. We should fix it.

**Comment by jlewi** [comment]
Do we have issues tracking fixing Bayes Optimization and adding tests?
Will this be fixed by #188?

**Comment by YujiOshima** [comment]
@jlewi I hope so.

**Comment by YujiOshima** [comment]
Fixed by #188 
/close
