### ISSUE TITLE
[Juju] Update Juju operator with webhook manifests changes

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1453]
/kind feature

After this PR: https://github.com/kubeflow/katib/pull/1450, we should update our Juju operators with the latest manifest changes. 

/cc @DomFleischmann @knkski @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
Thank you for creating this issue @andreyvelich !! We'll take a look into it :)

**Comment by andreyvelich** [comment]
@DomFleischmann @knkski @RFMVasconcelos I have released the latest commit: `c6c9172` in the `kubeflowkatib` registry: https://hub.docker.com/u/kubeflowkatib.
You should be able to use latest tag to get the latest changes for the controller now.
