### ISSUE TITLE
[Juju] Create script to update manifest from Katib origin YAMLs

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1468]
/kind feature

Check discussion: https://github.com/kubeflow/katib/pull/1465#discussion_r592519705.
We should create a script to automatically update YAML structure from Katib manifest.

/cc @DomFleischmann @knkski @RFMVasconcelos

**Comment by RFMVasconcelos** [comment]
Hi @andreyvelich ! 

Thank you for creating this and sorry that we didn't get to it yet. We've had our hands full with the v1.3 operators and have just now been able to grow the team. Hopefully we'll get to this soon :)

**Comment by andreyvelich** [comment]
Thank you for this effort @RFMVasconcelos!
Look forward to it.

**Comment by andreyvelich** [comment]
We removed Juju operator from upstream Katib manifests.
