### ISSUE TITLE
Why is this project named katib?

### ISSUE THREAD

**Issue by cheyang** [kubeflow/katib#147]
I'm just wondering what katib stands for? I guess it's Kubernetes automatic tunning ...?

**Comment by YujiOshima** [comment]
https://github.com/kubeflow/katib/blob/master/README.md
>Katib stands for secretary in Arabic. As Vizier stands for a high official or a prime minister in Arabic, this project Katib is named in the honor of Vizier.

**Comment by cheyang** [comment]
Thank you!
