### ISSUE TITLE
Katib Roadmap 2021

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1484]
We should discuss our Katib Roadmap for 2021.

Some points from my side:

## Katib enhancements
- Finish AWS CI/CD migration for the release process.
- New Katib UI implementation: https://github.com/kubeflow/katib/projects/1.
- Support [multiple versions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) in Katib CRDs.
- Support various parameter distribution: https://github.com/kubeflow/katib/issues/1207.
- Finish validation for the algorithms: https://github.com/kubeflow/katib/issues/1126.

## Advanced AutoML features
- Refactor Hyperband: https://github.com/kubeflow/katib/issues/1389.
- Support [ASHA](https://arxiv.org/pdf/1810.05934.pdf), I believe it is very popular.
- Separate CRD for NAS and HP ?
- Support Population Based Training: https://github.com/kubeflow/katib/issues/1382.
- Support AutoMC: https://github.com/kubeflow/katib/issues/460.
- Support Feature Engineering: https://github.com/kubeflow/katib/issues/475.

Please give your feedback and what do you want to see in Katib 2021.
cc @gaocegege @johnugeorge @PatrickXYS @terrytangyuan @kimwnasptd @yanniszark @jbottum  @c-bata @RFMVasconcelos @knkski @anneum @thomas-mueller

Let's finalise our Roadmap on the upcoming WG meetings (24th of March and 7th of April).

**Comment by PatrickXYS** [comment]
This is awesome! Getting a roadmap and get all the items shipped at the end of the 2021 will be a great milestone

**Comment by c-bata** [comment]
I think it is great if Katib dashboard will support a visualization of hyperparameter importance using fANOVA algorithm.
https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_param_importances.html#optuna.visualization.plot_param_importances

optuna-dashboard will support it from the next release:
https://github.com/optuna/optuna-dashboard/pull/54#discussion_r593776351

And I'm planning to implement fANOVA algorithm in [Goptuna](https://github.com/c-bata/goptuna) next month 👍

**Comment by andreyvelich** [comment]
It's great idea @c-bata.
I think we can try to include this feature in the new Katib UI.
cc @kimwnasptd 

Btw, @c-bata do we have plans to integrate https://github.com/kubeflow/katib/issues/1283 in Katib 2021 ?

**Comment by c-bata** [comment]
YES! Sorry, I forgot it.

**Comment by andreyvelich** [comment]
Support MLMD for Katib Experiment.

**Comment by frankmanbb** [comment]
TFX also has a tuner, https://www.tensorflow.org/tfx/guide/tuner, any possibility that we can use Katib in tfx as well? Maybe as a custom tfx component?

**Comment by andreyvelich** [comment]
> TFX also has a tuner, https://www.tensorflow.org/tfx/guide/tuner, any possibility that we can use Katib in tfx as well? Maybe as a custom tfx component?

This is interesting. That should be possible when TFX is running on top of Kubernetes.
WDYT @gaocegege @johnugeorge ?
@Bobgy Do we have any examples when KFP and TFX are running together ?
