### ISSUE TITLE
Failed to run the Minikube example

### ISSUE THREAD

**Issue by cheyang** [kubeflow/katib#149]
I'm trying to run the latest code of the Minikube example:

```
go run client-example.go -s 172.16.2.134:6789 -a rand
om
2018/08/19 19:35:33 StudyConfig Error rpc error: code = Internal desc = grpc: error unmarshalling request: unexpected EOF
exit status 1
```
Can you help me with it? thanks.

**Comment by YujiOshima** [comment]
@cheyang It is probably mismatch the API version between server and client. 
You may resolve it by using `:master` tagged images for the katib components.
We are preparing more simple getting start demo in #141 .
Sorry for inconvenient.

**Comment by cheyang** [comment]
I've tried to change to `:master`.

But I also see 

```
go run client-example.go -s 172.16.2.135:6789 -a random
2018/08/20 06:40:47 StudyConfig Error rpc error: code = Unknown desc = Error 1136: Column count doesn't match value count at row 1
exit status 1
```

**Comment by nidhidamodaran** [comment]
@cheyang , #140  workaround for the same.

**Comment by jlewi** [comment]
Has this issue been resolved?

**Comment by YujiOshima** [comment]
Yes, please use studyjob crd.
/close
