### ISSUE TITLE
Using katib-launcher with TFJob fails

### ISSUE THREAD

**Issue by janousy** [kubeflow/katib#1496]
/kind bug

**What steps did you take and what happened:**
I defined my pipeline using the kfp SDK to launch a TFJob with the [katib-launcher](https://github.com/kubeflow/pipelines/tree/master/components/kubeflow/katib-launcher) to tune the learning rate of my tensorflow keras model. To do so, I modified the MPIJob example [here](https://github.com/kubeflow/pipelines/blob/master/samples/contrib/kubeflow-katib/mpi-job-horovod.py).
The pipeline compiles without issues. When I upload the tar.gz file to the Kubeflow pipelines interface, the experiment fails immediately with the following error:

`Error: Failed to getArtifactTypes: Http response at 400 or 500 level. Code: 5 Click Details for more information.`
`{"code":5,"message":"Failed to getArtifactTypes: Http response at 400 or 500 level"}`

The pipeline run logs say this (full logs attached):
`
RuntimeError: Exception when calling CustomObjectsApi->create_namespaced_custom_object:         (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Cache-Control': 'no-cache, private', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'de3c2d6e-cc35-43dc-b0ca-7b74f316732d', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'cb74c7cd-58e4-4c77-af7d-9f87e20f88c6', 'Date': 'Mon, 29 Mar 2021 19:44:44 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
`

[logs.txt](https://github.com/kubeflow/katib/files/6224348/logs.txt)

Moreover, I can create katib experiments with yaml files such as [this](https://github.com/janousy/cdl/blob/master/deployments/hptuning/fmnist-experiment-distributed.yaml) without issues.
I only have one namespace called `admin` besides the default `kubeflow` namespace

My [pipeline](https://github.com/janousy/cdl/blob/master/katib/tfjob_katib_sample.py) is defined as follows:

          @dsl.pipeline(
              name="Launch Katib TFJob Experiment",
              description="An example to launch Katib Experiment with TFJob"
          )
          def fmnist_hpo(
                  name="fminst-hpo-{{workflow.uid}}",
                  experiment_namespace="admin",
          ):
          
              # Trial count specification.
              max_trial_count = 6
              max_failed_trial_count = 3
              parallel_trial_count = 3
          
              # Objective specification.
              objective = V1beta1ObjectiveSpec(
                  type="maximize",
                  goal=0.9,
                  objective_metric_name="val_accuracy",
                  additional_metric_names=["loss", "accuracy"]
              )
          
              # Algorithm specification.
              algorithm = V1beta1AlgorithmSpec(
                  algorithm_name="random",
                  algorithm_settings=[
                      V1beta1AlgorithmSetting(
                          name="random_state",
                          value="10"
                      )
                  ]
              )
          
              # Experiment search space.
              # In this example we tune learning rate and number of training steps.
              parameters = [
                  V1beta1ParameterSpec(
                      name="lr",
                      parameter_type="double",
                      feasible_space=V1beta1FeasibleSpace(
                          min="0.001",
                          max="0.05"
                      ),
                  ),
              ]
          
              rawTemplate = {
                  "apiVersion": "kubeflow.org/v1",
                  "kind": "TFJob",
                  "metadata": {
                      "name": "{{.Trial}}",
                      "namespace": "{{.NameSpace}}"
                  },
                  "spec": {
                      "template": {
                          "spec": {
                              "restartPolicy": "Never",
                              "containers": [
                                  {"name": "{{.Trial}}",
                                   "image": "docker.io/janousy/fmnist-train-keras:v1.1",
                                   "imagePullPolicy": "Always",
                                   "command": [
                                       "python /opt/model.py "
                                       "--tf-mode=local"
                                       "--tf-learning-rate",
                                          "${trialParameters.learningRate}",
                                   ]
                                   }
                              ]
                          }
                      }
                  }
              }
          
              trial_spec = {
                  "goTemplate": {
                      "rawTemplate": json.dumps(rawTemplate)
                  }
              }
          
              # Configure parameters for the Trial template.
              trial_template = V1beta1TrialTemplate(
                  # primary_pod_labels={
                  #     "mpi-job-role": "launcher"
                  # },
                  #primary_container_name="tf-launcher",
                  success_condition='status.conditions.#(type=="Succeeded")#|#(status=="True")#',
                  failure_condition='status.conditions.#(type=="Failed")#|#(status=="True")#',
                  trial_parameters=[
                      V1beta1TrialParameterSpec(
                          name="learningRate",
                          description="Learning rate for the training model",
                          reference="lr"
                      ),
                  ],
                  trial_spec=trial_spec
              )
          
              # Create Experiment specification.
              experiment_spec = V1beta1ExperimentSpec(
                  max_trial_count=max_trial_count,
                  max_failed_trial_count=max_failed_trial_count,
                  parallel_trial_count=parallel_trial_count,
                  objective=objective,
                  algorithm=algorithm,
                  parameters=parameters,
                  trial_template=trial_template
              )
          
              # Get the Katib launcher.
              # Load component from the URL or from the file.
              katib_experiment_launcher_op = components.load_component_from_url(
                  "https://raw.githubusercontent.com/kubeflow/pipelines/master/components/kubeflow/katib-launcher/component.yaml")
          
              # Katib launcher component.
              # Experiment Spec should be serialized to a valid Kubernetes object.
              # The Experiment is deleted after the Pipeline is finished.
              op = katib_experiment_launcher_op(
                  experiment_name=name,
                  experiment_namespace=experiment_namespace,
                  experiment_spec=ApiClient().sanitize_for_serialization(experiment_spec),
                  experiment_timeout_minutes=60)
          
              # Output container to print the results.
              dsl.ContainerOp(
                  name="best-hp",
                  image="library/bash:4.4.23",
                  command=["sh", "-c"],
                  arguments=["echo Best HyperParameters: %s" % op.output],
              )
        
          
          
          if __name__ == "__main__":
              kfp.compiler.Compiler().compile(fmnist_hpo, __file__ + ".tar.gz")

**What did you expect to happen:**
The pipeline should launch a katib experiment which runs a TFJob to tune the learning rate of my [tensorflow keras model](https://github.com/janousy/cdl/blob/master/model/tf/model.py). The image lies on a public DockeHub.

**Anything else you would like to add:**
- katib controller (`kubectl get deploy katib-controller -n kubeflow -o yaml`) -> see attached katib-controller.txt
[katib-controller.txt](https://github.com/kubeflow/katib/files/6224346/katib-controller.txt)

- the model image used in the TFJob can be found [here](https://github.com/janousy/cdl/blob/master/model/tf/model.py).

**Environment:**
Kubeflow was deployed using [these](https://www.kubeflow.org/docs/started/workstation/kubeflow-on-microk8s/) instructions. Additionally, I am using a VPN SOCKS proxy on port 9999 to access the dashboard.

- Kubeflow version (`kfctl version`): v1.2
- Microk8s version: microk8s 1.20 /stable 
- Kubernetes version: (use `kubectl version`): GitVersion:"v1.20.4-34+1ae8c29b
- OS (e.g. from [`/etc/os-release`):] https://releases.ubuntu.com/20.04/

I compile the pipeline locally, thus:
- kubeflow-katib version (` pip show kubeflow-katib`):  0.10.1
- kfp SDK version (`pip show kfp`):  1.5.0rc0

[katib-controller.txt](https://github.com/kubeflow/katib/files/6224346/katib-controller.txt)
[logs.txt](https://github.com/kubeflow/katib/files/6224348/logs.txt)

**Comment by janousy** [comment]
As an update, when I try to run [this](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/tfjob-example.yaml) example from the katib repository (chaning the namespace to "admin" instead of "kubeflow") using `kubectl apply -f katib-tfjob-example.yaml` I get the reponse:

`error: unable to recognize "katib-tfjob-example.yaml": no matches for kind "Experiment" in version "kubeflow.org/v1beta1"`

According to the [Kubeflow documentation](https://www.kubeflow.org/docs/reference/version-policy/), Kubeflow 1.2.0 (on microk8s v1.20.4) comes with Katib application version v1alpha3. Is this correct? Would this mean I have to upgrade Katib first?

**Comment by andreyvelich** [comment]
Thank you for creating this @janousy.
> According to the Kubeflow documentation, Kubeflow 1.2.0 (on microk8s v1.20.4) comes with Katib application version v1alpha3. Is this correct? Would this mean I have to upgrade Katib first?

Yes, you are right. The Katib KFP example is created for the Katib 0.10.
So you should update the Katib version on your cluster.

**Comment by janousy** [comment]
Thanks for the reply @andreyvelich! As I couldn't find any documentation about this, do you know where to find resources on how to update katib on an existing microk8s cluster?

**Comment by andreyvelich** [comment]
> Thanks for the reply @andreyvelich! As I couldn't find any documentation about this, do you know where to find resources on how to update katib on an existing microk8s cluster?

You should delete all Katib resources first. I think you can use [this commit](https://github.com/kubeflow/katib/tree/4559e16114a62cd78c3e0a512c271df562f373b9/manifests/v1alpha3) to remove v1alpha3 Katib resources.

Then, follow [this step](https://github.com/kubeflow/katib#katib) to install latest Katib version.

**Comment by janousy** [comment]
Okay thanks for your help, I'll wait for the KF 1.3 release.
