### ISSUE TITLE
Two lines of error messages are reversed.

### ISSUE THREAD

**Issue by CR1SceNT** [kubeflow/katib#1516]
The error messages of lines 100 and lines 108 are reversed in cmd/katib-controller/v1beta1/main.go. The first error should be "Failed to create the manager." and the other should be "unable add APIs to scheme".

**Comment by andreyvelich** [comment]
@CR1SceNT Thank you for investigating this!
It would be great if you could create a PR to fix this.

/good-first-issue

**Comment by himanshu007-creator** [comment]
hi! I would like to work on this issue

**Comment by andreyvelich** [comment]
Thank would be helpful, thanks @himanshu007-creator!
