### ISSUE TITLE
Experiment completed but stuck in running state

### ISSUE THREAD

**Issue by richardagalvez** [kubeflow/katib#1540]
/kind bug

**What steps did you take and what happened:**
I have an experiment which I began with maxTrialCount 100, but I edited it while running to decrease to 34. Experiment successfully completed 34 trials, but deployment, pod, and stateful set continues to exist with the experiment stuck in running state. All trials completed.

**What did you expect to happen:**
I am unsure how to forcefully set the experiment status to successfully completed.

**Environment:**

- Kubeflow version (`kfctl version`):  kfctl v1.2.0-0-gbc038f9
- Minikube version (`minikube version`): on production aws env
- Kubernetes version: (use `kubectl version`):  1.18
- OS (e.g. from `/etc/os-release`): mac os

**Comment by richardagalvez** [comment]
This is not a bug. Please edit as necessary. Help appreciated!

**Comment by andreyvelich** [comment]
Thank you for creating this @richardagalvez.
Please can you show the Katib Controller logs ?
Also, all 34 Trials are in Succeeded state, right ?
