### ISSUE TITLE
Renaming katib

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/katib#1548]
/kind feature

I remember a while ago that there was a desire to change the name of `katib` to be more descriptive.

_PP: I think `kubeflow-tune` (kftune) is the logical choice as [AutoML is used by GCP](https://cloud.google.com/automl)_

**Comment by thesuperzapper** [comment]
What is the status of this @kubeflow/wg-automl-leads?

**Comment by johnugeorge** [comment]
Yes. There were discussions before. Because of the bigger effort required in getting the name changes across  CI/CD env, docs and code, we didn't take it at that time.

**Comment by andreyvelich** [comment]
Our users also voted for Katib name after the survey: https://docs.google.com/forms/d/e/1FAIpQLSdbtUn95BfI4iWcgwhvRy38ZG7637dV0hXDAPqx-g_7Nk4Rnw/viewanalytics.
