### ISSUE TITLE
tfjob error

### ISSUE THREAD

**Issue by seoha-kim** [kubeflow/katib#1551]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

/usr/local/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
/usr/local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)
ERROR:grpc._server:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 434, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/opt/katib/pkg/apis/manager/v1beta1/python/api_pb2_grpc.py", line 131, in ValidateAlgorithmSettings
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
INFO:pkg.suggestion.v1beta1.skopt.base_service:----------------------------------------------------------------------------------------------------

INFO:pkg.suggestion.v1beta1.skopt.base_service:New GetSuggestions call

INFO:pkg.suggestion.v1beta1.skopt.base_service:Running Optimizer ask to query new parameters for Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:New suggested parameters for Trial: [0.00026700912731765963, 0.1100872303406049, 0.17887306987847956, 0.0025157863043380065, 6, 66095, 17, 2.9930915474229054e-05, 0.000523498414406722, 0.5681668745506113, 'adabelief', 5.957279166303203, 9.379509996103724, 1.5358479961654232, 4.2538343398852225]
INFO:pkg.suggestion.v1beta1.skopt.base_service:New suggested parameters for Trial: [0.0004736159260041258, 5.4115090885417925e-05, 4.8211487647887845e-08, 0.00039496013227641077, 4, 83796, 24, 5.9436510482988866e-05, 0.002143537851070294, 0.9314975906265118, 'adamw', 3.2476653465739727, 8.87954069127076, 1.408474426728863, 8.419695220046094]
INFO:pkg.suggestion.v1beta1.skopt.base_service:GetSuggestions return 2 new Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:----------------------------------------------------------------------------------------------------

INFO:pkg.suggestion.v1beta1.skopt.base_service:New GetSuggestions call

INFO:pkg.suggestion.v1beta1.skopt.base_service:Running Optimizer ask to query new parameters for Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:New suggested parameters for Trial: [2.4278930644303595e-09, 0.000365305590084265, 0.0014345726944696483, 0.00026736917002016434, 5, 91132, 29, 0.0002255731304146342, 0.0031198471925920086, 0.8760572398033475, 'ranger', 2.363634336815723, 6.530674018576151, 1.2202133986315813, 2.5082263592233898]
INFO:pkg.suggestion.v1beta1.skopt.base_service:GetSuggestions return 1 new Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:----------------------------------------------------------------------------------------------------

INFO:pkg.suggestion.v1beta1.skopt.base_service:New GetSuggestions call

INFO:pkg.suggestion.v1beta1.skopt.base_service:Running Optimizer ask to query new parameters for Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:New suggested parameters for Trial: [1.7899861506006096e-09, 0.04718676184663106, 1.1221578824446008e-09, 3.971347777685813e-05, 1, 43149, 19, 1.3406611831985525e-05, 0.0096894070429343, 0.7514167128021748, 'ranger', 8.640263788625038, 6.348515995933947, 1.0665282224301444, 7.795114623382364]
INFO:pkg.suggestion.v1beta1.skopt.base_service:GetSuggestions return 1 new Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:----------------------------------------------------------------------------------------------------

INFO:pkg.suggestion.v1beta1.skopt.base_service:New GetSuggestions call

INFO:pkg.suggestion.v1beta1.skopt.base_service:Running Optimizer ask to query new parameters for Trials

INFO:pkg.suggestion.v1beta1.skopt.base_service:New suggested parameters for Trial: [0.002690048975994994, 1.2195748753503807e-09, 6.559796207881978e-06, 0.44340647691865515, 2, 38000, 26, 0.00011095066948023851, 0.00016279858313919456, 0.8443338688078694, 'adamw', 6.131849205514535, 1.3091846147842097, 1.4405159045751632, 1.8574983271733239]
INFO:pkg.suggestion.v1beta1.skopt.base_service:GetSuggestions return 1 new Trials

it run normally when i applied -f with "Job"
but after i changed it to "TFJob",  there is error

for using custom loss metric, Don't I have to use a TFjob?

                    tf.summary.scalar('batch_3d_2d_loss', loss3d_dict['loss_2d'], step=self.train_global_step)
                    tf.summary.scalar('batch_3d_smpl_loss', loss3d_dict['loss_smpl'], step=self.train_global_step)
                    tf.summary.scalar('batch_3d_loss_rel', loss3d_dict['loss_3d_rel'], step=self.train_global_step)
                    tf.summary.scalar('batch_3d_loss_abs', loss3d_dict['loss_3d_abs'], step=self.train_global_step)

i heard that objective in yaml file mapping with tf.summary.scalar value

are there some error in my TFJob yaml format?
or can i using custom loss metric with Job yaml format

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version (`kfctl version`): 1.2
- Minikube version (`minikube version`): x
- Kubernetes version: (use `kubectl version`): 1.2
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by andreyvelich** [comment]
@seoha-kim Usually, you can use TFJob if you want to run distributive training: https://www.tensorflow.org/guide/distributed_training#setting_up_the_tf_config_environment_variable.

If you to run just a simple TF Training Job you can still use Kubernetes Job.

Ignore this error: `ERROR:grpc._server:Exception calling application: Method not implemented!`.
It just says that Validate Algorithm Setting method is not implemented in Suggestion.

**Comment by seoha-kim** [comment]
Oh Thank you
Can i ask one more question

I want to collect loss with format
loss(...) : {value}

for example:
Total: 0:06:53 | ETA: 0:08:26 | loss: 1.1260 | loss_2d: 0.1125 | loss_3d_rel: 0.3900 | loss_3d_abs: 0.1651 | loss_smpl: 0.3662

I want to collect
loss: 1.1260 
loss_2d: 0.1125
loss_3d_rel: 0.3900
loss_3d_abs: 0.1651
loss_smpl: 0.3662

how can I filter this?
I heard that "([\\w|-]+)\\s*:\\s*((-?\\d+)(\\.\\d+)?)" matches with {key}:{value} format in Katib
but I want to filter {key starts with 'loss'}:{value} only
I never know the regex.. so I need help
Thanks

@andreyvelich

**Comment by andreyvelich** [comment]
@seoha-kim If you want to collect all of your metrics, first of all you have to define them in the objective:
```

  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: loss
    additionalMetricNames:
      - loss_2d
      - loss_3d_rel
      - loss_3d_abs
      - loss_smpl
```
In that case, metrics collector will record all metrics with appropriate names and regex should be like this:
`(\\w+):\\s*((-?\\d+)(\\.\\d+)?)`
If you want to collect all `loss` values for the same Objective metric: `loss`, I think this regex should work for you.
`(loss)\\w*:\\s*((-?\\d+)(\\.\\d+)?)`
