### ISSUE TITLE
Use release tags for the Trial images

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1554]
/kind feature

As discussed in the AutoML meeting at 2021-03-24, we decided to use the latest tag in the `master` branch and release tag in the `release-` branch for the [Trial images](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/hp-tuning/random.yaml#L56).
Then, users can deploy examples for the specific Katib version and use the latest changes.

/cc @gaocegege @johnugeorge @yanniszark

**Comment by gaocegege** [comment]
LGTM!
