### ISSUE TITLE
the resource about studyjob

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#158]
now the studyjob cann't support resource’s configuration,  I want to know if there has a plan to it,  and I think it's a key feature

**Comment by YujiOshima** [comment]
@wukong1992 Please tell me for more detail.
What do you mean the resource’s configuration?

**Comment by wukong1992** [comment]
cpu limit,memory limit and gpu limit

**Comment by YujiOshima** [comment]
You can set these limits for each worker by setting it to [their template](https://github.com/kubeflow/katib/blob/master/examples/workerConfigMap.yaml).
Is it not enough for you?
