### ISSUE TITLE
Automate Container Build for Trial training containers

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1585]
/kind feature

We discussed in our WG meetings and in the summit on 2021-07-16 about Trial training container's source code automation.

Many users request automation for container build instead of manually building images. In that case, users will have uniform experience to tune HP from the Jupyter Notebooks.
We might extend the Katib SDK to support it.

Let's continue discussion about it under this issue.

Resources from GCP: [using Buildpacks](https://cloud.google.com/blog/products/containers-kubernetes/google-cloud-now-supports-buildpacks?_lrsc=c87ebc65-7b47-4d40-bc5f-fce4a2f97f4b&utm_source=elevate&utm_medium=social&utm_campaign=elevate_TwG&utm_term=elevate_TwG_SEID:277467_BID:1111642_TID:6109_SHID:23512237).

cc @gaocegege @johnugeorge 
/priority p2

**Comment by johnugeorge** [comment]
Related Issue in Operators - https://github.com/kubeflow/common/issues/66
