### ISSUE TITLE
Use Trial worker with old Katib version v0.8

### ISSUE THREAD

**Issue by tranlyvu** [kubeflow/katib#1587]
/kind bug
**What steps did you take and what happened:**
Hi all,

1) We are currently using kf v1.0 that shipped with Katib v0.8. 
2)  However, we wanted to follow [this document from kf v1.3 ](https://www.kubeflow.org/docs/components/katib/trial-template/#use-custom-kubernetes-resource-as-a-trial-template)that  to define trial workers xgboostjob.
3) We tried to install  newer version of katib separately,  but  the controller keep crashing
> {"level":"error","ts":1627036996.234885,"logger":"controller-runtime.manager","msg":"error received after stop sequence was engaged","error":"Timeout: failed waiting for *v1beta1.Trial Informer to sync","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2/pkg/manager/internal.go:529"}

We would like to ask:
1) Is there anyway we can define trial workers in old Katib version v0.8
2) Is it possible to deploy new Katib version on kf 1.0 ?

**What did you expect to happen:**
- Able to define xgboostjob and run the task

**Environment:**
- Kubeflow version (`kfctl version`):   v1.0
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`):  v1.15
- OS (e.g. from `/etc/os-release`):  Ubuntu

**Comment by andreyvelich** [comment]
Thank you for creating this @tranlyvu.
Yes, it should be possible.
First of all, you should remove all resources that Katib v0.8 uses, including `MutatingWebhookConfiguration` and `ValidatingWebhookConfiguration`. Then, try to install latest manifest from Katib repository on your cluster.
