### ISSUE TITLE
Is there any REST API reference page?

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1592]
/kind feature

**Describe the solution you'd like**
- HTTP API reference page or docs like [pipeline api refernce](https://www.kubeflow.org/docs/components/pipelines/reference/api/kubeflow-pipeline-api-spec/)
  - I mean [this backend's api](https://github.com/kubeflow/katib/blob/master/pkg/new-ui/v1beta1/backend.go) to request from new-ui frontend
- I guess there is only grpc API refernce page [here](https://www.kubeflow.org/docs/reference/katib/v1beta1/katib/), right?

**Anything else you would like to add:**
Is there any solution to build such http api reference page from source code, I'll be appreciated to let me know hot to do it. Thanks.

**Comment by andreyvelich** [comment]
I think you can use Kubernetes APIs and Katib SDK to perform CRUD calls.
You can find Katib UI backend APIs here: https://github.com/kubeflow/katib/blob/master/cmd/new-ui/v1beta1/main.go#L49-L68
@kimwnasptd What do you think, will it be useful for our users to document our Katib UI APIs?

@anencore94 Please can you explain what is your use-case to run Katib UI APIs outside of Katib frontend ?

In the documentation we have description only for gRPC API as you mentioned.

**Comment by anencore94** [comment]
Thanks for the reply :) @andreyvelich 
Me and my company have been used kubeflow and katib, and we want to customize the whole frontend ui including central dashboard, katib-ui, and so on to meet our purpose.(i.e. integrate with mlflow and minio, add our own product, ...)
So it would be nice if there is an well organized API reference, I guess it's not easy to figure out how to fill the request body, what are the required fields, error codes, ...
And there could be someone else like us to customize the frontend

**Comment by andreyvelich** [comment]
Thank you for providing this information @anencore94.
We can explain our UI APIs somewhere in the docs as part of new Katib UI integration.

@kimwnasptd @johnugeorge @gaocegege What do you think ?

**Comment by johnugeorge** [comment]
Related: #1595

**Comment by johnugeorge** [comment]
Closing this as this is tracked in #1595 
/close
