### ISSUE TITLE
Remove Kubeflow Training imports from go.mod

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1596]
As we discussed in our WG community meeting we can remove packages for `kubeflow/common` and `kubeflow/tf-operator` from Katib controller.
That will help us to decrease dependencies.
We are using this only in Validation webhook: https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L350-L371 which is not necessary.

/cc @gaocegege @johnugeorge 
/area release
/priority p1

/assign @andreyvelich

**Comment by gaocegege** [comment]
SGTM!
