### ISSUE TITLE
Can the different Katib trials run from the same volume/model? 

### ISSUE THREAD

**Issue by PatrickGhosn** [kubeflow/katib#1598]
/kind question

Question:
We are currently running the pytorch Katib pods by mounting the data and model from a shared NFS volume. Does that cause any issues? Should each trial have its own volume for the model? Or perhaps every worker as well?

**Comment by andreyvelich** [comment]
@PatrickGhosn You should be able to mount any volume to your Trial Worker's pods.

>Should each trial have its own volume for the model? Or perhaps every worker as well?

Every Trial Worker should have its own volume to be able to run a Training Job.

If you try to mount same volume on multiple Pods, make sure that your PV supports `ReadWriteMany` mode: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes.
