### ISSUE TITLE
Add Linter and Formatter for python source codes

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1601]
/kind feature

**Describe the solution you'd like**

In kubeflow/katib, there are lots of source codes written in python. Even though there are well-defined CI processes for source codes written in Golang, however for Python codes, only charmed-katib seems to have such process now.

There should be a fixed linter, formatter and tester with some rule-config files(.flake8, .pylintrc, ...) and the github action workflow to check those all. For example, there are lots of unit test codes for suggestion, but current CI process doesn't check if they are failed or check the test coverage decreased in every PR.
If there are any convention checking tools, please share in katib community :)

**Anything else you would like to add:**
If you guys agree to this, I'd like to contribute to this feature in some parts.

**Comment by andreyvelich** [comment]
That is a great suggestion and it will be very useful for us.
Thank you for your help @anencore94!

In addition to that, I think we should move our current Python tests from AWS CI Workflow to GitHub actions: https://github.com/kubeflow/katib/blob/master/test/scripts/v1beta1/python-tests.sh.

Currently, we are not using AWS Kubernetes cluster requirement to perform this workflow step.
We can create separate GitHub Actions Workflow for all Python tests (linter, formatter, unit), similar to Go: https://github.com/kubeflow/katib/tree/master/.github/workflows.

cc @gaocegege @johnugeorge ?

**Comment by anencore94** [comment]
Using mypy to type check would be nice too.

**Comment by gaocegege** [comment]
SGTM, I am not quite familiar with Python, I think we need it.

**Comment by sandipanpanda** [comment]
I would like to work on this.
/assign

**Comment by sagnik3788** [comment]
@sandipanpanda still working on it ?

**Comment by sandipanpanda** [comment]
Sorry, this fell off my radar. @sagnik3788 feel free to work on this.
/unassign

**Comment by forsaken628** [comment]
Which formater is better, [black](https://github.com/psf/black), [autopep8](https://github.com/hhatto/autopep8) or something else?

**Comment by tenzen-y** [comment]
> Which formater is better, [black](https://github.com/psf/black), [autopep8](https://github.com/hhatto/autopep8) or something else?

We are supposed to use the flake8 and black.

**Comment by Souradip121** [comment]
@sagnik3788 still working on it??

**Comment by tenzen-y** [comment]
This has already been fixed by https://github.com/kubeflow/katib/pull/2407.
/close

/assign @Ygnas
