### ISSUE TITLE
Does Katib need Cluster level scope?

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#162]
See #1213

We'd like to be able to scope Kubeflow to a particular namespace to better support multi-tenant environments.

It looks like Katib  is creating a ClusterRole; is this necessary? I suspect its needed if user wants to be able to launch jobs in other namespaces.

Could we add an option though where we restrict Katib to one or more namespaces?

**Comment by chrisheecho** [comment]
/remove-priority p1

No eng resource

**Comment by andreyvelich** [comment]
Ref issue: https://github.com/kubeflow/katib/issues/1295
