### ISSUE TITLE
[UI] Unable to select Experiment parameters

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1620]
/kind bug

I built Katib UI image from the latest master commit.
I am getting the following error:
![Experiment Bug](https://user-images.githubusercontent.com/31112157/129397636-e35ccec2-3cc7-4738-a965-53924ea99e36.gif)

/assign @kimwnasptd 
/priority p0

**Comment by andreyvelich** [comment]
@kimwnasptd I was able to find this problem.
That happens if my K8s cluster doesn't have [Trial Templates](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/controller/trial-templates.yaml).
Once I deployed this ConfigMap with the appropriate Label, form was complete.

I think here: https://github.com/kubeflow/katib/blob/master/pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html#L81-L88, before re-calculate Trial parameters, we have to make sure that Templates were received properly.

Also, when user selects ConfigMaps, we should display that templates don't exists.
We did it in the previous UI: https://github.com/kubeflow/katib/blob/master/pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialConfigMap.jsx#L224.

**Comment by kimwnasptd** [comment]
Thanks for finding and reporiting this @andreyvelich. Both your suggestions make sense.

I'll be on PTO on this week but I'll start working immediately on this once I'll be back.

**Comment by kimwnasptd** [comment]
I'm back, picking this up to include this fix in the 1.4 Kubeflow release
