### ISSUE TITLE
Reconsider Katib Metrics Collector Injection Label

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1622]
/kind discussion

To be consistent with these PRs: https://github.com/kubeflow/katib/pull/1611, https://github.com/kubeflow/katib/pull/1621, we might change our [`katib-metricscollector-injection: enabled`](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/namespace/namespace.yaml#L6) label.

My suggestion is to name this label like this: `katib.kubeflow.org/metrics-collector-injection: enabled`
This will require [Profile Controller](https://github.com/kubeflow/kubeflow/blob/master/components/profile-controller/config/base/namespace-labels.yaml#L15) changes.

Checklist:

- [x] Modify Katib manifests. https://github.com/kubeflow/katib/pull/1740.
- [x] Modify Profile controller. https://github.com/kubeflow/kubeflow/pull/6225

What do you think @gaocegege @alculquicondor @johnugeorge @yanniszark ?

**Comment by gaocegege** [comment]
Should we use katib or automl? automl.kubeflow.org/xxx

**Comment by alculquicondor** [comment]
`katib.kubeflow.org/metrics-collector-injection` sgtm for consistency with #1611

**Comment by gaocegege** [comment]
Then SGTM

**Comment by johnugeorge** [comment]
Do we still need this label in the namespace ?

**Comment by andreyvelich** [comment]
> Do we still need this label in the namespace ?

Yes, we allow to submit Katib Experiments only in namespace with this label: https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validation_webhook.go#L91.

**Comment by andreyvelich** [comment]
We can close this issue.
