### ISSUE TITLE
Katib not ready for K8s 1.22

### ISSUE THREAD

**Issue by DomFleischmann** [kubeflow/katib#1628]
/kind bug

With the new Kubernetes 1.22 release, some APIs have been removed: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

The katib project still uses some of these APIs and will therefore not work on k8s 1.22.

For example, the following CRDs are still using `apiextensions.k8s.io/v1beta1`:
```
trials.kubeflow.org
suggestions.kubeflow.org
experiments.kubeflow.org
```

**Comment by gaocegege** [comment]
dup https://github.com/kubeflow/katib/issues/1581

Thanks for the issue. It should work in the next release.

**Comment by andreyvelich** [comment]
Thank you for creating this @DomFleischmann!
Let's keep this issue re-open.
We have to update rest of deprecated resources: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes.
For example:
- [AdmissionReviewVersion](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/webhook/webhooks.yaml#L11).
- [CertificateSigningRequest](https://github.com/kubeflow/katib/blob/master/hack/cert-generator.sh#L74).

I haven't tested Katib with Kubernetes v1.22, but we should try to upgrade above resources in the next version (e.g. Katib 0.13).
