### ISSUE TITLE
Rename request_number parameter in gRPC manager

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1637]
/kind feature

This PR: https://github.com/kubeflow/katib/pull/1633 introduces `total_request_number ` parameter.
To be consistent, we should rename `request_number` to `current_request_number`.
After that, all suggestions have to be modified.

Does it sound good to you @johnugeorge @gaocegege ?

**Comment by johnugeorge** [comment]
LGTM 

/assign

**Comment by gaocegege** [comment]
SGTM
