### ISSUE TITLE
stdout metric collector

### ISSUE THREAD

**Issue by chenwenjun-github** [kubeflow/katib#1646]
/kind feature

**What steps did you take and what happened:**
1. now stdout metric collector is a sidecar which wait train container complete, but like evaluator of tfjob can't be collected now, the reason is that evaluator can't complete normally and it wiil be deleted forcelly when chief complete, so stdout sidecar  will be killed when pod has been deleted, the evaluator metric can't be collected.

2. now time and metric value which user specify will be collected by stdout metric collector, and time must be RFC3339Nano,  but someboby don't know how to print RFC3339Nano time style when they use python.

**What did you expect to happen:**
1. the metric can be collected realtime rather than wait train container complete

2. parse step rather than time when stdout metric collector parse logs like tensorboard.

**Comment by andreyvelich** [comment]
Thank you for creating this @chenwenjun-github.

>  it wiil be deleted forcelly when chief complete, 

Does the chief have the evaluator metrics or metrics are located only on the evaluator pod ?

> the metric can be collected realtime rather than wait train container complete

In that case, we can't guarantee that all metrics will be collected. For example, pod will be completed before the latest metric is collected.

> parse step rather than time when stdout metric collector parse logs like tensorboard.

That's a good point, we might evaluate how we can modify Metrics Collector settings to support different time specification. cc @gaocegege @johnugeorge

**Comment by chenwenjun-github** [comment]
Thank you for response @andreyvelich .
> Does the chief have the evaluator metrics or metrics are located only on the evaluator pod ?

**Comment by andreyvelich** [comment]
> whether we can collect metric realtime but stop still wait train container complete

When does Chief clean Evaluator pod ? It won't wait until sidecar will be finished, right ?

**Comment by chenwenjun-github** [comment]
it's right. But it can collect part of metrics at least before Chief clean Evaluator pod, now it can't collect anything, i think it will be better.

**Comment by andreyvelich** [comment]
Does it sound consistent to collect not all of the metrics from the training container ?
What do you think @gaocegege @johnugeorge @anencore94 ?

**Comment by anencore94** [comment]
Hmm, It makes sense to collect metrics in real time while training container is still running.
When one trial is too big to finish the whole epoch, user might want to check the progress such as loss is decreasing well or not.

If there isn't difficult to implement for collecting metrics and inserting them to katib-mysql in real-time, such feature would be useful for big models.

**Comment by chenwenjun-github** [comment]
I have implement it and it seem work well in my test,  I can sumbit a pr, what do you think?

**Comment by gaocegege** [comment]
> I have implement it and it seem work well in my test, I can sumbit a pr, what do you think?

Thanks for your contribution! What feature do you mean, can you please explain more about it?

**Comment by gaocegege** [comment]
Can you please update the issue title to the feature you proposed?

**Comment by chenwenjun-github** [comment]
> Thanks for your contribution! What feature do you mean, can you please explain more about it?

I mean that the metric will be collected real-time rather than wait train container complete in stdout mode.

**Comment by gaocegege** [comment]
Gotcha, SGTM.

WDYT @kubeflow/wg-automl-leads

**Comment by andreyvelich** [comment]
If metrics will be collected in the real-time we have to invoke gRPC APIs ([`reportObservationLogs`](https://github.com/kubeflow/katib/blob/master/cmd/metricscollector/v1beta1/file-metricscollector/main.go#L391-L398)) after each log line, if it contains metrics.

I am worry about latency issues, we should test it properly.

What do you think @johnugeorge ?

**Comment by johnugeorge** [comment]
What is the interval in which it is called? what is the trigger logic? @chenwenjun-github
