### ISSUE TITLE
SDK: Change API's return type to custom object

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1647]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

For now, Many APIs in [katib_client.py](https://github.com/kubeflow/katib/blob/master/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py) don't treat type strictly, just using `dict`.

We could change those to deserialize well, and finally use katib's custom objects(classes).

There was a discussion for this issue.
- https://github.com/kubeflow/katib/pull/1630#discussion_r692158614

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by midhun1998** [comment]
Hi @anencore94 . If this is still open I can pick this up.
