### ISSUE TITLE
Hack: automatically generate KatibClient.md doc from `post_gen.py`

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1648]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

There is a script for generating api docs from swagger, but doesn't generate `KatibClient.md` for now. So we should modify manually when api changed.

There was a discussion for this
- https://github.com/kubeflow/katib/pull/1630#discussion_r693344353

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
Should be fixed by this: https://github.com/kubeflow/katib/issues/2081
