### ISSUE TITLE
Reimplement katib-cert-generator in Go

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1656]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, [katib-cert-generator](https://github.com/kubeflow/katib/blob/2d87caafb12e79b2a9e2d534bf513d0a2fa6b7cc/hack/cert-generator.sh) is written in shell script, but shell script is not high maintenance.
Also, the katib-cert-generator needs to support multiple API versions of `certificates.k8s.io`, which will make maintainability even worse.

Ref: https://github.com/kubeflow/katib/issues/1628#issuecomment-901069046.

So I'd like to reimplement it in Go. If the community agrees, I'd like to work on this issue.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
Sure, sounds good to me.
Thank you @tenzen-y!
WDYT @gaocegege @johnugeorge ?

**Comment by johnugeorge** [comment]
How about using cert-manager instead of maintaining one ?

**Comment by andreyvelich** [comment]
@johnugeorge It is useful for environment where cert-manager is not installed.
cert-manager requires much more resources than our simple cert-generator script.

**Comment by tenzen-y** [comment]
Thank you comment. @andreyvelich 
I'd like to take this issue.
