### ISSUE TITLE
golint has been archived

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1670]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, we are using [golint](https://github.com/kubeflow/katib/blob/master/hack/verify-golint.sh) as a linter for Go, although [golint repository](https://github.com/golang/lint) has been archived. So, it might be better replace golint to other linter(ex: [golangci-lint](https://github.com/golangci/golangci-lint)).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
Thank you for creating this @tenzen-y.
Sounds good to me, I guess Kubernetes team is also using this: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-golangci-lint.sh.

WDYT @gaocegege @johnugeorge ?

**Comment by tenzen-y** [comment]
@andreyvelich 
Thanks for your comments!

I believe it might be better to use golangci-lint, but it specifies GPL-3.0 License. I'm not familiar with the OSS license, is there a problem with using it with Katib?
https://github.com/golangci/golangci-lint/blob/master/LICENSE

**Comment by andreyvelich** [comment]
I think it should be fine, since we just run this CLI `golangci-lint`. Right @gaocegege @johnugeorge ?

**Comment by gaocegege** [comment]
LGTM

**Comment by gaocegege** [comment]
It does not affect us. We just use the binary, we do not introduce it as a library.

**Comment by tenzen-y** [comment]
@andreyvelich @gaocegege 
Thank you for the explanation! I'd like to take this issue.

/assign

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:
