### ISSUE TITLE
[PaddlePaddle Hackathon] 94 Implement AutoDL for PaddlePaddle based on KubeFlow Katib

### ISSUE THREAD

**Issue by tizhou86** [kubeflow/katib#1673]
（This is a task ISSUE for PaddlePaddle Hackathon, for more details, see [PaddlePaddle Hackathon](https://www.paddlepaddle.org.cn/PaddleHackathon)）

【Task Specification】

- Title：Implement AutoDL for PaddlePaddle based on KubeFlow Katib
- Tag：Framework，C++，Python，Hyper-Parameter Tuning
- Difficulty：Medium
- Detailed Description： Katib is an inborn project of Kubernetes designed for Automatic Deep Learning (AutoDL). It supports hyper-parameter tuning and neural architecture search. Currently, Katib supports deep learning frameworks, including TensorFlow, MXNet, PyTorch, XGBoost, etc. For this project,  PaddlePaddle AutoDL based on Kubeflow Katib should be implemented.

  Steps：

  1. Download and compile the source code of Katib from GitHub. 
  2. Understand content of the task by referring to sample codes.
  3. Read related documents and codes to understand how to implement PaddlePaddle AutoDL by leveraging Katib.
  4. Complete unit testing and related demo.
  5. Generate PR and related documents.

【Content Submission】

- Project PR to [Katib](https://github.com/kubeflow/katib)
- Related technical documents

【Technical Requirements】

- Proficiency in C++，Python
- Understanding of hyper-parameter tuning in deep learning

**Comment by gaocegege** [comment]
I think this proposal is to support Paddle in Katib, it is helpful for both paddle and katib community 🥂

**Comment by andreyvelich** [comment]
Will be very nice to see integration between Paddle and Katib.
Thank you for driving this @tizhou86!
