### ISSUE TITLE
Add validating webhooks for early stopping experiment

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1680]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently, there are no validating webhooks for early stopping, so users can not notice wrong parameters until to start trial Pod.
So, I'd like to add validating webhooks for the following parameters. 

- `spec.earlyStopping.algorithmName`
- `spec.earlyStopping.algorithmSettings`

What do you think?

/assign

**Comment by tenzen-y** [comment]
Does it sound good ? @andreyvelich @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
Thank you for creating this!
Do you mean similar to [`ValidateAlgorithm`](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L159-L173) ?

**Comment by tenzen-y** [comment]
Thank you for your comment!
Yes, I consider it is better to implement it using [GetEarlyStoppingConfigData](https://github.com/kubeflow/katib/blob/877a7ce123fb7d1d00e428aaafc4950123cdbd61/pkg/util/v1beta1/katibconfig/config.go#L146).

**Comment by andreyvelich** [comment]
Sounds good!

**Comment by tenzen-y** [comment]
I take this Issue.

**Comment by tenzen-y** [comment]
@andreyvelich 
I noticed there are no unit tests for GetFooConfigData in [katibconfig](https://github.com/kubeflow/katib/blob/6f0b2b1e5407deda5b508f97bcdc0869b7439b60/pkg/util/v1beta1/katibconfig/config.go) when I'm implementing unit tests for this Issue. Are they being tested anywhere?

**Comment by tenzen-y** [comment]
I'd like to create PR to add unit tests for `GetFooConfigData` (ex. [`GetSuggestionConfigData`](https://github.com/kubeflow/katib/blob/6f0b2b1e5407deda5b508f97bcdc0869b7439b60/pkg/util/v1beta1/katibconfig/config.go)) before resolving this issue.

**Comment by andreyvelich** [comment]
You are right @tenzen-y.
Currently, only [`composer`](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/suggestion/composer/composer_test.go) tested GetSuggestionConfig, but it doesn't cover all test-cases.

**Comment by tenzen-y** [comment]
Thank you for your answer! @andreyvelich 
First, we'd like to implement unit tests for GetFooConfigData.
