### ISSUE TITLE
Pass Kubeflow pipeline to Katib yaml directly

### ISSUE THREAD

**Issue by ommmid** [kubeflow/katib#1682]
/kind feature

**Describe the solution you'd like**
Passing the Kubeflow pipeline (maybe its yaml file?) inside the Katib yaml file would be an ideal functionality to make the flow smooth in Kubeflow. Instead of creating ML component (creating docker container) inside Katib yaml file, passing a whole pipeline that we already created in Kubeflow makes things much smoother.

**Comment by akonneker** [comment]
Is there any reason we can't use the compiled output yaml of a kubeflow pipeline as an Argo workflow as in this example: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/argo/argo-workflow.yaml

**Comment by andreyvelich** [comment]
Thank you for creating this @ommmid.
This is very useful use-case and we are more than happy to add this example under `/examples/v1beta1/pipelines`.

@akonneker is absolutely right, we can define Argo Workflow under Katib Experiment to handle Kubeflow Pipeline.

@akonneker @ommmid Do you have any interest to add similar examples to this repository ?


cc @kimwnasptd @StefanoFioravanzo as Kale owners you might be interested in that issue. I remember you have made some progress in that.

**Comment by anencore94** [comment]
How about creating an another interface to use Kubeflow PIpeline into Katib with passing kubeflow pipeline's `id`(which is already uploaded) and hyperparameters space? Rather than the whole yaml file(which is actually an Argo Workflow)

**Comment by johnugeorge** [comment]
@anencore94 How would the trial spec look in your proposal?

**Comment by andreyvelich** [comment]
I also great idea.

@anencore94 @johnugeorge I think we can extend [Trial Spec](https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L240-L247) with the new API, for example: 
```
PipelineID string `json:"pipelineID,omitempty"
```

**Comment by anencore94** [comment]
> PipelineID string `json:"pipelineID,omitempty"

We can start from @andreyvelich 's idea. However, I think it's a little bit tricky for hyperparameters and objective metrics.

Since there is the information about arguments in kubeflow pipeline already, but user might want to use some arguments as a hyperparameters with some space and fill other arguments with fixed values.

So I guess we need to make some more detailed field (interface) to get these information from users.

**Comment by andreyvelich** [comment]
> Since there is the information about arguments in kubeflow pipeline already, but user might want to use some arguments as a hyperparameters with some space and fill other arguments with fixed values.

I think substitution of the HPs should be done by Katib Controller. 
Is it possible to get Pipeline by ID similar to ConfigMap data, as we do here: https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/manifest/generator.go#L192-L205 ?
