### ISSUE TITLE
Provide the manifest combination to install Katib with Kubeflow and with external DB

### ISSUE THREAD

**Issue by akdigitalself** [kubeflow/katib#1686]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It would be great if there is an option to install Katib with Kubeflow and with external DB.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
My setup consists of Katib in Kubeflow v1.3 and using RDS as the external DB. 

I can't use the `katib-external-db` install option as it brings in `Namespace` and `katib-cert-generator`. So I use the [katib-with-kubeflow](https://github.com/kubeflow/manifests/tree/master/apps/katib/upstream/installs/katib-with-kubeflow) install option and [the katib-db-manager patch.](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/installs/katib-external-db/patches/db-manager.yaml). As I also have a local patch, I can't use the upstream patch file as a patch along with my local patch - `patchesStrategicMerge` throws an error. So I need to copy the contents of `installs/katib-external-db/patches/db-manager.yaml` in my local patch to make it work.

Having the option to install Katib with Kubeflow and with external DB will be helpful in such setup. Thanks :)

**Comment by andreyvelich** [comment]
Thank you for creating this @akdigitalself, this is very useful use-case.

I think, first of all we should [create new interface](https://github.com/kubeflow/katib/blob/master/pkg/db/v1beta1/db.go#L26-L32) in katib-db-manager to support RDS.
Currently, it supports only mysql backend.
What do you think @akdigitalself @gaocegege @johnugeorge ?

**Comment by johnugeorge** [comment]
Yes. This is a nice feature to support cloud based databases

**Comment by akdigitalself** [comment]
The external DB manifest works well. However using it [as is](https://github.com/kubeflow/katib/blob/v0.12.0/manifests/v1beta1/installs/katib-external-db/kustomization.yaml) brings in the resources I don't want (such as `Namespace` and `katib-cert-generator` as I mentioned in the description above) as I also use `katib-with-kubeflow`. In other words, all manifests work flawlessly by themselves. It's just that there's no manifest combination in [this installs directory](https://github.com/kubeflow/katib/tree/v0.12.0/manifests/v1beta1/installs) to use Katib with Kubeflow AND with external DB (which is how my setup looks like).
