### ISSUE TITLE
Demo Katib+Argo at the Argo community meeting, or blog

### ISSUE THREAD

**Issue by alexec** [kubeflow/katib#1698]
/kind feature

It'd be awesome to have you come demo your new Argo support. We could also do a collaborative blog post too!

@andreyvelich

**Comment by johnugeorge** [comment]
@alexec Created the meeting on 27th. We will try to join. 

btw, Missed to link this GitHub chat in the meeting description for reference.

**Comment by alexec** [comment]
This was done - thank you!
