### ISSUE TITLE
Support leader-election (HA) for Katib Components

### ISSUE THREAD

**Issue by aaron-arellano** [kubeflow/katib#1705]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Ability to enable leader-election for Katib components. We run kubeflow in multiple AZs and strive to achieve HA whenever possible for our components to guarantee SLOs for our users.  We would like for Katib components to support leader-election to enable HA in the event a node goes down in a particular AZ.

**Comment by tenzen-y** [comment]
I'm interested in this feature!
Can I take this? @kubeflow/wg-automl-leads

**Comment by johnugeorge** [comment]
@tenzen-y Thanks for the interest.
Assigned to you

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:
