### ISSUE TITLE
Bump Python version to 3.9

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1730]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Python 3.6 is approaching EOL(2021-12-23) although all suggestions and earlystopping services are used it.
So, bump Python version to 3.9.

https://devguide.python.org/#status-of-python-branches

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/assign

**Comment by tenzen-y** [comment]
Also, I think it needs to upgrade tensorflow since tensorflow 1.11.0 does not distribute binary for Python 3.7 in tfevent-metricsconllector.

https://github.com/kubeflow/katib/blob/16e0574647ace79ccedd248d072c77139feab5e5/cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile#L1

Ref: https://pypi.org/project/tensorflow/1.11.0/#files

**Comment by tenzen-y** [comment]
I'm wondering if I should upgrade to v1.5.5, which is the last release of Tensorflow v1 or upgrade to the latest release, v2.7.0. 
WDYT about the TensorFlow version? @kubeflow/wg-automl-leads

**Comment by andreyvelich** [comment]
Thank you for creating this @tenzen-y.

Should we jump to Python 3.9 if it is possible, do we have any concern about it ? 

> I'm wondering if I should upgrade to v1.15.5, which is the last release of Tensorflow v1 or upgrade to the latest release, v2.7.0.

I think TF >= 2.0 requires some code changes, especially in ENAS Suggestion.
If we can handle it, sure we can use the latest TF release.

**Comment by tenzen-y** [comment]
Thanks for the suggestion! @andreyvelich 

> Should we jump to Python 3.9 if it is possible, do we have any concern about it ?

I also think we can jump to Python 3.9.

> I think TF >= 2.0 requires some code changes, especially in ENAS Suggestion.
If we can handle it, sure we can use the latest TF release.

I see, I would like to update to Tensorflow >2.0 and also modify ENAS.

**Comment by gaocegege** [comment]
Does TF 2.0 metrics collector work well with TF 1.x events?

**Comment by tenzen-y** [comment]
I believe that the output format of metrics has not changed between TF v1 and v2, as shown in the following document.

- v1:
```shell
events.out.tfevents.1613185647.kokoro-gcp-ubuntu-prod-2039871251.28609.1446.v2
```

- v2:

```shell
events.out.tfevents.1613185646.kokoro-gcp-ubuntu-prod-2039871251.28609.5.v2
```

https://www.tensorflow.org/tensorboard/migrate#in_tf_2x

WDYT? @gaocegege @andreyvelich

**Comment by andreyvelich** [comment]
Sounds good @tenzen-y.
Once we modify TF Event metrics collector, we need to be sure that it is working with TF 2.0

**Comment by tenzen-y** [comment]
> Once we modify TF Event metrics collector, we need to be sure that it is working with TF 2.0

SGTM

I think it might be better to create a training code using TF 2.0 based on [mnist_with_summaries.py](https://github.com/kubeflow/training-operator/blob/c41956d1c71283302f796b401ad633e0baf3aad0/examples/tensorflow/mnist_with_summaries/mnist_with_summaries.py), to add it as the e2e test separate from [tfjob](https://github.com/kubeflow/katib/blob/cffab076b67714ff0e8849142df953e458b58300/test/e2e/v1beta1/argo_workflow.py#L80).

WDYT? @andreyvelich @gaocegege

**Comment by andreyvelich** [comment]
Sounds good to me, we can maintain another image under [trial-images](https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images) with TF with summaries example.
What do others think @gaocegege @johnugeorge ?

**Comment by tenzen-y** [comment]
> we can maintain another image under trial-images with TF with summaries example.
Sounds good, thanks!
