### ISSUE TITLE
Katib examples in https://github.com/kubeflow/examples/

### ISSUE THREAD

**Issue by js-ts** [kubeflow/katib#1733]
https://github.com/kubeflow/examples/blob/master/demos/yelp_demo/
https://github.com/kubeflow/examples/blob/master/tensorflow_cuj/neural_machine_translation
https://github.com/kubeflow/examples/blob/master/tensorflow_cuj/text_classification/
https://github.com/kubeflow/examples/blob/master/code_search/
https://github.com/kubeflow/examples/blob/master/github_issue_summarization
https://github.com/kubeflow/examples/blob/master/demos/simple_pipeline/
https://github.com/kubeflow/examples/blob/master/test/

@andreyvelich @johnugeorge  can you please check or test if these are working or need to be deprecated

**Comment by andreyvelich** [comment]
Thank you for pointing this @js-ts.
As I can see, most of these examples are using `v1alpha1` Katib API from 2018-2019

@js-ts If you are able to find volunteers who want to update and contribute some of these examples under [Katib Upstream](https://github.com/kubeflow/katib/tree/master/examples/v1beta1), I am ok with that.

cc @kubeflow/wg-automl-leads

**Comment by js-ts** [comment]
@tenzen-y it would be great if you can help update them.

**Comment by tenzen-y** [comment]
@js-ts 
I'm focused on improving this repo, so I may not be able to help update them.

**Comment by js-ts** [comment]
@tenzen-y thanks for the reply , The examples would be in upstream in the examples folder

**Comment by tenzen-y** [comment]
@js-ts 
Does it mean `kubeflow/examples` is upstream of `kubeflow/katib/examples/v1beta1`?

**Comment by js-ts** [comment]
these repos 
https://github.com/kubeflow/examples/blob/master/demos/yelp_demo/
https://github.com/kubeflow/examples/blob/master/tensorflow_cuj/neural_machine_translation
https://github.com/kubeflow/examples/blob/master/tensorflow_cuj/text_classification/
https://github.com/kubeflow/examples/blob/master/code_search/
https://github.com/kubeflow/examples/blob/master/github_issue_summarization
https://github.com/kubeflow/examples/blob/master/demos/simple_pipeline/
https://github.com/kubeflow/examples/blob/master/test/

would be in  kubeflow/katib/examples/v1beta1 as submodule I think like https://github.com/githubtraining/example-dependency which has js @ c3c5887 likewise these example folders would be in kubeflow/katib/examples/v1beta1 please correct me if I'm wrong

**Comment by tenzen-y** [comment]
Thank you for the explanation!

**Comment by tenzen-y** [comment]
I think those examples in `kubeflow/examples` are not added in `kubeflow/katib/examples` as submodules.

https://github.com/kubeflow/katib/tree/0.6/examples/v1alpha1

**Comment by js-ts** [comment]
Not currently but when new examples are added or these old examples are updated I would add them then ,thanks for the question

**Comment by tenzen-y** [comment]
I see. Thank you for answering my question! @js-ts
