### ISSUE TITLE
Add `shellcheck` to CI

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1734]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Add [`shellcheck`](https://github.com/koalaman/shellcheck) to verify all shell scripts in this repository.

Ref: https://github.com/kubeflow/katib/pull/1731#discussion_r751174167

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by anencore94** [comment]
Absolutely agree :)
also, I think add yamllint on CI could make yaml files more readable for newbies.
(https://github.com/adrienverge/yamllint)

Furthermore, I'm not sure since I didn't used this actually, but just try examining kube-linter would be nice too.(https://github.com/stackrox/kube-linter)

**Comment by tenzen-y** [comment]
It sounds good to me, thanks! @anencore94

**Comment by tenzen-y** [comment]
I take this issue.
/assign

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by johnugeorge** [comment]
/lgtm

@gaocegege Can you review this as well?

**Comment by tenzen-y** [comment]
Thanks, @johnugeorge!
#1857 resolves this issue.

**Comment by gaocegege** [comment]
Thanks for your contribution!

I reviewed and merged it. Can we close the issue, or is there anything we should do next?

**Comment by tenzen-y** [comment]
> Thanks for your contribution!
> 
> I reviewed and merged it. Can we close the issue, or is there anything we should do next?

Thanks for your review @gaocegege !
I'd like to create another issue to track [this feature](https://github.com/kubeflow/katib/issues/1734#issuecomment-972703530).
