### ISSUE TITLE
Can katib works with hyper-params described in json?

### ISSUE THREAD

**Issue by mf-giwoong-lee** [kubeflow/katib#1735]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
```
{     
     "general_configs": 
     {
          ...
          
     },

     "trainer_configs": 
     {
          "batch_size": 64,
          "epochs": 1000,
          "num_batches_per_epoch": 50
          "num_cells": 40,
          "num_layers": 3
     },

}
```
In Katib examples, hyper-params are accepted by using argument parser!

But in many cases, hyper-params are managed in json or other file types.

Is there any solution for this kind of case?
 
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
@mf-giwoong-lee Thank you for creating this!

Please can you explain your use-case, and when you want to specify HPs in json format ?

What Kubernetes resource you want to use to run your training process, and how the Katib Experiment should look like ?

**Comment by mf-giwoong-lee** [comment]
I was working with NNI(made in microsoft).

NNI defines search spaces in json format and NNI api helps to match HPs in json and HPs in codes.

If I have many HPs and pass HPs in argument parser, then it is difficult to manage.

Because of this reason, I find file format containing HP search spaces and code level api of Katib.

**Comment by andreyvelich** [comment]
@mf-giwoong-lee You can create your training script which accepts JSON as input parameter and define HPs in this JSON.

For example, for ENAS training container we parse Neural Network config from JSON:
1. https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py#L15-L16
2. https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py#L12-L17

**Comment by mf-giwoong-lee** [comment]
Thanks for replying!

I also see [https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/enas-gpu.yaml#L137-L148](url)

So I understand that katib can accept JSON as input parameter but there are no JSON in that example folder..

I want to see actual input parameter JSON!

Above enas-gpu.yaml has nn_config which is consumed as input parameter JSON but actual parameter definition or JSON file path is not appeared in YAML file

**Comment by mf-giwoong-lee** [comment]
```
{
    "dropout_rate":{
        "_type": "uniform",
        "_value": [0.0, 0.3]
    },
    "num_cells":{
        "_type": "choice",
        "_value": [40, 80, 160, 320]
    },
    "num_layers":{
        "_type": "choice",
        "_value": [2, 3, 4, 5]
    },
    "batch_size":{
        "_type": "choice",
        "_value": [4, 16, 64]
    },
    "learning_rate":{
        "_type": "uniform",
        "_value": [0.0002, 0.01]
    },
    "weight_decay":{
        "_type": "uniform",
        "_value": [1e-06, 1e-03]
    }
}
```
This is a example of NNI search space described in JSON. Is it possible for katib to accept this kind of input parameter JSON which has range of parameter and selection type.

**Comment by andreyvelich** [comment]
Thank you for the example @mf-giwoong-lee.
So this is the current API implementation: https://github.com/kubeflow/katib/blob/master/pkg/apis/controller/experiments/v1beta1/experiment_types.go#L186-L190.
Also, you can see the example how we define the parameter search space: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/hp-tuning/sobol.yaml#L18-L35

So for your example, you can write a script to modify your JSON to follow the Experiment API guidelines.
