### ISSUE TITLE
Request to be User Group Contributor for Kubeflow 1.5 for the AutoML Working Group

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1747]
Hello guys, I'm a MLOps Engineer at MakinaRocks in South Korea. (I have CKA and my company have KCSP certification) We've used kubeflow to try and share ML experiments easily.

I've used Kubernetes since 2020 and Kubeflow since 2021 in production level.

My experience with Kubeflow includes:
- Deploy and maintatin kubeflow in private 10 nodes gpu cluster and aws EKS.
- Customize several kubeflow components:
  - make kubeflow/manifests repo as an ansible playbook
  - modify kubeflow/katib to use with istio-sidecar and make user could do HPO with kubeflow pipeline
  - make some wrapper python sdk and CLI of kfp to make users to feel easier.
- Contribute to some repos of kubeflow org including pipelines, katib and some others.
  - you may check my contributions for kubeflow [here](https://github.com/kubeflow/internal-acls/pull/487)

I'd like to see release process of kubeflow, and give any help if I could do.
If you guys are ok, I'd like to collaborate with you guys and other User Group Contributors like #1745

cc @kubeflow/wg-automl-leads

Please let me know if you need more information!

**Comment by andreyvelich** [comment]
Hi @anencore94, thank you for your interest and help with Kubeflow projects!
It would be great to see you as User Group Contributor in Katib project as part of Kubeflow 1.5

If you are available, let's discuss in our [AutoML Community Meeting](https://bit.ly/2PWVCkV) on December 1st the Katib issues that you would like to work on.

cc @gaocegege @johnugeorge

**Comment by anencore94** [comment]
@andreyvelich Thank you for saying so. However, I'm sorry I couldn't make to attend the Metting on December 1st.
I have a schedule on December 2nd, so I will attend the next meeting on December 15th. Is it ok ?

**Comment by andreyvelich** [comment]
Sure, sounds good @anencore94.
In the meantime, you can link issues/proposals here that you want to take.

**Comment by anencore94** [comment]
First of all, I'd like to work on #1207, maybe I could collaborate with #1708
