### ISSUE TITLE
Add unit tests for File Metrics Collector

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#1756]
/kind feature

We should add unit test for our [File Metrics Collector](https://github.com/kubeflow/katib/tree/master/pkg/metricscollector/v1beta1/file-metricscollector) to verify log parsing. 
That will help to avoid issues similar to: https://github.com/kubeflow/katib/issues/1754

/help
/good-first-issue

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by Electronic-Waste** [comment]
I want to have a try! It may help me better understand the metrics collecting logics.

**Comment by Electronic-Waste** [comment]
@tenzen-y thank you!

**Comment by Electronic-Waste** [comment]
@tenzen-y I notice that you left a comment in the unit test file `file-metricscollector_test.go`:
>  TODO (tenzen-y): We should add tests for logs in TEXT format.

Does it mean that the additional test cases are supposed to be TEXT format? If so, can you provide an example of TEXT format log file for me? Thanks!

**Comment by kshitijdshah99** [comment]
@andreyvelich I would love to contribute to this issue just wanted to ask that I have to add unit tests for parseLogsInTextFormat and parseLogsInJsonFormat functions and [modify test cases in this file](https://github.com/kubeflow/katib/blob/master/pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go), am I right??

**Comment by tenzen-y** [comment]
> @andreyvelich I would love to contribute to this issue just wanted to ask that I have to add unit tests for parseLogsInTextFormat and parseLogsInJsonFormat functions and [modify test cases in this file](https://github.com/kubeflow/katib/blob/master/pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go), am I right??

@kshitijdshah99 This is already taken by @Electronic-Waste. I'd be happy to be taken another issue by you.

**Comment by Electronic-Waste** [comment]
@tenzen-y  Current error comparison in `file-metricscollector_test.go` is based on boolean rather than error content itself. To make test cases more detailed and accurate, we need to expose error and compare them. I would like to open another PR to fix this for this is a different feat compared with adding test cases for TEXT format log file.

**Comment by tenzen-y** [comment]
> @tenzen-y Current error comparison in `file-metricscollector_test.go` is based on boolean rather than error content itself. To make test cases more detailed and accurate, we need to expose error and compare them. I would like to open another PR to fix this for this is a different feat compared with adding test cases for TEXT format log file.

SGTM

**Comment by tenzen-y** [comment]
/reopen

We need another followup PR.
