### ISSUE TITLE
Musl upgrade in images

### ISSUE THREAD

**Issue by Jose-Matsuda** [kubeflow/katib#1775]
/kind bug

**What steps did you take and what happened:**
My team has been looking into cleaning up cleaning critical vulnerabilities on our cluster and noticed one triggered by the following images `katib-controller`, `katib-db-manager` and `katib-ui`. Our cluster is running `v1beta1-a96ff59` but upon scanning the more up to date versions (v0.12.0) the issue is still there.

![image](https://user-images.githubusercontent.com/23174198/149399356-722962ab-a74a-471e-a9e1-cf0af022de7a.png)

Below is the output of a `trivy image --severity CRITICAL kubeflowkatib/katib-db-manager:v0.12.0`
![image](https://user-images.githubusercontent.com/23174198/149399432-964f330c-858e-4692-9565-1a7df578e216.png)

**What did you expect to happen:**
For this to be patched throughout the images

**Anything else you would like to add:**
Probably avoid updating to 1.2.1 as on the [musl website](https://musl.libc.org/) they do note of another CVE affecting releases through 1.2.1 (1.2.2 is the most recent)

**Environment:**

- Katib version 0.12.0 (and earlier ones):
- Kubernetes version: (`kubectl version`):
- OS (`uname -a`):

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by tenzen-y** [comment]
Thank you for reporting this! @Jose-Matsuda 
Maybe, all katib-components that use `alpine:3.7` as the base image will be affected by this issue, so we should upgrade `alpine`.

/cc @kubeflow/wg-automl-leads

**Comment by tenzen-y** [comment]
I built a `katib-controller` image with `alpine:3.15` as the base image and scanned it for vulnerabilities and the problem went away.

```shell
$ trivy image --severity CRITICAL ytenzen/katib-controller:bump-alpine
2022-01-14T16:38:59.596+0900    INFO    Need to update DB
2022-01-14T16:38:59.596+0900    INFO    Downloading DB...
25.49 MiB / 25.49 MiB [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 3.46 MiB p/s 8s
2022-01-14T16:39:10.421+0900    INFO    Detected OS: alpine
2022-01-14T16:39:10.421+0900    INFO    Detecting Alpine vulnerabilities...
2022-01-14T16:39:10.422+0900    INFO    Number of language-specific files: 1
2022-01-14T16:39:10.422+0900    INFO    Detecting gobinary vulnerabilities...

ytenzen/katib-controller:bump-alpine (alpine 3.15.0)
====================================================
Total: 0 (CRITICAL: 0)


app/katib-controller (gobinary)
===============================
Total: 0 (CRITICAL: 0)
```

**Comment by andreyvelich** [comment]
Thank you for this @Jose-Matsuda!
Probably, we should integrate vulnerabilities scan to our CI in the near future.
