### ISSUE TITLE
New UI broken in Firefox

### ISSUE THREAD

**Issue by knkski** [kubeflow/katib#1776]
/kind bug

**What steps did you take and what happened:**

Opened up the new UI in Firefox, and got this:

![image](https://user-images.githubusercontent.com/20422884/149406551-8953c81f-0170-42dc-9afd-af4b8e287534.png)

**What did you expect to happen:**

I expected the icons to show up instead of text.

**Anything else you would like to add:**

I was able to edit the DOM and add in this `<link>` element to get the icons working on the main page:

https://stackoverflow.com/a/49796321

However, that still left a broken new experiment page:

![image](https://user-images.githubusercontent.com/20422884/149406864-9f700030-fb2b-4a64-ab76-9bce79e4fc34.png)

Switching over to Chrome made everything work. Other Kubeflow dashboards worked fine in Firefox.

**Environment:**

- Katib version (check the Katib controller image version): docker.io/kubeflowkatib/katib-controller:v0.12.0
- Katib UI version: Both `v0.12.0` and `latest`
- Kubernetes version: (`kubectl version`): MicroK8s 1.21
- OS (`uname -a`): Ubuntu 20.04

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @knkski!
@kimwnasptd Please can you take a look at this issue.

**Comment by kimwnasptd** [comment]
Yes, I have it on my radar. I'll try to report back soon within the week.

**Comment by andreyvelich** [comment]
Sorry for the late reply!
@knkski, do you still see this issue in newer Katib UI versions ?

**Comment by andreyvelich** [comment]
@tenzen-y Should we close this issue until more users complain about problems with running Katib UI in Firefox ?

**Comment by tenzen-y** [comment]
> @tenzen-y Should we close this issue until more users complain about problems with running Katib UI in Firefox ?

I'm ok with either way.

**Comment by andreyvelich** [comment]
Let me close it for now.
Please feel free to re-open it or create a new issue if you experience issues with Firefox and Katib UI.
