### ISSUE TITLE
Add support to configure kubernetes spec for Suggestion deployment and trial sidecar containers

### ISSUE THREAD

**Issue by moorthy156** [kubeflow/katib#1785]
/kind feature

**Describe the solution you'd like**
Add support to configure Suggestion deployment and sidecar parameters like security context through config or CR spec. This will enable suggestion to match kubernetes deployment/container offering.

Though some customization is available like resources, this will enable katib to match kubernetes deployment/pod spec

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
right now, namespaces need root privilege to run katib side car and suggestion deployment. This will enable katib to run without root privilege  and also will open other parameters like nodeselector, etc to take full advantage of kubernetes
---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @moorthy156!
We have the similar request: https://github.com/kubeflow/katib/issues/1737.
Let's track the progress there.

If you want to help us with this feature that would be amazing!
