### ISSUE TITLE
Display more detailed information and logs of experiment on the user interface

### ISSUE THREAD

**Issue by javen218** [kubeflow/katib#1789]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We may often meet a situation that everything seems Ok on the UI，the status of experiment and trials are remaining running， but actually there are something wrong have already happened with the experiment and trials. 

To determine if everything is ok, we have to use commands like `kubectl logs` and `kubectl describe` to check logs and Events of almost every resource associating katib experiment. This is very unfriendly for data scientists, who may want focus on machine learning problems.

**Therefore, I suggest to display more detailed information and logs of experiment on the user interface, make us easy to know if the experiment and trials are actrually runing well from the UI.**
 
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by javen218** [comment]
If there already have any convenient way to get error information of experiments, please tell me. Thanks!

**Comment by kimwnasptd** [comment]
@javen218 this makes total sense, and it's the direction we are also heading towards. We want users to be able to do every `kubectl` action via the UI, which includes exposing logs, events etc. 

We have also started an effort to create distinct pages for each Trial, to expose more such information https://github.com/kubeflow/katib/issues/1763. Next steps we could do in parallel would be exposing events for both `Experiment` and `Trial` objects.

Also for anyone wanting to contribute, we can break this into smaller tasks to help with this effort.

**Comment by javen218** [comment]
Thank you for your reply! That's great. @kimwnasptd 
I'm looking forward to seeing you guys complete these features soon! Thanks!

**Comment by andreyvelich** [comment]
Thank you for creating this @javen218.
Let's track the progress in the corresponding issues.
