### ISSUE TITLE
the error about the modeldb for the latest version

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#179]
The studyjob's name disappear in the frontend,there is only one entry. Different studyjob merged into one entry.

**Comment by YujiOshima** [comment]
@wukong1992 Did you use a different `studyname` for studyjob? not `studyjob/name`
https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml#L9

We defined the study name independently from studyjobname. It enables you to run multi studyjobs for one study simultaneously.

**Comment by wukong1992** [comment]
I just use the example in this project, and didn't change anything: kubectl apply -f random-example.yaml

**Comment by wukong1992** [comment]
@YujiOshima

**Comment by YujiOshima** [comment]
Sorry, I'm not sure about your problem. 
Could you explain more details?

**Comment by wukong1992** [comment]
I didn't know if it's about the latest update, before is okey. 
![_001](https://user-images.githubusercontent.com/13702081/46060040-3bf48000-c194-11e8-997d-721d433ba4a8.png)
there is no studyname, and the yaml file is okey.  when i create another stuydjob, it also merged into this entry.

**Comment by wukong1992** [comment]
@YujiOshima

**Comment by YujiOshima** [comment]
I understood. I can see the same problem in my environment.
 I'm not sure about the reason but I will fix. Thank you for reporting!
