### ISSUE TITLE
GPU is not utilising while running Katib NAS example 

### ISSUE THREAD

**Issue by ashissharma97** [kubeflow/katib#1792]
Hi,
I am running [Katib NAS example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/enas-gpu.yaml) I have noticed that it is running but it is not able to utilise the GPU of the machine. So I went inside the pod and try to call tensorflow from the pod then I am getting the following error:-

```
2022-01-25 11:19:26.568346: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2022-01-25 11:19:26.569961: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
```

Please help with this

Thanks

**Comment by d-gol** [comment]
@ashissharma97 you need to mount the nvidia driver and set appropriate environment variables in the YAML.
You can check a full example here: https://github.com/d-gol/kubeflow-examples/blob/main/katib_job_gpu.yaml

Have a look at the lines:
[131](https://github.com/d-gol/kubeflow-examples/blob/main/katib_job_gpu.yaml#L131) - nvidia-driver volume
[153](https://github.com/d-gol/kubeflow-examples/blob/main/katib_job_gpu.yaml#L153) - nvidia-driver volume mount
[140](https://github.com/d-gol/kubeflow-examples/blob/main/katib_job_gpu.yaml#L140) - ENVs

Another approach is to use admissionwebhook with a PodDefault to automatically add volume, volume mount and envs - https://github.com/kubeflow/kubeflow/blob/master/components/admission-webhook/README.md

**Comment by ashissharma97** [comment]
@d-gol Thanks for the reply.
I added the above values in the YAML file but getting following error

`Error: failed to generate container "72eba45dbb0be7f31d3894c2bded5cbeafaeabd26852017ebc2b09e6634ed754" spec: failed to generate spec: failed to mkdir "/opt/nvidia-driver": mkdir /opt/nvidia-driver: read-only file system`

**Comment by d-gol** [comment]
@ashissharma97  hm, maybe your driver is not installed in `/opt/nvidia-driver`
To debug you could do:

Get k8s nodes:

`kubectl get nodes`

ssh into a GPU node:

`ssh USERNAME@GPU_NODE_NAME`

Make sure the nvidia driver is installed with: `nvidia-smi`
Try to run the training script directly in the node.
Check `PATH` and `LD_LIBRARY_PATH` envs, find where is the driver installed in the node.

Set volume, volume mounts, and envs in the Katib job YAML to correspond to these values.

Resubmit the Katib job, try again what you already did, exec into a Pod, do: `nvidia-smi`
Then check if the training script works.

If it works on the node, and not in the pod, find out what is different between the environments (envs, nvidia-driver path, etc).

Hope this helps.

**Comment by ashissharma97** [comment]
Hi @d-gol,
As per this doc https://cloud.google.com/container-optimized-os/docs/how-to/run-gpus even after mounting getting the same error.

I changed "/opt/nvidia-driver" to "/usr/local/nvidia" and changed env variables respectively.

I have one question why do I need to mount the drivers whereas I am installing all Nvidia drivers inside the container. "nvidia-smi" is running inside the pod but in the GPU-Util column it is showing zero.

Thanks

**Comment by d-gol** [comment]
@ashissharma97, so you are using GCP. In our on-premise cluster, we have drivers installed on the nodes, so we mount them. 

On the link you sent (https://cloud.google.com/container-optimized-os/docs/how-to/run-gpus) there is a note:
`NVIDIA GPU drivers: You must install NVIDIA GPU drivers by yourself on your Container-Optimized OS VM instances. This section explains how to install the drivers on Container-Optimized OS VM instances.`

meaning the drivers should be installed in the VMs (Kubernetes nodes).
It may be possible to install drivers in a container, I just never tested myself, so can't help much.

Maybe the issue is with CUDA/Tensorflow compatibility, or CUDA installation path.
These threads might help if that's the issue:
- nhttps://github.com/tensorflow/tensorflow/issues/46975
- https://github.com/tensorflow/tensorflow/issues/52988

**Comment by ashissharma97** [comment]
No problem @d-gol, BTW thanks for your help I'll surely check the links you have shared.

**Comment by andreyvelich** [comment]
Feel free to re-open issue if issue still persists.
