### ISSUE TITLE
Katib logo

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#180]
I want to create a logo for Katib.
Though Katib is a component of KubeFLow, it can work independently.
So we can have a logo! I heard requests from some users.
WDYT? @gaocegege @jlewi

**Comment by gaocegege** [comment]
SGTM! I also think that we need a logo for katib.

**Comment by YujiOshima** [comment]
![logo_transparent](https://user-images.githubusercontent.com/10014831/46056813-67c03780-c18d-11e8-8272-b5f0ad638faa.png)
This is one of a candidate.
the telescope means finding the best hyperparameter from massive parameters (stars).

**Comment by YujiOshima** [comment]
![katib](https://user-images.githubusercontent.com/10014831/46258347-0b01ab80-c504-11e8-98e1-eeaf91eb734d.png)

I updated the logo. 
* use heptagon like k8s and KubeFlow.
* make more easy to understand the icon is a telescope.

@gaocegege WDYT?  If it is OK, I want to use this for Katib logo!
