### ISSUE TITLE
dose katib support Multi-tenant?

### ISSUE THREAD

**Issue by AnberLu** [kubeflow/katib#182]
if many user use katib,how to manager it?

**Comment by YujiOshima** [comment]
Katib cannot separate users. 
You can set owner for job but all users can touch other users job.
If you need to strict Multi-tenant, please separate namespace and deploy katib for each space.
I think a policy of kubeflow is the same.

**Comment by andreyvelich** [comment]
@AnberLu Currently Katib isolates user's resources by profile namespace, like other training operators.
