### ISSUE TITLE
the suggestion number

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#184]
Now,  katib now only supports request_num and no longer supports suggectionnum, will katib support in the future?

**Comment by YujiOshima** [comment]
@wukong1992 Do suggectionnum mean the max number for suggestions?
We can support max suggestion num or max request count.
These are essentially same since  max request count * request num = max suggestion num.
Which is more suitable for your use-case?

**Comment by mayankjuneja** [comment]
Hi @YujiOshima, I had a similar question on this. By default, will Katib continue to run trials indefinitely, until stopped? Is there a way to specify max iterations/trials? This seems different from the older version (prior to CRD implementation).

**Comment by wukong1992** [comment]
@YujiOshima Both are okey, as long as you can control the number of suggestions.

**Comment by jlewi** [comment]
Is this something that needs to be fixed in 0.4.0? If so lets add the tag area/0.4.0.

**Comment by johnugeorge** [comment]
Closing this issue as #193 is merged
/close
