### ISSUE TITLE
Trial name could not be passed to env  

### ISSUE THREAD

**Issue by alexeygorobets** [kubeflow/katib#1844]
/kind bug

**What steps did you take and what happened:**
I am trying to get access to the trial name from the trial's pod (I need it to build S3 bucket path for trained model).
I follow [this example](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/trial-template/trial-metadata-substitution.yaml#L69). 
But I've got an error 
```
Error from server: error when creating "trial-metadata-substitution.yaml": admission webhook "validator.experiment.katib.kubeflow.org" denied the request: parameter reference ${trialSpec.Name} does not exist in spec.parameters: [{lr double {0.03 0.01 [] }}]
```

This example itself does not work.

**What did you expect to happen:**
Trials running with env TRIAL_NAME resolved as trail's name.

**Anything else you would like to add:**
This example was working on Katib 0.12.0. 
It looks like additional check added in this [PR](https://github.com/kubeflow/katib/pull/1726) might cause this issue. One of the resolution might be to skip this check [here](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validator/validator.go#L313) if it's trial metadata   ([such as name, kind, apiversion etc.](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/consts/const.go#L158)).

But I will be happy with any other solution which allows me to pass trial name to pod as environment variable.

**Environment:**

- Katib version (check the Katib controller image version): 0.13.0
- Kubernetes version: 1.22
- OS : CentOS

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by wenxinax** [comment]
same problem...

**Comment by johnugeorge** [comment]
This needs to be fixed.

**Comment by johnugeorge** [comment]
Validation added in https://github.com/kubeflow/katib/pull/1726 needs to be extended to reserved keywords as well

**Comment by henrysecond1** [comment]
I'm sorry that I didn't consider the parameter substitution case.

As @alexeygorobets said, I think we can skip parameter reference checking when it's a trial metadata. Please let me know if there's anything I can help with.
