### ISSUE TITLE
Upgrading Optuna from v2.x.x to v3.0.0

### ISSUE THREAD

**Issue by himkt** [kubeflow/katib#1851]
/kind feature

(Sorry but it is not a feature request)

Related: optuna/optuna#2941

Thank you for integrating Optuna for the hyperparameter optimization feature. We, Optuna dev-team, are working on the next major version of the library Optuna v3. In Optuna v3, we will deprecate distributions used in:

https://github.com/kubeflow/katib/blob/7f1afbdaa93591baefdc6ef29afe5a5f2ce5e95b/pkg/suggestion/v1beta1/optuna/service.py#L148-L157

We will introduce `FloatDistribution` and `IntDistribution`. So distributions in OptunaService will have to be updated:

- `UniformDistribution(low, high)` => `FloatDistribution(low, high)`
- `IntUniformDistribution(low, high)` => `IntDistribution(low, high)`

Now katib installs the latest Optuna. Users will see the deprecation warnings in the Optuna v3 release. I will open a PR that restricts the constraint to avoid such warnings. Note that it doesn't mean Optuna v3 is imcompatible with Optuna v2. It only shows warnings and deprecated distributions are internally converted to appropriate distributions.

**Describe the solution you'd like**
- Add version constraint of Optuna to avoid showing deprecation messages to users
- Track the status of the release of the development of Optuna v3.0.0

I create this issue to track the status of Optuna.
After Optuna v3 is available, we want to upgrade the library. 
We will back here when the release is available.

**Anything else you would like to add:**
If you have some concerns or questions, please feel free to contact Optuna dev-team.
🔗 https://github.com/optuna/optuna/issues/2941

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by johnugeorge** [comment]
Thanks @himkt for reporting this
