### ISSUE TITLE
How to customize/specify Katib namespace in UI

### ISSUE THREAD

**Issue by zoefyz12** [kubeflow/katib#1855]
In katib UI, I want to specify a namespace and don't allow user choose namespace. I can easily remove the namespace selection bar but hard to create a namespace object. I find **namespace** is defined from kubeflow library, if I want to define and create a **namespace** object, how to do it? And if I done create a namespace object, is it possible to use it communicate with backend?

Example:
```
import {
  ConfirmDialogService,
  DIALOG_RESP,
  ExponentialBackoff,
  NamespaceService,
  TemplateValue,
  ActionEvent,
  DashboardState,
} from 'kubeflow';


```

**Comment by johnugeorge** [comment]
Are you using default multi tenant kubeflow installation?

related: https://github.com/kubeflow/kubeflow/issues/5566
