### ISSUE TITLE
[Feature] Add Helm supports

### ISSUE THREAD

**Issue by haoxins** [kubeflow/katib#1856]
/kind feature

Can we add Helm supports just like what KServe did?

See https://github.com/kserve/kserve/pull/1878

- It will help the users to customize the installation more easier. Such as
  1. The live/ready probes
  2. The MySQL version
  3. Others

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by gaocegege** [comment]
/cc @kubeflow/wg-automl-leads 

I remember that we maintained a helm chart before. Then we removed it after we migrated to ksonnet in the kubeflow community

**Comment by johnugeorge** [comment]
In kubeflow release, plain manifests are used for installation. https://github.com/kubeflow/manifests   In each KF release, katib manifests are synced upstream automatically. 

The concern  in having  helm charts  is the overhead in maintaining them in extra to plain manifests

**Comment by zw0610** [comment]
Are you referring the correct issue from training-operator?

**Comment by haoxins** [comment]
> In kubeflow release, plain manifests are used for installation. https://github.com/kubeflow/manifests In each KF release, katib manifests are synced upstream automatically.
> 
> The concern in having helm charts is the overhead in maintaining them in extra to plain manifests

I deployed the Kubeflow by Argo CD and have a fork version of https://github.com/argoflow/argoflow-gcp inside my company.
I agree that it's overhead if we maintain both the Helm charts and plain manifests so that I open this issue after the KServe community has supported Helm.

I think the Helm is adopted by more and more cloud native components and it will made the kubeflow-manifests project more maintainable.
