### ISSUE TITLE
Migrate kubeflow-katib-presubmit to GitHub Actions

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1878]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As described in https://github.com/kubeflow/katib/pull/1877#issuecomment-1140715656, we need to migrate our `kubeflow-katib-presubmit` test to Github Actions from kubeflow test-infra since it has been removed from the prow.

/cc @kubeflow/wg-automl-leads 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by johnugeorge** [comment]
Related: https://github.com/kserve/kserve/pull/2206
