### ISSUE TITLE
Remove unused `pkg/suggestion/v1beta1/bayesianoptimization`

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1904]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
There are Python codes for the bayesian optimization suggestion service in [`pkg/suggestion/v1beta1/bayesianoptimization`](https://github.com/kubeflow/katib/tree/master/pkg/suggestion/v1beta1/bayesianoptimization), but since their codes are unused anywhere, not tested, and no exist Docker images, we are not sure if compatible with current Katib.

So, it would be better to remove `pkg/suggestion/v1beta1/bayesianoptimization`.

What do you think about this? @kubeflow/wg-automl-leads

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by andreyvelich** [comment]
Yes, let's remove this, since this code is not longer maintained and use Scikit optimize for BO.
