### ISSUE TITLE
Release v0.14.0 tracking 

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#1908]
This PR is tracking new release v0.14.0 and related pending  issues

Related: https://github.com/kubeflow/manifests/issues/2195

**Comment by johnugeorge** [comment]
Pending issues for RC0 cut

1.  https://github.com/kubeflow/training-operator/issues/1622
2. https://github.com/kubeflow/katib/pull/1783

**Comment by johnugeorge** [comment]
3. https://github.com/kubeflow/katib/pull/1828

**Comment by johnugeorge** [comment]
4. https://github.com/kubeflow/katib/pull/1909

**Comment by johnugeorge** [comment]
3 is not considered for this release

Ref: https://github.com/kubeflow/manifests/issues/2207#issuecomment-1169854274

**Comment by johnugeorge** [comment]
Katib v0.14.0 RC0 is created from release-0.14 branch
https://github.com/kubeflow/katib/releases/tag/v0.14.0-rc.0

Katib SDK v0.14.0 RC0 is out
https://pypi.org/project/kubeflow-katib/0.14.0rc0/

**Comment by tenzen-y** [comment]
@andreyvelich @johnugeorge @gaocegege @anencore94 
Maybe, I think that we need to remove the `request_number` gRPC API in our v0.14 release.

ref: https://github.com/kubeflow/katib/pull/1728#issuecomment-959328401 

WDYT?

**Comment by gaocegege** [comment]
@tenzen-y 

LGTM, I think it is a huge tech debt.

**Comment by anencore94** [comment]
@tenzen-y SGTM :) it's time to remove it

**Comment by johnugeorge** [comment]
Shall we takeout up in the next release ?

**Comment by tenzen-y** [comment]
> Shall we take it up in the next release since we already cut RC

@johnugeorge I see.
It might be better to postpone removing the deprecated gRPC API since removing it is a breaking change.

**Comment by johnugeorge** [comment]
Final release update

Katib v0.14.0 is created from release-0.14 branch
https://github.com/kubeflow/katib/releases/tag/v0.14.0

Katib SDK v0.14.0 is out
https://pypi.org/project/kubeflow-katib/0.14.0/

**Comment by tenzen-y** [comment]
@johnugeorge Probably, we can close this.
