### ISSUE TITLE
list_trials function do not respect experiment name filter

### ISSUE THREAD

**Issue by ekesken** [kubeflow/katib#1919]
/kind bug

**What steps did you take and what happened:**

`KatibClient.list_trials` function is broken, it no more respects to the experiment name parameter, it returns all the existing trials for all the experiments.  As you'll see `name` parameter is only used in the Exception message now.

**What did you expect to happen:**

I expect it to return the filtered trails of the experiment whose name is passed as a parameter.

**Anything else you would like to add:**
It's broken in this [PR](https://github.com/kubeflow/katib/pull/1630/files#diff-bc6841536c6ef19d4354a2de49e5f29e9863be2d42a70b774c048eb6371bb14cL343-R347).

**Environment:**

- Katib version (check the Katib controller image version): v0.13.0
- Kubernetes version: (`kubectl version`): v1.20.15
- OS (`uname -a`): `Linux ... 5.4.188-104.359.amzn2.x86_64 #1 SMP Thu Apr 14 20:53:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by johnugeorge** [comment]
Thanks for reporting this.

/cc @anencore94

**Comment by anencore94** [comment]
Thanks for checking :+1:  I'll check and fix this soon. @ekesken @johnugeorge
