### ISSUE TITLE
Metrics can go out of view when visualizing experiment metrics

### ISSUE THREAD

**Issue by AlexandreBrown** [kubeflow/katib#1923]
/kind bug

**What steps did you take and what happened:**
It appears that metrics can go outside the viewport when visualizing katib metrics.  
![image](https://user-images.githubusercontent.com/26939775/183264414-7888fd40-f966-4c62-8997-a67cb2baf34f.png)

**What did you expect to happen:**
I expected the metrics to be bounded by the viewport so that they are always visible (we should always be able to see y = 0) or to have the ability to zoom in or scroll.

**Environment:**

- Katib version (check the Katib controller image version): katib-controller:v0.12.0, katib sdk `0.13.0`
- Kubernetes version: (`kubectl version`): 1.21
- OS (`uname -a`): Ubuntu
- Kubeflow: 1.4.1
- Cloud provider: AWS
- Screen resolution : 1920x1080 100% (not zoomed in)

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by johnugeorge** [comment]
@elenzio9 Is this issue still there after the recent fixes?

**Comment by johnugeorge** [comment]
Thanks @elenzio9 for the update.
