### ISSUE TITLE
How to use LightGBM with Katib?

### ISSUE THREAD

**Issue by r-matsuzaka** [kubeflow/katib#1927]
/kind feature

**Describe the solution you'd like**
I want to use LightGBM with `Katib` and found [this yaml file](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-training-operator/xgboostjob-lightgbm.yaml) and [merged PR](https://github.com/kubeflow/katib/pull/1603).  
Can you tell me how  to run LightGBM jobs with this yaml?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by johnugeorge** [comment]
You need to install kubeflow training operator which supports XGBoostJob

**Comment by r-matsuzaka** [comment]
Thank you very much.
So you mean XGBoostJob supports LightGBM, right?

**Comment by johnugeorge** [comment]
Please see https://github.com/kubeflow/training-operator/tree/master/examples/xgboost/lightgbm-dist

**Comment by r-matsuzaka** [comment]
I read but it runs xgboostjob not lightgbmjob.

**Comment by johnugeorge** [comment]
I didn't get your question. This example shows how to run distributed lightbm(of [example](https://github.com/microsoft/LightGBM/tree/master/examples/parallel_learning))  with XGboost operator.

If you are not using distributed version, you can just use Kubernetes `Job ` to run your container as in https://github.com/kubeflow/katib/blob/master/examples/v1beta1/hp-tuning/random.yaml#L51

**Comment by r-matsuzaka** [comment]
Thank you very much, I understood.
Excuse me, I misunderstood.
I will check the Docker image and python  file.
