### ISSUE TITLE
Try to add a cmd line arg on 'connectTimeout ' to satisfy low performance storage.

### ISSUE THREAD

**Issue by techwolf139** [kubeflow/katib#1928]
/kind feature

When using some old storage, katib-mysql may init fail.
when init kubeflow on some TCP net disk or glusterfs(with TCP).

the mysql.go init connectTimeout  is set to 60 sec.

May add a arg on this timeout setting.

So user can set a longer time on init katib-mysql.

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by techwolf139** [comment]
In my case , i think the
katib-db-manager

will auto exit with in 60 sec, what erver the pod setting.

**Comment by tenzen-y** [comment]
Thanks for requesting new feature!
I would like to implement this after #1921 is merged.

**Comment by johnugeorge** [comment]
Thanks @tenzen-y

**Comment by techwolf139** [comment]
cheers
Is there some other hard coded timeout setting?
