### ISSUE TITLE
Implement Readiness/LivenessProbe endpoint for katib-controller

### ISSUE THREAD

**Issue by anencore94** [kubeflow/katib#1930]
/kind feature

**Describe the solution you'd like**
Even though katib-controller pod's status became ready. It does not mean that katib-controller is available for all feature.

For example, if user request `/validate-experiment` API to katib-controller, right after katib-controller was just created, It returns 200 response without actually processing the real logic.

First, we need to define how to determine if katib-controller is ready or live. and then implement it.

In usual cases, readiness endpoint checks whether app could process all requests (usually try connecting to the database).
Also, liveness endpoint checks just the container is alive or not.

**Anything else you would like to add:**

Raised from https://github.com/kubeflow/katib/pull/1921#discussion_r944579336

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by anencore94** [comment]
I'd like to take this issue.

**Comment by tenzen-y** [comment]
SGTM.
Thanks @anencore94!
