### ISSUE TITLE
Drop Kubernetes v1.21 and introduce Kubernetes v1.24

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#1945]
/kind discussion 

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
It seems that Kubernetes v1.21 reached EOL upstream on 2022-06-28 [in this documentation](https://kubernetes.io/releases/).
So, it would be nice to stop supporting v1.21 and start supporting v1.24 since the next katib release. (katib v0.15.0 ?)

What do you think? @kubeflow/wg-automl-leads @anencore94 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by johnugeorge** [comment]
Yes. We should provide a list of supported k8s versions against each Katib release. This should be same as matrix list used in CI

**Comment by tenzen-y** [comment]
> Yes. We should provide a list of supported k8s versions against each Katib release. This should be same as matrix list used in CI

SGTM
