### ISSUE TITLE
Should MutatingWebhook failurePolicy be `Ignore`?

### ISSUE THREAD

**Issue by ca-scribner** [kubeflow/katib#1946]
/kind feature

**Describe the solution you'd like**
Not sure if this is a bug or a feature request, but the MutatingWebhook `failurePolicy`s are set to `Ignore`, which means it is easy to not notice if your webhook calls are failing.  This was noticed when debugging #1795.  

Is this the best configuration?  Are there cases where having the Experiment and Pod mutations fail can still lead to viable setups?  If there are not, maybe `failurePolicy: Fail` would be better so configuration errors are easier to find.  

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
Thanks for reminding me! @johnugeorge 
I agree with @ca-scribner.

**Comment by anencore94** [comment]
I agree with you too. It would be better for safe use.
