### ISSUE TITLE
Katib experiment detail page 500 error after refresh

### ISSUE THREAD

**Issue by shaowei-su** [kubeflow/katib#1967]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Katib experiment detail page can be accessed after a given namespace (non default one) is chosen, however, upon page refresh or direct access page URL e.g `https://service-name/katib/experiment/exp-name`, UI will throw out 500 error.
<img width="783" alt="Screen Shot 2022-09-29 at 20 02 01" src="https://user-images.githubusercontent.com/7682657/193181398-047075ac-f4d9-4305-8156-cea8bfd8185c.png">

By checking the requested URL, it seems that the actual API request sent is `https://service-name/katib/fetch_hp_job_info/?experimentName=exp-name&namespace=kubeflow-user` where the namespace is default to `namespace=kubeflow-user`.

**What did you expect to happen:**

The experiment detail page should able to refresh and directly accessible. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version): v0.13.0
- Kubernetes version: (`kubectl version`): N/A
- OS (`uname -a`): N/A

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by tenzen-y** [comment]
@shaowei-su Thanks for reporting this!
Did you get the same error with katib v0.14.0?

**Comment by shaowei-su** [comment]
Hi @tenzen-y yeah I just tried `v0.14.0` UI component and it failed with the same error. Are you able to reproduce this on your side?

**Comment by tenzen-y** [comment]
@shaowei-su Sorry for the late response.
In my local kind cluster, I faced that issue.

<img width="1909" alt="2022-11-03 4 52 36" src="https://user-images.githubusercontent.com/68272500/199589534-8944f43a-7402-497c-bd81-a49a44a84f11.png">

**Comment by tenzen-y** [comment]
@kimwnasptd Can you help with fixing this bug?

**Comment by johnugeorge** [comment]
/cc @elenzio9 

Can you please take a look at this? This seems to be a blocker for new UI 

Ref: https://github.com/kubeflow/katib/pull/1982#issuecomment-1300813767

**Comment by kimwnasptd** [comment]
Thanks for the ping! 

Yes we'll take a look at this one within the next week.

**Comment by johnugeorge** [comment]
Thanks @kimwnasptd 

Related: https://github.com/kubeflow/katib/pull/1983

**Comment by elenzio9** [comment]
The problem was that the link itself didn't have information about the selected namespace. To solve this, we added the namespace variable as an extra query parameter to the route: `{ path: 'experiment/:namespace/:experimentName',component: ExperimentDetailsComponent }`. So each time the detail page is initialized both the namespace and the name variables will be set using the information from the currently activated route.

**Comment by kimwnasptd** [comment]
Small clarification, the above problem only happened in the standalone mode of the UI.

In the app with Kubeflow we don't see this problem, since the CentralDashboard is always propagating the selected namespace in the underlying app.

**Comment by johnugeorge** [comment]
Fixed by https://github.com/kubeflow/katib/pull/2001 

Closing this PR
