### ISSUE TITLE
Question about storage

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#197]
At present, Katib stores data in k8s (instance), and also stores data in a local database. The content of both is basically repeated. Has Katib considered storing all the data in k8s except the metrics log, I don't know if it works?

**Comment by wukong1992** [comment]
@YujiOshima

**Comment by YujiOshima** [comment]
The data stored CR is not persistent. It is a status of an ephemeral job.
We should store data of Trial, Worker after even the Job is completed and deleted.

**Comment by gaocegege** [comment]
@wukong1992 Same idea with you. PTAL #464
