### ISSUE TITLE
Katib-DB-Manager is not automatically creating katib database in external mysql DB

### ISSUE THREAD

**Issue by moorthy156** [kubeflow/katib#1971]
/kind bug

**What steps did you take and what happened:**
When we point Katib-DB-manager to AWS RDS MySql Database, it is not automatically creating katib database automatically like pipeline/metadata pods

**What did you expect to happen:**
katib-db-manager to automatically create database in RDS mysql (external-db)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version): 0.14.0
- Kubernetes version: (`kubectl version`): 1.22
- OS (`uname -a`): 

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/mysql/mysql.yaml#L37  For mysql docker image, MYSQL_DATABASE var value will be automatically created during image startup. See https://hub.docker.com/_/mysql/ 


For AWS-RDS, I am not sure if there is a way to create DB by default. Else, you have to create it by yourself.
