### ISSUE TITLE
yaml to python sdk submission example needed

### ISSUE THREAD

**Issue by dandawg** [kubeflow/katib#2006]
/kind feature

**Describe the solution you'd like**
There is a need for an example that submits an Experiment YAML via the Katib SDK. I have written an example, and I plan to submit it as a PR.

My reasoning is this:

The Katib SDK exposes the power of Python programming to Katib users; however, the code structure is significantly more complex than in the case of direct YAML submission using kubectl.

In contrast, direct Katib Experiment submission via YAML offers an easy-to-read (and to maintain) structure, but it is very basic, and it lacks advantages that the SDK route provides.

There is a way to submit a YAML file by converting it to a Python dictionary and then passing it to the Katib SDK, so an example is in order.

**Anything else you would like to add:**
In the long run, it would be nice to have this functionality in the SDK (that is, load a YAML file, then update chosen parameters, all in an object that can be passed to create_experiment). For now, this example can help users engage easier with the SDK, especially in the case where they already have experiments defined in YAML, but want to submit via the SDK.

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by dandawg** [comment]
I just submitted PR https://github.com/kubeflow/katib/pull/2008 to address this issue.

**Comment by johnugeorge** [comment]
@dandawg Does this https://github.com/kubeflow/katib/blob/master/examples/v1beta1/sdk/tune-train-from-func.ipynb help you? It takes python function as the argument
