### ISSUE TITLE
Dedicated yaml tab for Trials

### ISSUE THREAD

**Issue by elenzio9** [kubeflow/katib#2011]
/kind feature

**Describe the solution you'd like**
 Our goal is to create a new yaml tab that will show the full YAML as it comes from the backend using the new Editor component introduced in https://github.com/kubeflow/kubeflow/pull/6733.

Related issue: https://github.com/kubeflow/katib/issues/1763

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by andreyvelich** [comment]
This had been implemented. Thank you for the contribution!
