### ISSUE TITLE
KatibClient can not use on application which out the k8s cluster

### ISSUE THREAD

**Issue by zhangxueren9** [kubeflow/katib#2046]
I want to use katib client in my ec2 which is out from the k8s cluster 
my code 
=====================
import kubeflow.katib as katib
katib_cli  = katib.KatibClient()

print(katib_cli.list_experiments())
=======================
the code run good in cluster  

but in my ec2 
thow this error 

so how do I use katibClient in my ec2?

RuntimeError: There was a problem to get experiments in namespace default. Exception:           HTTPSConnectionPool(host='xxxx', port=443): Max retries exceeded with url: /apis/kubeflow.org/v1beta1/namespaces/default/experiments (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1131)')))

**Comment by andreyvelich** [comment]
Sorry for the late reply @zhangxueren9.

You can use [`client_configuration` in `KatibClient`](https://github.com/kubeflow/katib/blob/923d0fcca8f38cbabfbf94376dd927076fce1dfe/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py#L43) to access your Kubernetes cluster.
For example:
1. Obtain SA Token which has required RBAC in your Kubernetes Cluster
2. Create KatibClient as follows:
```
from kubernetes import client
from kubeflow.katib import KatibClient

TOKEN = "<ADD TOKEN HERE>"

configuration = client.Configuration()

# API Server URL
configuration.host = "<EKS_API_SERVER_URL>"

# Service Account Token
configuration.api_key["authorization"] = TOKEN
configuration.api_key_prefix["authorization"] = "Bearer"

# List of Experiments.
katib_client = KatibClient(client_configuration=configuration)
print(katib_client.list_experiments(namespace="<USER_NAMESPACE>"))
```

3. Check this example: https://github.com/kubernetes-client/python/blob/67f9c7a97081b4526470cad53576bc3b71fa6fcc/examples/remote_cluster.py#L31
