### ISSUE TITLE
stop trials when experiment completed

### ISSUE THREAD

**Issue by zhixian82** [kubeflow/katib#2061]
/kind bug

**What steps did you take and what happened:**
create an experiment with: 
```
MaxTrialCount: 12
MaxFailedTrialCount: 3
```
when 3 trials failed, the experiment status was set to failed, bug some trials still in running status

**What did you expect to happen:**

when experiment completed(successed/failed), stop running trials

- Katib version (check the Katib controller image version): v0.14.0

**Comment by johnugeorge** [comment]
To be more clear, running trials are the ones which got started before experiment is in completed state?

**Comment by zhixian82** [comment]
> To be more clear, running trials are the ones which got started before experiment is in completed state?

yes
