### ISSUE TITLE
Add Label to Disable Katib Webhooks

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#2069]
In this PR: https://github.com/kubeflow/katib/pull/2018#issuecomment-1330713221, I proposed to introduce label for disabling Katib Webhooks (validator, defaulter, mutator). For example: `katib.kubeflow.org/webhooks: disabled`.
Let's discuss if that would be useful for the users with large-scale environment.

Currently, if user's namespace has `katib.kubeflow.org/metrics-collector-injection: enabled` label, Katib Mutation Webhook runs for every Pod in that namespace. That might increase latency in the Kubernetes API server. Some users might want to use Katib Experiments and run other pods in their namespaces without Webhook execution.

What do you think @gaocegege @johnugeorge @tenzen-y @anencore94 @terrytangyuan ?

/kind discussion

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
@andreyvelich Does that mean if that experiment with that labels deployed, all webhooks (validator, defaultor, mutator) are ignored?
Or ignored only the mutator?

**Comment by johnugeorge** [comment]
Effectively, this will create problems with Katib. I would not suggest this unless a non Katib user complains about the performance?

**Comment by andreyvelich** [comment]
> Does that mean if experiments with that label deployed, all webhooks (validator, defaultor, mutator) are ignored?

@tenzen-y Yes, we can give user an option to disable all 3 webhooks by setting label in Katib Experiment (disable validator and defaulter) and in user's pods (mutator).

>  I would not suggest this unless a non Katib user complains about the performance?

Let's hold this issue for some time and ask users to provide feedback.

**Comment by andreyvelich** [comment]
We can close this issue this @tenzen-y integrated cert-generator to Katib Controller startup 🎉 
If we need to deactivate webhook for namespace Pod Mutation, we will create separate issues.

**Comment by tenzen-y** [comment]
/reopen 

I found this issue still remains, and the replicaset-controller occasionally faces this issue:

```shell
Warning  FailedCreate  39s (x15 over 2m2s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "mutator.pod.katib.kubeflow.org": failed to call webhook: Post "[https://katib-controller.kubeflow.svc:443/mutate-pod?timeout=10s](https://katib-controller.kubeflow.svc/mutate-pod?timeout=10s)": dial tcp 10.100.157.27:443: connect: connection refused
```

The above error will happen if the katib starts up in the following steps:

1. webhooks are registered to kube-apiserver.
2. the deployment-controller creates the ReplicaSet.
3. the replicaset-controller tries to create pods.

I think we can select one of the following option:

1. Revert the following PRs. This means the katib will start up, as well as v0.15.0.
  - #2196 
  - #2018 
  - #2185
3. Introduce label `katib.kubeflow.org/metrics-collector-injection: disabled` as @andreyvelich proposed in https://github.com/kubeflow/katib/pull/2018#issuecomment-1329353739.
Draft PR: #2203
5. Replace failurePolicy with `Ignore` in the MutatingWebhookConfiguration `mutator.pod.katib.kubeflow.org`.

@andreyvelich @johnugeorge WDYT?

**Comment by tenzen-y** [comment]
I think `2` would be better because consolidating the cert-generator gives users the following advantages:

1. Allow users to deploy easily.
2. Allow users easily debug, and then it is possible to avoid the following confusion:
#1946 
#1795

**Comment by andreyvelich** [comment]
@tenzen-y Did you see the errors even without Leader Election mode enabled ?
What if you just create WebhookConfiguration without `caBundle` and start Katib DB Manager.
Will the Katib DB Manager deployment fail ?

**Comment by tenzen-y** [comment]
> @tenzen-y Did you see the errors even without Leader Election mode enabled ? What if you just create WebhookConfiguration without `caBundle` and start Katib DB Manager. Will the Katib DB Manager deployment fail ?

@andreyvelich Yes, I see it on the installation without leader election mode. You can check the error in the following:

With `caBundle`: https://github.com/kubeflow/katib/actions/runs/5848826299/job/15856504332
Without `caBundle`: https://github.com/kubeflow/katib/actions/runs/5848990494/job/15856837725
