### ISSUE TITLE
The `operators` directory is a bit out of date

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2072]
/kind discussion

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
The [`operators`](https://github.com/kubeflow/katib/tree/master/operators) directory corresponds to katib v0.12.0, which is a bit out of date.

Also, it looks like the latest Charmed katib-operator exists at https://github.com/canonical/katib-operators. Those Charmed katib-operators don't seem to sync. This situation is likely to be confusing for users.

@DomFleischmann @DnPlas @ca-scribner @knkski Would you like to keep maintaining both `kubeflow/katib/operators` and `canonical/katib-operators`? Or would you like to remove Charmed katib-operator from this repository (katib repo)?

/cc @kubeflow/wg-automl-leads

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
ping @DomFleischmann @DnPlas @ca-scribner @knkski

**Comment by ca-scribner** [comment]
Thanks @tenzen-y, I'll raise this in the team

**Comment by tenzen-y** [comment]
> Thanks @tenzen-y, I'll raise this in the team

Thanks!
