### ISSUE TITLE
Docker Free Teams Organizations will be sunset

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2127]
Currently, WG AutoML is using dockerhub to publish our container images, and we have a dockerhub Org.

- https://hub.docker.com/u/kubeflowkatib

However, according to [this](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/), Docker will stop providing Free Team Organization on April 13, 2023, and It seems that we will be unavailable to push new images and tags, although we will be able to pull existing Images.

ref: https://github.com/docker/hub-feedback/issues/2314

So we must apply for Docker-Sponsored Open Source (DSOS) program or migrate the image registry to another one.

cc: @kubeflow/wg-automl-leads @anencore94 

related: https://github.com/kubeflow/training-operator/issues/1781

/kind discussion

**Comment by andreyvelich** [comment]
Thank you for letting us know about this @tenzen-y!

We should discuss it since we use docker hub for almost all Kubeflow components (Notebooks, Central Dashboard, Training, Katib).

What other Working Groups think about it ? Should we try to apply for DSOS as Kubeflow community if that is possible ?

cc @kubeflow/wg-training-leads @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads

**Comment by johnugeorge** [comment]
Note: The deadline is  April 13, 2023 and  we need to get it approved within a month if we are planning to use DSOS route.

/cc @jbottum

**Comment by tenzen-y** [comment]
It seems that Docker doesn't lock our registry while the DSOS application is under review, as described in Docker's blog:

> For new users interested in joining DSOS from a previous Free Team organization, we will defer any organization suspension or deletion while the DSOS application is under review. This will give organizations at least 30 days before we suspend them if the application is ultimately rejected. We are listening to feedback and may offer additional programs or plans based on [your input](https://github.com/docker/hub-feedback/issues/).

**Comment by terrytangyuan** [comment]
We should consider alternatives like quay.io. Many other projects have migrated to that.

**Comment by jbottum** [comment]
Thanks for alerting the Community to this requirement.    I will put it on the Community meeting agenda.    IMO, it would be good to consolidate to a registry that provides valuable services i.e. CVE scanning, no limits, ? and low/no cost (but that might be wishful thinking).

**Comment by jbottum** [comment]
@kubeflow/wg-notebooks-leads @kubeflow/wg-manifests-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-automl-leads  I want to make the Kubeflow Working Group leads aware of this requirement to make a decision on this registry issue.   Our timeline to make a decision, identify our lead, fill out the form, and drive new process is time bound, which means we need to complete this by April 13.     We need an actionable first step i.e. At a minimum, should we consolidate the separate Docker registries that the different Kubeflow working groups are using into one docker registry for the whole community ? +1 ? -1?

**Comment by terrytangyuan** [comment]
Docker has changed its plan https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

**Comment by tenzen-y** [comment]
> https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

Thank you for letting me know! We may be able to stop migrating the registry.

**Comment by andreyvelich** [comment]
We can close this issue, since we can continue to use Docker Free Team for now.
