### ISSUE TITLE
After updating to version 0.15.0, the name argument in KatibClient().get_success_trial_details() has disappeared.

### ISSUE THREAD

**Issue by moey920** [kubeflow/katib#2132]
/kind bug

**What steps did you take and what happened:**
The code below, which worked well in version 0.14.0, fails because of the name parameter in version 0.15.0.
```
trial_details_log = kclient.get_success_trial_details(
     name=experiment, namespace=namespace
)
```

**What did you expect to happen:**
I wonder if this was done intentionally in version 0.15.0 or if a bug fix is needed. Is it something that will be changed in the future update version?

- Katib version (check the Katib controller image version): 0.15.0
- Kubernetes version: (`kubectl version`): v1.21.11
- OS (`uname -a`): `Linux control-plane.minikube.internal 5.4.0-144-generic #161~18.04.1-Ubuntu SMP Fri Feb 10 15:55:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by anencore94** [comment]
I'm sorry about the confuse, but the name of the parameter was changed on v0.15.0. and this feature is uncompatible with the previous version.
You need to change your source code to compatible with the new sdk version if you need to update the sdk.

### v0.14

    def get_success_trial_details(
        self, name=None, namespace=utils.get_default_target_namespace()
    ):
        """Get the Trial details that have succeeded for an Experiment.

        :param name: Experiment name.
        :param namespace: Experiment namespace.
        If the namespace is None, it takes namespace from the Experiment or "default".

        :return: Trial names with the hyperparameters and metrics.
        :type: list[dict]
        """


### v0.15.0
    def get_success_trial_details(
        self,
        experiment_name: str = None,
        namespace: str = utils.get_default_target_namespace(),
        timeout: int = constants.DEFAULT_TIMEOUT,
    ):
        """Get the Succeeded Trial details. If Experiment name is set,
        it returns Succeeded Trials details belong to the Experiment.

        Args:
            experiment_name: Optional name for the Experiment.
            namespace: Namespace to list the Trials.
            timeout: Optional, Kubernetes API server timeout in seconds
                to execute the request.

        Returns:
            list[dict]: Trial names with hyperparameters and metrics.
            It returns empty list if Succeeded Trials cannot be found.

        Raises:
            TimeoutError: Timeout to list Katib Trials.
            RuntimeError: Failed to list Katib Trials.
        """

**Comment by moey920** [comment]
Thank you for your answer. Hope you have a nice day :)
