### ISSUE TITLE
Consolidate katib-cert-generator to katib-controller

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2149]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I would like to consolidate the katib-cert-generator to the katib-controller.

Currently, if we use the standalone cert-generator to generate self-signed certs for the webhooks, we can not use `Fail` as a failurePolicy for the `mutator.pod.katib.kubeflow.org` since we face the deadlock when we create the cert-generator pod via batch/job.

By generating the self-signed certs in katib-controller, we can avoid the above dead lock.

Ref: #2018

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
We need to migrate the below args in the cert-generator to the katib-config or the args of the katib-controller.

https://github.com/kubeflow/katib/blob/fcea7a36cb48f9f799de94de4da13f514d9c569d/pkg/cert-generator/v1beta1/generate/generate.go#L64-L66

I hesitate to add these args to the args of the controller since these args don't directly relate to operations for the controller. So I'd prefer to add these options to katib-config.

@andreyvelich @johnugeorge @gaocegege  WDYT?

**Comment by andreyvelich** [comment]
Thank you for starting this @tenzen-y.

Let's continue the discussion how we want to implement it after this discussion: https://github.com/kubeflow/katib/issues/2150

**Comment by tenzen-y** [comment]
> Thank you for starting this @tenzen-y.
> 
> Let's continue the discussion how we want to implement it after this discussion: #2150

Sure!
