### ISSUE TITLE
[Release] Katib 0.16 Release

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#2156]
This is the tracking issue for Katib 0.16 release.
The feature freeze date for the next Kubeflow 1.8 release is **August 2nd.**

We are targeting the following features for Katib 0.16.

### Katib Backend

- [x] Support `v1.25-v1.27` Kubernetes version - [#2155](https://github.com/kubeflow/katib/issues/2155)
- [x] https://github.com/kubeflow/katib/issues/2150
- [x] https://github.com/kubeflow/katib/issues/2149

### Katib UI

-  [x] https://github.com/kubeflow/katib/pull/2179

### Misc

- [x] https://github.com/kubeflow/katib/pull/2178
- [x] https://github.com/kubeflow/katib/pull/2183

Please let me know if I missed something.

cc @kubeflow/wg-training-leads @tenzen-y @anencore94 @a9p @jbottum @kubeflow/release-team @elenzio9 @apo-ger

**Comment by tenzen-y** [comment]
Thank you for creating this! SGTM

**Comment by DnPlas** [comment]
@andreyvelich just for correctness, the feature freeze is on Aug 2nd, according to the [timeline](https://github.com/kubeflow/community/tree/master/releases/release-1.8#timeline). I just wanted to confirm this is correct and the WG is prepared for the upcoming feature freeze.

**Comment by andreyvelich** [comment]
Katib 0.16 has been released, thanks everyone for your contributions 🎉 
https://github.com/kubeflow/katib/releases/tag/v0.16.0
