### ISSUE TITLE
Enable namespace specification in `KatibClient` class

### ISSUE THREAD

**Issue by droctothorpe** [kubeflow/katib#2180]
/kind feature

**Describe the solution you'd like**
It would enhance UX if namespace could be specified at `KatibClient` instantiation time, similar to what the KFP Client [supports](https://kubeflow-pipelines.readthedocs.io/en/sdk-2.0.1/source/client.html#kfp.client.Client). It could still be overwritten in individual method calls.

**Anything else you would like to add:**
Happy to contribute this feature.

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by andreyvelich** [comment]
That is great suggestion @droctothorpe. Sure, we can do it.
I think, we can setup it as follows:

```
class KatibClient(object):
    def __init__(self, ..., namespace=utils.get_default_target_namespace()):
        ....
        self.namespace = namespace

    def create_experiment(self, experiment: models.V1beta1Experiment, namespace: str = None):
        namespace = namespace or self.namespace
        ...
 ```
 
 WDYT @droctothorpe @tenzen-y @johnugeorge ?

**Comment by andreyvelich** [comment]
@droctothorpe That would be nice if you could contribute that feature before feature freeze date (Aug 2nd). So we can include it in Katib 0.16 release.

**Comment by droctothorpe** [comment]
Exactly, @andreyvelich. I should be able to submit a PR on Monday if that's okay.

**Comment by andreyvelich** [comment]
Thank you, @droctothorpe! Let me know if you need my help.
