### ISSUE TITLE
Scheme of DB will be changed

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#220]
There are several requirements and bugs that needs to modify the scheme of DB

* Include StudyName to workerID #196 
* Include the StudyJob Info to study
* Duplication of Worker Log Bug

So v0.4 will not be compatible with v0.3 and before.

cc @vinaykakade @shibuiwilliam @mayankjuneja @wukong1992

**Comment by wukong1992** [comment]
@YujiOshima What's the second and third bugs? and what to do now?

**Comment by YujiOshima** [comment]
@wukong1992 
Second is not a bug. Currently, any information about StudyJob is not stored in Katib DB. For UI, It is better to store a status of Studyjob in DB.
The third is my colleague found it and he is fixing it now.
I expect Katib DB check the timestamp of metrics and avoid duplicating the Metrics even if a metrics is reported several times.
But it is not working correctly now.
