### ISSUE TITLE
Error while creating new Katib experiment after upgrade: the namespace lacks label "katib.kubeflow.org/metrics-collector-injection: enabled"

### ISSUE THREAD

**Issue by mChowdhury-91** [kubeflow/katib#2200]
/kind bug

**What steps did you take and what happened:**
Step 1: Upgraded to latest version of Katib(I tested with v0.12.0 and it worked fine)
Step 2: Create a new Katib experiment
Error:  I upgraded to latest Katib version..
While creating a new experiment, I'm getting error, [500] admission webhook "[validator.experiment.katib.kubeflow.org](http://validator.experiment.katib.kubeflow.org/)" denied the request: Cannot create the Experiment "median-stop-stdout" in namespace "xx": the namespace lacks label "katib.kubeflow.org/metrics-collector-injection: enabled"

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version): latest or v0.16.0
- Kubernetes version: (`kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (`uname -a`):

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by tenzen-y** [comment]
@mChowdhury-91 Can you tell me how to upgrade Katib?

**Comment by mChowdhury-91** [comment]
@tenzen-y I just went to the master branch, got the latest code into my local copy and did a **"kustomize build katib-with-kubeflow | kubectl apply -f -"**
All the pods came up right with "latest" image tag, but when I tried to create an experiment I faced the above error.

**Comment by tenzen-y** [comment]
@mChowdhury-91 I see. Since the Katib v0.13.0, the namespace lablel is changed. So can you add a label with `kubectl label ns ${YOUR_NAMESPACE} katib.kubeflow.org/metrics-collector-injection=enabled` to the namespace where you want to deploy Experiment?

https://github.com/kubeflow/katib/releases/tag/v0.13.0

**Comment by mChowdhury-91** [comment]
@tenzen-y There are many namespaces which uses Katib, should it be applied to all the namespaces?

**Comment by tenzen-y** [comment]
> @tenzen-y There are many namespaces which uses Katib, should it be applied to all the namespaces?

@mChowdhury-91 Yes, we must apply it to all namespaces.

**Comment by tenzen-y** [comment]
@mChowdhury-91 Is this issue fixed?

**Comment by mChowdhury-91** [comment]
@tenzen-y Thanks, Yes it worked. 
I have another question though, after I upgraded the Katib to latest, the katib-db-manager pod keeps restarting. Is it expected behaviour?

**Comment by tenzen-y** [comment]
> after I upgraded the Katib to latest, the katib-db-manager pod keeps restarting. Is it expected behaviour?

The behavior isn't expected. All of the katib components should be worked well.

**Comment by mChowdhury-91** [comment]
@tenzen-y Can you please help me here to fix the db-manager restart issue.

**Comment by tenzen-y** [comment]
Sure. Can you share logs from `db-manager`?

**Comment by mChowdhury-91** [comment]
@tenzen-y Here is the log from db-manager:

I0907 10:51:35.636117 1 db.go:32] Using MySQL
I0907 10:51:40.641711 1 init.go:27] Initializing v1beta1 DB schema
I0907 10:51:40.650039 1 main.go:113] Start Katib manager: 0.0.0.0:6789
I0907 10:56:35.496589 1 db.go:32] Using MySQL
I0907 10:56:40.502574 1 init.go:27] Initializing v1beta1 DB schema
I0907 10:56:40.510672 1 main.go:113] Start Katib manager: 0.0.0.0:6789
I0907 11:01:35.469396 1 db.go:32] Using MySQL
I0907 11:01:40.475491 1 init.go:27] Initializing v1beta1 DB schema
I0907 11:01:40.486599 1 main.go:113] Start Katib manager: 0.0.0.0:6789

**Comment by tenzen-y** [comment]
Uhm. The logs look good. Can you also show me `kubectl describe db-manager -n kubeflow` and `kubectl get pods -n kubeflow`?

**Comment by mChowdhury-91** [comment]
@tenzen-y Andrey helped me to understand and fix the restart issue. I have downgraded Katib to v0.15 as I'm on K8s version 1.21 and the restart issue doesn't show up. 
Thanks.
