### ISSUE TITLE
AttributeError: module 'kfp.dsl' has no attribute 'VolumeOp' while running kubeflow pipeline

### ISSUE THREAD

**Issue by mayankagarwal19911** [kubeflow/katib#2223]
/kind bug

**What steps did you take and what happened:**
I am new to AI/ML stream, while running https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-pipelines/kubeflow-e2e-mnist.ipynb in jupyter notebook I am getting below error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[16], line 6
      3 namespace="kubeflow-user"
      4 training_steps="200"
----> 6 @dsl.pipeline(
      7     name="End to End Pipeline",
      8     description="An end to end mnist example including hyperparameter tuning, train and inference"
      9 )
     10 def mnist_pipeline(name: str = name, namespace: str = namespace, training_steps: str = training_steps):
     11     # Run the hyperparameter tuning with Katib.
     12     katib_op = create_katib_experiment_task(name, namespace, training_steps)
     14     # Create volume to train and serve the model.

File ~/.local/lib/python3.11/site-packages/kfp/components/pipeline_context.py:65, in pipeline(func, name, description, pipeline_root, display_name)
     62 if pipeline_root:
     63     func.pipeline_root = pipeline_root
---> 65 return component_factory.create_graph_component_from_func(
     66     func,
     67     name=name,
     68     description=description,
     69     display_name=display_name,
     70 )

File ~/.local/lib/python3.11/site-packages/kfp/components/component_factory.py:616, in create_graph_component_from_func(func, name, description, display_name)
    605 """Implementation for the @pipeline decorator.
    606 
    607 The decorator is defined under pipeline_context.py. See the
    608 decorator for the canonical documentation for this function.
    609 """
    611 component_spec = extract_component_interface(
    612     func,
    613     description=description,
    614     name=name,
    615 )
--> 616 return graph_component.GraphComponent(
    617     component_spec=component_spec,
    618     pipeline_func=func,
    619     display_name=display_name,
    620 )

File ~/.local/lib/python3.11/site-packages/kfp/components/graph_component.py:58, in GraphComponent.__init__(self, component_spec, pipeline_func, display_name)
     49     args_list.append(
     50         pipeline_channel.create_pipeline_channel(
     51             name=arg_name,
     52             channel_type=input_spec.type,
     53             is_artifact_list=input_spec.is_artifact_list,
     54         ))
     56 with pipeline_context.Pipeline(
     57         self.component_spec.name) as dsl_pipeline:
---> 58     pipeline_outputs = pipeline_func(*args_list)
     60 if not dsl_pipeline.tasks:
     61     raise ValueError('Task is missing from pipeline.')

Cell In[16], line 15, in mnist_pipeline(name, namespace, training_steps)
     12 katib_op = create_katib_experiment_task(name, namespace, training_steps)
     14 # Create volume to train and serve the model.
---> 15 model_volume_op = dsl.VolumeOp(
     16     name="model-volume",
     17     resource_name="model-volume",
     18     size="1Gi",
     19     modes=dsl.VOLUME_MODE_RWO
     20 )
     22 # Run the distributive training with TFJob.
     23 tfjob_op = create_tfjob_task(name, namespace, training_steps, katib_op, model_volume_op)

AttributeError: module 'kfp.dsl' has no attribute 'VolumeOp'

**What did you expect to happen:**
Pipeline should get submitted to kubeflow.

**Anything else you would like to add:**

**Environment:**
   - kfp version is 2.0.1

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by mayankagarwal19911** [comment]
To add on top of it.

- I running the notebook on GKE

and using below version so of SDK

- !pip install kfp==2.0.1
- !pip install kubeflow-katib==0.16.0rc0

**Comment by andreyvelich** [comment]
I think, this example is based on KFP v1 and doesn't work with KFP v2.

Please try to run the following example which was changed by @zijianjoy before: https://github.com/kubeflow/pipelines/blob/master/samples/contrib/kubeflow-e2e-mnist/kubeflow-e2e-mnist-kfpv2.ipynb

We might need to add this KFP v2 example to Katib examples as well. cc @johnugeorge @tenzen-y

**Comment by mayankagarwal19911** [comment]
Thanks @andreyvelich.

**Comment by tenzen-y** [comment]
> We might need to add this KFP v2 example to Katib examples as well. 

Creating an issue might be better.
