### ISSUE TITLE
Add function of tune, a function supported by Katibclient on python sdk

### ISSUE THREAD

**Issue by jason9319** [kubeflow/katib#2225]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add function of tune, a function supported by Katibclient on python sdk
Please support algorithm settings as an argument from the KatibClient.tune function
I think that the algorithm_setting value should be entered at the moment of defining the Experiment.Spec.algorithm inside the tune function.
like this
` experiment.spec.algorithm = models.V1beta1AlgorithmSpec(
            algorithm_name=algorithm_name,
            algorithm_settings=algorithm_settings
        )`
please support it.
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @jason9319.

Sure, that is great addition to `tune` API.
Any suggestion how the algorithm settings argument in tune API should look like ?
Maybe we could have something like this:

```
client.tune(
    ....
    algorithm_name="tpe",
    algorithm_settings={
        "random_state": 10,
        "gamma": 0.02
    }
    ...
)
```
I think, the downside of this approach is that user has to know which alorithm settings are supported by which algorithm by following this guide: https://www.kubeflow.org/docs/components/katib/experiment/#search-algorithms-in-detail

Any other ideas @jason9319 @johnugeorge @tenzen-y @droctothorpe ?

/area sdk

**Comment by jason9319** [comment]
As you have already suggested, I think following katib algorithms official guide is best.

**Comment by droctothorpe** [comment]
I think this is a great idea. Just had one of our platform users request the same thing. Theoretically, we could create config objects for each algorithm, though that might incur significant operational overhead as the algorithms evolve.
