### ISSUE TITLE
Support log scaled grid in Grid Suggestion

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#224]
There is a big demand for Supporting the log scaled grid.

**Comment by mickeyh** [comment]
Would you accept a PR for log scaling in Random/Hyperopt suggestion (but not Grid search)?

**Comment by YujiOshima** [comment]
@mickeyh Of course! Very welcome!

**Comment by YujiOshima** [comment]
@mickeyh Great thank you for your code base suggestion! Can I fork from your PR?

**Comment by mickeyh** [comment]
Sure
