### ISSUE TITLE
Support experiments with generate_name feature

### ISSUE THREAD

**Issue by fensterwetter** [kubeflow/katib#2243]
/kind feature

**Describe the solution you'd like**
The Python katib client (again) supports experiments with the `generate_name` feature.

**Anything else you would like to add:**
After upgrading from kubeflow-katib 0.14.0 to 0.16.0, I noticed that the `create_experiment` function in `katib_client.py` now implicitly makes the assumption that the `experiment` object contains an attribute called `.metadata.name`. However, generally `name` can be missing in favour of `generate_name` which is then treated as a prefix which gets an additional suffix from the server. In version 0.14.0, the server return was used to access the resulting final name. At least from kubeflow-katib version 0.15.0 onwards, the server return is no longer captured and the original experiment object is used to access the `name` attribute.

I was wondering if the change was a conscious decision or rather a side effect that could be reverted. I am also happy to collaborate in case this is something that makes sense for katib to support.

Thanks
Thomas

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tenzen-y** [comment]
That makes sense. We should get the generated name if the name is empty here:

https://github.com/kubeflow/katib/blob/fc6beec8358f1c4a50d86de63c5906fce2eba373/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py#L104-L114

cc: @andreyvelich

**Comment by bharathk005** [comment]
@tenzen-y I can work on this if this feature is still needed.

**Comment by tenzen-y** [comment]
> @tenzen-y I can work on this if this feature is still needed.

Yes, I believe that this is still needed. Feel free to open the PR.

**Comment by bharathk005** [comment]
@tenzen-y 
Do we need to handle this scenario in the backend as well?

https://github.com/kubeflow/katib/blob/fc6beec8358f1c4a50d86de63c5906fce2eba373/pkg/ui/v1beta1/backend.go#L130

**Comment by tenzen-y** [comment]
> katib/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py

@bharathk005 That backend is only for Katib UI. So, we can improve only SDK.
