### ISSUE TITLE
Support Kubernetes v1.27 - v1.29

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#2256]
As part of Katib 0.17 release we need to support Kubernetes `v1.27 - v1.29` versions.

Currently, we validate Katib for Kubernetes `v1.25 - v1.27` in our integration tests.
We should drop support for `v1.25` and `v1.26` and add support for `v1.28` and `v1.29`.

Let's identify the required changes in this issue.

cc @kubeflow/wg-training-leads @tenzen-y @kubeflow/release-team

**Comment by tenzen-y** [comment]
> /assign @Ayush9026 i will solve this issue sir.

@Ayush9026 Are you still working on this? If so, could you 2 separate PRs so that we can revert the dedicated commit once we face the dependency issues?

The first one: Drop `v1.25` and Intriduce `v1.28`
The second one: Drop: `v1.26` and Introduce `v1.29`.

**Comment by Ayush9026** [comment]
Yes @tenzen-y sir i am working on it thanks for telling i will create two separate PR as you tell.

**Comment by andreyvelich** [comment]
@Ayush9026 Please can you let us know what is the status of this issue ?
We need to create PR this week since we are going to cut the Katib release in 2 weeks.

**Comment by tenzen-y** [comment]
This is the significant blocker for our next release. So, I take this issue.
/unassign @Ayush9026 
/assign
