### ISSUE TITLE
I'm getting this error when creating a katib experiment. Please check.

### ISSUE THREAD

**Issue by limes22** [kubeflow/katib#2259]
I'm getting this error when creating a katib experiment. Please check.

![image](https://github.com/kubeflow/katib/assets/102801493/1d4913c8-6dd1-4831-a099-e51eb897a1fc)

**Comment by UrkoAT** [comment]
Not a Katib expert but that doesn't look like a Katib issue. It appears that the experiment cant download the dataset (guessing for the mnist) and it throws an error. Then Katib reads this error and sets the experiment as failed.

**Comment by tenzen-y** [comment]
@lluunn Could you share which example you use?
I suspect that the examples using mxnet were broken: https://github.com/kubeflow/katib/pull/2252#issuecomment-1948890342

**Comment by tenzen-y** [comment]
> @lluunn Could you share which example you use? I suspect that the examples using mxnet were broken: [#2252 (comment)](https://github.com/kubeflow/katib/pull/2252#issuecomment-1948890342)

Ah, I found that the MXNet project has already closed. So the model registry would be closed :(

https://github.com/apache/mxnet

**Comment by tenzen-y** [comment]
This should be resolved by #2261 
/close
