### ISSUE TITLE
DARTS algorithm fails to create more than one trial

### ISSUE THREAD

**Issue by MatthiasCarnein** [kubeflow/katib#2265]
/kind bug

**What steps did you take and what happened:**
I'm running into an issue with the DARTS algorithm for Neural Architecture Search. The suggestion service only creates the initial trial but fails to create subsequent trials.

To reproduce, take the DARTS example but increase maxTrialCount to any value >1: 
https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/darts-gpu.yaml

The first trial will run successfully but upon generating a second trial the suggestion service will error with:
`UnboundLocalError: local variable 'num_layers' referenced before assignment`

The issue seems to be that `num_layers` , `search_space_str` and `algorithm_settings_str` are only defined in the first run and are unavailable for the creation of subsequent trials:
https://github.com/kubeflow/katib/blob/8df3c5c8383db6ee601f0ed8642cd554ee2234b6/pkg/suggestion/v1beta1/nas/darts/service.py#L50-L72

**What did you expect to happen:**

The suggestions service should successfully create new trials after the first set of trials has finished.

**Anything else you would like to add:**

From what I can tell all the examples and unit tests for DARTS use a single trial which is probably why this issue has not surfaced so far.

**Environment:**

- Katib version (check the Katib controller image version): v0.16.0 but it's a longer standing issue
- Kubernetes version: (`kubectl version`):
- OS (`uname -a`):

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by andreyvelich** [comment]
Thank you for testing DARTS algorithm in Katib @MatthiasCarnein!

If you take a closer look at the implementation it is intentionally that Katib creates just a single Trial for DARTS.

As described in this doc: https://github.com/kubeflow/katib/tree/master/pkg/suggestion/v1beta1/nas/darts#katib-implementation, 
Suggestion generates set of primitives from Experiment NAS Config, number of layers, and algorithm settings.
After that, single Trial evaluates DARTS algorithm using this script: https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images/darts-cnn-cifar10.
Finally, Metrics Collector saves best genotype in the Experiment metrics.

Katib [Hyperparameter tuning architecture](https://www.kubeflow.org/docs/components/katib/overview/#architecture) with Experiment, Suggestion, Trials is not ideally designed for various architecture search algorithm.
That is why we have to follow this model to run DARTS with Katib controllers.

**Comment by MatthiasCarnein** [comment]
Oh I see, I wasn't aware that DARTS is designed to run as a single trial. Thank you for the explanation!
