### ISSUE TITLE
Replace reflect.DeepEqual with cmp.Diff in tests

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2268]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
To improve visibility, we should replace `reflect.DeepEqual` with `cmp.Diff` in all test cases: https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md#go-development

Here is an example for using `cmp.Diff`: https://github.com/kubeflow/katib/blob/8df3c5c8383db6ee601f0ed8642cd554ee2234b6/pkg/apis/config/v1beta1/defaults_test.go#L88-L90

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tariq-hasan** [comment]
@tenzen-y I would like to take on this ticket.

**Comment by tenzen-y** [comment]
> @tenzen-y I would like to take on this ticket.

Sure, Feel free to assign this yourself with "/assign" comment.

**Comment by Mu-Magdy** [comment]
Hi @tenzen-y 

Is this issue solved or I can work on it?

**Comment by tenzen-y** [comment]
@tariq-hasan Are you still working on this?

**Comment by tariq-hasan** [comment]
I am working on it. I will open a new PR.
