### ISSUE TITLE
Flaky Test: Trial status is succeeded and metrics are properly populated

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2269]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Flaky Test: "Expect that Trial status is succeeded and metrics are properly populated Metrics available because GetTrialObservationLog returns values":  https://github.com/kubeflow/katib/blob/8df3c5c8383db6ee601f0ed8642cd554ee2234b6/pkg/controller.v1beta1/trial/trial_controller_test.go#L263-L274

```shell
--- FAIL: TestReconcileBatchJob (82.19s)
    trial_controller_test.go:274: 
        Timed out after 80.001s.
        Expected
            <bool>: false
        to be true
FAIL
	github.com/kubeflow/katib/pkg/controller.v1beta1/trial	coverage: 83.6% of statements
```

https://github.com/kubeflow/katib/actions/runs/8125174959/job/22207477654?pr=2267#step:4:106

**What did you expect to happen:**
No errors occur.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Katib version (check the Katib controller image version):
- Kubernetes version: (`kubectl version`):
- OS (`uname -a`):

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by PeterWrighten** [comment]
May I work for this bug?
/assign

**Comment by PeterWrighten** [comment]
I consider it should work by just modifying timeout threshold from 80 to 100.

**Comment by tenzen-y** [comment]
> I consider it should work by just modifying timeout threshold from 80 to 100.

I don't think so. Despite we applied a similar approach, this issue still remains.

**Comment by PeterWrighten** [comment]
> > I consider it should work by just modifying timeout threshold from 80 to 100.
> 
> 
> 
> I don't think so. Despite we applied a similar approach, this issue still remains.
> 
> 

Seem that it's an interesting issue. I would do some surveys and try working on it.

**Comment by tenzen-y** [comment]
@PeterWrighten Are you still working? If not, could you unassign yourself from this issue?

**Comment by tenzen-y** [comment]
This should be fixed by https://github.com/kubeflow/katib/pull/2350
/close
