### ISSUE TITLE
Whether the hyperparameter search algorithm will refer to the value of additionalMetricNames

### ISSUE THREAD

**Issue by kldancer** [kubeflow/katib#2286]
If not, is the purpose of the additionalMetricNames parameter just for visualization? It will not affect the experimental results？
Please help me answer this question, thank you very much !!!🙏

**Comment by andreyvelich** [comment]
That is correct @YKL2436542696 

Currently, additionalMetricNames is only used for metrics tracking purposes. So you can get them in the Katib UI or using Katib SDK.
We have an open issue to support multi-objective optimization, but it has not been implemented yet: https://github.com/kubeflow/katib/issues/1549

**Comment by YKL2436542696** [comment]
@andreyvelich  Thank you。 Can I understand it this way? The strategies for additionalMetricNames in Spec.Objective.MetricStrategies currently have no practical effect. (This may work when multi-objective optimization is supported in the future)

**Comment by YKL2436542696** [comment]
And I noticed that the metrics values output by the "/katib/fetch_hp_job_info/" interface in the katib-ui module are based on spec.Objective.Type and have nothing to do with Spec.Objective.MetricStrategies。
I'm curious why the metric values are not output according to the strategy defined by Spec.Objective.MetricStrategies 🤯

**Comment by andreyvelich** [comment]
> The strategies for additionalMetricNames in Spec.Objective.MetricStrategies currently have no practical effect. 

That's right, we check if Experiment goal is reached based on objective metric name and its metrics strategy: https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/util/status_util.go#L166

However, we send those metrics to the suggestion service based on the strategies: https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go#L419.
So if user implements custom algorithm service that analyses all Trial metrics that might give some value.

**Comment by andreyvelich** [comment]
>I'm curious why the metric values are not output according to the strategy defined by Spec.Objective.MetricStrategies

It's a good point, actually UI should show just take Trial metrics results from `.status.observation`, not from metrics logs as we do right now: https://github.com/kubeflow/katib/blob/master/pkg/ui/v1beta1/hp.go#L156-L166
Thanks for reporting!

/bug
/area frontend
/good-first-issue

**Comment by live2awesome** [comment]
i am interested in solving this /assign

**Comment by andreyvelich** [comment]
@xr-dev-saurabh @live2awesome Do you still want to work on this issue ?
