### ISSUE TITLE
Migrate away from deprecated github.com/hpcloud/tail

### ISSUE THREAD

**Issue by AndersBennedsgaard** [kubeflow/katib#2299]
/kind feature

**Describe the solution you'd like**

As https://github.com/hpcloud/tail hasn't been touched for 6 years (it is using Go v1.5.1), and the https://github.com/hpcloud organisation doesn't have any (public) members, we should really stop depending on their code. Multiple forks has been created, but it seems like https://github.com/nxadm/tail is the most popular one, so this could be a potential candidate

**Anything else you would like to add:**

The reason I found this usage of a deprecated package, is that I hit https://github.com/kubeflow/katib/issues/1769 and tried to investigate the issue

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by tariq-hasan** [comment]
I am interested to take on this one.

/assign
