### ISSUE TITLE
Return validation errors after all fields are verified

### ISSUE THREAD

**Issue by tenzen-y** [kubeflow/katib#2302]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Currently, the katib validator returns errors once the error is found: https://github.com/kubeflow/katib/blob/7df05c23a55363ba7cbbd7b9859943562afd71f4/pkg/webhook/v1beta1/experiment/validation_webhook.go#L95

As we discussed [here](https://github.com/kubeflow/training-operator/pull/2035#discussion_r1555708045), to improve UX, we should return errors after all fields are verified like the training-operator: https://github.com/kubeflow/training-operator/blob/b5e23d0325005dd0ecae7d41ad6a80ba1459b275/pkg/webhooks/pytorch/pytorchjob_webhook.go#L66-L67

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

**Comment by ckcd** [comment]
@tenzen-y may I take this issue please?

**Comment by tenzen-y** [comment]
> @tenzen-y may I take this issue please?

Sure, feel free to assign yourself with `/assign`.
