### ISSUE TITLE
some questions about NAS

### ISSUE THREAD

**Issue by YKL2436542696** [kubeflow/katib#2306]
Hello, @andreyvelich  😀  I would like to know some questions about NAS。🙏
1. In fact, after running the experiment using ENAS and DARTS, the results obtained were some network architecture configurations, such as nn-COnfig, algorithm settings, and search space. Training containers need to expose corresponding parameters to use these configurations to build neural networks. Instead of directly obtaining a neural network model. That is to say, the logic for building neural networks needs to be defined in the training container.

2. I ran NAS and DARTS examples on katib version 0.15, but there is no visual result graph. So I want to know how to view the results of the neural network architecture shown in the video: "https://www.youtube.com/watch?v=Rqah6F0D6-Y". Did new-ui abandon this part?🤔

**Comment by andreyvelich** [comment]
Thank you for testing Architecture Search functionality in Katib @YKL2436542696!

> In fact, after running the experiment using ENAS and DARTS, the results obtained were some network architecture configurations, such as nn-COnfig, algorithm settings, and search space. Training containers need to expose corresponding parameters to use these configurations to build neural networks. Instead of directly obtaining a neural network model. That is to say, the logic for building neural networks needs to be defined in the training container.

That's right, the output of these algorithm is Graph Neural Network which represents CNN for image classification problems. I remember that DARTS and ENAS can be used for NLP use-cases as well based on the research papers, but we haven't explored them yet.

It would be nice to see integration between Kubeflow Model Registry and Katib NAS algorithms to store the best model in the registry. cc @tarilabs @dhirajsb 

>I ran NAS and DARTS examples on katib version 0.15, but there is no visual result graph. 

Yes, unfortunately the existing UI doesn't support it. We have an open issue to add it and we are looking for contributors who can work on that: https://github.com/kubeflow/katib/issues/1444.

**Comment by tarilabs** [comment]
> It would be nice to see integration between Kubeflow Model Registry and Katib NAS algorithms to store the best model in the registry

+1 !
If you have a little demo on the Katib side, we can work on the remainder, so to show one possible integration example as part of the example documentation. wdyt?

**Comment by andreyvelich** [comment]
Sure @tarilabs, maybe it worths to discuss these topics in one of Kubeflow community, Model Registry, or Katib community calls.
