### ISSUE TITLE
[feasibility research] Investigate implementation sharing of algorithms between advisor and katib

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#232]
https://github.com/tobegit3hub/advisor is yet another system similar to Google Vizier, katib and advisor has different use cases while we could share the same algorithm libraries. Thus we should investigate if we could unity the API in suggestion level and share the implementation.

/cc @tobegit3hub @YujiOshima

**Comment by gaocegege** [comment]
Recently I am working on the prototype of katib, in the prototype, I introduce a unified service called advisor, which will do some pre and post work to wrap GetSuggestionRequest to study and trials that advisor is defined https://github.com/tobegit3hub/advisor/blob/master/advisor_server/suggestion/algorithm/abstract_algorithm.py#L9

We need to update the code of suggestions in advisor, mainly to avoid getting study and trial from advisor db. We pass the study config and trials as arguments. It works for advisor-randomsearch now. I can present the work when the prototype is ready.

**Comment by tobegit3hub** [comment]
Thanks @gaocegege . It may work if we pass the study config to generate the `suggestion` without reading the `advisor db`. However, now we use `db` to store the `study config` and the `trial result`. The `Bayesian optimizer` relies on the previous `trial result` to generate new `trial` which is different from `Random search`.

I'm not sure if we want to refactor the project as the standalone library or not. Since `Google Vizier` has the backend service, it can support more functions with the stored data.

**Comment by gaocegege** [comment]
In the prototype, I am trying to pass all information needed by the suggestion (study config, previous trials) to suggestion services. And the information will be stored in K8s apiserver as CRDs (Study CRD, Trial CRD).

As for the self-maintained DB, katib v1alpha2 follows the similar design of advisor and vizier, which introduces a DB to store studies, trials and metrics. But the abstraction and table definition are different from advisor. Thus advisor cannot be used in katib directly. If we unify the db, we could implement such a feature.

Personally, I think katib is built on top of k8s, and should be k8s native. Thus I think we could store experiments and trials as k8s CRDs. Then keep a time series DB to store metrics. All info (e.g. previous trial results) needed by the suggestion will be sent to the suggestion as arguments. Suggestion service may maintain an RDB to persist its own state. In other words, I want to use k8s as backend of the system.

If the prototype is not accepted by the community, we have two options to share the implementation:

- Keep katib DB and advisor DB consistent. We could use the same table definitions, then the algorithm code in advisor could be used in katib with 0 code change.
- Introduce a data store interface, keep different implementations in katib and advisor. When the algorithms are used in different systems, we can use different data store implementations.
