### ISSUE TITLE
Python SDK for Katib and Kubeflow Pipelines can not be installed at the same time

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/katib#2346]
### What happened?

Currently, If you try install the latest versions of the `kfp` and `kubeflow-katib` libraries at the same time, there is a dependency version conflict.

This is caused by a number of conflicts:

1. [`kfp==2.7.0` needs `protobuf>=4.21.1,<5`](https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/requirements.in#L21) but [`kubeflow-katib` needs `protobuf>=3.19.5,<=3.20.3`](https://github.com/kubeflow/katib/blob/v0.17.0-rc.0/sdk/python/v1beta1/setup.py#L26)
2. [`kfp==2.7.0` needs `kubernetes>=8.0.0,<27`](https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/requirements.in#L20) but [`kubeflow-katib` needs `kubernetes>=27.2.0`](https://github.com/kubeflow/katib/blob/v0.17.0-rc.0/sdk/python/v1beta1/setup.py#L24)

See for yourself by trying the following command:

```shell
pip install kfp==2.7.0 kubeflow-katib==0.17.0rc0
```

### What did you expect to happen?

The latest versions of both `kfp` and `kubeflow-katib` can be installed at the same time.

### Environment

Kubernetes version:
```bash
$ kubectl version

```
Katib controller version:
```bash
$ kubectl get pods -n kubeflow -l katib.kubeflow.org/component=controller -o jsonpath="{.items[*].spec.containers[*].image}"

```
Katib Python SDK version:
```bash
$ pip show kubeflow-katib

```

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by thesuperzapper** [comment]
For those wondering, the latest versions which will work together are:

```shell
pip install kfp==2.5.0 kubeflow-katib==0.16.0
```

**Comment by thesuperzapper** [comment]
Can the @kubeflow/pipelines and @kubeflow/wg-automl-leads please work together to try and prevent this kind of dependency conflicts in the python packages, so we can always install the latest versions of both in Kubeflow Notebooks.

**Comment by tenzen-y** [comment]
IIRC, This protobuf version limitation is brought us from #2141.
So, Unless we resolve the #2141, we can not update the protobuf version to v4.

**Comment by thesuperzapper** [comment]
I have raised a similar issue for KServe, which also has a dependency conflict with `protobuf`: https://github.com/kserve/kserve/issues/3730

**Comment by tenzen-y** [comment]
/assign
After #2344 is merged, I will open a PR to resolve this conflict.
