### ISSUE TITLE
Add unit test for `tune` in the `katib_client` module

### ISSUE THREAD

**Issue by tariq-hasan** [kubeflow/katib#2372]
### What you would like to be added?

We need to add unit test for the `tune` function in the `katib_client` module.

### Why is this needed?

Parent issue: [Add unit tests to the Katib SDK #2184](https://github.com/kubeflow/katib/issues/2184)

Unit tests already implemented:
- [Add unit test for create_experiment in the katib_client module #2325](https://github.com/kubeflow/katib/pull/2325)

Bugs due to missing unit tests:
- [[SDK] Fix empty list for env variables and numpy version #2360](https://github.com/kubeflow/katib/pull/2360)

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

**Comment by tariq-hasan** [comment]
\assign

**Comment by andreyvelich** [comment]
This has been completed by: https://github.com/kubeflow/katib/pull/2399.
