### ISSUE TITLE
Add e2e test for `tune` in the `katib_client` module

### ISSUE THREAD

**Issue by tariq-hasan** [kubeflow/katib#2383]
### What you would like to be added?

We need to add e2e test for the `tune` function in the `katib_client` module.

### Why is this needed?

**References**
- e2e test for `create_experiment` in the `katib_client` module: https://github.com/kubeflow/katib/blob/master/test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py#L172
- e2e test for `training-operator` SDK: https://github.com/kubeflow/training-operator/blob/master/sdk/python/test/e2e/test_e2e_pytorchjob.py#L174

**Source**
- https://github.com/kubeflow/katib/pull/2325#issuecomment-2186646927

**Related issues**
- [Add unit tests to the Katib SDK #2184](https://github.com/kubeflow/katib/issues/2184)
- [Add unit test for create_experiment in the katib_client module #2325](https://github.com/kubeflow/katib/pull/2325)
- [Add unit test for tune in the katib_client module #2372](https://github.com/kubeflow/katib/issues/2372)

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @tariq-hasan!
/area sdk
/area testing
/remove-lifecycle needs-triage
/good-first-issue

**Comment by kyooosukedn** [comment]
Would like to try on this :)

**Comment by andreyvelich** [comment]
@kyooosukedn @tariq-hasan Do you time working on this ? I think, it would be great to have some simple test using `tune` API.
We can even take the getting started example: https://www.kubeflow.org/docs/components/katib/getting-started/#getting-started-with-katib-python-sdk

Similar to [the Training Operator](https://github.com/kubeflow/training-operator/blob/master/sdk/python/test/e2e/test_e2e_pytorchjob.py#L174), we should just add another test to the [run-e2e-experiment.py](https://github.com/kubeflow/katib/blob/master/test/e2e/v1beta1/scripts/gh-actions/run-e2e-experiment.py#L157).

**Comment by kyooosukedn** [comment]
Hi @andreyvelich, sorry that it took me so long to finally work on this.. will do to try replicate this and get working.Thanks for your lead.

**Comment by andreyvelich** [comment]
Thank you for your time!

**Comment by Electronic-Waste** [comment]
I will work on this :)

/assign
