### ISSUE TITLE
Refactor `/pkg/webhook/v1beta1/pod/inject_webhook_test.go` according to Developer Guide.

### ISSUE THREAD

**Issue by Electronic-Waste** [kubeflow/katib#2388]
### What you would like to be added?

Refactor `/pkg/webhook/v1beta1/pod/inject_webhook_test.go` to obey rules defined in the [Developer Guide](https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md).

### Why is this needed?

Currently, testcases in `/pkg/webhook/v1beta1/pod/inject_webhook_test.go` are defined in slices and use `reflect.Equal` for comparison. It's not recommended according to the Developer Guide. We should:

1. Use [cmp.Diff](https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff) instead of reflect.Equal, to provide useful comparisons.

2. Define test cases as maps instead of slices to avoid dependencies on the running order. Map key should be equal to the test case name.

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

**Comment by andreyvelich** [comment]
Thank you for creating this @Electronic-Waste!

Do you want to work on this testing improvement ?

**Comment by Electronic-Waste** [comment]
@andreyvelich Yes, I will work on this testing improvement when I have the bandwidth.

/assign
