### ISSUE TITLE
Provide python or CL interface to generate StudyJob yaml and/or StudyJob

### ISSUE THREAD

**Issue by cwbeitel** [kubeflow/katib#240]
It would be convenient if users could define and create a katib StudyJob YAML from a Python interface. It would also be nice to be able to submit and poll for the status of this from python as well.

In the case of https://github.com/kubeflow/examples/pull/322 it looks like we can easily launch a [kubeflow/pipelines](https://github.com/kubeflow/pipelines) pipeline for a single [train_mnist call](https://github.com/kubeflow/examples/blob/8622fb0e7105f1d4ed3f3203a05100459d9eebad/demos/simple_pipeline/gpu-example-pipeline.py#L12). But then when we want to go and tune the same with katib a [yaml](https://github.com/kubeflow/examples/blob/8622fb0e7105f1d4ed3f3203a05100459d9eebad/demos/simple_pipeline/gpu-example-katib.yaml) needs to be written.

- One approach would be to enable katib jobs to be configured and launched from a CLI. This could then be wrapped with a kfp.ContainerOp (roughly as below) and thereby made more testable and easier to include in a broader pipeline.
- Another would be to enable katib jobs to be triggered from a python call. This could also be wrapped in a container op but I'm guessing doing it this way would allow the result of the op to be more readily consumed.

```python
import kfp.dsl as kfp
 def training_op(learning_rate: float, ... ):
  return kfp.ContainerOp(
    name=step_name,
    image='katib/mxnet-mnist-example',
    command=['katib-studyjob-launcher'],
    arguments=[
      '--cmd', 'python', '/mxnet/example/image-classification/train_mnist.py'
      '--hparam="--lr","%s","%s"' % (min_learningrate, max_learningrate),
      '--'
      '--batch-size', '64',
      ...
    ]
  )
 @kfp.pipeline(
  name='KatibStudyJob',
)
 def kubeflow_training(
  learning_rate: kfp.PipelineParam = kfp.PipelineParam(name='min_learningrate', value=0.1),
  learning_rate: kfp.PipelineParam = kfp.PipelineParam(name='max_learningrate', value=0.3),
...
):
  training = training_op(min_learningrate, max_learningrate, ...)

```

/cc @jlewi @texasmichelle

**Comment by YujiOshima** [comment]
@janvdvegt That's great! I'm so interested in your project. Very welcome to contribute!
We can make two level IF. 
A high level IF is manage StudyJob with your project.
A low level iF is calling Katib API directly.

**Comment by andreyvelich** [comment]
We created [Python SDK](https://github.com/kubeflow/katib/tree/master/sdk/python/v1beta1) for Katib to run Experiments.
