### ISSUE TITLE
Katib UI should allow sorting by column value

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#248]
For longer studies with lots of workers, this will allow the user to find the configuration with best results easier.

Workaround is to download the csv and edit it in a spreadsheet.

**Comment by ssiegel95** [comment]
How does one download as CSV?

**Comment by andreyvelich** [comment]
Hi @ssiegel95.
We haven't implemented it yet.
Follow this issue to track it: https://github.com/kubeflow/katib/issues/642.
