### ISSUE TITLE
Create a generic template for TF event metric collector

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#249]
Allow the user to import a template TF event metric collector. This will reduce the verbosity of the study job yaml file.

**Comment by jlewi** [comment]
@richardsliu what is the priority of this issue? Are we likely to get it done in 0.5 or should we move it to 0.6?

**Comment by richardsliu** [comment]
Depending on how we implement metrics in v1alpha2, this may be obsolete. I'll move it to 0.6.0 for now.
