### ISSUE TITLE
[Feature] AutoML/NAS support in Katib

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#257]
We have an early design arch of AutoML/NAS support in Katib.  

Doc link: https://docs.google.com/document/d/1fE5yKG4d1eOC8vXvxNoAiTHErLfkVbvC-i_cArZp9Jo/edit

Please review the design

Related issues: 
https://github.com/kubeflow/kubeflow/issues/1074
#24 

Contributed by @Akado2009 @DeeperMind @garganubhav @andreyvelich @tremblerz

/cc @YujiOshima @gaocegege @jlewi

**Comment by DeeperMind** [comment]
A presentation of our work cab be found in https://docs.google.com/presentation/d/1SfcKy7fzHFJZMChodCR1uBN44yX6p6QEkb0gRO0w_JI/edit?usp=sharing

**Comment by andreyvelich** [comment]
A final Katib-NAS design doc can be found here 
https://docs.google.com/document/d/1qGWy-C5XSQmh82XYoMcJ_JWLHwmyvdMRjCkFMfkO0vE/edit

**Comment by gaocegege** [comment]
https://github.com/Microsoft/nni/blob/b6cf7cee0e72671672b7845ab24fcdc5aed9ed48/docs/en_US/GeneralNasInterfaces.md#example-enas-macro-search-space

NNI developed by MSRA has a document about their design decisions on NAS. It is really helpful for us.

**Comment by richardsliu** [comment]
Any more remaining work here?

**Comment by andreyvelich** [comment]
@richardsliu I think we can close this issue, since we support NAS in v1alpha1 and v1alpha2. 
For any other NAS improvements we can create another issue.
