### ISSUE TITLE
About the system design of Katib-NAS

### ISSUE THREAD

**Issue by DeeperMind** [kubeflow/katib#266]
We just came up with a new system design for Katib-NAS: https://drive.google.com/file/d/1WjJbuUro0BQY1VW-iHs-ir9uxeQcywVl/view?usp=sharing
Compared with the previous one (https://docs.google.com/document/d/1fE5yKG4d1eOC8vXvxNoAiTHErLfkVbvC-i_cArZp9Jo/edit), we made NAS algorithm part of Katib suggestion. In this way, it can utilize the current components of Katib more. Also, we corrected the error that trial pods are spawned by StudyJob Controller, not GRPC server.

Which one do you think is better? Your review is much appreciated.

Related to 
https://github.com/kubeflow/katib/issues/257

**Comment by andreyvelich** [comment]
@DeeperMind Should we change ModelDB to mySQL DB?

**Comment by DeeperMind** [comment]
> @DeeperMind Should we change ModelDB to mySQL DB?

Changed
