### ISSUE TITLE
CLI for Katib-NAS system

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#272]
We should create CLI for Katib-NAS system.
Related to https://github.com/kubeflow/katib/issues/257

**Comment by YujiOshima** [comment]
What kind of CLI? Please tell me a detail of the CLI.

**Comment by andreyvelich** [comment]
@YujiOshima We want to create simple CLI for users who don't want to use our UI. 
In first release we want to add this commands to CLI: create, delete NAS job from yaml file, list of all NAS jobs, describe current NAS job.
That will be binary file which you need to install in your cluster.
Pretty much the same what you did here [Katib CLI](https://github.com/kubeflow/katib/tree/master/cmd/cli). 
And what we have in [Argo CLI](https://github.com/argoproj/argo/tree/master/cmd/argo).
I am using cobra framework for this as well.

**Comment by gaocegege** [comment]
Could we define NAS Job as a CRD to make use of kubectl as our CLI?

@andreyvelich

**Comment by andreyvelich** [comment]
@gaocegege 
Right now, yes we can. 
But, if we want to implement some other functionality to NAS Job, that kubectl can't provide, we should create our own CLI.
