### ISSUE TITLE
Vizier core rest GetWorkers not working

### ISSUE THREAD

**Issue by janvdvegt** [kubeflow/katib#276]
According to the Swagger definitions, GetWorkers should be a Get method where I pass study_id, trial_id and/or worker_id. No matter how I pass these it will return the following 500 response:

    {
        "error": "worker_id, trial_id or study_id must be set",
        "code": 2
    }

I looked in the source code (although my Go is abysmal) and I tried different naming conventions as well. Example of how I make the GET call:

URI: localhost:8001/api/Manager/GetWorkers

Body: {"study_id": "f9d4365bb7d3241a"}

Headers: application/json

The above response is what I get.

**Comment by johnugeorge** [comment]
It looks like study_id field is empty when received at the server.   The problem should be the way you send the Get parameters. 

Try a simple curl 
curl localhost:8001/api/Manager/GetWorkers?study_id= f9d4365bb7d3241a

**Comment by janvdvegt** [comment]
I have no idea what is wrong with me, I spent a few hours on this. Thank you and sorry for wasting your time.
