### ISSUE TITLE
studyJob cannot recover once Completed or Failed

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#291]
Now studyJob cannot recover once **Completed or Failed.**
When a studyJob CRD created, I can update it by "kubectl apply" or else, but if the studyJob condition is  Completed or Failed, we never start next suggestion schedule.
For example, a user creates a studyJob with an invalid workerSpec, which would lead to spawnWorker return error and studyJob goes to **Failed**. Then the user can correct workerSpec by "kube apply", expecting studyJob re-triggered. However, nothing will happen.

@here we should discuss the behavior of updating a studyJob CRD (when it is in RUNNING, Completed or FAILED)

```
	if instance.Status.Condition == katibv1alpha1.ConditionCompleted || instance.Status.Condition == katibv1alpha1.ConditionFailed {
		nextSuggestionSchedule = false
	}
```

**Comment by hougangliu** [comment]
1. At least, for Failed studyJob, we should try to rehandle it when updated.
2. For completed studyJob, we should reject updating it by (webhook)[https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/webhook] (we need upgrade controller-runtime, and webhook can validate studyJob to fix #317).

**Comment by jlewi** [comment]
This seems like its working as intended to me.

Once a job reaches a terminal state (failed or succeseded) updates to the job should not be allowed.
This is consistent with how native K8s jobs work.

If a user wants to update the spec they could create a new job.

/cc @johnugeorge @richardsliu

**Comment by johnugeorge** [comment]
Agree.  K8s job works in the same way.

**Comment by gaocegege** [comment]
/close

We deprecated v1alpha1.
