### ISSUE TITLE
name of workerspec and metricsCollectorspec template must follow rule

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#297]
for a studyJob, in its workerSpec and metricsCollectorSpec tempalte, the k8s resource (Job, PytorchJob or TFJob for worker, and CronJob for metricsCollector) metadata.name value must be specified with `{{.WorkerID}}`. In Katib source code, this name rule is followed to manage worker and  metricsCollector k8s resource.

Solution:
1. doc that in studyJob workerSpec and metricsCollectorSpec tempalte,  the k8s resource metadata.name value must be specified with `{{.WorkerID}}`;
2. in source code, decouple this name restriction.
```
metadata:
      name: {{.WorkerID}}
```

**Comment by hougangliu** [comment]
@YujiOshima any comment?

**Comment by YujiOshima** [comment]
@hougangliu I'm not sure about the second one. 
In another way, we can dismiss metadata.name  in a template and overwrite it with `{{.WorkerID}}`. Of course, need to explain in a doc.

**Comment by hougangliu** [comment]
namespace of workerspec and metricsCollectorspec must keep same with the studyJob

**Comment by hougangliu** [comment]
we can dismiss metadata.name in a template and overwrite it with {{.WorkerID}}. but for namespace, if overwrite with studyJob namespace, something maybe go wrong. for example, default secret role the Pod mount may change, or even the pod may mount a PVC (which is namespaced).

@YujiOshima  So should we make a constraint that workerspec and metricsCollectorspec must keep same namespace with its studyJob (otherwise the studyJob goes failed) and the name must be {{.WorkerID}} (otherwise replaced with {{.WorkerID}}  and a warning message logged)

**Comment by johnugeorge** [comment]
Please document it if we are planning to change the behavior.

If we are planning to override name and namespace, One solution can be  changing job template to PodSpec(like in TFJob/PytorchJob).

**Comment by hougangliu** [comment]
In sum, for current source code, we must make sure worker and metricsCollector template with  {{.WorkerID}} name and same namespace as the studyJob. Here, we need decide the behavior when the two metadata attributions don't follow this constraint respectively.

P.S I notice that default workerTemplate and metricsCollectorTemplate hard-code namespace as `kubeflow`

**Comment by richardsliu** [comment]
For now I would prefer to document the `{{ .WorkerID }}` usage more clearly (option 1). Replacing the name introduces an inconsistent behavior that can confuse users.

In our future (v1beta) API, we can discuss the longer term plan.

**Comment by hougangliu** [comment]
@richardsliu Then I think we should mark stutdyJob Failed if user doesn't follow the guideline, right?

**Comment by richardsliu** [comment]
Yes, we need to validate the studyjob (and add tests to verify this).

**Comment by hougangliu** [comment]
@richardsliu thanks! get it
