### ISSUE TITLE
Add example doc for TFJob and PytorchJob

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#313]
To run examples for  TFJob or PytorchJob, we should install corresponding job-operators by kfctl.
@richardsliu @johnugeorge Could you add docs for it?

**Comment by johnugeorge** [comment]
Docs are added in the package Readme https://github.com/kubeflow/kubeflow/tree/master/kubeflow/katib

**Comment by richardsliu** [comment]
We should add the documentation to https://github.com/kubeflow/katib/blob/master/README.md as well, and reference the TF/Pytorch examples.
