### ISSUE TITLE
Katib StudyInfo UI always shows horizontal scrollbar.

### ISSUE THREAD

**Issue by TimZaman** [kubeflow/katib#316]
On Kubeflow 0.4.0-rc3; GKE CLI. Google Chrome Version 71.0.3578.98 (Official Build) (64-bit).

See title. Quite pedantic UI issue: total P4.

I think the ui always takes into account some horizontal space for a vertical scrollbar, and therefore offsets. Even on large view the UI is _always_ larger than your display:

![image](https://user-images.githubusercontent.com/7721540/50708379-f4925100-1018-11e9-95f4-a022cdbb7832.png)

If i then scroll to the right, you can see this in the top-right corner:
![screenshot 2019-01-04 at 12 06 03](https://user-images.githubusercontent.com/7721540/50708472-3de2a080-1019-11e9-8081-d05022998cff.png)

**Comment by gaocegege** [comment]
/close

Thanks for the issue. We now have a new UI for v1alpha3.
