### ISSUE TITLE
ROADMAP for 2019 Katib

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#318]
Can we get a ROADMAP for Katib? This can be fairly high level like the overall Kubeflow ROADMAP

https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md

/cc @johnugeorge @YujiOshima @gaocegege

**Comment by YujiOshima** [comment]
@jlewi my plan for the next step of Katib is

* Katib-NAS (cc @DeeperMind 
* Enrich UI for not specialist of k8s CRD.
* Enforce reproducibility: Integrate Model management, experimental tracking.

@johnugeorge @gaocegege WDYT?

**Comment by johnugeorge** [comment]
Agree. We should break these down into multiple issues and tag them into upcoming releases 

Related #319

**Comment by gaocegege** [comment]
SGTM, I am looking forward to joining the development of Katib again in March. I am going to finish my studies in February :smile:

**Comment by richardsliu** [comment]
I believe this can be closed now.

**Comment by YujiOshima** [comment]
We add the roadmap by #348. Thanks @richardliu!

/close
