### ISSUE TITLE
Plans for Katib in v0.5

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#319]
Opening this issue to track planning for Katib in v0.5?

Do we want to define a minimal critical user journey (CUJ) for Katib and then create a backlog of issues to deliver it?

For me the priority would be enabling users to easily walk through doing a hyperparameter search using Katib. It would be great to get Katib integrated into one of our E2E examples such as

* mnist
* GitHub issue summarization
* object detection

/cc @johnugeorge @YujiOshima @gaocegege

**Comment by johnugeorge** [comment]
Currently, mnist example is already added in katib repo 
https://github.com/kubeflow/katib/pull/309

@jlewi  you mean, adding the same to the examples repository?

**Comment by jlewi** [comment]
@johnugeorge I think the example is a good start. However, I think the question is do we have a good E2E story for how users go from building a model to doing a hyperparameter search to identify the best model?

I think a big piece we are missing is a CUJ defining what the experience should look like. I think @richardsliu is going to start putting together an initial draft.

It looks like the instructions for Katib could probably use more work as well.
https://www.kubeflow.org/docs/guides/components/hyperparameter/

**Comment by johnugeorge** [comment]
@jlewi  Yes. I agree with you. E2E experience is not described well enough. I talked with @richardsliu and he is working on the CUJ . One the CUJ is out, we will fix all the missing pieces for a good E2E story.

**Comment by richardsliu** [comment]
CUJ: https://docs.google.com/presentation/d/1S_dqk84rKGQpRNRagqiqykMrdjGO3_uG7e5nrtzW6tM/edit#slide=id.g4b349cd762_0_151

**Comment by richardsliu** [comment]
Roadmap: https://github.com/kubeflow/katib/pull/348
Issues for 0.5: https://github.com/kubeflow/katib/issues?utf8=%E2%9C%93&q=+label%3Aarea%2F0.5.0+

For 0.5, I think the P0 goals should be:
- enhance the status fields
- enable running katib jobs in different namespaces

The P1 goal is to explore integration with fairing.

@johnugeorge @YujiOshima @gaocegege @hougangliu WDYT?

**Comment by YujiOshima** [comment]
@richardsliu Thanks, I agree with P0 goals.

> The P1 goal is to explore integration with fairing.

Does it mean integration with jupyter? pipeline? or both?

**Comment by jlewi** [comment]
@richardsliu @johnugeorge Can we file issues related to all the work we want to get done in 0.5 for this CUJ and label them for 0.5 (and ideally add a cuj/hp-tuning label)?

Once we do that I think we can close this issue out.

Looks like there are currently 9 issues tagged in the kanban board for 0.5.
https://github.com/orgs/kubeflow/projects/4

**Comment by richardsliu** [comment]
I added an area/cuj label and put a bunch of additional issues to the kanban board. Closing this issue for now.

**Comment by jlewi** [comment]
Renamed the label to [cuj/hp-tuning](https://github.com/kubeflow/katib/labels/cuj%2Fhp-tuning) to match other cuj labels.
