### ISSUE TITLE
[release] Ksonnet the katib

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#32]
> Please try to use ksonnet. We should try to be consistent about how we package things. We want to have a single registry for all our packages and deploy them in a consistent fashion.

**Comment by jlewi** [comment]
I added a guide to adding new ksonnet packages [here](https://github.com/kubeflow/kubeflow/blob/master/docs_dev/ksonnet_packages.md).

It should be straightforward assuming you have existing json/yaml K8s manifests.

**Comment by lluunn** [comment]
Has anyone started on this? If not, I can pick it up.
@YujiOshima @gaocegege

**Comment by gaocegege** [comment]
No, we both are not familiar with ksonnet, thanks for your help :tada:

**Comment by YujiOshima** [comment]
@lluunn Great! Thank you for your help!
