### ISSUE TITLE
Studyjob controller fails to resolve vizier-core's DNS name when running katib in custom namespace

### ISSUE THREAD

**Issue by xyhuang** [kubeflow/katib#323]
looks like this is caused by a hard-coded namespace:
https://github.com/kubeflow/katib/blob/bca0b58789845225b3127d9f555521ea100e3ebe/pkg/types.go#L4

**Comment by hougangliu** [comment]
now all katib components must be deployed in same namespace, and the namespace is now hard-code 
 by `kubeflow`. also katib manifests hard-code namespace by `kubeflow`.

@YujiOshima @richardsliu do you think we should remove the constraint?

**Comment by johnugeorge** [comment]
Katib manifests in this repo are just examples. User can install the manifests in any namespace. 

I had pointed out in an earlier comment 

https://github.com/kubeflow/katib/pull/302#discussion_r243148029

**Comment by hougangliu** [comment]
> Katib manifests in this repo are just examples. User can install the manifests in any namespace.
> 
> I had pointed out in an earlier comment
> 
> [#302 (comment)](https://github.com/kubeflow/katib/pull/302#discussion_r243148029)
> 
> You might have missed it

@johnugeorge sorry, I missed your comment.

Then I think we should make rule as below:
1. all Katib components must be deployed in same namespace.
2. since metric-collector (which may be deployed in another namespace, same with studyJob) also need call vizer-core api to get study, we can pass katib namespace to metric-collector to compose vizor-core service dns name.

@richardsliu @YujiOshima any comment?

**Comment by johnugeorge** [comment]
@hougangliu 

> > Katib manifests in this repo are just examples. User can install the manifests in any namespace.
> > I had pointed out in an earlier comment
> > [#302 (comment)](https://github.com/kubeflow/katib/pull/302#discussion_r243148029)
> > You might have missed it
> 
> @johnugeorge sorry, I missed your comment.
> 
> Then I think we should make rule as below:
> 
> 1. all Katib components must be deployed in same namespace.


If Katib is deployed via kubeflow package, all components are automatically deployed in the same namespace.  
 Also what is the use case for a situation where katib components are installed across multiple namespaces?  Do we really need to support it?

> 2. since metric-collector (which may be deployed in another namespace, same with studyJob) also need call vizer-core api to get study, we can pass katib namespace to metric-collector to compose vizor-core service dns name.

Namespace is already passed to metric-collector as a flag. 

> 
> @richardsliu @YujiOshima any comment?

**Comment by hougangliu** [comment]
for 2, what Namespace passed to metric-collector as a flag is metric-collector pod's namespace, not vizier-manager deployment's namespace
