### ISSUE TITLE
Delete StudyJob failed

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#325]
I tried to create my own image for StudyJob controller and deployed Katib in cluster. 
I submitted [random-example](https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml) to my deployment. After finishing this example I tried to delete studyjob and got this errors in logs of study-job-controller:
```
2019/01/15 14:49:14 DeleteStudy error rpc error: code = Unimplemented desc = unknown method DeleteStudy
2019/01/15 14:49:14 Fail to delete rpc error: code = Unimplemented desc = unknown method DeleteStudy
```

In that case I have only one way to delete StudyJobs:
```
kubectl patch studyjob/random-example -n $NAMESPACE -p '{"metadata": {"finalizers":[]}}' --type=merge
```

**Comment by johnugeorge** [comment]
@andreyvelich which vizier-core image are you using?. This api was added in https://github.com/kubeflow/katib/pull/315

**Comment by andreyvelich** [comment]
@johnugeorge gcr.io/kubeflow-images-public/katib/vizier-core:v0.4.0

**Comment by johnugeorge** [comment]
i am not sure if 0.4.0 has the api updated. Can you try using the latest image gcr.io/kubeflow-images-public/katib/vizier-core:v0.1.2-alpha-111-g0ed361c

**Comment by andreyvelich** [comment]
Thanks a lot, it helped!
