### ISSUE TITLE
[feature] Save temporary data of suggestions to DB.

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#33]
Currently, suggestions store the intermediate information in their memory.
It makes the services stateful.
We should make DB interface for suggestion services.

**Comment by jlewi** [comment]
@YujiOshima @gaocegege Should we try to fix this in 0.3.0? How important and how hard is it?

**Comment by YujiOshima** [comment]
It's already supported in random, gird, and hyperband. @libbyandhelen how about BO?

**Comment by jlewi** [comment]
Are we going to try to fix this in 0.4.0? Should we open up specific issues to track this for specific algorithms?

**Comment by johnugeorge** [comment]
Suggestion is a CR in v1alpha3 which has algorithm settings in Status. This is the latest settings provided in the GetSuggestions response.

**Comment by johnugeorge** [comment]
Closing the issue as it is fixed in v1alpha3
