### ISSUE TITLE
[feature] Use vitess instead of MySQL

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#34]
I think vitness is more appropriate than mysql since it is cloud native. https://github.com/vitessio/vitess

**Comment by jlewi** [comment]
Why not make the storage backend pluggable?

See this [comment](https://github.com/kubeflow/katib/pull/119#issuecomment-401562779)

See also #138 requesting a design doc.

**Comment by gaocegege** [comment]
/close

We will support multiple backends
