### ISSUE TITLE
Katib job and Katib services cannot be in different namespaces due to metrics collector service account

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#343]
just copy https://github.com/kubeflow/kubeflow/issues/2311 here to trace

**Comment by jlewi** [comment]
@johnugeorge @YujiOshima @richardsliu Are we planning on fixing this as part of 0.5 or should we move it to 0.6?

Is this P1 or P2?

**Comment by richardsliu** [comment]
Moved out of 0.5.

**Comment by gaocegege** [comment]
I think we still cannot solve it in 0.6

**Comment by johnugeorge** [comment]
Yes. There is no cleaner way to solve it using current metric collector design

**Comment by gaocegege** [comment]
Yeah, then we could put the issue in 0.7

**Comment by richardsliu** [comment]
Moved to 0.7.0.

**Comment by johnugeorge** [comment]
This issue is resolved with new metric collector implementation in v1alpha3

**Comment by johnugeorge** [comment]
Closing this issue as https://github.com/kubeflow/katib/pull/738 is merged.

Proposal: https://github.com/kubeflow/katib/pull/732
