### ISSUE TITLE
support worker/metricsCollector template from specified configmap + path

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#349]
For now, when specify worker and  metricsCollector by TemplatePath, this path must exist in kubeflow/configmaps/worker-template for worker and kubeflow/configmaps/metricscollector-template for metrics collector.

we should cover a use case: a user who can only create/update studyjob and configmap in  non-kubeflow namespace , but he wants to persist his worker/metricscollector template in configmap fo re-use (even more, he wants to persist worker/metricscollector of a studyjob in one configmap for better management, saying mnistStudyJobConfigmap, yoloStudyJobConfigmap and so on)

**Comment by hougangliu** [comment]
I plan refactor GoTemplate as below
```
type TemplatePath struct {
	ConfigMapName string `json:"configmapName,omitempty"`
	ConfigMapNamespace string `json:"configmapNamespace,omitempty"`
	TemplatePath string `json:"templatePath,omitempty"`
}

type GoTemplate struct {
	TemplateFromConfigmap TemplatePath `json:"templateFromConfigmap,omitempty"`
	RawTemplate  string `json:"rawTemplate,omitempty"`
}
```
@richardsliu @YujiOshima @gaocegege @johnugeorge  any comments?

**Comment by richardsliu** [comment]
Maybe call the field and type TemplateSpec instead of TemplateFromConfigmap/TemplatePath? Otherwise sounds ok to me.

**Comment by johnugeorge** [comment]
Closing this issue as fields are included in v1alpha2 API
/close
