### ISSUE TITLE
Katib status should return optimal parameters values

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#356]
Enhance Katib StudyJob status to have more info, e.g.
- Successful/Pending/Failed trials
- best hyper parameters till now
- etc.

Currently, output of “kubectl describe studyjob” gives very limited view of status. Looking at the output status, we can't really tell what is going on with the algorithm right now, how many iterations have passed. It would be interesting to see how far are we  from the "Optimization goal".

**Comment by jlewi** [comment]
Is this on track to land in 0.5 or should move it to 0.6?

**Comment by richardsliu** [comment]
We can close this one since the design for v1alpha2 API covers this. Implementation will be completed in 0.6.

/close
