### ISSUE TITLE
CI seems to be running on somewhere else than $CLUSTER_NAME

### ISSUE THREAD

**Issue by toshiiw** [kubeflow/katib#359]
test/scripts/unit-test.sh creates a mysql pod for testing. During #352 it was found to contain some older DB schema, resulting a failed unit test.
I created #357 to investigate the issue. As I changed the kubeconfig set up script to just use "gcloud container clusters get-credentials ${CLUSTER_NAME}", I got this error

```
Error from server (NotFound): error when creating "STDIN": namespaces "kubeflow-test-infra" not found  
```

I think the mysql pod used to run on the cluster where argo ran.

**Comment by toshiiw** [comment]
Just using the default namespace and also modifing run-test.sh seems to be the way to go.
Am I right?

**Comment by YujiOshima** [comment]
@richardsliu @jlewi do you have any ideas?

**Comment by richardsliu** [comment]
It is probably running under the kubeflow-testing cluster. I will look at your fix.

**Comment by toshiiw** [comment]
@richardsliu As I wrote in a comment in #360 , I'm having trouble getting a working kubeconfig.
The kubeconfig seems to lack a proper admin priviledge to create clusterrole things. Could you help?
