### ISSUE TITLE
unify name style of api/studyjob field whose type is array in v1alpha2 API version

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#371]
now we have some API/filed whose type is array, some of them are named with plural type and some are named with List-suffix (such as below). I think we should name them with same style in v1alpha2 API.

rpc GetStudyList(GetStudyListRequest) returns (GetStudyListReply)
rpc GetTrials(GetTrialsRequest) returns (GetTrialsReply)

type StudyJobStatus struct {
...
**Trials []TrialSet `json:"trials,omitempty"`**
...
}
type TrialSet struct {
TrialID string `json:"trialid,omitempty"`
**WorkerList []WorkerCondition `json:"workeridlist,omitempty"`**
}

**Comment by johnugeorge** [comment]
Closing this issue. Implementation is tracked in #370 

/close
