### ISSUE TITLE
need validate nasConfig

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#372]
Now for a studyjob, we never check if a nasConfig is valid or not.
#339 is nasrl suggestion service, which always expects graphConfig (numlayers, input size,outputsize) and operations field present. we need validate nasconfig filed before store studyjob info into db.

@andreyvelich WDYT?

**Comment by andreyvelich** [comment]
@hougangliu 
This is a good point! 
Do you think, we should check it in the controller step? 
For example, if something wrong with nasConfig structure, studyJob status should be Failed and controller should stop the job?

**Comment by johnugeorge** [comment]
See validateStudy  in https://github.com/kubeflow/katib/blob/f11c13e8c65a9236afe2878e5c915a1c769ad52b/pkg/controller/studyjob/katib_api_util.go#L28

**Comment by andreyvelich** [comment]
@johnugeorge 
Thats cool! 
Should I add a part there for the NAS job ?
