### ISSUE TITLE
Don't run full testing suite for docs/ changes

### ISSUE THREAD

**Issue by alexandraj777** [kubeflow/katib#374]
PR #369 added a few links to [docs/developer-guide.md](https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md), and was not expected to have any effects on katib code. However, a full test suite was required to pass before merging the PR. Due to repeated test failures, the suite needed to be run three times before passing.

Blocking docs changes on full test failures may discourage frequent and casual documentation updates. Is there a smaller / lighter test suite that can run for either `*.md` files, or the `README.md` + `docs/*.md` files?

**Comment by jlewi** [comment]
You can use include_dirs in the prow_config to only trigger an E2E test if files in certain directories are changed.
https://github.com/kubeflow/kubeflow/blob/master/prow_config.yaml#L24

**Comment by alexandraj777** [comment]
Excuse me for not knowing, but what is an E2E test? End-to-end?

**Comment by gaocegege** [comment]
@alexandraj777 Yeah, End to end.
