### ISSUE TITLE
Usability for datascientists

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#377]
@johnugeorge pointed https://github.com/kubeflow/katib/pull/375#issuecomment-463566604

>In general, I feel that we are moving away from the data scientist point of view, instead thinking from a kubernetes developer perspective. Currently, a data scientist will find it extremely difficult to write a katib study job config correctly without good kubernetes experience. For eg: Currently in the studyjob config, there is a namespace for overall studyjob, a namespace for the workerspec, namespace for ConfigMap, namespace for metric collector . Won't this be complicated for the users by exposing much details?

I agree that writing StudyJob CR is difficult for data scientists.
IMO, data scientist will use Katib from WebUI or Jupyter integration instead of writing complex yamls.
The API of StudyJob CRD is for k8s specialists who develop and manage an infra system for ML.
So it should be flexible and customizable for their environment.
On the other hand in WebUI, these complexities from k8s must be covered up.

So refining API, enrich UI, and more docs are important for Katib usability.

@richardsliu @hougangliu @gaocegege WDYT?

**Comment by gaocegege** [comment]
I agree with @YujiOshima , I think the design of API should be flexible and we can use UI to hide some details of the system, just like what tf-operator does.

**Comment by gaocegege** [comment]
/close

It is stale. But feel free to ask here.
