### ISSUE TITLE
Reintroduce vendoring

### ISSUE THREAD

**Issue by jayunit100** [kubeflow/katib#384]
# Why vendoring is critical

- Airgapped places and people building release candidates need all the dependencies, and cant rely on the internet (even if its available - see the next bullet
- In upstream kubernetes, we were burnt pretty bad with https://github.com/kubernetes/kubernetes/issues/65871 , so, as we move to more stable , independently runnable katib releases, we'll definetly want a hermetic build for the overall project.
- Convention: other CNCF projects vendor all dependencies 

Especially in the case of many AI companies ~ its pretty critical to be able to build a project without any external dependencies, and makes CI easier.  

cc @pdmack  @jlewi 

# Can we do it while still making PRs easy to review ?

Yes:
- Lets make a policy that any vendor changes will happen in a separate commit, that is quite easy to enforce, and can even be automatically enforced 
- i volunteer to add a check for this that confirms orthogonal commits if thats a gating factor to reintroduce vendoring.

**Comment by jlewi** [comment]
Are you proposing this just for Katib or more generally?

/cc @richardsliu @johnugeorge

**Comment by johnugeorge** [comment]
Yeah. we haven't followed consistent style across packages. eg: TF/Pytorch operators are vendored. But, MPI-operator, Katib are not vendored currently.

**Comment by richardsliu** [comment]
I agree, we should follow a consistent standard across our operators and introduce proper vendoring.

**Comment by andreyvelich** [comment]
What do you think about using `Go module`, instead of `go dep` ? 
Pipelines have already migrated on it: 
https://github.com/kubeflow/pipelines/pull/581

**Comment by richardsliu** [comment]
We are using go module in the common repo: https://github.com/kubeflow/common

The only requirement is moving to Golang 1.11 or above. I find it easier than vendoring.

**Comment by andreyvelich** [comment]
I think, we can switch to go module when v1alpha2 components will be merge. 
What do you think ?

**Comment by gaocegege** [comment]
SGTM, but I think we should come to an agreement at the community level.

**Comment by johnugeorge** [comment]
we can do it at a later point when all components are merged and before the current release in July.

**Comment by gaocegege** [comment]
/close

We have vendor now.
