### ISSUE TITLE
tolerate a worker fails

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#390]
now when a worker failed, we mark studyjob failed, too. But for some case, if we re-create another worker, everything may work well (for example, the worker is killed by eviction policy or node error, if the worker is scheduled to other node, everything can work). Maybe for a trial, when a worker failed, we can re-create another one until max-fail-time to mark  studyjob `Failed`. So in this case, multiple workers (max-fail-time at most) can belong to a trial.

**Comment by johnugeorge** [comment]
Doesn't this depend on the worker type? Eg: TF/Pytorch has restartPolicy field. If Onfailure is set, job is restarted when failure occurs. With backofflimit(https://github.com/kubeflow/tf-operator/issues/550), we should be able to limit the restart limit for a failing job.

**Comment by gaocegege** [comment]
@hougangliu Do you mean the trail worker or the worker in the distributed training jobs?

**Comment by hougangliu** [comment]
> @hougangliu Do you mean the trail worker or the worker in the distributed training jobs?
Yes,  but as @johnugeorge mentioned above, it seems we can handle it by setting backofflimit (or else) for the job
