### ISSUE TITLE
Store the checkpoint of suggestion in PVC

### ISSUE THREAD

**Issue by DeeperMind** [kubeflow/katib#395]
Currently the reinforcement learning suggestion stores the checkpoint inside the pod. In this way, however, all the job information will be lost if the suggestion pod is terminated unexpectedly. Therefore, it is more advisable to store the checkpoint in PVC. 

/assign @DeeperMind
/area nas

**Comment by johnugeorge** [comment]
There is suggestion CR which checkpoints the suggestion state.

**Comment by johnugeorge** [comment]
Closing the issue as the feature is already in v1alpha3
/close
