### ISSUE TITLE
[maintainnace] Invite more reviewers

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#40]
Now we have 0 reviewer, and it is not a good thing for an open source project.

**Comment by gaocegege** [comment]
@jose5918 @ddysher @DjangoPeng @mitake @AkihiroSuda @libbyandhelen  Would you please to be the reviewer of katib?

**Comment by ddysher** [comment]
sure :)

**Comment by jose5918** [comment]
Sure

**Comment by gaocegege** [comment]
@wbuchwalter 

We have a dashboard based on modeldb. Would you mind reviewing the frontend code for katib? Or do you have any candidate in the community who is familiar with js/css/html?
