### ISSUE TITLE
Help Wanted: Example code for StudyJob

### ISSUE THREAD

**Issue by opus111** [kubeflow/katib#403]
This is not a bug, but perhaps missing documentation

I want to use do basic HyperParameter optimization with Katib.  I did the tutorials, and read all the docs.  Unfortunately, the tutorials just load existing Docker images.  They do not explain how to implement your own StudyJob.

I could not find any example code that explains how a StudyJob interacts with Katib.  How does it get its parameters?  How does it report its results?  What is the contract?  I guess you would call this the StudyJob API

Any pointers to code or docs would be appreciated

Thank you
Peter

**Comment by johnugeorge** [comment]
Please follow the doc at https://www.kubeflow.org/docs/components/hyperparameter/

**Comment by johnugeorge** [comment]
One sample example that is using random algorithm: https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml

**Comment by opus111** [comment]
Thank you Johnu.  Yes, those are the documents I read, and the instructions I followed.  

Perhaps I am missing it, but nowhere in those docs are instructions for how to write your own StudyJob.  They show how to install Katib, and then run several pre-built examples.  It does not have any links to the code that created those examples, or documentation on how the code works.

There must be the equivalent of a StudyJob API which the Containers implement.  Where do I find that?

**Comment by opus111** [comment]
OK.  I found this...

https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md

In which is says this...

Implement new suggestion algorithm
Suggestion API is defined as GRPC service at API/api.proto. You can attach new algorithm easily.

    implement suggestion API

    make k8s service named vizier-suggestion-{ algorithm-name } and expose port 6789
    And to add new suggestion service, you don't need to stop components ( vizier-core, modeldb, and 
     anything) that are already running.

Unfortunately, there is no API/api.proto in the repository.

**Comment by YujiOshima** [comment]
@opus111 The `api.proto` is [this](https://github.com/kubeflow/katib/blob/master/pkg/api/api.proto)
Thank you for pointing it. We should fix `API/api.proto` to `pkg/api/api.proto`.
