### ISSUE TITLE
[feature] Add test code for each algorithms

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#42]
There is no test code for each suggestion and early stop algorithms.
We need to test the algorithms will work as expected.

**Comment by lluunn** [comment]
Does it mean adding unit test, like grid_service_test.go, in https://github.com/kubeflow/katib/tree/master/pkg/suggestion?

**Comment by jlewi** [comment]
Should we split this issue up into multiple issues?

**Comment by garganubhav** [comment]
@jlewi @YujiOshima is someone already doing this, or I should start working on this?

**Comment by YujiOshima** [comment]
@garganubhav Thanks. My colleague is working on random, grid, and hyperband. 
I'm so happy if you try to add tests to the Bayesian opt algorithm,

**Comment by jlewi** [comment]
@garganubhav @YujiOshima per my comment above can we file individual issues for adding tests for specific algorithms and assign them to individual owners?

**Comment by garganubhav** [comment]
@jlewi ok. I will file for Bayesian opt algorithm and work on it.

**Comment by jlewi** [comment]
@garganubhav any progress? Did you open up an issue for Bayesian optimization?

**Comment by garganubhav** [comment]
yes, working on it

**Comment by jlewi** [comment]
@garganubhav Any update on this? What is the remaining work? Do we have an estimate for when it will be completed?

**Comment by jlewi** [comment]
@garganubhav @johnugeorge @YujiOshima @gaocegege 

What's the current status of this issue?

It looks like there is #230 for a test for bayesian optimization. Can we close out this issue since that issue exists?

/cc @richardsliu

**Comment by jlewi** [comment]
@garganubhav @johnugeorge @YujiOshima @gaocegege  Ping?

**Comment by gaocegege** [comment]
We do not have sufficient test coverage for algos, IMO. And it is hard to import tools to show the coverage since we allow different languages to write suggestions.

**Comment by jdplatt** [comment]
Can we close this now #406 is merged?

**Comment by johnugeorge** [comment]
Closing this as #406 is merged.  Moving algorithms to Python is tracked in #407 

/close
