### ISSUE TITLE
gRpc API v2

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#423]
Now we merged v2 CRD API https://github.com/kubeflow/katib/pull/381
We need a new version of gRpc API which comples with the CRD.

**Comment by richardsliu** [comment]
Also need to create a new version of database schema.

**Comment by jlewi** [comment]
@richardsliu @YujiOshima @johnugeorge It looks like the PR is still in WIP. Since we are planning on cutting tomorrow I'm going to say this isn't going to make 0.5 so I'm moving it to 0.6.

**Comment by johnugeorge** [comment]
Closing this PR as GRPC PR is merged
/close
