### ISSUE TITLE
Checking failed Trials by Katib Controller

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#433]
Katib Controller can't check wether Trials were failed or not. 
In some cases Trials can be failed. It can be because of incorrect training container code or insufficient cluster resources. 
In that case, Controller just run GetSuggestion method again and Suggestion will have an empty results of the previous run if all Trials were failed. 
I think, if we have that situation, Controller should try to run Trials again. 
We can define a number, for example 5, to restart Trails run. 
If after 5 runs we will have an empty results, StudyJob should be failed.

Right now, in NAS we control that inside Suggestion, but it is not good, I think: 
https://github.com/kubeflow/katib/blob/master/pkg/suggestion/nasrl_service.py#L289

What do you think? 
@richardsliu @YujiOshima @hougangliu @johnugeorge

**Comment by YujiOshima** [comment]
It should be handled by Job (, TFJjob, and PytorchJob) operator.
For example, when you use a k8s Job, you can set `restartPolicy = "OnFailure"` and `backofflimit=5'. The Trial will be restart 5time. Then, its status would be `Failed` when all retry is failed.

**Comment by andreyvelich** [comment]
@YujiOshima If we setup right here https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml#L58 these params, Trials will restart for backofflimit times ?

**Comment by johnugeorge** [comment]
To be precise, each job has a backoffLimit. See https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy

In a similar manner, backOffLimit is proposed for custom job resources. See issue https://github.com/kubeflow/tf-operator/issues/550

**Comment by andreyvelich** [comment]
I have tried to setup `backofflimit` and `restartPolicy` inside `Random Example` here: https://github.com/kubeflow/katib/blob/master/examples/random-example.yaml#L43.
Training jobs stoped to spawn training pods after they reached backOffLimit times but StudyJob was still running. As well, job from MetricsCollector started to spawn pods to collect metrics and they were failed automatically. 
Probably, we should control that inside Controller or I did something wrong ? 
WDYT @johnugeorge @YujiOshima @hougangliu ?

**Comment by johnugeorge** [comment]
Individual jobs will report failed when `backOffLimit` number of retries are completed.  However, I don't think we are making StudyJob to be failed in such a case.  
We can think of adding `MaxFailedTrials` to indicate maximum number fo failed trials in a StudyJob. Once it is reached,  Studyjob is marked as failed. 
@richardsliu

**Comment by andreyvelich** [comment]
Is it possible to access `backOffLimit` from Controller somewhere?

**Comment by YujiOshima** [comment]
I agree with @johnugeorge. Studyjob should tolerate failed in individual jobs.
`MaxFailedTrials` or `FailedTrialsLimit` would be useful.

@andreyvelich The controller can get a spec of individual jobs and the backOffLimit is included in the spec.

**Comment by johnugeorge** [comment]
@andreyvelich Btw, why do you need `backOffLimit` from controllers?

**Comment by andreyvelich** [comment]
@johnugeorge I just need to access to `backOffLimit` of the Workers job. After that, we can check inside Controller wether it reached `MaxFailedTrials` or not.

**Comment by johnugeorge** [comment]
To avoid confusion, I will refer to trial instead of worker job(as in v1alpha2)

@andreyvelich `backOffLimit` in the TrialTemplate(https://github.com/kubeflow/katib/blob/master/pkg/api/operators/apis/experiment/v1alpha2/types.go#L187) defines the number of retries before a single Trial is marked as failed.  However, proposed `MaxFailedTrials` defines the max number of failed Trials(limit) in a StudyJob. When limit is reached,  trial will be marked as failed.  Both ideas are different.

**Comment by andreyvelich** [comment]
@johnugeorge We don't have `MaxFailedTrials` here: https://github.com/kubeflow/katib/blob/master/pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go. 
Should we do something in v1alpha1 to handle this?

**Comment by johnugeorge** [comment]
@andreyvelich I think, we can fix it in v1alpha2 directly.

**Comment by johnugeorge** [comment]
Added to v1alpha2: https://github.com/kubeflow/katib/blob/master/pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go#L45

@andreyvelich  close this PR?

**Comment by andreyvelich** [comment]
Yes, now it is fine!
