### ISSUE TITLE
studyjob-controller  ImagePullBackOff 

### ISSUE THREAD

**Issue by Niuxiaotong** [kubeflow/katib#439]
[root@k8s-master ~]# kubectl get pod -n kubeflow
NAME                                                      READY   STATUS             RESTARTS   AGE
ambassador-784d4d757-9764g                                1/1     Running            0          8h
ambassador-784d4d757-mbqwj                                1/1     Running            0          8h
ambassador-784d4d757-ph9v7                                1/1     Running            0          8h
argo-ui-76df9b9f98-kfwrp                                  1/1     Running            0          8h
centraldashboard-ddccf7bdb-8fjdj                          1/1     Running            0          8h
jupyter-0                                                 1/1     Running            0          8h
katib-ui-d9db794c9-zq6l8                                  1/1     Running            0          8h
metacontroller-0                                          1/1     Running            0          8h
minio-555568f9b9-qjvg4                                    1/1     Running            0          141m
ml-pipeline-544f888747-bgg9d                              0/1     ImagePullBackOff   0          112m
ml-pipeline-persistenceagent-794b44fb8d-d95jv             0/1     ImagePullBackOff   0          111m
ml-pipeline-scheduledworkflow-6774b894-zvwlx              0/1     ImagePullBackOff   0          110m
ml-pipeline-ui-75cf85bb5d-shggc                           0/1     ImagePullBackOff   0          108m
mysql-657f87857d-j4z42                                    1/1     Running            0          4h34m
pytorch-operator-f59d6d8c7-qxt2p                          1/1     Running            0          8h
spartakus-volunteer-78dcfbbb9f-fpq5w                      1/1     Running            0          8h
studyjob-controller-565c864549-gl7jh                      0/1     ImagePullBackOff   0          11m
tf-job-dashboard-68dd966b86-w9dzn                         1/1     Running            0          8h
tf-job-operator-v1beta1-7f896477dd-99666                  1/1     Running            0          8h
vizier-core-58bccb7b49-wc6gg                              1/1     Running            84         4h48m
vizier-core-rest-54f6c5d58c-gdh8t                         1/1     Running            0          4h51m
vizier-db-68f977d674-tvkzd                                1/1     Running            0          4h33m
vizier-suggestion-bayesianoptimization-69559668bf-7hrjr   1/1     Running            0          8h
vizier-suggestion-grid-66cc87575-2s8hv                    1/1     Running            0          8h
vizier-suggestion-hyperband-65fdc45887-85knv              1/1     Running            0          8h
vizier-suggestion-random-6fdb94957-qrptp                  1/1     Running            0          8h
workflow-controller-5b8d97cc6-2h5wj                       1/1     Running            0          8h

Events:
  Type     Reason     Age                   From                 Message
  ----     ------     ----                  ----                 -------
  Normal   Scheduled  23m                   default-scheduler    Successfully assigned kubeflow/studyjob-controller-565c864549-gl7jh to k8s-master
  Normal   Pulling    21m (x4 over 23m)     kubelet, k8s-master  pulling image "gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0"
  Warning  Failed     21m (x4 over 23m)     kubelet, k8s-master  Failed to pull image "gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0": rpc error: code = Unknown desc = Error 
response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)  Warning  Failed     21m (x4 over 23m)     kubelet, k8s-master  Error: ErrImagePull
  Warning  Failed     20m (x6 over 23m)     kubelet, k8s-master  Error: ImagePullBackOff
  Normal   BackOff    3m42s (x78 over 23m)  kubelet, k8s-master  Back-off pulling image "gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0"
---
docker images 
gcr.io/kubeflow-images-public/katib/studyjob-controller               v0.4.0                         63d4250ec85e
---
kubeamd-1.12.1 kubelet-1.12.1 
Any help is appreciated!

**Comment by Niuxiaotong** [comment]
20190328:
change studyjobcontroller.libsonnet imagePullPoilcy :IfNotPresent
docker images
gcr.io/kubeflow-images-public/katib/studyjob-controller v0.4.0 63d4250ec85e
appear similar erro:
kubectl describe pod studyjob-controller-565c864549-2nf6w -n kubeflow

  Normal   Pulling         73s (x2 over 2m24s)   kubelet, k8s-master  pulling image "gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0"
  Warning  Failed          9s (x2 over 84s)      kubelet, k8s-master  Failed to pull image "gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0": rpc error: code = Unknown desc = E
rror response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)  
Warning  Failed          9s (x2 over 84s)      kubelet, k8s-master  Error: ErrImagePull

**Comment by gaocegege** [comment]
Hi

Sorry for the late reply. It seems that you cannot access gcr.io/kubeflow-images-public/katib/studyjob-controller:v0.4.0. Maybe you can try if you could pull other images in gcr.io (gcr.io is banned in China.)

**Comment by hougangliu** [comment]
@richardsliu @jlewi 
do we have any plan to publish kubeflow released images in docker hub? AFAIK, a lot of kubeflow early adopters in China encounter the same gcr.io reject problem.

**Comment by gaocegege** [comment]
/close

It is stale. But feel free to ask here.
