### ISSUE TITLE
[v1alpha2] Data store interface

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#440]
Implementation of the new abstract data store interface.

PR: https://github.com/kubeflow/katib/pull/431

**Comment by richardsliu** [comment]
@mpvartak @achalshant Are you still interested in taking on this item for the v1alpha2 release?

**Comment by jlewi** [comment]
@mpvartak @achalshant any update?

**Comment by johnugeorge** [comment]
PR: #498

**Comment by mpvartak** [comment]
@achalshant recently started a new role and not sure he has bandwidth to
take this on at the moment.

We are also fully booked on the Verta side unfortunately. We should have
more cycles in June if that works // happy to review PRs in the interim.

**Comment by richardsliu** [comment]
@achalshant @mpvartak 
Johnu and I should have some free cycles to take on this item. If you don't have the bandwidth then we can patch the PR and merge it. Let us know if you are ok with this.

**Comment by mpvartak** [comment]
Sounds good, thanks!

**Comment by johnugeorge** [comment]
Thanks for the update

**Comment by gaocegege** [comment]
Will we solve it in 0.6?

**Comment by johnugeorge** [comment]
do we need this in 0.6? Else, we can push it to the next release since we don't have any other backends for now.

**Comment by gaocegege** [comment]
Agree with @johnugeorge

**Comment by gaocegege** [comment]
@johnugeorge @hougangliu 

Do we still need it? I think we can close it since we only store metrics in DB now

**Comment by hougangliu** [comment]
in fact, #760 had implemented it. I think we can close it now
