### ISSUE TITLE
[v1alpha2] Controller implementation

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#441]

**Comment by gaocegege** [comment]
@johnugeorge Are you working on this issue?

**Comment by johnugeorge** [comment]
Yes. I will add the initial implementation once #448 is merged.

**Comment by richardsliu** [comment]
@johnugeorge Can we break this item up into smaller issues? So community members can work on this together.

**Comment by gaocegege** [comment]
Agree. Or could you please open a WIP PR then we can review it earlier.

**Comment by johnugeorge** [comment]
Sure. I was waiting for #435 to get merged as GetSuggestions needs to be implemented first. Also, few  GRPC apis also need to be implemented and @YujiOshima is working on it. 
I will anyways raise my current changes in 1-2 days.

**Comment by richardsliu** [comment]
@YujiOshima Do you have a PR for the gRPC changes?

**Comment by YujiOshima** [comment]
I'm working on it. I will open PR this week.

**Comment by jlewi** [comment]
@richardsliu @johnugeorge @YujiOshima How's this coming?

**Comment by johnugeorge** [comment]
@jlewi  #457 is in the final review. It should be merged in 1-2 days
