### ISSUE TITLE
[v1alpha2] Metrics collection

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#442]

**Comment by richardsliu** [comment]
@YujiOshima @johnugeorge @gaocegege 
Per our discussion last week, until the metadata store is ready, the least costly solution would be to keep metrics collection as-is (i.e. using cron jobs). We will migrate to the new push model when the metadata APIs are ready.

**Comment by jlewi** [comment]
@johnugeorge  @richardsliu Could you provide an update for this issue please?

**Comment by johnugeorge** [comment]
@jlewi This is done. 
/close
