### ISSUE TITLE
how to save the files of the best trial

### ISSUE THREAD

**Issue by WestonLu** [kubeflow/katib#459]
may i ask, how can i save my files of the best trial?  For example, at each trial, i save a tf model or keras model，but when the job is done, how can i get the model file of the best trial? Thank you.

**Comment by hougangliu** [comment]
import file in https://github.com/kubeflow/katib/tree/master/pkg/api/v1alpha1/python and then call below method to get best trial for a studyjob_instance

def get_best_trial(studyjob_instace):
    trial_id = studyjob_instace["status"]["bestTrialId"]
    if not (studyjob_instace and studyjob_instace.status and studyjob_instace.status. bestTrialId):
        return None
    vizier_core = "vizier-core.kubeflow:6789"
    with grpc.insecure_channel(vizier_core) as channel:
        stub = api_pb2_grpc.ManagerStub(channel)
        response = stub.GetTrial(api_pb2.GetTrialRequest(trial_id=trial_id))
        return response.trial

**Comment by WestonLu** [comment]
thank you
