### ISSUE TITLE
error to list *v1beta1.TFJob

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#462]
I follow the ‘Getting Started’，however, the tfexpamle  studyjob is failed, the log in the studyjob-controller is "github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.TFJob: the server could not find the requested resource (get tfjobs.kubeflow.org)". I didn't figure where goes wrong

**Comment by gaocegege** [comment]
Did you register the CRD of TFJob v1beta1?

**Comment by wukong1992** [comment]
sorry, I configure wrong, I configure the v1beta2.
