### ISSUE TITLE
[question] What happened if we do not watch TFJob and PyTorchJob

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#487]
I found that we do not watch TFJob and PyTorchJob in trial v1alpha2 implementation. Then I am wondering how to sync the TFJob/PyTorchJob status to trial status. For example, if the TFJob is failed, the controller does not get the event from apiserver, then the trial controller cannot update the trial status.

Is there anything I misunderstand? I'd appreciate it if someone could help me, thanks.

/cc @richardsliu @johnugeorge

**Comment by johnugeorge** [comment]
@gaocegege Implementation of default batch job is only added currently. I am adding support for custom operators in a separate PR soon

**Comment by gaocegege** [comment]
Gotcha, thanks.
