### ISSUE TITLE
remove db dependency in katib CR reconcile main workflow

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#497]
katib CR (now experiment and trial) reconcile main workflow should remove db-write operation, a new controller need to be added to handle experiment and trial related info persistence in DB.

**Comment by gaocegege** [comment]
Thanks for the issue. Really looking forward to it.

**Comment by gaocegege** [comment]
Currently, We decided to use a backup controller, which watches experiments and trials, then does DB write requests.

**Comment by hougangliu** [comment]
Per discuss with team,  we will implement this feature after release 0.6

**Comment by johnugeorge** [comment]
DB dependency is removed from the main workflow in v1alpha3 with the new Suggestion CR implementation

**Comment by johnugeorge** [comment]
Closing this issue as https://github.com/kubeflow/katib/pull/742 is merged
