### ISSUE TITLE
Use klog for katib

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/katib#506]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Use the permanent forked version of glog for kubernetes instead of log.

ref:
kubernetes/kubernetes#70264
https://github.com/kubernetes/klog/blob/master/README.md

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

/cc @hougangliu @richardsliu @gaocegege

**Comment by gaocegege** [comment]
I think we are using it now, with the help of kube-builder.

**Comment by hougangliu** [comment]
https://github.com/kubeflow/katib/issues/112 traced log solution

**Comment by gyliu513** [comment]
@gaocegege The `klog` was not used by katib but using `log`. Now all of the kubernetes projects are migrating to `klog`, I think katib should also move this way?

**Comment by hougangliu** [comment]
#388 also traces it, we can keep one about log solution

**Comment by gyliu513** [comment]
@YujiOshima @richardsliu look forward to more comments from you as well.

**Comment by hougangliu** [comment]
I think `klog` is good solution for me

**Comment by YujiOshima** [comment]
SGTM. klog is the standard logging in k8s ecosystem and developed actively.

**Comment by johnugeorge** [comment]
@gyliu513 Katib v1alpha2 version uses log solution that is provided by controller-runtime and it is not the standard `log` package..  It is a flexible package where users can configure their own logger.   See the current usage:  https://github.com/kubeflow/katib/blob/master/cmd/katib-controller/v1alpha2/main.go#L35 configures zap logger 

It can support Klog also.  https://github.com/kubernetes-sigs/controller-runtime/issues/291  

Since we are using controller-runtime library for implementation, I feel that we should use the log package provided by controller-runtime and configure the logger(instead of using klog directly)

**Comment by gyliu513** [comment]
@johnugeorge I actually want to use `klog` instead of using `klog` in `controller-runtime`, using `klog` directly can always enable us to upgrade as we want to leverage the latest feature in klog. Comments?

**Comment by johnugeorge** [comment]
Sorry. I didn't understand. Why can't `klog` be upgraded in the latter case?  Can you please explain the difference between both? 

Another side effect is that logs in controller-runtime will get hidden(including error logs) if the log library is not initialized.  https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L41

**Comment by gyliu513** [comment]
> Sorry. I didn't understand. Why can't klog be upgraded in the latter case? Can you please explain the difference between both?

@johnugeorge If I want to upgrade `klog`, do I need to upgrade `controller-runtime`? Let me check more detail for how does federation v2 works https://github.com/kubernetes-sigs/federation-v2/pull/857

**Comment by johnugeorge** [comment]
No. You don't need to upgrade controller-runtime. Klog will be an external dependency.

**Comment by gyliu513** [comment]
@johnugeorge  I see, so we do not need to add `klog` to `Gopkg.toml` but depending on `klog` in `controller-runtime` is good enough. Comments?

**Comment by gyliu513** [comment]
There is an issue for klog at https://github.com/kubernetes/klog/issues/22 , the klog cannot handle the case of some sort with a predefined set of variables which are used as suffix for each log line. 

Will hold on for some files in katib like https://github.com/kubeflow/katib/blob/master/pkg/controller/v1alpha2/experiment/experiment_util.go#L24 etc.

**Comment by gaocegege** [comment]
I think it may affect us deeply. We rely on this feature in many files.

**Comment by gyliu513** [comment]
@gaocegege I will check how we can workaround for this, but meantime, can we avoid try to using child logger for future new added files?

**Comment by gaocegege** [comment]
I have no objection on it, LGTM
