### ISSUE TITLE
Redesign Suggestion service design

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#507]
Proposal is to make new Suggestion CR  to serve suggestion requests from the experiment controller. Currently, experiment controller directly talks to suggestion service and gets suggestions. 

In the new design,
Experiment controller creates Suggestion CR for each experiment to get suggestion results.Suggestion controller picks it up and talks to right algorithm service(as currently) and updates the Suggestion CR status with suggestion results and state. Experiment controller reads the suggestion results from CR and creates trials.

With new Suggestion CR and controller implementation,
1. It is more K8s native as DB dependency is avoided
2. It can take care of long running experiments. Suggestion CR is created per experiment by the experiment controller.
3. State or algorithm settings(key-value pair) will be stored in the CR instead of external DB.  Suggestion controller can thus send just the required information to each algorithm service.

/assign
/cc @gaocegege @richardsliu @hougangliu  @YujiOshima 

/kind feature

Related: #463 #471 #500

**Comment by gaocegege** [comment]
According to the experiment, I found that we can support grid search with the new design. We can get all grids each time and calculate which grids will be used according to the numbers of succeeded trials. The idea is inspired by advisor here: https://github.com/tobegit3hub/advisor/blob/master/advisor_server/suggestion/algorithm/grid_search.py#L65

**Comment by johnugeorge** [comment]
Draft of the Suggestion CRD: 
  The main idea is that we keep the state of the suggestions(per experiment) as CR without any external dependency.  

```
type SuggestionSpec struct {

//Name of the algorithm 
AlgorithmName string

// Number of suggestions requested
 RequestCount int  

//Algorithm settings set by the user in the experiment config
AlgorithmSettings []AlgorithmSetting

}

type AlgorithmSetting struct {
	Name  string 
	Value string
}

type SuggestionStatus struct {
   // Suggestion results
  Assignments [] ParameterAssignment
   
  Conditions []SuggestionCondition
  // include all common fields
   
}

type ParameterAssignment struct {
	Name  string 
	Value string
}

type Suggestion struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SuggestionSpec   `json:"spec,omitempty"`
	Status SuggestionStatus `json:"status,omitempty"`
}

```
Once an experiment is created, Experiment controller during its reconcile creates a Suggestion CR. The SuggestionCR is deleted only when experiment is deleted. Hence it is possible to resume the experiment as the state is maintained in the CR. 
When SuggestionCR is initialized by SuggestionController(during reconcile),  SetupSuggestion API is first called on the AlgorithmService for that experiment.  This api can be used by the AlgorithmService to initialize any state if needed for the experiment.  However, this call can be invoked multiple times due to k8s reconcile pattern.   Similarly before deletion of SuggestionCR, DestroySuggestion API is called on the AlgorithmService for that experiment. This api can be used by the AlgorithmService to clear any state if needed. 

When SuggestionCR is in running state, SuggestionController during reconcile  looks at the request count,  calls GetSuggestions and ensures that len(Assignments) == RequestCount in spec.

**Comment by johnugeorge** [comment]
Questions:
1. Can all suggestions work only with final metrics of Trials?
2. How to handle update algorithm settings from experiment config?
3. How to handle update algorithm settings from suggestion algorithm? do we need it?

**Comment by gaocegege** [comment]
As for the first question, I looked through all the algorithms in advisor and katib. I think the final metrics is the only thing that a suggestion needs.

**Comment by gaocegege** [comment]
As for the second question, if we make the suggestion stateless, we can safely update the suggestion service, and make maxUnavailable 0. Then it will be rolling updated.

**Comment by gaocegege** [comment]
As for the third question, I think we should not support the feature. If the suggestion needs some backend to persist state. We should use pvc to do it. We should not support such a feature because it is not a good practice, IMO.

**Comment by gaocegege** [comment]
> In fact, for suggestion CRD solution. I think trial owerreference should include both experiment and suggestion. I think suggestion controller should monitor trial so that when trial completed, fill back its final metrics to suggestion CR so that suggestion algorithm service can use previous suggestion CR to make new suggestion

From @hougangliu

**Comment by hougangliu** [comment]
> 1. Can all suggestions work only with final metrics of Trials?

for now, we only call new suggestion create API when previous trials (final metrics filled in), so I think at least for now,  all suggestions can work only with final metrics of Trials

> 2. How to handle update algorithm settings from experiment config?
> 3. How to handle update algorithm settings from suggestion algorithm? do we need it?

at first, we need it in some algorithms, for example hyperband, it need store some intermediate value about the algorithm.
I think suggestion CR should store the algorithm settings each time after a suggestion algorithm service call (if suggestion algorithm service need update algorithm settings, it should not update it in DB, but return new algorithm settings along with assignment, suggestion controller should store both assignment and new algorithm settings in suggestion CR, and when call new Suggestion API to suggestion service, suggestion controller can pass history assignment/final metrics, latest algorithm settings to  suggestion algorithm service as argument)

**Comment by gaocegege** [comment]
Now we only have the first question.

> How to handle update algorithm settings from experiment config?

We support it via suggestion CRD.

> How to handle update algorithm settings from suggestion algorithm? do we need it?

We do not need it. For these suggestions, we will introduce a DB to store the state. (mainly NAS algorithms)

**Comment by johnugeorge** [comment]
Related doc: #726

**Comment by gaocegege** [comment]
Supported Algorithms with the new design:

- random search(katib, hyperopt)
- hyperband(katib)
- TPE(hyperopt)
- bayesian optimization(skopt)

**Comment by johnugeorge** [comment]
New suggestion CR is introduced in https://github.com/kubeflow/katib/pull/740

**Comment by johnugeorge** [comment]
Closing this PR as controller is merged in https://github.com/kubeflow/katib/pull/742
