### ISSUE TITLE
Create kustomize packages for v1alpha2 version

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#513]
/kind feature

**Comment by jlewi** [comment]
Here's the manifest
https://github.com/kubeflow/manifests/blob/91c22388f5d1d9bf0f337185dcb36aca5c0f5ee8/katib/base/studyjob-crd.yaml#L7

It looks like it is still referring to v1alpha1.

Are there other changes that need to be made?

**Comment by jlewi** [comment]
Is anyone planning on picking this up?

**Comment by johnugeorge** [comment]
@jlewi https://github.com/kubeflow/manifests/pull/112
