### ISSUE TITLE
Add e2e tests for v1alpha2

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#514]

**Comment by jlewi** [comment]
@richardsliu @johnugeorge Any update on this? Is anyone planning on picking this up?

**Comment by johnugeorge** [comment]
we have some basic tests  added in https://github.com/kubeflow/katib/blob/master/test/e2e/v1alpha2/test-katib-manager.py 

 we can also add one entire experiment run in the presubmit

**Comment by richardsliu** [comment]
@johnugeorge This is done right?

**Comment by johnugeorge** [comment]
Yes. Closing this as #652  is merged
