### ISSUE TITLE
[bug] Fail to run unit test for v1alpha2 in kubenetes 1.12+

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#515]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

Ref https://github.com/kubernetes-sigs/controller-runtime/issues/318

We cannot run the test with kubernetes 1.12+

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by johnugeorge** [comment]
Unit tests are consisently passing now

**Comment by johnugeorge** [comment]
Closing the issue as it is no more valid
