### ISSUE TITLE
make katib-db configurable

### ISSUE THREAD

**Issue by naseemkullah** [kubeflow/katib#533]
https://github.com/kubeflow/katib/blob/3cbb5654042cf73b164685a0cf6f2f30e6286c8b/pkg/db/v1alpha2/interface.go#L21

Please make `katib-db:3306` configurable with  os.Getenv("MYSQL_HOST") and os.Getenv("MYSQL_PORT")

**Comment by gaocegege** [comment]
We expected that katib mysql is running in k8s, thus we use katib-db directly. But we should make it configurable. I agree.

**Comment by naseemkullah** [comment]
Thanks. I am working on a [helm chart](https://github.com/helm/charts/pull/13454) now, and it is not guaranteed that the name of the service will be `katib-db` for the helm release. In fact it probably won't be. This would really help!!

**Comment by gaocegege** [comment]
@naseemkullah Oh I really love helm chart! Do you have a deadline for it? We will release a new version at the end of this month maybe.

**Comment by naseemkullah** [comment]
Thanks! :) :)
Also want to shoutout @dodizzle who has been helping out.

I think I can have it ready soon, need some fixes in code change, mostly parameterizations for MYSQLs and such!

**Comment by gaocegege** [comment]
@naseemkullah @dodizzle Thanks for your work!

Are you packaging v1alpha1 or v1alpha2 for katib?

**Comment by naseemkullah** [comment]
I was confused about that actually.

https://github.com/kubeflow/katib/tree/master/manifests

Which should be ported?

So far we have the following workloads (please ignore helm generated prefix)
```
lumbering-pika-katib-core                               ClusterIP   10.63.254.111   <none>        6789/TCP            27m
lumbering-pika-katib-core-rest                          ClusterIP   10.63.252.99    <none>        80/TCP              27m
lumbering-pika-katib-studyjob-controller                ClusterIP   10.63.248.7     <none>        443/TCP             27m
lumbering-pika-katib-suggestion-bayesian-optimization   ClusterIP   10.63.242.172   <none>        6789/TCP            27m
lumbering-pika-katib-suggestion-grid                    ClusterIP   10.63.243.182   <none>        6789/TCP            27m
lumbering-pika-katib-suggestion-hyperband               ClusterIP   10.63.251.238   <none>        6789/TCP            27m
lumbering-pika-katib-suggestion-random                  ClusterIP   10.63.242.185   <none>        6789/TCP            27m
lumbering-pika-katib-ui                                 ClusterIP   10.63.252.249   <none>        80/TCP              27m
```

**Comment by naseemkullah** [comment]
I was confused about that actually. Never used kubeflow, really approaching this from Ops perspective.

https://github.com/kubeflow/katib/tree/master/manifests

Which should be ported?

So far we have the following workloads (please ignore helm generated prefix)

lumbering-pika-katib-core
lumbering-pika-katib-core-rest
lumbering-pika-katib-studyjob-controller
lumbering-pika-katib-suggestion-bayesian-optimization
lumbering-pika-katib-suggestion-grid
lumbering-pika-katib-suggestion-hyperband
lumbering-pika-katib-suggestion-random
lumbering-pika-katib-ui

**Comment by gaocegege** [comment]
Now we are working on v1alpha2. Thus we recommend doing it after v1alpha2 is released.

If you want to run v1alpha1, you should install all the components in manifests/v1alpha1

**Comment by gaocegege** [comment]
```
lumbering-pika-katib-core
lumbering-pika-katib-core-rest
lumbering-pika-katib-studyjob-controller
lumbering-pika-katib-suggestion-bayesian-optimization
lumbering-pika-katib-suggestion-grid
lumbering-pika-katib-suggestion-hyperband
lumbering-pika-katib-suggestion-random
lumbering-pika-katib-ui
```

Here missed a DB

**Comment by naseemkullah** [comment]
yes we have deployed with the helm mysql chart, as a dependency: https://github.com/helm/charts/blob/d87d8c7b7f4a374e39f152d3a9334ffc3d80c437/incubator/kubeflow/charts/katib/requirements.yaml
it generated `lumbering-pika-mysql` service...

Also created a temp service `katib-db` to bypass lack of configuration:
https://github.com/helm/charts/blob/d87d8c7b7f4a374e39f152d3a9334ffc3d80c437/incubator/kubeflow/charts/katib/templates/temporary-mysql-service.yaml

**Comment by gaocegege** [comment]
Then I think it should work. If the url is configurable.

**Comment by naseemkullah** [comment]
bump
