### ISSUE TITLE
ignore Retain field

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#565]
in experiment.spec.trialTemplate and experiment.spec.metricsCollectorSpec, `Retain` filed is defined, which is used to delete worker job and metricCollecoter job when trial completed, but now we ignore the field when create new trial( Trial struct has no counterpart field of  the two kind of `Retain`)

should we drop `Retain` in experiment and always delete worker job and metricCollecoter job when trial completed? or add two new field in trial.spec?

/cc @richardsliu @gaocegege @johnugeorge @YujiOshima which one do you prefer?

**Comment by gaocegege** [comment]
I have a question may not be related to the issue. How to support the case that the users want to create new trials for the completed experiment? Do we plan to support it? Ref https://github.com/kubeflow/katib/issues/346

**Comment by johnugeorge** [comment]
I think, `Retain` is not needed now.  `RetainHistoricalData` serves the same purpose from the experiment level. Right?

**Comment by hougangliu** [comment]
> I have a question may not be related to the issue. How to support the case that the users want to create new trials for the completed experiment? Do we plan to support it? Ref #346

We need discuss it more in next meeting or in #346. Anyway, I think the feature may be not included in release 0.6

**Comment by johnugeorge** [comment]
> I have a question may not be related to the issue. How to support the case that the users want to create new trials for the completed experiment? Do we plan to support it? Ref #346

Other k8s objects follow the same convention right?  eg: K8s Job
