### ISSUE TITLE
Add undeploy.sh to delete katib

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/katib#578]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
We only have a `deploy.sh` at https://github.com/kubeflow/katib/blob/master/scripts/v1alpha2/deploy.sh but no scripts to delete, it is better add a file to delete the katib to facilitate development process.

/cc @hougangliu @gaocegege @richardsliu 

/assign

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gaocegege** [comment]
SGTM
