### ISSUE TITLE
Fine grained docker image build

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/katib#580]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

We are now using https://github.com/kubeflow/katib/blob/master/scripts/v1alpha2/build.sh to build all of the katib images at one time, it is better to update makefile by introducing fine grained docker image build. Like I can use `make katib-controller` to build katib controller etc, this can facilitate the development process, as I do not need to build all images every-time.

/cc @hougangliu @gaocegege @richardsliu

**Comment by gaocegege** [comment]
SGTM

**Comment by gaocegege** [comment]
@gyliu513 Can you help us on the issue?
