### ISSUE TITLE
[feature] NASRL in v1alpha2

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#583]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Support NASRL in v1alpha2

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
/assign

Will make changes for v1alpha2.

**Comment by gaocegege** [comment]
Thank you @andreyvelich

**Comment by gaocegege** [comment]
Can we close the issue after #614 is merged?

**Comment by andreyvelich** [comment]
Yea.
/close
