### ISSUE TITLE
[feature][0.6] Upgrade pytorchjob and tfjob from v1beta1 to v1

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#589]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We do not have v1beta1 anymore, thus I think we should upgrade it to v1.

WDYT @richardsliu @johnugeorge @hougangliu 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by johnugeorge** [comment]
I feel that we can upgrade it to v1 version closer to 0.6 release when all fixes are in.
