### ISSUE TITLE
Name of the Trial from Suggestion

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#610]
Right now, in v1alpha2, we generate name of the Trial here: https://github.com/kubeflow/katib/blob/master/pkg/controller/v1alpha2/experiment/experiment_util.go#L27 with experiment name + random string of 8 symbols.

In `GetSuggestionsReply` we can return the name of the Trial: https://github.com/kubeflow/katib/blob/master/pkg/api/v1alpha2/api.proto#L525.

I think, we should provide functionality, when user can specify special name to create Trial. 
In that case, from the Controller, we can assign random name for the Trial, if Trial doesn't have a name or name from the `GetSuggestionReply`. 

What do you think @gaocegege @hougangliu @johnugeorge @richardsliu ?

/kind feature

**Comment by gaocegege** [comment]
SGTM

**Comment by johnugeorge** [comment]
This is no more needed as suggestion service gets the list of trials in each GetSuggestions call

**Comment by johnugeorge** [comment]
Closing the issue
