### ISSUE TITLE
Clean Trial pods when Experiment is deleted

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#611]
My experiment spawns Trial and that Trial was failed. I tried to delete this Experiment, but my Trial pod was not deleted. Do we need to add additional finalizers here: https://github.com/kubeflow/katib/blob/master/pkg/controller/v1alpha2/experiment/experiment_util.go#L95 for Trial pods ? 
/cc @johnugeorge @hougangliu @gaocegege 
/kind bug

**Comment by gaocegege** [comment]
Maybe related to https://github.com/kubeflow/katib/issues/597.

**Comment by andreyvelich** [comment]
@gaocegege You are right, the same issue. We can close it.
/close
