### ISSUE TITLE
Handle failed Trials in v1alpha2

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/katib#612]
Right now, if all Trials were failed, in any case, we will run `GetSuggestions` and `GetObservationLog` will return 0. For example, if GPU resources not available, Trials won't run.
Do we need to handle failed trails in the controller before running `GetSuggestions` again? 

In NAS RL Suggestion, if the results from previous run return 0, we spawn failed Trails again. You can find logic here: https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1alpha1/nasrl_service.py#L282. 
I think, it is not a good solution for this situation.

What do you think @johnugeorge @gaocegege @richardsliu @hougangliu ?

**Comment by gaocegege** [comment]
I think we should implement MaxFailedTrialCount. Now we missed the implementation.

**Comment by johnugeorge** [comment]
it is already implemented: https://github.com/kubeflow/katib/blob/master/pkg/controller/v1alpha2/experiment/util/status_util.go#L157

**Comment by gaocegege** [comment]
Then I think the current design works for me.

**Comment by andreyvelich** [comment]
However, do we need to run `GetSuggestions` again, if we spawn 3 Trial and all of them were failed. 
In that case, e.g, `MaxFailedTrialCount` = 12.

**Comment by gaocegege** [comment]
What can we do to avoid the problem?

**Comment by johnugeorge** [comment]
@andreyvelich  Isn't this behavior correct? Can you explain more?

**Comment by andreyvelich** [comment]
@gaocegege We can restart Trials from the controller, for example, if we don't have any observation log from them.

 @johnugeorge It depends on the approach that we want to follow in Katib. I am not sure that it is correct to run `GetSuggestions` from the controller, if we don't have any results from the previous run.
