### ISSUE TITLE
UI: Autogenerate yaml previews

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#639]
On the experiment creationg page, the changes I made in the Parameters tab are not reflected when I switch to "YAML", and vice versa.

We should allow the user to preview the generated yaml if possible.

**Comment by gaocegege** [comment]
Do not think we can implement it before 0.7

I have no idea about how to implement it.

**Comment by andreyvelich** [comment]
That was implemented in: https://github.com/kubeflow/katib/pull/1427.
