### ISSUE TITLE
Experiment summary page enhancements

### ISSUE THREAD

**Issue by richardsliu** [kubeflow/katib#642]
The experiment summary page should support:
- Sorting on column names
- Exporting as csv
- Changing how many results to display per page
- Should be able to get the original YAML file from this page

**Comment by wronk** [comment]
@richardsliu, is there a workaround for exporting the csv? You mentioned one [here](https://github.com/kubeflow/katib/issues/248), but I don't see how to do it

**Comment by bwassie** [comment]
/reopen

I think it would be really nice to have an export to CSV feature. I run many TFJob experiments with many workers and end up spawning tons of pods. I delete my experiments to get rid of the underlying pods/declutter and saving my results before doing that is not super easy.

I'm currently doing this using a [table capture](https://chrome.google.com/webstore/detail/table-capture/iebpjdmgckacbodjpijphcplhebcmeop?hl=en) chrome extension but it would be nice if I could just do it from the Katib UI directly.

**Comment by andreyvelich** [comment]
Thank you for your feedback @bwassie!
Since this issue includes other items also, please can you create separate issue to track the export CSV feature in the Katib UI?
