### ISSUE TITLE
Need to add namespace to katib, cluster level scope is not necessary

### ISSUE THREAD

**Issue by wuyinzhenjun** [kubeflow/katib#668]
/kind bug

**What steps did you take and what happened:**
try to launch katib to a ns limit k8s, seems ns should be set for controller and clusterRole change to Role also works 

**What did you expect to happen:**
add ns, remove cluster level scope

**Comment by hougangliu** [comment]
@wuyinzhenjun can you detail more about what this issue is about? Have no idea about what `add namespace to katib` mean
Thanks
