### ISSUE TITLE
While running PytorchStudyJob with larger requestNumber getting "rpc error" for few random workerid pods

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#674]
/kind bug

**What steps did you take and what happened:**
While running PytorchStudyJob with larger requestNumber getting "rpc error" for few random workerid pods. In the study-job ..yaml file I mention requestNumber=256 to create more number of jobs. as a result I am seeing the error.
```
2019/07/03 05:17:20 Study ID: y9a61220d5733a42, Trial ID: bf2824d43515111b, Worker ID: x8cba42216c05340, Worker Kind: PyTorchJob
2019/07/03 05:17:40 Failed to GetStudyConf: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"
```

**Environment:**

- Kubeflow version: 0.5.1
- Kubernetes version: (use `kubectl version`): 1.14.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

Thanks.

**Comment by gaocegege** [comment]
V1alpha1 is deprecated now, please try v1alpha3 in 0.7 release
