### ISSUE TITLE
HELP WANTED: bayesian optimization

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#676]
I would like to use the Bayesian optimizer algorithm.
I ran the file bayseopt-example.yaml like random-example.yaml in v1alpha1.
`kubectl apply -f bayseopt-example.yaml`

But when I enter kubectl -n kubeflow get studyjob, it fails.
Like this, 
```
NAME               CONDITION   AGE
bayseopt-example   Failed      5m53s
```

And these are logs.
```
2019/07/07 11:57:09 Adding finalizer clean-studyjob-data
2019/07/07 11:57:09 Start to Validate Suggestion Parameters
2019/07/07 11:57:09 Suggestion Parameters are valid
2019/07/07 11:57:09 Create Study bayseopt-example
2019/07/07 11:57:09 Study ID w4f47537575c2907
2019/07/07 11:57:09 Study ID w4f47537575c2907 StudyConf name:"bayseopt-example" owner:"crd" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.03" min:"0.01" > > configs:<name:"--num-layers" parameter_type:INT feasible:<max:"4" min:"1" > > configs:<name:"--optimizer" parameter_type:CATEGORICAL feasible:<list:"sgd" list:"adam" list:"ftrl" > > > objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" jobId:"596eb0de-a0ae-11e9-96b4-080027178de6" job_type:"HP" 
2019/07/07 11:57:09 Study: w4f47537575c2907 Suggestion Spec &{bayesianoptimization [{burn_in 5}] 3}
2019/07/07 11:57:09 Study: w4f47537575c2907 setSuggesitonParameterReply param_id:"k24e01a9a2b7d37c" 
2019/07/07 11:57:09 Start to Validate Suggestion Parameters
2019/07/07 11:57:09 Suggestion Parameters are valid
2019/07/07 11:57:09 Create Study bayseopt-example
2019/07/07 11:57:09 CreateStudy Error rpc error: code = Unknown desc = Study bayseopt-example in Job 596eb0de-a0ae-11e9-96b4-080027178de6 already exist.
2019/07/07 11:57:09 Fail to initialize rpc error: code = Unknown desc = Study bayseopt-example in Job 596eb0de-a0ae-11e9-96b4-080027178de6 already exist.
2019/07/07 11:57:10 Study: w4f47537575c2907 GetSuggestion Error rpc error: code = Unknown desc = Exception calling application: y cannot be None
2019/07/07 11:57:10 Fail to check status rpc error: code = Unknown desc = Exception calling application: y cannot be None
```

How can I use bayseopt-example.yaml?
Should I install something else?

+
I tried to "hypb-example.yaml" but it is not ran.
error is

`Error from server: error when creating "hypb-example.yaml": admission webhook "validating.studyjob.kubeflow.org" denied the request: No worker template name cpuWorkerTemplate.yaml`

How do I use this algorithm?

Please help me!
/cc @hougangliu @andreyvelich @johnugeorge

**Comment by hougangliu** [comment]
@warf34 how do you install katib, and if you install katib by install kubeflow, which version of kubeflow do you install? it says there is no "cpuWorkerTemplate.yaml" in worker-template configmap of kubeflow namespace.

**Comment by warf34** [comment]
> @warf34 how do you install katib, and if you install katib by install kubeflow, which version of kubeflow do you install? it says there is no "cpuWorkerTemplate.yaml" in worker-template configmap of kubeflow namespace.

I have used "Minikube" and kubectl version is 1.14 and i installed "katib" this way
`wget https://github.com/kubeflow/katib/archive/master.zip`
i ran "deploy.sh" in "katib-master\examples\v1alpha1\MinikubeDemo"

And do you know how bayesian solves?

**Comment by hougangliu** [comment]
add below into `worker-template` configmap of kubeflow namespace, and try again.
```
          "cpuWorkerTemplate.yaml": |
            apiVersion: batch/v1
            kind: Job
            metadata:
              name: {{.WorkerID}}
              namespace: kubeflow
            spec:
              template:
                spec:
                  containers:
                  - name: {{.WorkerID}}
                    image: katib/mxnet-mnist-example
                    command:
                    - "python"
                    - "/mxnet/example/image-classification/train_mnist.py"
                    - "--batch-size=64"
                    {{- with .HyperParameters}}
                    {{- range .}}
                    - "{{.Name}}={{.Value}}"
                    {{- end}}
                    {{- end}}
                  restartPolicy: Never
```

**Comment by warf34** [comment]
> add below into `worker-template` configmap of kubeflow namespace, and try again.
oh... I have worked in "Minikube" like this "Simple Minikube Demo"
https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/README.md
so i could not find "worker-template" in my desktop
is it impossible in "Minikube"?

**Comment by warf34** [comment]
> add below into `worker-template` configmap of kubeflow namespace, and try again.
> 
> ```
>           "cpuWorkerTemplate.yaml": |
>             apiVersion: batch/v1
>             kind: Job
>             metadata:
>               name: {{.WorkerID}}
>               namespace: kubeflow
>             spec:
>               template:
>                 spec:
>                   containers:
>                   - name: {{.WorkerID}}
>                     image: katib/mxnet-mnist-example
>                     command:
>                     - "python"
>                     - "/mxnet/example/image-classification/train_mnist.py"
>                     - "--batch-size=64"
>                     {{- with .HyperParameters}}
>                     {{- range .}}
>                     - "{{.Name}}={{.Value}}"
>                     {{- end}}
>                     {{- end}}
>                   restartPolicy: Never
> ```

add below into worker-template configmap of kubeflow namespace, and try again.
oh... I have worked in "Minikube" like this "Simple Minikube Demo"
https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/README.md
so i could not find "worker-template" in my desktop
is it impossible in "Minikube"?

**Comment by hougangliu** [comment]
kubectl edit configmap worker-template -n kubeflow

**Comment by warf34** [comment]
> kubectl edit configmap worker-template -n kubeflow

hmm... Do you know how to solve  bayesian optimization problem?
If you know this solution, please tell me.

**Comment by hougangliu** [comment]
sorry to make you confused, I mean:
use `kubectl edit configmap worker-template -n kubeflow` to add `cpuWorkerTemplate.yaml` as above content into  worker-template, then you can try `kubectl apply -f bayseopt-example.yaml`

**Comment by bandi900811** [comment]
I can see the same issue with kubeflow 5.1 (installed with kfctl)

**Comment by warf34** [comment]
> sorry to make you confused, I mean:
> use `kubectl edit configmap worker-template -n kubeflow` to add `cpuWorkerTemplate.yaml` as above content into worker-template, then you can try `kubectl apply -f bayseopt-example.yaml`

I really appreciate your kind reply.
but, I did not understand it right.
I want to know how to use both "bayesian" and "hyperband".

this is bayesian optimization error
```
2019/07/07 11:57:09 Adding finalizer clean-studyjob-data
2019/07/07 11:57:09 Start to Validate Suggestion Parameters
2019/07/07 11:57:09 Suggestion Parameters are valid
2019/07/07 11:57:09 Create Study bayseopt-example
2019/07/07 11:57:09 Study ID w4f47537575c2907
2019/07/07 11:57:09 Study ID w4f47537575c2907 StudyConf name:"bayseopt-example" owner:"crd" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.03" min:"0.01" > > configs:<name:"--num-layers" parameter_type:INT feasible:<max:"4" min:"1" > > configs:<name:"--optimizer" parameter_type:CATEGORICAL feasible:<list:"sgd" list:"adam" list:"ftrl" > > > objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" jobId:"596eb0de-a0ae-11e9-96b4-080027178de6" job_type:"HP" 
2019/07/07 11:57:09 Study: w4f47537575c2907 Suggestion Spec &{bayesianoptimization [{burn_in 5}] 3}
2019/07/07 11:57:09 Study: w4f47537575c2907 setSuggesitonParameterReply param_id:"k24e01a9a2b7d37c" 
2019/07/07 11:57:09 Start to Validate Suggestion Parameters
2019/07/07 11:57:09 Suggestion Parameters are valid
2019/07/07 11:57:09 Create Study bayseopt-example
2019/07/07 11:57:09 CreateStudy Error rpc error: code = Unknown desc = Study bayseopt-example in Job 596eb0de-a0ae-11e9-96b4-080027178de6 already exist.
2019/07/07 11:57:09 Fail to initialize rpc error: code = Unknown desc = Study bayseopt-example in Job 596eb0de-a0ae-11e9-96b4-080027178de6 already exist.
2019/07/07 11:57:10 Study: w4f47537575c2907 GetSuggestion Error rpc error: code = Unknown desc = Exception calling application: y cannot be None
2019/07/07 11:57:10 Fail to check status rpc error: code = Unknown desc = Exception calling application: y cannot be None
```

and this is hyperband optimization error
`Error from server: error when creating "hypb-example.yaml": admission webhook "validating.studyjob.kubeflow.org" denied the request: No worker template name cpuWorkerTemplate.yaml`

First. Is cpuWorkerTemplate modification a solution of "bayesian optimization"?

Second. 
When I enter `kubectl edit configmap worker-template -n kubeflow`
this file name is changed like this
```
/tmp/kubectl-edit-ybyse.yaml
/tmp/kubectl-edit-wm2n3.yaml
etc...
```
This is the original content.
```
apiVersion: v1
data:
  defaultWorkerTemplate.yaml: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{.WorkerID}}
      namespace: {{.NameSpace}}
    spec:
      template:
        spec:
          containers:
          - name: {{.WorkerID}}
            image: alpine
          restartPolicy: Never
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"defaultWorkerTemplate.yaml":"apiVersion: batch/v1\nkind: Job\nmetadata:\n  name: {{.WorkerID}}\n  namespace: {{.NameSpace}}\nspec:\n  template:\n    spec:\n      containers:\n      - name: {{.WorkerID}}\n        image: alpine\n      restartPolicy: Never"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"worker-template","namespace":"kubeflow"}}
  creationTimestamp: "2019-07-09T16:42:28Z"
  name: worker-template
  namespace: kubeflow
  resourceVersion: "764"
  selfLink: /api/v1/namespaces/kubeflow/configmaps/worker-template
  uid: 89e7673c-a268-11e9-80e9-080027ce876e
```
and I modified like this
```
apiVersion: v1
data:
  "cpuWorkerTemplate.yaml": |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{.WorkerID}}
      namespace: {{.NameSpace}}
    spec:
      template:
        spec:
          containers:
          - name: {{.WorkerID}}
            image: katib/mxnet-mnist-example
            command:
            - "python"
            - "/mxnet/example/image-classification/train_mnist.py"
            - "--batch-size=64"
            {{- with .HyperParameters}}
            {{- range .}}
            - "{{.Name}}={{.Value}}"
            {{- end}}
            {{- end}}
          restartPolicy: Never
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"cpuWorkerTemplate.yaml":"apiVersion: batch/v1\nkind: Job\nmetadata:\n  name: {{.WorkerID}}\$
  creationTimestamp: "2019-07-09T16:42:28Z"
  name: worker-template
  namespace: kubeflow
  resourceVersion: "764"
  selfLink: /api/v1/namespaces/kubeflow/configmaps/worker-template
  uid: 89e7673c-a268-11e9-80e9-080027ce876e
```
Did I correct it correctly?

**Comment by hougangliu** [comment]
I think you did right
for bayseopt-example case, I think your env uses old data somehow(maybe you delete your kubelfow, with old studyjob info persisted, and when you reinstall a new one, DB uses old PV), you can delete bayseopt-example studyjob and rename it to another name such as "bayseopt-example-1"
For hyperband case, it says "cpuWorkerTemplate.yaml not in worker-template" (but you did add it), so I wonder how you can trigger this error, especially bayseopt-example has no such error while they use same cpuWorkerTemplate.yaml), it really doesn't make sense for me.

**Comment by warf34** [comment]
> I think you did right
> for bayseopt-example case, I think your env uses old data somehow(maybe you delete your kubelfow, with old studyjob info persisted, and when you reinstall a new one, DB uses old PV), you can delete bayseopt-example studyjob and rename it to another name such as "bayseopt-example-1"
> For hyperband case, it says "cpuWorkerTemplate.yaml not in worker-template" (but you did add it), so I wonder how you can trigger this error, especially bayseopt-example has no such error while they use same cpuWorkerTemplate.yaml), it really doesn't make sense for me.

well... i need how to use bayesian optimization more than hyperband optimization 
therefore i ask a question about bayesian first.

I reinstall kubectl, minikube, and redownload this zip file 
`https://github.com/kubeflow/katib/archive/master.zip`
(kubectl version: 1.15.0, minikube version: 1.2.0)

next, i ran deploy in katib-master/examples/v1alpha1/MinikubeDemo
and "bayseopt-example.yaml" like this "kubectl apply -f bayseopt-example.yaml"

but it still showed error as below
```
2019/07/10 06:25:20 Adding finalizer clean-studyjob-data
2019/07/10 06:25:20 Start to Validate Suggestion Parameters
2019/07/10 06:25:20 Suggestion Parameters are valid
2019/07/10 06:25:20 Create Study random-example
2019/07/10 06:25:20 Study ID x953d6b74d3d1ee2
2019/07/10 06:25:20 Study ID x953d6b74d3d1ee2 StudyConf name:"random-example" owner:"crd" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.03" min:"0.01" > > configs:<name:"--num-layers" parameter_type:INT feasible:<max:"4" min:"1" > > configs:<name:"--optimizer" parameter_type:CATEGORICAL feasible:<list:"sgd" list:"adam" list:"ftrl" > > > objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" jobId:"777f7270-fa16-40e2-bef4-dea27a347064" job_type:"HP" 
2019/07/10 06:25:20 Study: x953d6b74d3d1ee2 Suggestion Spec &{bayesianoptimization [{burn_in 5}] 3}
2019/07/10 06:25:20 Study: x953d6b74d3d1ee2 setSuggesitonParameterReply param_id:"qc16e5a40a084b37" 
2019/07/10 06:25:20 Start to Validate Suggestion Parameters
2019/07/10 06:25:20 Suggestion Parameters are valid
2019/07/10 06:25:20 Create Study random-example
2019/07/10 06:25:20 CreateStudy Error rpc error: code = Unknown desc = Study random-example in Job 777f7270-fa16-40e2-bef4-dea27a347064 already exist.
2019/07/10 06:25:20 Fail to initialize rpc error: code = Unknown desc = Study random-example in Job 777f7270-fa16-40e2-bef4-dea27a347064 already exist.
2019/07/10 06:25:21 Study: x953d6b74d3d1ee2 GetSuggestion Error rpc error: code = Unknown desc = Exception calling application: y cannot be None
2019/07/10 06:25:21 Fail to check status rpc error: code = Unknown desc = Exception calling application: y cannot be None
```
and when i renamed studyjob to "bay", this error is showed
```
2019/07/10 06:30:42 Adding finalizer clean-studyjob-data
2019/07/10 06:30:42 Start to Validate Suggestion Parameters
2019/07/10 06:30:42 Suggestion Parameters are valid
2019/07/10 06:30:42 Create Study bay
2019/07/10 06:30:42 Study ID m14bc29dda2a5598
2019/07/10 06:30:42 Study ID m14bc29dda2a5598 StudyConf name:"bay" owner:"crd" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.03" min:"0.01" > > configs:<name:"--num-layers" parameter_type:INT feasible:<max:"4" min:"1" > > configs:<name:"--optimizer" parameter_type:CATEGORICAL feasible:<list:"sgd" list:"adam" list:"ftrl" > > > objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" jobId:"035bd202-5df4-4a3f-8dd8-436aa60539c6" job_type:"HP" 
2019/07/10 06:30:42 Study: m14bc29dda2a5598 Suggestion Spec &{bayesianoptimization [{burn_in 5}] 3}
2019/07/10 06:30:42 Study: m14bc29dda2a5598 setSuggesitonParameterReply param_id:"t31cb18b9a8e9489" 
2019/07/10 06:30:42 Study: m14bc29dda2a5598 GetSuggestion Error rpc error: code = Unknown desc = Exception calling application: y cannot be None
2019/07/10 06:30:42 Fail to check status rpc error: code = Unknown desc = Exception calling application: y cannot be None
```
I am wondering why this error occurs even after reinstalling.
I think my env don't use old data. because i have reinstalled now!
Is this bayesian optimization not run in Simple Minikube Demo?

**Comment by warf34** [comment]
> I can see the same issue with kubeflow 5.1 (installed with kfctl), worker-template is already configured (hypb-example.yaml is running). bayseopt-example.yaml throws the same error :
> 
> ```
> 2019/07/09 09:59:50 Fail to initialize rpc error: code = Unknown desc = Study random-example-bayseopt-2 in Job 4aa278e2-a230-11e9-91f6-588a5ae9d6ca already exist.
> 2019/07/09 09:59:51 Study: vb0f442fa046c3b2 GetSuggestion Error rpc error: code = Unknown desc = Exception calling application: y cannot be None
> 2019/07/09 09:59:51 Fail to check status rpc error: code = Unknown desc = Exception calling application: y cannot be None```
> ```

Could you let me know if you found a solution?

**Comment by hougangliu** [comment]
sorry that I doesn't notice you followed https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/README.md to deploy katib, the doc is actually out of date, we will fix it soon about how to install katib individually instead of a component of kubeflow

**Comment by warf34** [comment]
I think there are many mathods to install katib and kubeflow.
Is there a recommended method to install katib and kubeflow?

**Comment by warf34** [comment]
> sorry that I doesn't notice you followed https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/README.md to deploy katib, the doc is actually out of date, we will fix it soon about how to install katib individually instead of a component of kubeflow

I think there are many mathods to install katib and kubeflow.
Is there a recommended method?

**Comment by warf34** [comment]
> sorry that I doesn't notice you followed https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/README.md to deploy katib, the doc is actually out of date, we will fix it soon about how to install katib individually instead of a component of kubeflow

I think there are other mathods to install katib and kubeflow.
Is there a recommended method?

**Comment by hougangliu** [comment]
we think you can install kubeflow (kabit will be installed by default, too) as [here](https://www.kubeflow.org/docs/started/getting-started/), all images are released.

**Comment by warf34** [comment]
> we think you can install kubeflow (kabit will be installed by default, too) as [here](https://www.kubeflow.org/docs/started/getting-started/), all images are released.

I installed "MiniKF", and I successfully ran "random-example".
However, it was failed to run bayesian optimization.
Why can't I run it? Is 'Generated StudyJob YAML' wrong?

I created StudyJob in `http://10.10.10.10:8080/_/katib-dashboard`
This is my StudyJob YAML.
```
apiVersion: kubeflow.org/v1alpha1
kind: StudyJob
metadata:
  namespace: kubeflow
  labels:
    controller-tools.k8s.io: '1.0'
  name: bayesian-example
spec:
  studyName: bayesian-example
  owner: crd
  optimizationtype: maximize
  objectivevaluename: Validation-accuracy
  optimizationgoal: 0.99
  metricsnames:
    - accuracy
  parameterconfigs:
    - name: '--lr'
      parametertype: double
      feasible:
        max: '0.03'
        min: '0.01'
    - name: '--num-layers'
      parametertype: int
      feasible:
        max: '5'
        min: '2'
    - name: '--optimizer'
      parametertype: categorical
      feasible:
        list:
          - sgd
          - adam
          - ftrl
  requestcount: 10
  suggestionSpec:
    suggestionAlgorithm: bayesianoptimization
    requestNumber: 3
    suggestionParameters:
      - name: burn_in
        value: '5'
  workerspec:
    goTemplate:
      templatePath: cpuWorkerTemplate.yaml
  metricscollectorspec:
    goTemplate:
      templatePath: defaultMetricsCollectorTemplate.yaml
```

**Comment by hougangliu** [comment]
@warf34 maybe you'd better try v1alpha2 katib including running bayesian optimization. refer to https://github.com/hougangliu/katib/tree/add-example-doc-v1alpha2/examples/v1alpha2 about the tutorials.

**Comment by warf34** [comment]
> @warf34 maybe you'd better try v1alpha2 katib including running bayesian optimization. refer to https://github.com/hougangliu/katib/tree/add-example-doc-v1alpha2/examples/v1alpha2 about the tutorials.

Thanks for your kind reply.
If you don't mind, can you tell me [how to use tensorflow-gpu?](https://github.com/kubeflow/katib/issues/705)
I tried katib(v1alpha2) in minikube with tensorflow-gpu. but it was failed.

**Comment by johnugeorge** [comment]
what do you mean by it failed?

**Comment by warf34** [comment]
> what do you mean by it failed? Can you post error logs?

If i entered command "kubectl get po -n kubeflow", it show like below
```
NAME                                                    READY   STATUS    RESTARTS   AGE
katib-controller-7f985d6cd6-jwcfk                       1/1     Running   1          49m
katib-db-b48df7777-t7g5b                                1/1     Running   0          49m
katib-manager-7946dd5984-gvpqp                          1/1     Running   0          49m
katib-manager-rest-647f694b7d-vfp45                     1/1     Running   0          49m
katib-suggestion-bayesianoptimization-94c87dd64-lfhct   1/1     Running   0          49m
katib-suggestion-grid-58d9dfb5fd-wrlhc                  1/1     Running   0          48m
katib-suggestion-hyperband-778bb768c8-gmfgz             1/1     Running   0          48m
katib-suggestion-nasrl-d84fbb8f4-pdwmx                  1/1     Running   0          48m
katib-suggestion-random-7f96c4d77b-5jd68                1/1     Running   0          49m
katib-ui-6cf97db464-8zrkh                               1/1     Running   0          48m
random-mnist-gpu-psgqx427-z985z                         0/1     Pending   0          5m23s
random-mnist-gpu-rl6ds9d6-gn72t                         0/1     Pending   0          5m23s
random-mnist-gpu-v6w4rk67-78gqm                         0/1     Pending   0          5m23s
```

logs are below
```
{"level":"error","ts":1564650302.02284,"logger":"experiment-controller","caller":"experiment/experiment_controller.go:250","msg":"Create experiment in DB error","Experiment":"kubeflow/random-mnist-gpu","error":"rpc error: code = Unknown desc = Error 1062: Duplicate entry 'random-mnist-gpu' for key 'name'","stacktrace":"github.com/kubeflow/katib/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/katib/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/katib/pkg/controller/v1alpha2/experiment.(*ReconcileExperiment).Reconcile\n\t/go/src/github.com/kubeflow/katib/pkg/controller/v1alpha2/experiment/experiment_controller.go:250\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:207\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1564650302.0230024,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"experiment-controller","Request":"kubeflow/random-mnist-gpu","error":"rpc error: code = Unknown desc = Error 1062: Duplicate entry 'random-mnist-gpu' for key 'name'","stacktrace":"github.com/kubeflow/katib/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kubeflow/katib/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/kubeflow/katib/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kubeflow/katib/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1564650303.0239356,"logger":"experiment-controller","caller":"experiment/experiment_controller.go:347","msg":"CreateTrials","Experiment":"kubeflow/random-mnist-gpu","addCount":3}
{"level":"info","ts":1564650303.1141796,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.1142302,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-rl6ds9d6"}
{"level":"info","ts":1564650303.1142774,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-v6w4rk67"}
...
{"level":"info","ts":1564650303.3270493,"logger":"trial-controller","caller":"trial/trial_controller.go:262","msg":"Creating Job","Trial":"kubeflow/random-mnist-gpu-psgqx427","kind":"Job","name":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.3643112,"logger":"trial-controller","caller":"trial/trial_controller.go:340","msg":"Creating Metrics Collector","Trial":"kubeflow/random-mnist-gpu-psgqx427","name":"random-mnist-gpu-psgqx427","namespace":"kubeflow"}
{"level":"info","ts":1564650303.4092865,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-psgqx427"}
{"level":"info","ts":1564650303.409339,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-rl6ds9d6"}
{"level":"info","ts":1564650303.4093537,"logger":"experiment-status-util","caller":"util/status_util.go:72","msg":"Objective metric name not found","trial":"random-mnist-gpu-v6w4rk67"}
```

**Comment by johnugeorge** [comment]
Can you check the events of pod to see why it is pending?
` kubectl describe pod random-mnist-gpu-psgqx427-z985z `

**Comment by warf34** [comment]
Thank you for your response.
I will close this issue and continue with the issues below.
[GPU](https://github.com/kubeflow/katib/issues/705)
[CPU](https://github.com/kubeflow/katib/issues/712)
