### ISSUE TITLE
I need your help please, How to use bayesian optimization?

### ISSUE THREAD

**Issue by radics93** [kubeflow/katib#679]
Hello, I want to use "bayesian optimization".
i ran it in "katib-master\examples\v1alpha1\MinikubeDemo" but it failed.
my error like this #676 
why this error is thrown?
how to use bayesian optimization?

**Comment by johnugeorge** [comment]
how did you deploy katib? which version?

**Comment by radics93** [comment]
> how did you deploy katib? which version?

I downloaded this zip file in this github and unzip.
next, i entered like this
`bash katib-master/examples/v1alpha1/MinikubeDemo/deploy.sh`

i reinstalled just now, my kubectl is 1.15 version, minikube is 1.2.0

**Comment by johnugeorge** [comment]
Closing this issue as bayesian example works well in the CI tests

https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/bayesianoptimization-example.yaml
