### ISSUE TITLE
distributed suggestion service

### ISSUE THREAD

**Issue by ddysher** [kubeflow/katib#68]
suggestion service is inherently stateful, we want to make sure a study is processed by a single suggestion service instance.  For example, in current setup, if we run 2 replicas of grid service, they will both receive requests, thus essentially suggesting the same parameters twice.

The simplest solution would be to change the service affinity to 'ClientIP' in kubernetes.  However, in the long run, we need to have proper handling in our suggestion services themselves as well, to handle potential failure cases.

/cc @YujiOshima @gaocegege

**Comment by ddysher** [comment]
saving all trials to db sounds like a good first step, but once we can support large number of trials per study, and large number of studies, we might need to do more optimizations
> The solution I can come up with now is save all info of trial to DB and any suggestion instance can get info from DB.

**Comment by jlewi** [comment]
@ddysher @YujiOshima @gaocegege Is there specific work related to this issue for 0.3? If so what is the priority?

**Comment by gaocegege** [comment]
It is similar to #33 at the beginning, thus we do not need to add it into 0.3

**Comment by YujiOshima** [comment]
I think we can solve this by solving #33 . But we need a test.
I agree we do not need to add this into 0.3. This is a little advanced.

**Comment by gaocegege** [comment]
Now we keep one suggestion for one experiment. But we still need #33 .

/close
