### ISSUE TITLE
build-ui for v1alpha2 fail

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#699]
build-ui for v1alpha2 in Katib CI is always likely to fail somehow, but it can succeed if we trigger it many times.
@andreyvelich can you please take a look?

**Comment by johnugeorge** [comment]
@andreyvelich is unavailable for a week or two. Can you paste the error?

**Comment by hougangliu** [comment]
the build stopped during docker build, but each time it may fail in different step. katib-ui build takes some time, so I wonder if there is timeout of argo step to cause this error

**Comment by johnugeorge** [comment]
There is chance for it. may be resource limitation too

**Comment by andreyvelich** [comment]
@hougangliu Sorry for the long reply. 
Is it still failing in PreSubmit? In that case, we can remove npm build script from Dockerfile and manually npm build every time, when we change Katib UI.

**Comment by hougangliu** [comment]
@andreyvelich I had disabled the katib-ui build (katib-ui build nearly always fails), need your help to fix it. thanks

**Comment by johnugeorge** [comment]
UI is enabled again. Currently, we are not seeing any problems.

**Comment by johnugeorge** [comment]
Closing the issue for now.
