### ISSUE TITLE
v1alpha2 does not show any data immediately after starting a katib experiment in the HP monitor UI.

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#704]
v1alpha2 does not show any data immediately after starting a katib experiment. We can only see the the experiment entry in the HP monitor. If I click on experiment, It's empty. should I wait till the experiment done?

But v1alpha1 shows the all the trials lists immediately in the UI, once you start a studyjob. 

- Kubeflow version: 0.6.1
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

Thanks.

**Comment by jlewi** [comment]
I'm not seeing any data in the Katib Monitoring UI even though I have experiments running.

```
kubectl get experiments
NAME                        STATUS    AGE
tune-191002-081855   Running   7m
```
![katib](https://user-images.githubusercontent.com/777219/66029238-7f18ca00-e531-11e9-973b-d974990ddbdf.png)

I'm using Kubeflow 0.6..2

I've been working on adding HPTuning to the xgboost_synthetic example and you should be able to use that to repo this.
https://github.com/jlewi/examples/commit/621f5252407cbb19881119afc0319d163786e878

**Comment by johnugeorge** [comment]
Currently, UI doesn't show trials till metrics are reported for at least one trial.  Till then, UI doesn't show any data.

**Comment by gaocegege** [comment]
@jlewi Do you see the experiment in the UI?

Maybe like this.

![Screenshot from 2019-10-03 10-22-05](https://user-images.githubusercontent.com/5100735/66094764-b934ab00-e5c7-11e9-80fb-d9922e6b0587.png)

**Comment by jlewi** [comment]
@gaocegege no I didn't see any experiment in the UI.

Could this be an issue with multi-user and missing service accounts? I was running my experiments in a namespace other than the Kubeflow namespace. 

As part of that I ran into problems with service accounts missing (e.g kubeflow/katib#843) so one possibility is that the katib backend either isn't listing experiments in other namespace or else is having problems because of missing RBAC permissions/service accounts.

**Comment by johnugeorge** [comment]
@jlewi The support for non kubeflow namespace in UI was added recently in v1alpha3. It is not supported in v1alpha2.   In v1alpha2, experiments are listed only from Kubeflow namespace

 Issue: https://github.com/kubeflow/katib/issues/774

**Comment by gaocegege** [comment]
As @johnugeorge said, we recently support multi-namespace. I think you should be able to get experiments on UI in v1alpha3.

Ref https://github.com/kubeflow/katib/issues/774
