### ISSUE TITLE
Once the Katib experiments are done trial pods are not shown in the pod list.

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#708]
I am using Katib [v1alpha2](https://github.com/kubeflow/katib/tree/master/examples/v1alpha2) examples. Once I launce the experiment example, things are running. I can see the pods in running state using `kubectl get pods -n kubeflow`. But once the rods are completed their job. No longer visible using `kubectl get pods -n kubeflow`. 

somehow only for one experiment is can see the completed pod list, But tried to recreated the same experiment. but not working. 

- Kubeflow version: 0.6.1
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by johnugeorge** [comment]
Trials are deleted by default by default. If you want to retain, set Retain flag in TrialTemplate

**Comment by asispatra** [comment]
Thanks @johnugeorge , It works as you mentioned.
```
  trialTemplate:
    retain: true
    goTemplate:
        rawTemplate: |-
```

Closing the issue.
