### ISSUE TITLE
Hyperband r_l value is forcing to change parallelTrialCount

### ISSUE THREAD

**Issue by asispatra** [kubeflow/katib#709]
I am using Katib [v1alpha2](https://github.com/kubeflow/katib/tree/master/examples/v1alpha2) examples. 

If I change the `r_l` for hyberpand algo, it is forcing me to change the `parallelTrialCount`. Is there is way That I wan to set `parallelTrialCount: 2` and `r_l: 9` ?

- Kubeflow version: 0.6.1
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by hougangliu** [comment]
For hyperband, parallelTrialCount should be
