### ISSUE TITLE
[docs] Add docs about how to implement a new algorithm

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#71]
We have description for it https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md#implement-new-suggestion-algorithm but it is outdated and does not show how to write it in Python.

**Comment by jlewi** [comment]
@gaocegege @YujiOshima Think we will get this done for 0.4.0 or should we move to 0.5?

**Comment by johnugeorge** [comment]
@jlwei I can help with it.

**Comment by bjones325** [comment]
Has there been any progress on this? I am looking to attach a python algorithm and am running into difficulties with the new suggestion spec being recognized. Thanks :)

**Comment by gaocegege** [comment]
/assign

I will work on it when v1alpha3 is ready

**Comment by gaocegege** [comment]
We already have it #769 

/close
