### ISSUE TITLE
Katib gpu-example fails

### ISSUE THREAD

**Issue by Kloempi** [kubeflow/katib#713]
**What steps did you take and what happened:**
I wanted to try the gpu-example.yaml that can be found [here](https://github.com/kubeflow/katib/blob/master/examples/v1alpha1/gpu-example.yaml)

After starting the example with kubectl apply -f gpu-example.yaml I could see a lot pods in "Error" states.

Further inspection showed the following error (the timestamp doesnt match the one of the studyjob-controller but there are severall of those pods)

`2019/08/07 14:26:11 Study ID: if542e78e9fcf38a, Trial ID: vf8d55fc1740800e, Worker ID: kc1e527624046b20, Worker Kind: Job`
`2019/08/07 14:26:11 Failed to Report logs: rpc error: code = Unknown desc = sql: no rows in result set`

The studyjob-controller did log some errors as well (i removed other lines):
`$kubectl -n kubeflow logs  studyjob-controller-6b6fc85c6c-jpxr6`
`2019/08/07 13:50:31 Fail to Update StudyJob if542e78e9fcf38a : Operation cannot be fulfilled on studyjobs.kubeflow.org "gpu-example": the object has been modified; please apply your changes to the latest version and try again`

The Vizier-DB pod didnt show any errors.

**What did you expect to happen:**
the gpu-example.yaml to complete as the random-example.yaml did

**Environment:**

- Kubeflow version: 0.5.0
- Kubernetes version: (use `kubectl version`): v1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.2 LTS

**Comment by gaocegege** [comment]
/close

It is stale. But feel free to ask here.
