### ISSUE TITLE
KAtib UI doc (KubeFlow v0.6.1)

### ISSUE THREAD

**Issue by kimchitsigai** [kubeflow/katib#722]
/kind feature

**Describe the solution you'd like**
An User Guide or Tutorial for the Katib UI (installed with KubeFlow v0.6.1 and kfctl_existing_arrikto.yaml).

**Anything else you would like to add:**
I don't understand how to use the Katib UI, as shown in this screenshot:

![katib_ui](https://user-images.githubusercontent.com/5181623/63261753-85eec480-c284-11e9-97cf-0408656d0511.PNG)

**Comment by andreyvelich** [comment]
Hi @kimchitsigai!
Right now, you can find information about Katib UI of the official Kubeflow website: https://www.kubeflow.org/docs/components/hyperparameter-tuning/experiment/#running-the-experiment-from-the-katib-ui.

**Comment by andreyvelich** [comment]
I think we can close this issue.
/close
