### ISSUE TITLE
Katib ui without internet connection

### ISSUE THREAD

**Issue by hegand** [kubeflow/katib#724]
Currently katib ui v1alpha2 is not working in an environment without internet connection.

Could it be possible to use local version of the external javascript libraries:
* https://code.jquery.com/jquery-3.2.1.slim.min.js
* https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
* https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
* https://d3js.org/d3.v5.min.js
* https://underscorejs.org/underscore-min.js
* https://ajaxorg.github.io/ace-builds/src-min-noconflict/ace.js
* https://ajaxorg.github.io/ace-builds/src-min-noconflict/mode-xml.js
* https://unpkg.com/viz.js@1.8.0/viz.js

**Comment by vanillakola** [comment]
yes, i also meet this problem.
