### ISSUE TITLE
CreateStudy RPC error: Objective_Value_Name is required

### ISSUE THREAD

**Issue by evandekieft** [kubeflow/katib#73]
When I try to run `Createstudy` as in the example I'm getting:

```
katib-cli -s 192.168.99.100:30678 -f examples/random.yml Createstudy
2018/04/24 06:43:11 connecting 192.168.99.100:30678
2018/04/24 06:43:11 study conf{  UNKNOWN_OPTIMIZATION 0 <nil> []    [] []  []  [] 0  <nil> }
2018/04/24 06:43:11 req Createstudy
2018/04/24 06:43:11 CreateStudy failed: rpc error: code = Unknown desc = Objective_Value_Name is required.
```

Is there a mismatch between the latest CLI [release](https://github.com/kubeflow/katib/releases/tag/v0.1.0-alpha) and the core image in source control? How does one build the CLI from source?

**Comment by gaocegege** [comment]
Yeah, it is a mismatch. You could build it using `go build -o katib-cli github.com/kubeflow/katib/cmd/cli`

**Comment by ddysher** [comment]
Should we create a new release or created versioned images ASAP?  @gaocegege

**Comment by YujiOshima** [comment]
@evandekieft Sorry for inconvenient.
@gaocegege @gaocegege We are refining API and CLI. I want to release the new version after that.
WDYT?
And we need to automat image building..

**Comment by gaocegege** [comment]
I agree that we could publish a new pre-release version. Could you do it for us?

**Comment by YujiOshima** [comment]
I can push docker images but I don't have permission to push binary to GitHub repo.

**Comment by gaocegege** [comment]
OK, I could do it. Could you tell me the commit ID that you used to push the docker images?

**Comment by gaocegege** [comment]
@evandekieft Does it work for you?

go build -o katib-cli github.com/kubeflow/katib/cmd/cli

**Comment by gaocegege** [comment]
@jlewi Could we give Yuji the permission to release the version?

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/releases/tag/v0.1.1-alpha

PTAL @evandekieft
