### ISSUE TITLE
pytorchjob and Tfjob labels changed

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#746]
https://github.com/kubeflow/tf-operator/pull/1064
https://github.com/kubeflow/pytorch-operator/pull/204

Above PRs update pytorchjob and tfjob pod labels, and now katib depends on these labels. For backward compatibility, now katib support both the old  and new version of labels.

In future, when pytorchjob and Tfjob  repo drops the old one, we should update katib related code, too.

**Comment by gaocegege** [comment]
Should we fix it before 0.7? @johnugeorge @hougangliu

**Comment by johnugeorge** [comment]
In this release, katib will use older labels while job operators supports both(old and new) labels. 

Post 0.7 release, katib should use newer labels.  We can keep this PR open to track this.

**Comment by andreyvelich** [comment]
@johnugeorge @gaocegege Should we close this, I think we have new labels: https://github.com/kubeflow/katib/blob/master/pkg/common/v1alpha3/common.go#L22?
