### ISSUE TITLE
what  the objective metrics format should be

### ISSUE THREAD

**Issue by wukong1992** [kubeflow/katib#748]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I start a experiment， the backend pod is completed, but the status of trial did not change, i guess the objective metrics's format may be wrong, but when i find the correct one, i cann't find in the docs. 

**What did you expect to happen:**
the objective metrics' format should be given in the docs

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
when the backend pod is completed, the upstream trial or experiment should give a status, eg, failed,succeed, unknown....; but now if the output metrics' format is not correct, the ttrial or experiment's status is never change.

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/blob/master/cmd/metricscollector/v1alpha2/main.go#L18

If you think it does not fit your requirements, you could write your own metrics collector.

**Comment by wukong1992** [comment]
> https://github.com/kubeflow/katib/blob/master/cmd/metricscollector/v1alpha2/main.go#L18
> 
> If you think it does not fit your requirements, you could write your own metrics collector.

it should be explained clearly in doc.

**Comment by gaocegege** [comment]
Yes, I think so. We are refactoring the metrics collection. After the refactor, I think we should enhance the doc

**Comment by gaocegege** [comment]
Thanks for your issue
