### ISSUE TITLE
[Help wanted] I want use gpu in minikube

### ISSUE THREAD

**Issue by warf34** [kubeflow/katib#757]
hello, i want use tensorflow gpu.
but this [manual](https://github.com/kubeflow/katib/blob/master/README.md#v1alpha1) don't have how to use gpu!
can you tell me how to use gpu?
i have to use only minikube

**Comment by gaocegege** [comment]
First, you need to make sure that kubelet has the GPU support in minikube. Then you can use resource.limit to use GPU.

**Comment by gaocegege** [comment]
https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/ may be helpful
