### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/katib#77]
@gaocegege @jlewi 
Who is the owner of the [kubeflow docker hub repos](https://hub.docker.com/u/kubeflow/)?
Can you setup dockerhub's Automated Build for Katib images?

**Comment by gaocegege** [comment]
I think Jeremy is the owner, and I have no permission to do it.

**Comment by YujiOshima** [comment]
@jlewi OK! I will try to build our images with Kaniko.

**Comment by gaocegege** [comment]
It seems that Kaniko does not support multiple stage build.

> I see, let's skip Katib for now, will wait kaniko support multi stage or we find better tool

**Comment by gaocegege** [comment]
But we definitely need CD for CLI and the docker images. There are some issues about it

Ref #80

**Comment by YujiOshima** [comment]
Hmm, without multi-stage build, the image size will be so large.
But CD build is a high priority since we will probably cause an inconvenience for users.

* Use Kaniko without muti-stage build for now. We wait it will be supported by Kaniko.
* Use another tool (e.g. docker-hub automated build) until muti-stage build is supported by Kaniko.

IMHO, we can use kaniko without muti-stage build for now.
WDYT? @gaocegege @jlewi

**Comment by gaocegege** [comment]
Ref https://github.com/GoogleContainerTools/kaniko/issues/175

It works for me, but I think we should ask the kaniko owner if they want to implement the feature in the future.

**Comment by gaocegege** [comment]
https://github.com/GoogleContainerTools/kaniko/pull/141/

It seems that they are working on it these days.

**Comment by YujiOshima** [comment]
@jlewi @gaocegege 
I have some troubles to use kaniko for building images.
* How to send the katib source to kaniko worker(nfsPVC? or GCS?)
* How to send the credentials to kaniko?

But now automated build and release process is the high priority since many user's issues are related to version mismatch.
So I want to use gcloud tool or docker command for now.
Then, which registry should I push to and how to use their credentials?
Would you help me?
