### ISSUE TITLE
Can not find experiments in frontend if namespace is not kubeflow

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/katib#774]
/kind bug

**What steps did you take and what happened:**
I am new to katib and not sure if this is an issue.

Based on my finding, I notice if I submit experiments in different namespaces other than kubeflow. There're two problems

1. Can not find experiments on UI
2. Sometimes experiment never get done. Seems pod are done but `experiment` status are not updated. Checked status using command `kubectl get experiments`

**What did you expect to happen:**
We want every individual user create experiment in their own namespace. 

**Environment:**

- Kubeflow version: 0.6.2
- Kubernetes version: (use `kubectl version`): 1.13.8

**Comment by SatyaNarayan1** [comment]
facing the same issue kubeflow version 0.6.2. Cant see any thing in experiments UI also experiments/trials in running state.

**Comment by johnugeorge** [comment]
Yes. This is a known issue. This issue will be solved in upcoming 0.7 release

**Comment by SatyaNarayan1** [comment]
@johnugeorge is there any earlier version in which experiment UI is working?

**Comment by johnugeorge** [comment]
I was referring to issue where Katib job and services are in different namespaces: 

Related: https://github.com/kubeflow/katib/issues/343

**Comment by johnugeorge** [comment]
@SatyaNarayan1 Do you have them in different namespaces?

**Comment by SatyaNarayan1** [comment]
@johnugeorge I tried both approach 
1) Keeping in same namespace "kubeflow"
2) Keeping in two different namespace in both cases experiment UI is blank

<img width="1378" alt="Screen Shot 2019-09-23 at 12 25 38 PM" src="https://user-images.githubusercontent.com/6360289/65406498-67d53080-ddfd-11e9-8cf4-70997681d3d6.png">
<img width="1375" alt="Screen Shot 2019-09-23 at 12 25 24 PM" src="https://user-images.githubusercontent.com/6360289/65406516-6e63a800-ddfd-11e9-94dc-25bb3c1e63f6.png">

**Comment by gaocegege** [comment]
So, current implementation is such that we do not provide namespace, it is uses the namespace of the deployment (which is KF)

From @johnugeorge

**Comment by Jeffwan** [comment]
@gaocegege @johnugeorge 

New to Katib project and do we have an estimate on work to support different namespace. Since most important components are moved to multi-tenancy mode, I hope users can submit their katib experiment in their own namespace.  Otherwise, user may not have permission on kubeflow in most of the enterprise envs. This should be a high priority improvement.

**Comment by gaocegege** [comment]
Hi @Jeffwan 
/cc @johnugeorge 

I think we are going to give katib cluster scoped access and show all the experiments in all namespaces.

And I will work on it. Does it work for you?

**Comment by Jeffwan** [comment]
@gaocegege That makes sense. Show all experiments is good enough now.

**Comment by gaocegege** [comment]
/close 

#835 #827 #839 fixed this issue.

**Comment by Jeffwan** [comment]
Great! Thanks @gaocegege

**Comment by gaocegege** [comment]
Thanks for the issue! @Jeffwan
