### ISSUE TITLE
[enhancement] Add grpc health check against suggestion port to report it being ready.

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#778]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaocegege** [comment]
Example here https://github.com/grpc/grpc/blob/master/src/python/grpcio_health_checking/grpc_health/v1/health.py

**Comment by johnugeorge** [comment]
Similar check in manager: 

https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/manager/deployment.yaml#L37
https://github.com/kubeflow/katib/blob/master/cmd/manager/v1alpha3/main.go#L139

**Comment by johnugeorge** [comment]
Merged as part of https://github.com/kubeflow/katib/pull/779

**Comment by johnugeorge** [comment]
Closing this issue
