### ISSUE TITLE
Release process for CLI

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#78]
It looks like Katib includes a CLI. We'll need a release process for this and a way to distribute releases.

What are the initial platforms for which we want to build and release the CLI?

**Comment by gaocegege** [comment]
https://github.com/kubeflow/katib/releases/tag/v0.1.1-alpha

Now we have two supported platform: 

- katib-cli-darwin-amd64
- katib-cli-linux-amd64

**Comment by jlewi** [comment]
@YujiOshima @gaocegege Do we need to release an updated CLI?

**Comment by jlewi** [comment]
Do we still use the CLI @gaocegege @YujiOshima ?

There is no mention of the CLI in the docs?
https://www.kubeflow.org/docs/guides/components/hyperparameter/

**Comment by YujiOshima** [comment]
@jlewi We don't use it now. 
We could remove it in this release.

**Comment by jlewi** [comment]
Great. Thanks.

**Comment by jlewi** [comment]
Created a separate issue to delete the CLI code.
