### ISSUE TITLE
cli failed to connect

### ISSUE THREAD

**Issue by lluunn** [kubeflow/katib#80]
I was trying the getting start [guide](https://github.com/kubeflow/katib/blob/master/docs/getting-start.md).
I can see the pod using kubectl.

But
``` 
katib-cli -s gke-test-katib-default-pool-b88188d2-jnvp:30678 Getstudies
2018/05/09 11:38:13 connecting gke-test-katib-default-pool-b88188d2-jnvp:30678
2018/05/09 11:38:14 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup gke-test-katib-default-pool-b88188d2-jnvp on 127.0.0.1:53: no such host"; Reconnecting to {gke-test-katib-default-pool-b88188d2-jnvp:30678 <nil>}
2018/05/09 11:38:14 GetStudy failed: rpc error: code = 14 desc = grpc: the connection is unavailable
```

```
11:38:14lunkai@None:katib$ katib-cli
2018/05/09 11:38:34 connecting 127.0.0.1:6789
2018/05/09 11:38:34 Method not found: 
```

Do we need to configure cli somehow?

**Comment by lluunn** [comment]
download from github, as https://github.com/kubeflow/katib/blob/master/docs/getting-start.md#install-the-system-and-cli

**Comment by gaocegege** [comment]
Then you need to checkout v0.1.0-alpha to have a try. We do not have a CD process for CLI so it is version specific.

**Comment by gaocegege** [comment]
Wait a minute, @YujiOshima Does our images have the tag `v0.1.0-alpha` or `v0.1.1-alpha` for test?

**Comment by lluunn** [comment]
I am using v0.1.1-alpha now. Got a different error

```
13:28:10lunkai@None:katib$ katib-cli -s gke-test-katib-default-pool-b88188d2-jnvp:30678 get studies
2018/05/22 13:28:41 GetStudy failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: 
connection error: desc = "transport: Error while dialing dial tcp: lookup gke-test-katib-default-pool-b88188d2-jnvp on 127.0.0.1:53: no such host"
```

It seems it's trying to find the pool on 127.0.0.1?

**Comment by YujiOshima** [comment]
It looks problem of DNS setting on your host.
Can you `nslookup gke-test-katib-default-pool-b88188d2-jnvp` from your host?

**Comment by lluunn** [comment]
```
nslookup gke-test-katib-default-pool-b88188d2-jnvp
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find gke-test-katib-default-pool-b88188d2-jnvp: NXDOMAIN
```

To clarify, I am deploying katib to a GKE cluster, and calling katib-cli from my laptop.
Is it expected to work this way?
Do a need to setup anything for my cluster?

**Comment by YujiOshima** [comment]
You failed to resolve the name `gke-test-katib-default-pool-b88188d2-jnvp`.
Try to use the IP address of the node.
And in GKE, you should add a firewall rule to accessing to port 30678.
e.g. `gcloud compute firewall-rules create katibservice --allow tcp:30678`
