### ISSUE TITLE
[enhancement] Add e2e test cases for different metrics collector kinds

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#807]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

/cc @hougangliu 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by johnugeorge** [comment]
Do we have examples for each metric collector?

**Comment by gaocegege** [comment]
dup with #825
