### ISSUE TITLE
[enhancement] Ensure that metrics are deleted when experiment is deleted

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#808]
When experiment is deleted, metrics should be deleted

**Comment by gaocegege** [comment]
We come to an agreement that we should implement the feature in Trial level. I am going to add a finalizer in Trial CRD and an API in manager to implement it.

**Comment by gaocegege** [comment]
We dropped the useless APIs in GRPC #818 , then we need to add a new API to let trial controllers delete the metrics when the trial is deleted.
