### ISSUE TITLE
[enhancement] Update manifests in kubeflow/manifests

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#811]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

/priority p0

/assign @johnugeorge 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaocegege** [comment]
We should make sure that namespace label is added in Kubeflow.

**Comment by johnugeorge** [comment]
Merged as part of https://github.com/kubeflow/manifests/pull/442 and https://github.com/kubeflow/manifests/pull/406

**Comment by johnugeorge** [comment]
Closing as PRs are merged
