### ISSUE TITLE
[request] Invite libbyandhelen as reviewer for algorithm support

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#82]
libbyandhelen implemented Bayesian Optimization for katib and are implementing Covariance Matrix Adaptation Evolution Strategy these days. His contribution demonstrates his knowledge on katib code base.

@libbyandhelen Then would you like to be an reviewer of katib and help us review the code about suggestion algorithms? I'd appreciate it.

/cc @YujiOshima

**Comment by libbyandhelen** [comment]
@gaocegege 
Sure! Thank you for your invitation. I would love to:)

**Comment by jlewi** [comment]
Invite sent.
/close
