### ISSUE TITLE
Metric collector containers are not added when deployed in non kubeflow namespace

### ISSUE THREAD

**Issue by johnugeorge** [kubeflow/katib#823]
/kind bug

/assign @hougangliu

**Comment by hougangliu** [comment]
For now, metrics-collector sidecar container is only injected into the namespace with label `katib-metricscollector-injection: enabled` by design

**Comment by gaocegege** [comment]
Yeah, I think it is a feature to avoid performance issues.

**Comment by gaocegege** [comment]
We decided to add a validation webhook to avoid silent failure.

**Comment by gaocegege** [comment]
I think we could close it. https://github.com/kubeflow/katib/pull/828 fixed it.

/close
