### ISSUE TITLE
[enhancement] Support customized trial template name in UI

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#834]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by yeya24** [comment]
Can you explain this feature request a little bit?

**Comment by gaocegege** [comment]
@yeya24 

https://github.com/kubeflow/katib/blob/master/pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx#L130

In front-end, the configmap name is hard-coded. The list only contains the templates defined in the hard-coded configmap.

**Comment by andreyvelich** [comment]
@gaocegege I believe, we can close this, since we support Trial Templates in all namespaces and all configMaps names.
