### ISSUE TITLE
[bug] Same name in different namespaces causes error in DB

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#840]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Consider this case: There are two experiments, one is `experiment-1` in `kubeflow`, other is `experiment-1` in `kubeflow-user`. It will cause problems in DB. Because we do not make namespace as a primary key.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by johnugeorge** [comment]
Which DB table are you referring to?

**Comment by gaocegege** [comment]
Observation, I think.

**Comment by johnugeorge** [comment]
It doesn't have experiment info - https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/mysql/init.go#L9

**Comment by gaocegege** [comment]
Yeah, if the trial name is the same, then we will have problems. Although it is hard to meet.

**Comment by gaocegege** [comment]
Maybe we do not need to fix it. After thinking, I think even in one same namespace, we also may have the problem.
