### ISSUE TITLE
Can't create Experiment from notebook - default-editor doesn't have sufficient permission

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#843]
/kind bug

Using 0.6.2 I'm trying to create a Katib Experiment from a notebook using the K8s python client library.

I get an RBAC error because the service account for the notebook doesn't have permission to create experiments.

```
ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '71d20446-dac9-4a74-b5f6-76e792a9fe5d', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Tue, 01 Oct 2019 08:19:25 GMT', 'Content-Length': '356'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"experiments.kubeflow.org is forbidden: User \"system:serviceaccount:jlewi:default-editor\" cannot create resource \"experiments\" in API group \"kubeflow.org\" in the namespace \"jlewi\"","reason":"Forbidden","details":{"group":"kubeflow.org","kind":"experiments"},"code":403}
```

We should fix this as part of the work @krishnadurai is doing in 0.7 to clean up the Kubeflow roles using role aggregation.

We should ensure the kubeflow-editor role has permission to create experiments and other katib resources.

# Work Around

In the interim you can easily work around this by manually creating the role.

```
kubectl -n ${NAMESPACE} create rolebinding katib-editor --clusterrole=katib-controller --serviceaccount=${NAMESPACE}:default-editor 
```

**Comment by gaocegege** [comment]
@johnugeorge Do we have a notebook in katib deployment?

**Comment by johnugeorge** [comment]
@gaocegege from the Notebooks deployed in Kubeflow

This issue should be tracked in Kubeflow repo as the fix lies outside.

**Comment by krishnadurai** [comment]
@hougangliu here is the reference for the ClusterRoles being added for Katib:
https://github.com/kubeflow/manifests/pull/448

You may have to associate the service account with this role ref.

P.S. The ClusterRole was unfortunately removed with the new Katib manifests being merged.

**Comment by hougangliu** [comment]
@krishnadurai cool. Updated https://github.com/kubeflow/manifests/pull/471

**Comment by hougangliu** [comment]
https://github.com/kubeflow/manifests/pull/448 had fixed it.
thanks @krishnadurai

**Comment by johnugeorge** [comment]
Closing this issue

**Comment by sachdevayash1910** [comment]
Updating this thread with the right command in case someone lands here from a search:
`kubectl -n ${NAMESPACE} create rolebinding katib-editor --clusterrole=katib-controller --serviceaccount=${NAMESPACE}:default-editor `
