### ISSUE TITLE
trial stuck because metrics collector doesn't report metric because of job failures - v1alpha2 - kubeflow 0.6.2

### ISSUE THREAD

**Issue by jlewi** [kubeflow/katib#849]
/kind bug

I had a trial which was stuck in the Running state even though the training job had completed.

When I looked at the metric collector pod it had a log 

```
"Metrics reported. :" 
```

So it looked like the metric collector wasn't reporting any metrics for the job and that's what caused the trial to get stuck in the running state.

It looked like the training job had 1 successfullly completed pod and a couple failed pods.

```
kubectl  get pods -l job-name=tune-191002-092445-vbgxkjz5
NAME                                       READY   STATUS      RESTARTS   AGE
tune-191002-092445-vbgxkjz5-8xm5c   0/1     Error       0          4h23m
tune-191002-092445-vbgxkjz5-nczhq   0/1     Completed   0          3h14m
tune-191002-092445-vbgxkjz5-s4vxk   0/1     Error       0          4h15m
```

My conjecture  was that the failed pods were confusing the metric collector. 

To validate this I deleted the pods in the error state. Sure enough the trial was then marked as succeeded.

So it looks like there are two issues

1. metrics collector doesn't properly handle the case where there are more than 1 pod for the training job
1. trial controller will potentially wait forever if metrics collector doesn't collect and report metrics

**Comment by gaocegege** [comment]
Please add a tag to show it is from v1alpha2 or 0.6.

**Comment by jlewi** [comment]
@gaocegege Do you mean labels? I don't see any existing labels for v1alpha2.

**Comment by johnugeorge** [comment]
If you could add the version, it would be helpful. 
Some of the issues that you have raised are resolved in v1alpha3

**Comment by gaocegege** [comment]
@jlewi No, I mean the issue labels. Since we do not have the permission to add labels, I'd apprecaite it if you could add the issues 0.6 label since as Johnu said, some of them are fixed in v1alpha3(0.7)

**Comment by jlewi** [comment]
I created the label katib v1alpha2 and also added it to project 0.6. We use projects not labels to associate issues with releases.

**Comment by johnugeorge** [comment]
1. metrics collector doesn't properly handle the case where there are more than 1 pod for the training job

trial controller will potentially wait forever if metrics collector doesn't collect and report metrics
This is fixed in

**Comment by hougangliu** [comment]
> So it looks like there are two issues

> metrics collector doesn't properly handle the case where there are more than 1 pod for the training job

In katib design, for Job kind worker, only logs of the first container of the Pod is collected and parsed.

**Comment by hougangliu** [comment]
@gaocegege @johnugeorge do you think we should fix the gaps for v1alpha2?
in kubeflow 0.7 release, katib will release v1alpha3, which uses totally different way to collect metrics. In v1alpha3, #841 and this issue will all be gone. @jlewi WDYT?

**Comment by johnugeorge** [comment]
I think, we can skip v1alpha2 fixes. Even v1alpha2 manifests are deleted from the kubeflow/manifests.
