### ISSUE TITLE
kfctl delete does not remove katib

### ISSUE THREAD

**Issue by shaunc** [kubeflow/katib#888]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Tried to install kubeflow on docker-for-mac. Got errors. Tried to remove and reinstall different version. First got errors with Istio. After removing Istio-system namespace, now getting error on generate:
```
couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application katib-db
```

**What did you expect to happen:**

katib components should be removed by `kfctl delete` if they are created by `kfctl generate` or `kfctl init`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Presumably, properly name spacing katib on install would make removal easier. In https://github.com/kubeflow/kubeflow/issues/3767#issuecomment-543221421 I suggest prefixing all namespaces with `kubeflow-` by default.

**Environment:**

Docker desktop 2.1.4.0

- Kubeflow version:

Tried 0.6.2 and 0.7-rc2
- Minikube version:
- Kubernetes version: (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):

Mac OS 10.14.16

**Comment by gabrielwen** [comment]
I was not able to reproduce this..  could you try to run `kfctl build -f && kfctl apply -f` with the latest 0.7 RC and delete it with `kfctl delete -f` to see if the bug is still there?

**Comment by andreyvelich** [comment]
The latest version should work well with `kfctl`. Feel free to re-open this if you have any other problems.
