### ISSUE TITLE
[feature] Add new trials to a succeeded Experiment

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#891]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Now we cannot achieve it because of:

```go
	reconcileRequired := !instance.IsCompleted()
	if reconcileRequired {
		r.ReconcileTrials(instance, trials.Items)
	}
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by johnugeorge** [comment]
Yes. We have to add extra check when we support resuming trials

**Comment by johnugeorge** [comment]
#952
