### ISSUE TITLE
error when creating "katib/examples/v1alpha2/tfjob-example.yaml":

### ISSUE THREAD

**Issue by moonyoung430** [kubeflow/katib#902]
When I run kubectl apply -f tfjob-example.yaml in katib/examples/v1alpha2/,I got this

Error from server: error when creating "tfjob-example.yaml": admission webhook "validating.experiment.kubeflow.org" denied the request: Fail to check record for the experiment in DB: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"

**Environment:**

- Kubeflow version: 0.6
- Minikube version:
- Kubernetes version: (use `kubectl version`): 1.13.4
- OS (e.g. from `/etc/os-release`): 
katib environment
![image](https://user-images.githubusercontent.com/31330980/67845528-96e86b80-fb3a-11e9-8738-70f5fbcd2d67.png)

**Comment by gaocegege** [comment]
Can you try our v1alpha3 version, which is included in kubeflow 0.7? v1alpha2 is deprecated. It seems that there is something wrong in your DB.

**Comment by moonyoung430** [comment]
@gaocegege thanks for your reply
I just upgraded to v0.6 T.T few days ago ,Can I use v1alpha3 in v0.6??
and Can you talk about DB in detail? I'm just getting started, Thanks

**Comment by gaocegege** [comment]
You can install v1alpha3 using the manifests in our repo.

**Comment by johnugeorge** [comment]
Shall we close this?
