### ISSUE TITLE
Katib to wikipedia

### ISSUE THREAD

**Issue by arun-gupta** [kubeflow/katib#903]
/kind feature

Add katib to https://en.wikipedia.org/wiki/Hyperparameter_optimization

**Comment by gaocegege** [comment]
Thanks for the suggestion. Can you help us add katib into the wiki?

/priority p3

Help wanted

**Comment by arun-gupta** [comment]
Sure, how about the following lines?

In `Grid search` category:

`Katib is a Kubernetes-native system which includes grid search`

In `Random search` category:

`Katib is a Kubernetes-native system which includes random search`

In `Bayesian` category:

`Katib is a Kubernetes-native system which includes bayesian optimization`

In `Other` category:

`Katib is a Kubernetes-native system which includes grid, random search, bayesian optimization, hyperband, and NAS based on reinforcement learning`.

Katib will be a hyperlink for each line.

**Comment by gaocegege** [comment]
LGTM. Thanks for your help! :tada:

**Comment by gaocegege** [comment]
/close

@arun-gupta Thanks!
