### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by x28646510** [kubeflow/katib#915]
/kind feature

Hello, I'd like to request a feature for manager to register logs to PostgreSQL. Do you have any plan?

**Describe the solution you'd like**
Current, only MySQL is supported as Log DB. So, I would like a feature for manager to register logs to PostgreSQL because PostgreSQL is major database as much as MySQL.

**Comment by gaocegege** [comment]
If there is enough interest (upvotes needed), then this could be part of this project's roadmap.

And, also welcome your contribution!

**Comment by javen218** [comment]
It is great if katib and pipeline support postgreSQL database! Is there any plan to make database optional? @gaocegege @andreyvelich

**Comment by Edward-liang** [comment]
MySQL is no longer best choice for many, since purchased by Oracle Company. 
The cake of Kubeflow is free, except the MySQL piece. And this makes us hesitate to introduce kubeflow into our project.

**Comment by johnugeorge** [comment]
@Edward-liang  @javen218  Katib can be configured to have any backend DB. It can be supported by implementing this interface for any DB- https://github.com/kubeflow/katib/blob/master/pkg/db/v1beta1/common/kdb.go and use the DB in the manifests - https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/db-manager/db-manager.yaml#L26   We can aim it for next release.  It would be great if you can contribute it.

**Comment by javen218** [comment]
Thank you very much for your reply！ @johnugeorge @gaocegege 
We are highly looking forward to seeing this new feature in the next release!!!

**Comment by anencore94** [comment]
If you guys think it is worth enough. I could try working on supporting Postgres as a katib db-manager's built-in feature.
Even though katib already supports the interface for general DB, it could be some time-consuming job to many users if they should implement for themselves.
WDYT? @kubeflow/wg-automl-leads

**Comment by gaocegege** [comment]
@anencore94 Thanks for your contribution! I agree with you.

**Comment by johnugeorge** [comment]
Thanks @anencore94
