### ISSUE TITLE
Move Katib E2E tests to use kubeflow-ci-deployment project

### ISSUE THREAD

**Issue by zhenghuiwang** [kubeflow/katib#919]
/kind bug

**What steps did you take and what happened:**

As part of Katib e2e tests, a GKE cluster is created in kubeflow-ci project. The problem is`kubeflow-ci` is supposed to host only Argo workflows for e2e tests; and only `kubeflow-ci-deployment` has the cron job to properly reclaim resources.

**What did you expect to happen:**
The GKE clusters for E2E tests in Katib are created in kubeflow-ci-deployment project.

**Comment by andreyvelich** [comment]
We use AWS infra now.
