### ISSUE TITLE
Make db deployment optional

### ISSUE THREAD

**Issue by xaniasd** [kubeflow/katib#921]
/kind feature

**Describe the solution you'd like**
n the current setup, katib deploys a database in the base layer. This database is insecurely configured (e.g. root password "test"). Production deployments will (hopefully) want to use a different setup; especially for cloud deployments, managed SQL services such as RDS in AWS are good replacement candidates.

It is possible to customize the katib-controller deployment with an overlay and avoid using katib-db, I would like to avoid deploying it altogether.

**Anything else you would like to add:**
We can solve this by moving katib-db related resources out of the base layer. I'm more than happy to submit a PR if the solution is acceptable.

**Comment by johnugeorge** [comment]
Currently, katib supports only mysql as the underlying DB. You could change the credentials by setting here https://github.com/kubeflow/katib/blob/master/manifests/v1alpha3/manager/deployment.yaml#L25 

It is also possible to add any custom database by extending https://github.com/kubeflow/katib/blob/master/pkg/db/v1alpha3/common/kdb.go 

Please feel free to contribute if you would like to use a different DB. 
Related: https://github.com/kubeflow/katib/issues/915

**Comment by xaniasd** [comment]
hi @johnugeorge, my proposal is slightly different; I still want to use mysql as a database, but on a  pod/server/service external to the katib deployment. In that case, I would prefer not to deploy the one in the base layer at all. Anyway, I'll create a PR and see how it fares :)

**Comment by johnugeorge** [comment]
You could then use overlays in manifests
See https://github.com/kubeflow/manifests/blob/master/katib/katib-controller/overlays/ibm-storage-config/kustomization.yaml how to override the base db deployment

**Comment by barambani** [comment]
I tried to customise the MySql instance as well. I did it trough env var but I couldn't find a way to set a username. Are there variables for that ? I checked [here](https://github.com/kubeflow/katib/blob/d9bb39e338d0cd317ef869914cf4712f0cd912ad/pkg/db/v1alpha3/common/const.go#L6). 
Also, it looks like that the db name is hardcoded and cannot be changed. Again, if I sett the `KATIB_MYSQL_DATABASE ` variable [here](https://github.com/kubeflow/katib/blob/d9bb39e338d0cd317ef869914cf4712f0cd912ad/pkg/db/v1alpha3/common/const.go#L6) it fails (I think because of [this check](https://github.com/kubeflow/katib/blob/27893d37123fdc1e0776ccc470482eee704b7de9/pkg/db/v1alpha3/db.go#L12). What's the reason of that ? Is there another way ?
Thanks a lot.

**Comment by johnugeorge** [comment]
@barambani Can you explain more on what you are trying to customize?

**Comment by barambani** [comment]
Sure, I'm trying to use a managed solution as database (in my case AWS Aurora). Also I need to change the database name as I have some instances writing to the same Aurora cluster at the same time. For that I was assuming that I needed to set mysql's
- user name
- password
- host
- port
- database name

**Comment by xaniasd** [comment]
@barambani [here](https://github.com/kubeflow/pipelines/pull/2668) is a relevant PR for pipelines, I'll submit a similar one for katib soon. You'll probably need to configure other parameters (like TLS) as well. 

@johnugeorge I guess I can set the number of replicas to 0 in my custom overlay, however this seems more convoluted to me (and certainly less clean) than not deploying the db resources at all, if I don't use them.

**Comment by barambani** [comment]
Brilliant thanks. I'm already able to use set up pipelines to store to Aurora using the environment libraries overrides. Related to pipelines (sorry if this is not the most relevant place for it), can you point me to the code or the an example where I can see how to move to S3 also the pipeline's graph metadata that are currently stored to minio's pvc ? I would like to have backed up managed persistence for them as well, but I couldn't find a right way to set the minio client for it work.
