### ISSUE TITLE
Kaitb experiment error

### ISSUE THREAD

**Issue by pavan-infiswift** [kubeflow/katib#922]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I have deployed katib as part of kubeflow and ran the following example:
https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/random-example.yaml
This example successfully ran.

 I changed the image name to custom image from private gcr registry and added ImagePullSecrets in the specification.
First experiment failed due to incorrect yaml specification.
For the second experiment, I deleted the failed expriment from katib UI ,corrected the yaml specification and changed the experiment name and deployed the new experiment. UI says deployment successfull.

**What did you expect to happen:**
I expected my new example to run successfully. But I get the following error in the katib-con troller logs:
`{"level":"error","ts":1574221670.238136,"logger":"experiment-controller","msg":"Create trial instance error","Experiment":"kubeflow/pavan","trial":{"parameterAssignments":[{"name":"--dropout","value":"0.47598135301177175"},{"name":"--lr","value":"0.0153275"}],"name":"pavan-wl4cmhxq"},"error":"trials.kubeflow.org \"pavan-wl4cmhxq\" already exists","stacktrace":.....`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I have changed the name of the experiment but why doews it says the trial already exists?

**Environment:**

- Kubeflow version: 0.7
- Minikube version: Not using
- Kubernetes version: (use `kubectl version`):1.14.5
- OS (e.g. from `/etc/os-release`): ubuntu 18.04.3

**Comment by johnugeorge** [comment]
Due to reconcile logic, this log can occur and it is necessarily not an error.

What is the  experiment final status?

what is the status of
kubectl -n kubeflow get experiment pavan-wl4cmhxq -o yaml

kubectl -n kubeflow get trials
