### ISSUE TITLE
collect metrics information

### ISSUE THREAD

**Issue by cleveryg** [kubeflow/katib#923]
/kind bug

Training can be automated but katib cannot collect metrics information
katib-controller Log an error：
request":"mykubeflow/bayseopt-example","error":"Operation cannot be fulfilled on experiments.kubeflow.org \"bayseopt-example\": the object has been modified; please apply your changes to the latest version and try again"

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version: 0.7
- Minikube version:
- Kubernetes version: (use `kubectl version`):1.13.4
- OS (e.g. from `/etc/os-release`):CentOS Linux release 7.7.1908

**Comment by gaocegege** [comment]
dup with #930

/Close
