### ISSUE TITLE
[feature] Support Resources for Suggestions

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#927]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Now we do not set resources for suggestions. We should support it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by johnugeorge** [comment]
In certain class of suggestion algorithms, all trials are not run with same set of resources.  This feature is useful in such cases

**Comment by gaocegege** [comment]
@johnugeorge 

The feature you suggested is not actually the same as this one. This is to add resource requirements for suggestion deployment. Your idea is to let suggestions provide resource requirements for the trial if I do not misunderstand it.

**Comment by johnugeorge** [comment]
Got it. Both are different.  
We can expose the suggestion deployment resources through the config file.  What do you think?

**Comment by gaocegege** [comment]
I think so. I have a PR to add hard-coded config #932 

In the future, we should have it in katib-config.

**Comment by andreyvelich** [comment]
@gaocegege We can close it, we implemented it in: https://github.com/kubeflow/katib/pull/958.
