### ISSUE TITLE
Job level webhook for metrics collector sidecar container

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#928]
/kind feature
/P2
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
for now, we inject metrics collector sidecar container in Pod webhook, we can consider metrics collector sidecar container in Job webhook level for performance.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by johnugeorge** [comment]
This is no more required in k8s 1.15 as we could use more efficient object selector in web hooks

**Comment by vpavlin** [comment]
This could actually solve https://github.com/kubeflow/katib/issues/963 as it would reorder actions - first add the container in the Job and then let a job controller generate the pod, so it makes sense form my point of view:)

**Comment by hougangliu** [comment]
> This could actually solve #963 as it would reorder actions - first add the container in the Job and then let a job controller generate the pod, so it makes sense form my point of view:)

@vpavlin yes, it can solve #963, but it is low priority as plan and will be included in Kubeflow 1.0 release
