### ISSUE TITLE
stop a running experiment without deleting it

### ISSUE THREAD

**Issue by wstian** [kubeflow/katib#934]
/kind feature

**Describe the solution you'd like**
Sometimes I'd like to stop a running experiment because it's not good or something else, 
but currently the only way I found is to delete the experiment, which will clear all the related information, including all trials.

In fact, I'd like the trials saved.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by gaocegege** [comment]
@wstian There are several ways you can try.

- Delete experiment while using orphan policy
- Update the experiment.spec.Trials to a small number.

**Comment by hougangliu** [comment]
> * Update the experiment.spec.Trials to a small number.

I think you mean `experiment.spec.maxTrialCount`

**Comment by gaocegege** [comment]
Yeah, I think so. Thanks

**Comment by andreyvelich** [comment]
@wstian Right now, you can modify running Experiment (e.g. decrease `maxTrialCount`)  and use Resume Experiment feature.
Check the documentation here: https://github.com/kubeflow/website/pull/2324.
