### ISSUE TITLE
Cannot get pod name in injector webhook

### ISSUE THREAD

**Issue by yeya24** [kubeflow/katib#941]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Check the logs of katib-controller

![image](https://user-images.githubusercontent.com/25150124/69918222-8aa74500-143d-11ea-9b4e-9b0797921004.png)

The experiment with TFJob kind, it will print pod name. But for Batch job experiment,  the printed pod.name is ""

**What did you expect to happen:**
I can see the Batch job pod name as well, instead of ""

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I use the latest katib controller image.

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yeya24** [comment]
Seems the Batch Job pod doesn' t have a Name field. It only has a GenerateName and we cannot get the pod name in mutating web hook.
``` yaml
GenerateName string `json:"generateName,omitempty" protobuf:"bytes,2,opt,name=generateName"`
```

**Comment by gaocegege** [comment]
The webhook works at the pod level. The pod should have a name, although we use generate name in job. I think we should have a look at this issue.

Thanks for the report.

**Comment by hougangliu** [comment]
I think it works as expected, for Kubernetes controller, when generating a Pod, it only specifies `GenerateName`, before persisting the Pod, it will call webhook (`Name` still be not generated based on `GenerateName`)
For kubeflow Pod (Tfjob and PytrochJob), its name is specified when generated, so in webhook, the `Name` is not ""

**Comment by yeya24** [comment]
@hougangliu  Thanks for your reply.
Yes, this still works as expected. So this issue is only about the log cannot print the pod name. Just that, in the webhook level, it still works well.

**Comment by hougangliu** [comment]
I don't think it is an issue. it is Kubernetes feature that Webhook can never get Pod name if it is only set `GenerateName` (if the pod is generated by Job, RS and so on).
I think we can close it

**Comment by yeya24** [comment]
@hougangliu  Agree. Close now
