### ISSUE TITLE
katib cannot work in namespace with istio-injection enabled

### ISSUE THREAD

**Issue by hougangliu** [kubeflow/katib#955]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
For now, in Kubeflow notebook server, when a notebook created, a namespace aslo is created with label `istio-injection: enabled`. If a user create a katib experiment in the namespace, all katib Pods will be injected with Istio-proxy sidecar container, which will lead to the Pod never completed. refer to https://github.com/istio/istio/issues/11659

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by hougangliu** [comment]
@johnugeorge @gaocegege @richardsliu WDYT about this issue?

**Comment by gaocegege** [comment]
I think we can refer to istio's design. They support fine-grained control of the injection logic.

**Comment by hougangliu** [comment]
yes, adding `sidecar.istio.io/inject: “false”` in pod annotation can stop injecting, but I wonder if it is good to do that

**Comment by vpavlin** [comment]
Adding istio sidecars only makes sense if the container exposes any open ports, right? Which parts of Katib are you talking about here? 

My guess is this is about jobs generated by trials. In that case, I would say adding `inject: false` is a pretty safe bet as jobs should not expose anything via network anyway as a user cannot really control their run (unlike for deployments).

**Comment by gaocegege** [comment]
> Adding istio sidecars only makes sense if the container exposes any open ports, right? Which parts of Katib are you talking about here?
> 
> My guess is this is about jobs generated by trials. In that case, I would say adding `inject: false` is a pretty safe bet as jobs should not expose anything via network anyway as a user cannot really control their run (unlike for deployments).

SGTM. From the perspective of users, I think they do not want to have a long running istio sidecar in the training pod.

**Comment by andreyvelich** [comment]
We will update doc with this info. See comment: https://github.com/kubeflow/katib/pull/1338#issuecomment-708108674.
