### ISSUE TITLE
[design] How and which Katib services need to be exposed to users?

### ISSUE THREAD

**Issue by lluunn** [kubeflow/katib#96]
- vizier-core is now a NodePort service. Should we have an ingress / LB?
- modeldb ingress has hard-coded [host](https://github.com/kubeflow/katib/blob/master/manifests/modeldb/frontend/ingress.yaml#L8): k-cluster.example.net.  The endpoint k-cluster.example.net/katib mentioned in getting-start won't work.

**Comment by YujiOshima** [comment]
@lluunn 
* Yes. Since the previous version of nginx ingress didn't support GRPC, we didn't use the ingress. 
But it is supported now. We should use it.
* It is a problem for easy get starting. Is it able to be solved by ksonnet?

**Comment by jlewi** [comment]
I don't think we just want to use an ingress/LB that would potentially be very insecure. Unless we can somehow use gRPC to control authorization and access.

We need a way to secure it; e.g. some secure proxy as discussed in: kubeflow/kubeflow#11.

I think before we can begin to answer this there are a couple design questions that need to be understood

1. Which services need to be accessed from outside the cluster

   * Are they gRPC? Regular HTTP? Or both?

1. Can we assume the HP controller (e.g. [client-example.go](https://github.com/kubeflow/katib/blob/master/examples/client-example.go)) runs within the cluster?

There's an open issue to create a design doc #138 that should help answer these questions.

Here's my initial understanding

* We want to be able to access the Katib UI. This is an HTTP service so we can expose it like we do other web apps (see kubeflow/kubeflow#11)
     * So far the Katib UI appears to work just fine with a reverse proxy
* We probably want to support the Katib CLI which I think is using gRPC.
     * This is probably the most difficult issue
     * kubectl port-forward provides a short term solution
* The controller programs in general probably run in the cluster
     * kubectl port-forward works just fine if you want to run the controller locally; e.g. for debugging/development.

**Comment by jlewi** [comment]
What should we do in 0.4.0 about this issue?

**Comment by jbottum** [comment]
area /0.5.0

**Comment by jlewi** [comment]
Closing this issue because our docs cover how to use kubectl port-forward and this seems sufficient for now.
https://www.kubeflow.org/docs/guides/components/hyperparameter/
