### ISSUE TITLE
Katib UI does not show in Kubeflow central dashboard

### ISSUE THREAD

**Issue by ethanscho** [kubeflow/katib#968]
/kind bug

**What steps did you take and what happened:**
installed
- microk8s 1.14/stable
- kubeflow 0.7.0

accessed kubeflow central dashboard, but in the katib section, nothing was shown.

**What did you expect to happen:**
expected to see katib ui

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- ubuntu 16.04
- microk8s 1.14/stable
- kubeflow 0.7.0

**Comment by andreyvelich** [comment]
@ethanscho Can you check logs from the Katib-ui pod and Katib-ui image version, please?
Also, is status of Katib-ui pod `Running`?

**Comment by anupash147** [comment]
Same is the case for me, just that I have installed kubeflow version 1.0.0. All my katib deployments are working
![image](https://user-images.githubusercontent.com/8271182/75809279-29e61c00-5d4e-11ea-88a8-4af1362bb166.png)

The katib ui image am running is gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui:v0.8.0

**Comment by andreyvelich** [comment]
@anupash147 Are you using this config: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_istio_dex.v1.0.0.yaml ?

**Comment by terrykong** [comment]
I also am seeing the same thing (kubeflow v1.0.0 and this config https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.yaml). I can port forward the service via `kubectl port-forward svc/katib-ui -n kubeflow 8080:80` but nothing shows up for me either thru the central dashboard. The other components like pipelines/jupyter/artifacts are viewable, just not katib

**Comment by andreyvelich** [comment]
@terrykong Is you katib-ui pod Running?
Also, can you open console in your browser and check if you have any errors there?

**Comment by terrykong** [comment]
hey @andreyvelich 

the katib-ui pod is running, but i don't see any errors when i tail the log while i try to open the UI from the central-dashboard

**Comment by anupash147** [comment]
@andreyvelich  yes I am using kfctl_istio_dex.v1.0.0.yaml, Also for me when i port-forward, i can see the katib-ui just not in the dashboard.

**Comment by andreyvelich** [comment]
@terrykong @anupash147 Can you check any errors in the browser console, while opening Katib UI from the Central Dashboard?

**Comment by terrykong** [comment]
@andreyvelich this morning i tried to get to the katib UI from the central dashboard and it miraculously showed up. wished it didn't just go away on its own 😞 . if it disappears again i'll update.

**Comment by terrykong** [comment]
fwiw, even though the katib ui showed up i see a `Failed to retrieve GKE metadata TypeError: Failed to fetch` error in the console. not relevant to me I'm guessing since i'm not running my cluster on GKE

**Comment by andreyvelich** [comment]
@terrykong Did you access central dashboard using `port-forward`? And where you run your k8s cluster? Sometimes it can lose connection between Kubeflow components. Updating the page should help with it.

**Comment by terrykong** [comment]
@andreyvelich i've always accessed the central dashboard through the istio gateway through the istio gateway.

i'm running an on-prem cluster.

**Comment by andreyvelich** [comment]
@terrykong I think sometimes you should refresh page to see Katib UI in centerdashboard.
Next time you can't access Katib UI, please, show me the errors from the browser console.

**Comment by anupash147** [comment]
It working for me too ..
