### ISSUE TITLE
Show trial logs on the interface

### ISSUE THREAD

**Issue by prcastro** [kubeflow/katib#971]
/kind feature

**Describe the solution you'd like**

The problem is accessing and debugging the trials of a model. A possible solution is to have, on the interface, a way to access the logs of each trial. Seeing what trials are running and which ones are failing are a plus.

**Comment by nlarusstone** [comment]
This is also a question we have been having -- how are we intended to access the trial logs currently?

**Comment by andreyvelich** [comment]
@nlarusstone Right now, you can access Trial logs using `kubectl` or K8s APIs with corresponding training container.
In the future releases we have plans to add this feature on the UI as well.
/priority p2

**Comment by nlarusstone** [comment]
Forgive my ignorance, but where is the training container actually run? I can't seem to run `kubectl logs <trial-name>`

**Comment by andreyvelich** [comment]
@nlarusstone No worries!
If you want to save Trial's pods after completion, you have to specify `retain: True` in Experiment, e.g. [like here](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/tekton/pipeline-run.yaml#L32).

After that, you should be able to check logs from the created pods even if Trial is complete.
Trial's job should run in the same namespace as your Experiment.
