### ISSUE TITLE
Support for user configurable distributions for hyperparameters

### ISSUE THREAD

**Issue by ramdootp** [kubeflow/katib#983]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Users are restricted to use few katib initialized distributions for hyperparameters in random algo.
But, underlying hyperopt can supports a wide range of distributions.  
Please add support for user configurable distributions for hyperparameters.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
Let's continue discussion here: https://github.com/kubeflow/katib/issues/1207.
