### ISSUE TITLE
Replace mysql in pod with an external mysql

### ISSUE THREAD

**Issue by UrmsOne** [kubeflow/katib#984]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Distributed mysql services are provided in my company, so I would like to replace it with mysql 

provided by the company.But the database user name cannot be changed dynamically. 

As shown below:
![image](https://user-images.githubusercontent.com/31981402/71322169-a1523080-24ff-11ea-9bd2-6e215bf77e54.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Cloud you please expose it via a environment variable?**

**Comment by gaocegege** [comment]
You can do it with some changes to manifests, I think.
