### ISSUE TITLE
[feature] Show more information about best trial

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/katib#987]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

https://github.com/kubeflow/katib/pull/986#issuecomment-568371597

> > We show metrics and parameter assignments. I am not sure if I get your idea. Could you please explain more?
> 
> for example, for now if objective metrics is `loss`, in experiment or trial status, it show the best `loss` metrics minimum value like below:
> 
> ```
> observation:
>   metrics:
>     - name: loss
>        value: 0.0001
> ```
> 
> we can detail it more for a better viewpoint like `ray`:
> 
> ```
> observation:
>  metrics:
>    - name: loss
>      min: 0.0001
>      max: 0.1234
>      latest: 0.1111
> ```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by andreyvelich** [comment]
This was implemented.
