### ISSUE TITLE
unknown method 'GetSuggestions' error while running MinikubeDemo

### ISSUE THREAD

**Issue by vinaykakade** [kubeflow/katib#99]
While following instructions for MinikubeDemo, I get the following error:
```
$ go run random/random-suggest-demo.go 
2018/06/01 15:37:07 Study ID m9510a9448938b00
2018/06/01 15:37:07 Study ID m9510a9448938b00 StudyConfname:"grid-demo" owner:"katib" optimization_type:MAXIMIZE optimization_goal:0.99 parameter_configs:<configs:<name:"--lr" parameter_type:DOUBLE feasible:<max:"0.07" min:"0.03" > > > default_suggestion_algorithm:"grid" default_early_stopping_algorithm:"medianstopping" objective_value_name:"Validation-accuracy" metrics:"accuracy" metrics:"Validation-accuracy" 
2018/06/01 15:37:07 GetSuggestion Error rpc error: code = Unimplemented desc = unknown method GetSuggestions
exit status 1
```
Any thoughts on what may be going wrong? Also, I saw a comment regarding drastic changes in manager (https://github.com/kubeflow/katib/issues/97), is this related?

**Comment by mayankjuneja** [comment]
I am still looking more into this, but it could be because that the images (vizier-core) on dockerhub are not updated.  I was able to fix this error by building images locally, but getting a different error now. I will share more updates soon.

**Comment by vinaykakade** [comment]
This was fixed in the latest master, after https://github.com/kubeflow/katib/pull/103 was merged. Resolving.
